### ISSUE TITLE
Read snippet content from stdin

### ISSUE THREAD

**Issue by tclh123** [python-gitlab/python-gitlab#1002]
related https://github.com/python-gitlab/python-gitlab/issues/700

**Comment by tclh123** [comment]
Just create a wrapper script https://gist.github.com/tclh123/4ccb504839ad40229edfce2ef326ac92. In case someone need it.

**Comment by max-wittig** [comment]
@tclh123 Thanks for the update. I would say we close this as a duplicate of #700
