### ISSUE TITLE
Creation project with "." in name works incorrectly.

### ISSUE THREAD

**Issue by Mukhamedgarif** [python-gitlab/python-gitlab#1006]
## Description of the problem, including code/CLI snippet
I'm trying to create project with "." in both name and path, using:
```python
gl.projects.create({'namespace_id': group.id, 'name': projectName, 'path': projectName})
```

## Expected Behavior
Name and path are the same and equal to actual "projectName".
URL git_url/test_group/project.test
## Actual Behavior
Name is correct, but path has "." replaced with "-".
For example "project.test" has path "project-test".
URL: git_url/test_group/project-test

## Specifications

  - python-gitlab version: 1.12.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.1.4-ee

**Comment by max-wittig** [comment]
Thanks for the report. I guess GitLab changed it now that `.` is allowed in the path and name.

I don't think that this was possible before.

Btw. it's dangerous to still run `12.1`. There are a lot of critical security vulnabilites out in the open.

**Comment by Mukhamedgarif** [comment]
Thanks for reply. We tried as an experiment disable replacement and it looks that problem was solved.
gitlab/v4/objects.py
```python
- file_path = file_path.replace('/', '%2F').replace('.', '%2E')
+ file_path = file_path.replace('/', '%2F').replace('.', '.')
```

gitlab/__init__.py
```python
- new_path = parsed.path.replace('.', '%2E')
+ new_path = parsed.path.replace('.', '.')
```

But the question is: why %2E - "." becomes %2D - "-"?

In 12.1.4 I hadn't got any problems with creating project with "." in web UI.
