### ISSUE TITLE
How to integrate python-gitlab api in django application

### ISSUE THREAD

**Issue by pchandu587** [python-gitlab/python-gitlab#1012]
import gitlab
gl = gitlab.Gitlab('https://gitlab.com/***********',
                       private_token='*****************')
gl.auth()
projects = gl.projects.list()
return HttpResponse(projects[0].name)

I am try to get project name. But it shows error.
raise GitlabParsingError(error_message="Failed to parse the server message") 
How to solve this error. Can u please help me

**Comment by max-wittig** [comment]
Are you using a proxy in your application?

**Comment by pchandu587** [comment]
@max-wittig i didn't used any proxy

**Comment by max-wittig** [comment]
@pchandu587 Could you please provide more information about your environment?

I'm not having any trouble to integrate python-gitlab with django.

**Comment by max-wittig** [comment]
Feel free to re-open, if you got more info
