### ISSUE TITLE
How to upload files

### ISSUE THREAD

**Issue by niezhiyuan1** [python-gitlab/python-gitlab#1013]
## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
You can find the docs here: https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-files

**Comment by niezhiyuan1** [comment]
> You can find the docs here: https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-files

Thank you very much for your reply, this question has been solved, thanks @max-wittig
