### ISSUE TITLE
Add topic: gitlab-cli

### ISSUE THREAD

**Issue by katrinleinweber** [python-gitlab/python-gitlab#1019]
Thanks for publishing this! I think it would be better findable, if displayed on [GitHub.com/topics/gitlab-cli](https://github.com/topics/gitlab-cli), please consider [adding that topic](https://help.github.com/articles/about-topics/) to this repo. Thank you :-)

**Comment by max-wittig** [comment]
The CLI is actually kind of unmaintained, so I don't want to promote it even more. I would recommend this one: https://github.com/michaellihs/golab
