### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by heidricha** [python-gitlab/python-gitlab#1029]
## Description of the problem, including code/CLI snippet
Cannot connect to https site with custom CA-CERT, although CA-CERT is installed system-wide on client machine

## Expected Behavior
[admin@svr1 ~]$ curl https://gitlab/
<html><body>You are being <a href="https://gitlab/users/sign_in">redirected</a>.</body></html>[admin@svr1 ~]$

## Actual Behavior
g1=gitlab.Gitlab('https://gitlab', private_token='YpzMsy-19YmRNpygzyJo');
g1.auth()

...
/usr/local/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    512             if isinstance(e.reason, _SSLError):
    513                 # This branch is for urllib3 v1.22 and later.
--> 514                 raise SSLError(e, request=request)
    515
    516             raise ConnectionError(e, request=request)

SSLError: HTTPSConnectionPool(host='gitlab', port=443): Max retries exceeded with url: /api/v4/user (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),))

## Specifications

  - python-gitlab version: 2.0.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.7.5-ee (19edff260da)

**Comment by nejch** [comment]
The python requests library (which is used for the session) uses its own CA store. You need to tell it explicitly to use the sytem store:

https://stackoverflow.com/a/42982144

**Comment by nejch** [comment]
I've added some docs for this, hopefully this makes it clear.
