### ISSUE TITLE
Get email list for user not working

### ISSUE THREAD

**Issue by Chan9390** [python-gitlab/python-gitlab#1030]
## Description of the problem, including code/CLI snippet

I created a personal access token of Gitlab admin (with `read_user` permission) and tried to access the email of a particular user.

```
import gitlab
gl = gitlab.Gitlab('http://127.0.0.1', private_token='token')
gl.auth()
user = gl.users.list(username='user6')[0]
user.emails.list()
```

The result is 

```
[]
```

## Expected Behavior

Using curl to get information gives the following details:

`curl --header "PRIVATE-TOKEN: token" 'http://127.0.0.1/api/v4/users?username=user10'`

`[{"id":6,"name":"user 10","username":"user10","state":"active","avatar_url":"https://www.gravatar.com/avatar/006a8679155473958833a56b803eaf7d?s=80\u0026d=identicon","web_url":"http://127.0.0.1/user10","created_at":"2020-02-24T10:53:32.901Z","bio":null,"location":null,"public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":null,"last_sign_in_at":"2020-02-24T10:53:32.951Z","confirmed_at":"2020-02-24T10:53:32.767Z","last_activity_on":"2020-02-24","email":"user10@gmail.com","theme_id":1,"color_scheme_id":1,"projects_limit":100000,"current_sign_in_at":"2020-02-24T10:53:32.951Z","identities":[],"can_create_group":true,"can_create_project":true,"two_factor_enabled":false,"external":false,"private_profile":null,"is_admin":false}]`

Ideally the list should provide the following output:

```
['user10@gmail.com']
```

## Actual Behavior

The actual result is 

```
[]
```

## Specifications

  - python-gitlab version: 2.0.1
  - API version you are using (v3/v4): -
  - Gitlab server version (or gitlab.com): 11.10.4

**Comment by vishes-shell** [comment]
Why are you having different queries?

You have `username=user6` with `python-gitlab`, and `username=user10` with `curl`.

user**6** != user**10**

**Comment by Chan9390** [comment]
Sorry, I had posted the wrong curl command and output.

Curl command: `curl --header "PRIVATE-TOKEN: token" 'http://127.0.0.1/api/v4/users?username=user6'`

Curl output:

`[{"id":5,"name":"User 6","username":"user6","state":"active","avatar_url":"https://www.gravatar.com/avatar/498fac57d67a4fec6cd6c4bf53667b12?s=80\u0026d=identicon","web_url":"http://192.168.56.100/user6","created_at":"2020-02-24T09:22:48.252Z","bio":null,"location":null,"public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":null,"last_sign_in_at":"2020-02-24T09:22:48.283Z","confirmed_at":"2020-02-24T09:22:47.958Z","last_activity_on":"2020-02-24","email":"user6@badshah","theme_id":1,"color_scheme_id":1,"projects_limit":100000,"current_sign_in_at":"2020-02-24T13:20:43.132Z","identities":[],"can_create_group":true,"can_create_project":true,"two_factor_enabled":false,"external":false,"private_profile":null,"is_admin":false}]`

The python code:

```
import gitlab
gl = gitlab.Gitlab('http://127.0.0.1', private_token='token')
gl.auth()
user = gl.users.list(username='user6')[0]
user.emails.list()
```
Python output:

`[]`

**Comment by vishes-shell** [comment]
@Chan9390 you can see in the docs: https://docs.gitlab.com/ee/api/users.html#list-emails-for-user thats accessing user emails is available only for _admins_. If you want to access primary user email, you can get it from `user.email`.

**Comment by vishes-shell** [comment]
@Chan9390 you can try to get same output from `curl` for your _user_ (`username='user6'`)

```bash
curl --header "PRIVATE-TOKEN: token" 'http://127.0.0.1/api/v4/users/5/emails'
```

So thats equal to `gl.users.list(username='user6')[0].emails.list()`

**Comment by Chan9390** [comment]
> @Chan9390 you can see in the docs: https://docs.gitlab.com/ee/api/users.html#list-emails-for-user thats accessing user emails is available only for admins.

I am using admin's personal access token

> curl --header "PRIVATE-TOKEN: token" 'http://127.0.0.1/api/v4/users/5/emails'

I get `[]`

**Comment by vishes-shell** [comment]
@Chan9390 so that's why you are getting empty list. So that's expected behaviour and `python-gitlab` works correctly.

I believe gitlab doesn't include default email in list of user emails.

**Comment by Chan9390** [comment]
But the below curl gives the email of the user:

`curl --header "PRIVATE-TOKEN: token" 'http://127.0.0.1/api/v4/users/5'`

`{"id":5,"name":"User 6","username":"user6","state":"active","avatar_url":"https://www.gravatar.com/avatar/498fac57d67a4fec6cd6c4bf53667b12?s=80\u0026d=identicon","web_url":"http://127.0.0.1/user6","created_at":"2020-02-24T09:22:48.252Z","bio":null,"location":null,"public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":null,"last_sign_in_at":"2020-02-24T13:20:43.132Z","confirmed_at":"2020-02-24T09:22:47.958Z","last_activity_on":"2020-02-27","email":"user6@badshah","theme_id":1,"color_scheme_id":1,"projects_limit":100000,"current_sign_in_at":"2020-02-27T09:55:22.508Z","identities":[],"can_create_group":true,"can_create_project":true,"two_factor_enabled":false,"external":false,"private_profile":null,"is_admin":false,"highest_role":40}`

Is it possible to get the email using python-gitlab ?

**Comment by vishes-shell** [comment]
@Chan9390 as i was saying earlier:

> @Chan9390 you can see in the docs: https://docs.gitlab.com/ee/api/users.html#list-emails-for-user thats accessing user emails is available only for _admins_. If you want to access primary user email, you can get it from `user.email`.

you can get email from `user.email`.:)

**Comment by max-wittig** [comment]
@Chan9390 Feel free to re-open, if this doesn't solve the issue!
