### ISSUE TITLE
project.wikis.list() results in AttributeError: wikis

### ISSUE THREAD

**Issue by kernelport** [python-gitlab/python-gitlab#1031]
## Description of the problem, including code/CLI snippet
pages = project.wikis.list()

## Expected Behavior
Should List the wikis 

## Actual Behavior
Traceback (most recent call last):
  File "/home/neuber/anaconda3/lib/python3.7/site-packages/gitlab/base.py", line 60, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'wikis'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neuber/anaconda3/lib/python3.7/site-packages/gitlab/base.py", line 63, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'wikis'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neuber/anaconda3/lib/python3.7/site-packages/gitlab/base.py", line 83, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'wikis'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./unfuddle-notebook.py", line 303, in <module>
    pages = project.wikis.list()
  File "/home/neuber/anaconda3/lib/python3.7/site-packages/gitlab/base.py", line 85, in __getattr__
    raise AttributeError(name)
AttributeError: wikis

## Specifications

  - python-gitlab version: 2.0.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com and self hostet

**Comment by kernelport** [comment]
gitlab.com version ('12.9.0-pre', '80496c1469a')

**Comment by vishes-shell** [comment]
@kernelport can you show the way you retrieve your `project` variable?

**Comment by kernelport** [comment]
@vishes-shell this is the way I find the project
##############################
project = None
project_name='xxx'
projects = group.projects.list()
for project_ in projects:
    print("project in "+group_name+":", project_.name, project_.id)
    if project_.name == project_name:
        project = project_

if not project:
    project = root_gl.projects.create({'name': project_name, 'namespace_id': group.id, 'visibility': 'private'})

print("project:", project)

##################
project in groupname: xxx 17125117
project: <class 'gitlab.v4.objects.GroupProject'> => {'id': 17125117, 'description': None, 'name': 'xxx', 'name_with_namespace': 'groupname / xxx', 'path': 'xxx', 'path_with_namespace': 'groupname/xxx', 'created_at': '2020-02-25T14:13:02.573Z', 'default_branch': None, 'tag_list': [], 'ssh_url_to_repo': 'git@gitlab.com:groupname/xxx.git', 'http_url_to_repo': 'https://gitlab.com/groupname/xxx.git', 'web_url': 'https://gitlab.com/groupname/xxx', 'readme_url': None, 'avatar_url': None, 'star_count': 0, 'forks_count': 0, 'last_activity_at': '2020-02-25T14:13:02.573Z', 'namespace': {'id': 7260246, 'name': 'groupname', 'path': 'groupname', 'kind': 'group', 'full_path': 'groupname', 'parent_id': None, 'avatar_url': None, 'web_url': 'https://gitlab.com/groups/groupname'}, '_links': {'self': 'https://gitlab.com/api/v4/projects/17125117', 'issues': 'https://gitlab.com/api/v4/projects/17125117/issues', 'merge_requests': 'https://gitlab.com/api/v4/projects/17125117/merge_requests', 'repo_branches': 'https://gitlab.com/api/v4/projects/17125117/repository/branches', 'labels': 'https://gitlab.com/api/v4/projects/17125117/labels', 'events': 'https://gitlab.com/api/v4/projects/17125117/events', 'members': 'https://gitlab.com/api/v4/projects/17125117/members'}, 'empty_repo': True, 'archived': False, 'visibility': 'private', 'resolve_outdated_diff_discussions': False, 'container_registry_enabled': True, 'container_expiration_policy': {'cadence': '7d', 'enabled': False, 'keep_n': None, 'older_than': None, 'name_regex': None, 'next_run_at': '2020-03-03T14:13:02.617Z'}, 'issues_enabled': True, 'merge_requests_enabled': True, 'wiki_enabled': True, 'jobs_enabled': True, 'snippets_enabled': True, 'can_create_merge_request_in': True, 'issues_access_level': 'enabled', 'repository_access_level': 'enabled', 'merge_requests_access_level': 'enabled', 'wiki_access_level': 'enabled', 'builds_access_level': 'enabled', 'snippets_access_level': 'enabled', 'pages_access_level': 'private', 'emails_disabled': None, 'shared_runners_enabled': True, 'lfs_enabled': True, 'creator_id': 5502279, 'import_status': 'none', 'open_issues_count': 0, 'ci_default_git_depth': 50, 'public_jobs': True, 'build_timeout': 3600, 'auto_cancel_pending_pipelines': 'enabled', 'build_coverage_regex': None, 'ci_config_path': None, 'shared_with_groups': [], 'only_allow_merge_if_pipeline_succeeds': False, 'request_access_enabled': True, 'only_allow_merge_if_all_discussions_are_resolved': False, 'remove_source_branch_after_merge': True, 'printing_merge_request_link_enabled': True, 'merge_method': 'merge', 'suggestion_commit_message': None, 'auto_devops_enabled': False, 'auto_devops_deploy_strategy': 'continuous', 'autoclose_referenced_issues': True, 'mirror': False, 'external_authorization_classification_label': ''}

**Comment by kernelport** [comment]
I found the Solution by myself.
I got a GroupProject instead of a Project.
If I retrieve the project variable by projects = gl.projects.list() I get a Project object.
