### ISSUE TITLE
Example of usage - List all jobs from other user

### ISSUE THREAD

**Issue by jacksonpradolima** [python-gitlab/python-gitlab#1046]
Hello,
I am developing a research concerning CI testing, and I need to download the jobs. However, I am not the owner of the project. 
How can I access and download all jobs?

Thanks in advance

**Comment by max-wittig** [comment]
I'm not sure how I can help you. python-gitlab is just a wrapper around the [Gitlab API](https://docs.gitlab.com/ce/api/). You can download artifacts using the [artifacts wrapper](https://python-gitlab.readthedocs.io/en/stable/gl_objects/pipelines_and_jobs.html#id8)

Feel free to re-open, if you got any further questions.
