### ISSUE TITLE
Scope "bug"

### ISSUE THREAD

**Issue by sauravpandit** [python-gitlab/python-gitlab#1057]
## Description of the problem, including code/CLI snippet
I am using the list method of project.issues to list issues with certain label. I am searching issue having "vulcheck" as label. In my project I have one issue with "vulcheck" label

```python
def issue_by_project_label(self):
    print(self._project.issues.list(labels="vulcheck"))
```

## Expected Behavior
It should return me the issues with label "vulcheck". I have one issue with label "vulcheck".

## Actual Behavior
It is returning empty list

## Specifications

  - python-gitlab version: 2.1.2
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.6.6-ee

**Comment by nejch** [comment]
Thanks for the report @sauravpandit. I will be submitting a fix shortly.

In the meantime, as a workaround you can supply the label as a list with a single item instead of just a string:
```python
def issue_by_project_label(self):
    print(self._project.issues.list(labels=["vulcheck"]))
```
