### ISSUE TITLE
Documentation is missing an example how to make use of project import parameters

### ISSUE THREAD

**Issue by pritho** [python-gitlab/python-gitlab#1060]
## Description of the problem, including code/CLI snippet
Documentation is missing an example how to make use of project import parameters.
The Gitlab-API supports these parameters (name,file,path,overwrite) 

## Expected Behavior
It would be good to add an example to the documentation (if those parameters are supported) 

## Specifications

  - python-gitlab version: latest
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): EE

**Comment by nejch** [comment]
Hi @krathow, do you just want a more descriptive example with additional parameters, or do you mean that all of the API parameters (required and optional) should always be described in the examples?

I think it's sensible to add a more verbose example (also, feel free to open a PR! :)).

But keeping up to date with *all* of the parameters in the prose examples might be difficult long-term, as GitLab updates parameters probably every month that are sometimes tricky to track (but generally not an issue, as they are easy to supply in the dict param, as long as you refer to the GitLab API docs).

Maybe a clearer reference to check the GitLab API for the full list of parameters would help as well.

**Comment by krathow** [comment]
Hello @nejch :
Thanks for your answer.
Well I would happily create a MR if I understood the details here:
`gl.projects.import_project(open('/tmp/export.tgz',` 'rb'), `'my_new_project')`
has a file and a name in the call, but I would like to use further necessary parameteres like namespace,name or path which are essential here as per the API-description.
I fully understand that it is out of scope to keep following up with gitlab's API-changes,
but as the python project is a wrapper, I was just wondering about the exact syntax to use for specific settings, like for example:

path="mygroup/project1"
namespace="group123/place1"

**Comment by omonnig** [comment]
I'm having issues with `import_project`:

`    output = gl.projects.import_project(
        open(temp_dir + "/" + "gitlab-export.tgz", "rb"),
        project_path,
        name=str(project_name),
        namespace=str(project_namespace),
        overwrite=False,
        override_params={
            'description': project_description
        },
    )
`

The project imports fine, but the description attribute is None

A clear example of how to use 'override_params` would be really helpful.  I've tried several variations by modifying the source code locally, but still no joy.  The Gitlab API docs are of little help here.

Thanks,
Otto

**Comment by omonnig** [comment]
Taking advantage of Open Source and my own advice (read the source), I was able to dig into the libraries on both sides:

[python-gitlab](https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/v4/objects/projects.py)

[python-gitlab tests](https://github.com/python-gitlab/python-gitlab/blob/master/tools/functional/api/test_import_export.py)

[GitLab](https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/api/project_import.rb)

Through testing, it is not possible to change any repository parameters by injecting through `overwrite_params`.

This is the correct method to call the function:
`
output = gl.projects.import_project( 
open(temp_dir + "/" + "gitlab-export.tgz", "rb"), 
project_path, name=str(project_name), 
namespace=str(project_namespace), 
overwrite=False)
`

To modify project parameters, get() the project, modify the data fields and save() the project

**Comment by omonnig** [comment]
Thank you!

**Comment by pritho** [comment]
thanks!
