### ISSUE TITLE
Limited to 20 environment variables

### ISSUE THREAD

**Issue by MathieuCesbron** [python-gitlab/python-gitlab#1061]
When I retrieve a specific environment for a project, let's say:

` environment = project.environments.get(112)`

I only get the first 20 environment variables. 

If my my project has more than 20 environment variables, how can I get them all ?

Thanks in advance

**Comment by max-wittig** [comment]
The Gitlab API is paged. See https://docs.gitlab.com/ee/api/

To get all objects use the all=True argument.
