### ISSUE TITLE
How to delete identities with the API?

### ISSUE THREAD

**Issue by NikolausDemmel** [python-gitlab/python-gitlab#1070]
## Description of the problem, including code/CLI snippet

```
user.identities = []
user.save()
```

## Expected Behavior

Identities are deleted.

## Actual Behavior

Identities are unchanged.

## Specifications

  - python-gitlab version: 2.2.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.9

**Comment by NikolausDemmel** [comment]
I found out you can do:

```
for i in user.identities:
    gl.http_delete("/users/{}/identities/{}".format(user.get_id(), i["provider"]))
```

Would be nice to include in the API, but it works for now.

**Comment by nejch** [comment]
It seems like to delete an identity, you need to use a separate API endpoint:

https://docs.gitlab.com/ee/api/users.html#delete-authentication-identity-from-user

This still needs to be added to python-gitlab, I'll try to submit a PR soon. Thanks for the report and the workaround! ;)

**Comment by NikolausDemmel** [comment]
Ok cool. Thanks for this nice project btw!
