### ISSUE TITLE
ParticipantsMixin doesn't paginate?

### ISSUE THREAD

**Issue by 7adietri** [python-gitlab/python-gitlab#1084]
## Description of the problem, including code/CLI snippet

When calling `issue.participants(all=True)` or `issue.participants(as_list=False)` on a project issue with more than 20 participants, I only receive 20 of them.

It works when I call `issue.participants(per_page=100)`.

## Expected Behavior

The first two calls should return all issue participants.

## Actual Behavior

Only 20 participants are returned by the first two calls.

The call `issue.participants(as_list=False)` still returns a `list`.

## Specifications

  - python-gitlab version: 2.2.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by max-wittig** [comment]
Sadly this is not an issue in python-gitlab. I just tried it with a REST client. No matter what you send as http header. GitLab will only return 20 items on this endpoint

**Comment by max-wittig** [comment]
So you might want to search for an issue upstream/create an issue upstream.

**Comment by 7adietri** [comment]
I was just going to create an issue for GitLab, and tried to create a `curl` command for demonstrating the bug, but it looks to me like the API is responding correctly.

I used [this issue](https://gitlab.com/gitlab-com/www-gitlab-com/-/issues/8167) with 24 participants. Running this command:

    curl -s -H "Private-Token: TOKEN" "https://gitlab.com/api/v4/projects/7764/issues/8167/participants" -v | jq '.|length'

Returns 20 participants and a `Link` header containing a `next` URL, which returns the remaining 4 participants. Meanwhile, `python-gitlab` at version 2.5.0 still behaves as described above.

Am I overlooking something?
