### ISSUE TITLE
Can I get issue globally by "id" (not "iid") without specify the project?

### ISSUE THREAD

**Issue by stephane-klein** [python-gitlab/python-gitlab#1088]
Can I get issue globally by `id` (not `iid`) without specify the project?

For instance:

```
gl.issues.get(id=57566932)
```

Best regards,
Stéphane

**Comment by max-wittig** [comment]
Sadly that's not possible. This is just a wrapper around the Gitlab API and Gitlab doesn't seem to offer this endpoint.
