### ISSUE TITLE
Can't get informations with simple config

### ISSUE THREAD

**Issue by duane-etagen** [python-gitlab/python-gitlab#1095]
## Description of the problem, including code/CLI snippet

I am unable to access gitlab using a simple configuration file.

```
[global]
default=https://gitlab.com

[duane]
private_token=random-bits
```

## Expected Behavior

Successful connection and project listing

## Actual Behavior

$ gitlab --debug --verbose project --list
Impossible to get gitlab informations from configuration (https://gitlab.com)

## Specifications

  - python-gitlab version: 
```
$ gitlab --version
2.2.0
```
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by orzechow** [comment]
I guess you should use the correct syntax and variables:

```
[global]
default=duane

[duane]
url=https://gitlab.com
private_token=random-bits
```

See https://python-gitlab.readthedocs.io/en/stable/cli.html#content

**Comment by max-wittig** [comment]
@orzechow Just wanted to also paste this. Thanks for the help!
