### ISSUE TITLE
Load project pipelines created after a given date 

### ISSUE THREAD

**Issue by fdbatista** [python-gitlab/python-gitlab#1097]
## Description of the problem, including code/CLI snippet

Fetching the list of pipelines for a project returns the whole list of elements.
The problem is that I am trying to get this info for a project with more than 9000 executed pipelines, so it would be nice if we could use some parameter-based filtering like the `updated_after` one available in the Gitlab API. 

## Expected Behavior

Fetching data would be more efficient, something like this:
`project.pipelines.list(updated_after="2020-05-12T03:34:21.0324z")`

## Actual Behavior

If there are too many pipelines, the process hangs or takes too long.

## Specifications

  - python-gitlab version: 2.2.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
Doing `project.pipelines.list(updated_after='2020-09-01T09:16:19.567+02:00', all=True)` works as expected for me, and is much faster than fetching all pipelines in a project with several thousand pipelines.

Or do you mean that there should be a separate `created_after` parameter? In that case, you'll need to file an upstream bug at https://gitlab.com/gitlab-org/gitlab.

`python-gitlab` can only work with what's returned from the server, so it would still need to fetch all pipeline if you wanted to filter them on the client side.

**Comment by nejch** [comment]
I'll close this as I think the library works as expected, if there's a missing API filter this should be opened upstream, see link above.

If your API call still takes too long even with `updated_after`, I'd just increase the timeout e.g. with https://python-gitlab.readthedocs.io/en/stable/api-usage.html#timeout. Feel free to reopen though if still having issues :)
