### ISSUE TITLE
How to get the branch creation time

### ISSUE THREAD

**Issue by zzt-chun** [python-gitlab/python-gitlab#1103]
## Description of the problem, including code/CLI snippet
    How to get branch creation time like git command "git reflog show --date = iso master"
     Example    
     The branch creation time is "2019-12-23T18:41:30.000+08:00" and the latest commit time is "2020-05-22T19:23:14.000+08:00"

## Expected Behavior
    Branch creation time   "2019-12-23T18:41:30.000+08:00"

## Actual Behavior
    project.branches.get(target_branche)
    =>created_at = "2020-05-22T19:23:14.000+08:00"

## Specifications

  - python-gitlab version: 2.2.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
This is not returned by the GitLab API for branches, see https://docs.gitlab.com/ee/api/branches.html#get-single-repository-branch. You can file an upstream request at https://gitlab.com/gitlab-org/gitlab.

I'm also not sure local git reflog commands can really be compared to the server, it would more likely be the time of the first push.

You do get the latest commit time though:
```python
branch = project.branches.get('master')
latest_commit = branch.commit['created_at']
```

**Comment by max-wittig** [comment]
Unrelated to python-gitlab and already answered. GitLab sadly doesn't provide this information. Feel free to re-open, if you have further questions
