### ISSUE TITLE
Fix readthedocs deployment for python3

### ISSUE THREAD

**Issue by nejch** [python-gitlab/python-gitlab#1104]
It seems the RTD docs have not been properly deploying since the drop in python2 support, see:

https://readthedocs.org/projects/python-gitlab/builds/11110459/

A quick simple fix would probably just be to change the interpreter version to python3 in the RTD admin panel, but as a bonus it would be nice to eventually switch as much config as possible into the repo (would just need to extract some info from the RTD GUI):

https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by max-wittig** [comment]
Didn't even know about the admin panel! I added you as maintainers and switched the python version.
