### ISSUE TITLE
Fix snippet integration tests for GitLab 13.0

### ISSUE THREAD

**Issue by nejch** [python-gitlab/python-gitlab#1105]
I was working on something unrelated and snippet tests kept failing.. turns out that when GitLab introduced versioned snippets in 13.0, along the way there's been some changes in the create/update API behavior that broke the functional tests (maybe this one https://gitlab.com/gitlab-org/gitlab/-/commit/ac3438f5c2a4da780e730660bccea5f4ac12483d).

**Comment by max-wittig** [comment]
This does look like a GitLab error. Renaming the snippet via API deletes it's contents.

**Comment by max-wittig** [comment]
I reproduced it with curl and create an upstream issue: https://gitlab.com/gitlab-org/gitlab/-/issues/219348

**Comment by max-wittig** [comment]
This will be fixed in 13.1. by GitLab. It would say we leave it in our tests like this for now or should we add allow_fail? @nejch

**Comment by nejch** [comment]
Looks like I forgot about this one, but the tests are included as of https://github.com/python-gitlab/python-gitlab/pull/1205 :)
