### ISSUE TITLE
Changes to container_expiration_policy are not send to the GitLab server

### ISSUE THREAD

**Issue by drietmueller** [python-gitlab/python-gitlab#1106]
## Description of the problem, including code/CLI snippet
Changes made to the `container_expiration_policy` are not propagated to the GitLab server.

```python
project = ...
project.container_expiration_policy["enabled"] = False
project.save()
```
The `save` call does not send anything to the server. The reason for this seems to be that the `container_expiration_policy` is a dictionary which is returned by `gitlab.base.RESTObject.__getattr__` without any wrapping so changes to this dict are not tracked and therefore not send to the server when `save` is called.
 
## Expected Behavior
Changes to the property `container_expiration_policy` are send to the GitLab server when the `save` method is called.

## Actual Behavior
Nothing is send to the GitLab server.

## Specifications

  - python-gitlab version: 2.2.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.10.3-ee

**Comment by jeff-cook** [comment]
Still an issue with `python-gitlab==3.2.0`

(gitlab.com) GitLab Enterprise Edition 14.9.0-pre.

**Comment by jeff-cook** [comment]
> Found something interesting when updating the value you use `container_expiration_policy_attributes` instead of `container_expiration_policy`.
> 
> But when you read it is `container_expiration_policy`.

I did test setting `container_expiration_policy_attributes` with `python-gitlab==3.2.0` and it did work.

**Comment by nejch** [comment]
As @jeff-cook found out, sometimes the attributes returned by a GET call cannot be used in a POST/PUT call to edit an object. This is an upstream decision/issue and not something we can change here without a lot of custom code.

So in these cases you should follow upstream API docs on POST endpoints. Perhaps we can document this to avoid confusion in the future before we close this.

**Comment by SamirNabadov** [comment]
Hello, I have problem with container_expiration_policy. I want create project with adding  container_expiration_policy  settings. Could you help me how I can make it?

**Comment by nejch** [comment]
> Hello, I have problem with container_expiration_policy. I want to create project with adding container_expiration_policy settings. Could you help me how I can make it?

@SamirNabadov please read https://github.com/python-gitlab/python-gitlab/issues/1106#issuecomment-1063352888

**Comment by SamirNabadov** [comment]
I have read it, my problem is solved, thanks!

**Comment by nejch** [comment]
Revisiting this.. for now I think we should maybe avoid manual mappings when the upstream API has inconsistencies, as it's a maintenance burden even with existing attributes that we maintain manually.

For those who hit this issue, see comments above on what attributes are used by GitLab for POST vs GET.

If anyone disagrees here please just let us know, reopen, or open a new issue :)
