### ISSUE TITLE
Parse webhook JSON data?

### ISSUE THREAD

**Issue by koliyo** [python-gitlab/python-gitlab#1117]
## Description of the problem, including code/CLI snippet
How to get gitlab API representation from webhook event JSON data?

Eg if I have a Flask webserver receiving webhook data from a GitLab server.

## Expected Behavior
I can not find any documentation/example on how to convert GitLab webhook json data to API data using this library. It this not a good approach?

https://docs.gitlab.com/ee/user/project/integrations/webhooks.html

**Comment by max-wittig** [comment]
You can actually get all the attributes from an object using the `.attributes` property.

Does that help?

**Comment by koliyo** [comment]
Not sure I follow, I get a JSON string from the GitLab server.  And I can parse using normal python json parsing.

But to access members i now do like this

```py
data['user']['avatar_url']
```

I would instead like to do
```py
data.user.avatar_url
```

Maybe I can use any of the many existing auto-class/tuple generators available in PYPI, but I thought maybe this project had some mapping already available.

**Comment by max-wittig** [comment]
It does have some mappings, but it's hard to always keep up with the GitLab API. Not ever detail is mapped.

**Comment by koliyo** [comment]
Ok, thanks for response anyway! I'm closing this issue.
