### ISSUE TITLE
when i export my project ,it always throw gitlab.exceptions.GitlabCreateError: 404: 404 Not Found exception ,why ?

### ISSUE THREAD

**Issue by congratulation** [python-gitlab/python-gitlab#1118]
## Description of the problem, including code/CLI snippet
export my project

`    @staticmethod
    def export_project(project_id):
        # Create the export

        p = GitlabAPI.get_project(project_id)
        export = p.exports.create()

        # Wait for the 'finished' status
        export.refresh()
        while export.export_status != 'finished':
            time.sleep(1)
            export.refresh()

        # Download the result
        with open('/tmp/export.tgz', 'wb') as f:
            export.download(streamed=True, action=f.write)`
## Expected Behavior
no exception 

## Actual Behavior
Traceback (most recent call last):
  File "D:\workspace\seaway-backend\venv\lib\site-packages\gitlab\exceptions.py", line 279, in wrapped_f
    return f(*args, **kwargs)
  File "D:\workspace\seaway-backend\venv\lib\site-packages\gitlab\mixins.py", line 214, in create
    server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
  File "D:\workspace\seaway-backend\venv\lib\site-packages\gitlab\__init__.py", line 687, in http_post
    **kwargs
  File "D:\workspace\seaway-backend\venv\lib\site-packages\gitlab\__init__.py", line 575, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 404: 404 Not Found

## Specifications

  - python-gitlab version: 2.3.1
  - API version you are using (v3/v4):v4
  - Gitlab server version (or gitlab.com):9.4.1

**Comment by max-wittig** [comment]
Your GitLab version is highly insecure and not supported anymore, neither by GitLab nor by python-gitlab. GitLabs API might have changed in the meantime. Please try again with the latest version of GitLab and feel free to re-open, if it also happens there.
