### ISSUE TITLE
Unable to list active users

### ISSUE THREAD

**Issue by jsandova** [python-gitlab/python-gitlab#1122]
## Description of the problem, including code/CLI snippet
I am not able to list only active users or blocked users
root@gitlab:/var/log/gitlab/gitlab-rails# gitlab -g gitlab user list --active ACTIVE
Impossible to list objects (400: active is invalid)

root@gitlab:/var/log/gitlab/gitlab-rails# gitlab -g gitlab user list --blocked BLOCKED
Impossible to list objects (400: blocked is invalid)

## Expected Behavior
Should list active users or blocked users

## Actual Behavior
root@gitlab:/var/log/gitlab/gitlab-rails# gitlab -g gitlab user list --active ACTIVE
Impossible to list objects (400: active is invalid)

## Specifications

  - python-gitlab version: 1.15.0
  - API version you are using (v3/v4): 4
  - Gitlab server version (or gitlab.com):12.6.3

**Comment by nejch** [comment]
the `active` parameter is a boolean, so you need `true` or `false`:

```bash
gitlab -g gitlab user list --active true
gitlab -g gitlab user list --active false
gitlab -g gitlab user list --blocked true
gitlab -g gitlab user list --blocked false
```

See https://docs.gitlab.com/ce/api/users.html#for-normal-users

Please re-open if this didn't help :)
