### ISSUE TITLE
Wrong forks.create() example in docs

### ISSUE THREAD

**Issue by claudep** [python-gitlab/python-gitlab#1126]
On https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html?highlight=fork#examples, there is an example to create a fork with `fork = project.forks.create()` which is raising `TypeError` because the first positional `data` argument is mandatory. If passing an empty dict, Gitlab replies with 403: insufficient_scope.

**Comment by nejch** [comment]
Ahhh.. looks like this is an issue for a few managers that override CreateMixin's `create()`. I added a small change recently to avoid having to pass empty dicts, but this won't do for custom create methods.
https://github.com/python-gitlab/python-gitlab/blob/1d82310da1a15f7172a3f87c2cf062bc0c17944d/gitlab/v4/objects.py#L2442

Passing an empty dict should definitely work though, the 403 you're getting is probably a permission issue or the fork already exists in your namespace.

**Comment by claudep** [comment]
Your are totally right, the 403 was due to a read-only API token.
