### ISSUE TITLE
project members list returns empty list

### ISSUE THREAD

**Issue by Raysultan** [python-gitlab/python-gitlab#1129]
## Description of the problem, including code/CLI snippet
Hi guys, thank you for great work. Currently I am using 1.5.1 version of the package, cause our project uses Python 3.5. I was trying to get list of members of the project and the result is empty list every time. Is there any solutions or suggestions? 

## Expected Behavior
project.members.list() => list of ProjectMember instances

## Actual Behavior
project.members.list() => empty list

## Specifications

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by max-wittig** [comment]
I think your project might have no members. If you also want `inherited` members, you'll need to use `all`

https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-members

```python
project.members.all()
```

Feel free to re-open if you have further questions

**Comment by Raysultan** [comment]
> I think your project might have no members. If you also want `inherited` members, you'll need to use `all`
> 
> https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-members
> 
> ```python
> project.members.all()
> ```
> 
> Feel free to re-open if you have further questions

Thank you for your reply, the thing is that I tried it.
```
AttributeError: 'ProjectMemberManager' object has no attribute 'all'
```
As I said, we use 1.5.1 version of your package. Is there a way out?

**Comment by max-wittig** [comment]
I guess this was introduced later. Then I'm sorry, you'll need to upgrade. What's the reason for not upgrading to the latest version? python3.5 is gonna be dropped offically in september anyway (no more security fixes): https://devguide.python.org/#status-of-python-branches.

I may have dropped 3.5 support a bit early, but I can't really support all python versions with this library.

**Comment by Raysultan** [comment]
> I guess this was introduced later. Then I'm sorry, you'll need to upgrade. What's the reason for not upgrading to the latest version? python3.5 is gonna be dropped offically in september anyway (no more security fixes): https://devguide.python.org/#status-of-python-branches.
> 
> I may have dropped 3.5 support a bit early, but I can't really support all python versions with this library.

I got it, thank you very much. Great workj!
