### ISSUE TITLE
Project Import/Export on existing export [help needed]

### ISSUE THREAD

**Issue by Raysultan** [python-gitlab/python-gitlab#1135]
## Description of the problem, including code/CLI snippet
Hi! In the docs on project import/export it's said that you have to create the export and continue the process. What if I have already exported project that just has to be imported. Is there a way to download that export through the API?

## Specifications

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by max-wittig** [comment]
Not with python-gitlab I guess, because you don't have an Export object anymore.

Might be worth to add export by id. For now you can just use the GitLab export API

https://docs.gitlab.com/ee/api/project_import_export.html#export-download

**Comment by Raysultan** [comment]
Understood, thanks! Great job!
