### ISSUE TITLE
Allow export with project id

### ISSUE THREAD

**Issue by max-wittig** [python-gitlab/python-gitlab#1136]
Related to https://github.com/python-gitlab/python-gitlab/issues/1135

Usecase:

* You've started the export of a GitLab project, but `lost` the object somehow. E.g. script failed, other script is used

Should work like this:

```python
gl.projects.get(1).exports.create()
gl.exports.get(134).download()
```

**Comment by nejch** [comment]
I'm not sure this is possible with the current GitLab API - it doesn't create any ID's, the status returned is always for the "latest" export (triggered either by API or web UI)

Seems like you can just do this:
1. export via curl/other script/web GUI/python-gitlab
2. doesn't matter what happens after, as long as the latest export status is still finished (stays for 24 hours I think)
2. `export = project.exports.get()` -> doesn't need IDs
3. `export.download()`

So maybe either an upstream issue (to version exports with IDs) or just document this a little better?
