### ISSUE TITLE
commit.diff() cann't return all information and how to realize git diff --name-only

### ISSUE THREAD

**Issue by cthv5** [python-gitlab/python-gitlab#1141]
## Description of the problem, including code/CLI snippet
I want to get the list of all the files committed this time, however commit.diff() only return partial information,I guess there is paging in the return message，so how to get all information like git diff --name-only return

## Expected Behavior
commits = project.commits.list(XXXX)
for commit in commits:
  for file in commit.diff():
     print(file.get('new_path'))

avbove can get all commit files list.

## Actual Behavior
such as one commit has 165 files,only return 39

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):
gitlab.v4
python 3.7

**Comment by max-wittig** [comment]
You can specify how many items per page with the `per_page` parameter.

To get all pages, just supply all=True or `as_list=False`, which gives you an Iterator

```python
import gitlab

gl = gitlab.Gitlab("https://gitlab.com", "token", per_page=100)
project = gl.projects.get(1)
# as list
for commit in project.commits.list(as_list=False):
      print(commit)
# or all
commits = project.commits.list(all=True)
```

**Comment by max-wittig** [comment]
If that doesn't answer your question, feel free to reopen.

**Comment by cthv5** [comment]
thanks,I tried, but it didn't work
![image](https://user-images.githubusercontent.com/38455997/88771556-ff3fa880-d1b1-11ea-8639-240a368a0354.png)
![image](https://user-images.githubusercontent.com/38455997/88771736-42018080-d1b2-11ea-940d-5028499b53d1.png)
commit 'c93cfd77902aab68019bac352ef607a9353e2998' has 66 changed files,but result is 39 .

**Comment by cthv5** [comment]
> If that doesn't answer your question, feel free to reopen.
thanks,I tried, but it didn't work
