### ISSUE TITLE
Fix documentation / help for output and fields command line arguments

### ISSUE THREAD

**Issue by jkirk** [python-gitlab/python-gitlab#1149]
## Description of the problem, including code/CLI snippet

Please compare the `--help` output:

https://github.com/python-gitlab/python-gitlab/blob/1606310a880f8a8a2a370db27511b57732caf178/gitlab/cli.py#L113-L129

with the [CLI documentation](https://github.com/python-gitlab/python-gitlab/blob/1606310a880f8a8a2a370db27511b57732caf17/docs/cli.rst)
```
``--output``, ``-o``
    Output format. Defaults to a custom format. Can also be ``yaml`` or ``json``.

[snip]

``--fields``, ``-f``
    Comma-separated list of fields to display (``yaml`` and ``json`` output
    formats only).  If not used, all the object fields are displayed.
```

A few things to notice here:

* Please tell the user in the CLI documentation that fields can not be set in ``legacy`` output format. I would suggest "Not used with ``legacy`` output format."
* What is the custom format? I assume the same as `legacy`. Please use the same wording. I would suggest to change the line to "Defaults to ``legacy`` (custom) format output. Can also be ``yaml`` or ``json``"
* Please tell the user that the ``legacy`` output format does *not* show all fields (at least is seems so for me).
* (optional) Please tell the user that the output format and fields (currently) can not be configured via config file. (Or can it? *Disclaimer*: Now that I played around a bit it seems a bit difficult to implement because the fields output seem to depend on the query. But still: a default list of limited fields would be nice.)

_I am a first time user and I read RTD documentation first before realizing that the fields can not configure the legacy output format / "custom format"._ 

## Specifications

  - python-gitlab version: 2.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.2.3

**Comment by JohnVillalovos** [comment]
Current help output snippet:

```
  -o {json,legacy,yaml}, --output {json,legacy,yaml}
                        Output format (v4 only): json|legacy|yaml
  -f FIELDS, --fields FIELDS
                        Fields to display in the output (comma separated). Not used with legacy output
  --server-url SERVER_URL
```
