### ISSUE TITLE
Get all projects inside the subgroups not listing all projects

### ISSUE THREAD

**Issue by brenwhyte** [python-gitlab/python-gitlab#1176]
## Description of the problem, including code/CLI snippet

So I'm new to this (any python!) but what I'm trying to do is search all of our GitLab projects and check which ones have AutoDevOps enabled/disabled. So, I'm just wanting to check each project's "project.auto_devops_enabled" value.

Mostly plagiarized from the internet 

```
gl = gitlab.Gitlab(options.url, options.token)
group = gl.groups.get(options.namespace, lazy=True, include_subgroups=True)

projects = []

# Get all projects inside the namespace
for project in group.projects.list(
    all=True, owned=False
):
    projects.append(project)
#    print(" found " + project.path_with_namespace)


# Get all projects inside the subgroups
for group in gl.groups.list(
    all=True, owned=False, query_parameters={"id": options.namespace}
):

    for project in group.projects.list(all=True):
        projects.append(project)
        print("Auto DevOps is", project.auto_devops_enabled, "for", project.path_with_namespace)

```

## Expected Behavior
For each project to be listed with AutoDevops True or False

## Actual Behavior
Appears to work **but** is only showing 666 projects, I know there's 2800+ projects in our namespace.

## Specifications

  - python-gitlab version: 2.5.0  (Python 3.8.5 on Mac)
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

As a second query, assuming I'm not missing anything obvious, how could I change the code to do much the same but check each project's CI variables to see if SAST_DISABLED exists? Looking to see basically who's using AutoDevOps BUT has SAST disabled.

Thanks in advance!

**Comment by nejch** [comment]
`include_subgroups` will not have any effect on your initial `gl.groups.get()`. This is used for the group project list endpoint. See https://docs.gitlab.com/ee/api/groups.html#details-of-a-group vs https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects.

But later when you are calling this (`group.projects.list(all=True)`), you're not using it.

Also, I wouldn't pass ID's manually to `gl.groups.list()`, once you have the initial group object you can operate on it.

```python
group = gl.groups.get(options.namespace, lazy=True)
projects = group.projects.list(include_subgroups=True, all=True)

for project in projects:
    print("Auto DevOps is", project.auto_devops_enabled, "for", project.path_with_namespace)
```

This should already recurse projects from the top-level group down, see how it goes.

**Comment by brenwhyte** [comment]
Hi nejch,

Perfect, that works as expected. The correct number of projects are being returned. 👍 
Thanks for that pointer.

Q2: Would you know how I'd check each project's CI variables to see if `SAST_DISABLED` is added?
I tried with checking the [project ci vars](https://python-gitlab.readthedocs.io/en/stable/gl_objects/variables.html) but can't get that to work.

```
for project in projects:
    print(project.name)

while True:
    for variables in project:
        print(project.variables.get('DAST_DISABLED'))
```
But I get a `TypeError: 'GroupProject' object is not iterable`

Any ideas?

**Comment by nejch** [comment]
Listing a group's projects gives you a list of `GroupProject` objects. You need to create a proper `Project` object from each returned item using its ID to manipulate it. See [documentation](https://python-gitlab.readthedocs.io/en/stable/gl_objects/groups.html). There are other problems with your snippet, probably because you're new to python - but basically you can just try to get the specific project variable by key and skip projects where you get a 404 response (= variable is not there).

A quick snippet might be something like:
```python
for project in projects:
    proj = gl.projects.get(project.id) # Get an editable Project 
    try:
        variable = proj.variables.get('TEST')
        print(f"{proj.path_with_namespace} has {variable.key}")
    except gitlab.exceptions.GitlabGetError:
        pass

```

I'll close this, but if it doesn't solve it for you feel free to re-open :)

**Comment by brenwhyte** [comment]
Thanks nejch, that worked too as expected. I hope this helps any other novice like myself.
Thanks again! 🍻
