### ISSUE TITLE
Project Merge Request list ignores wip since 13.2

### ISSUE THREAD

**Issue by Oloremo** [python-gitlab/python-gitlab#1185]
## Description of the problem, including code/CLI snippet

A `project.mergerequests.list(state="opened", wip="no")` call now started to return a MRs in WIP status.
This seems to relate to 13.2 deprecation of WIP flag in favor of Draft: https://docs.gitlab.com/ee/user/project/merge_requests/work_in_progress_merge_requests.html

## Expected Behavior

`project.mergerequests.list(state="opened", wip="no")` doesn't return MRs in WIP state

## Actual Behavior

`project.mergerequests.list(state="opened", wip="no")` does return MRs in WIP state

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.3.5

**Comment by Oloremo** [comment]
Seems to be related https://gitlab.com/gitlab-org/gitlab/-/issues/32692

**Comment by nejch** [comment]
I think this was probably fixed upstream in 13.4, do you still get this?
See https://gitlab.com/gitlab-org/gitlab/-/merge_requests/40376

**Comment by Oloremo** [comment]
Fixed, indeed
