### ISSUE TITLE
Feature suggestion, and offer of help: new issue with description template

### ISSUE THREAD

**Issue by ernstki** [python-gitlab/python-gitlab#1191]
Hi, everyone. Hope you're well.

Would there be any interest in adding a `template` property to the `issues.create` method in order to create a new issue using a [description template]() _even if_ it relies on some non-API trickery in order to do so?

There is a git-lab org [issue #17522](https://gitlab.com/gitlab-org/gitlab/-/issues/17522) asking for this functionality to be added to the official API. There is another [issue #31884](https://gitlab.com/gitlab-org/gitlab/-/issues/31884) which is (I guess?) asking for issue descriptions to be added to the [templates API](https://docs.gitlab.com/ee/api/api_resources.html#templates-api-resources), so you could query the available ones.

What I'm proposing is a stub that reaches into the Git repository directly, which could be replaced with a proper API call later. (As things stand, it looks like you'd have to clone the repo and enumerate `.gitlab/issue_templates/*.md` in order to figure out which description templates were available.)

I can definitely anticipate some of your objections, particularly when this could very well bring in [GitPython](https://github.com/gitpython-developers/GitPython) as a dependency. But I'm willing to do the legwork, if you've got the patience to coach me through the testing aspect a little bit.

**Comment by nejch** [comment]
The thing is, you can easily make a wrapper function for this already, since we have the repository files API, no dependencies required. Would something like this work for you?

```python
def create_issue_from_template(project, template, data=None):
    if data is None:
        data = {"title": "New Issue"}

    template_file = f".gitlab/issue_templates/{template}.md"
    template = project.files.get(template_file, ref="master")

    data["description"] = template.decode()

    return project.issues.create(data)
```

I haven't tested this, but you'll get the idea from this I hope. You could make it more robust of course.

**Comment by max-wittig** [comment]
The idea of python-gitlab is to just be a small wrapper around the Gitlab API. As @nejch mentioned, this would need to be a small script on your side.

**Comment by ernstki** [comment]
OK, thanks guys. It seems I completely overlooked the existence of a file access API, my apologies.

Perhaps we can revisit this if and when such support for creating new issues based on description templates (as mentioned in the issues linked above) exists within the official API.

I don't think this gets said enough, but I actually deeply respect your not wanting to add _every_ feature to your project.

Cheers.
