### ISSUE TITLE
Trigger export using CLI

### ISSUE THREAD

**Issue by alper** [python-gitlab/python-gitlab#1197]
I would love to be able to trigger project exports using the CLI.

I'm fine with the export notification going to my e-mail and me downloading them from there if I can just automate half of it.

**Comment by nejch** [comment]
You can do this:

```shell
gitlab project-export create --project-id 1234
# wait for export 
gitlab project-export download --project-id 1234 > export.tar.gz
```

Just missing some docs on this. We'd also need to fix the CLI subcommands so we can check for export status. :)
