### ISSUE TITLE
/projects/:id/merge_requests/:iid/approval_rules is not supported

### ISSUE THREAD

**Issue by robinson96** [python-gitlab/python-gitlab#1199]
## Description of the problem, including code/CLI snippet
I would like to be able to call the `/projects/:id/merge_requests/:iid/approval_rules` endpoint as well as associated gets and updates.  

https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-merge-request-level-rules
https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-merge-request-level-rule
https://docs.gitlab.com/ee/api/merge_request_approvals.html#update-merge-request-level-rule

## Expected Behavior
Being able to call the endpoint, being able to get a list of approval_rules, create new rules, and update them.

## Actual Behavior
Endpoint not exposed in `python-gitlab` API

## Specifications

  - python-gitlab version: latest
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  latest

## FYI 
I actually have a branch where I've implemented this. PR should be up soon

**Comment by axelfauvel** [comment]
Hi there, any idea on how this feature will be released ? I'm interested :)
Thanks

**Comment by robinson96** [comment]
> 
> 
> Hi there, any idea on how this feature will be released ? I'm interested :)
> Thanks

It has been merged into master.

**Comment by nejch** [comment]
Shipped in v2.6.0 via #1200.
