### ISSUE TITLE
All projects in group by group_id

### ISSUE THREAD

**Issue by panterozo** [python-gitlab/python-gitlab#1217]
Hi there!

The next code give it by  @gpocentek https://github.com/python-gitlab/python-gitlab/issues/710, only returns 20 projects in the group:

```python
group = gl.groups.get(group_id_or_name, lazy=True)
projects = group.projects.list()
```

I need to get all projects in group by ID, so, I build the next code:

```python
all_projects = gl.projects.list(all=True)
for project in all_projects:
  # Check if namespace id is the same that I was looking for
  if(project.namespace["id"] == "my-group-id"):
    print("I got my project!")
```
Sadly, this code has really bad performance. I only need the projects from a group, not from all Gitlab instance. Particullarly, the code below:

```python
all_projects = gl.projects.list(all=True)
```

We have a lot of project in gitlab, and this approach take too much time. It works, but it is a real bad approach.

I couldn't find a way to do this giving the group ID only.

Im looking forward your answers ;)

Thanks in advance

**Comment by nejch** [comment]
You need to pass the `all=True` argument to the group project list:
```python
projects = group.projects.list(all=True)
```
If you have nested subgroups and need projects in those as well:
```python
projects = group.projects.list(all=True, include_subgroups=True)
```

Note you still need to create a proper Project out of the GroupProject objects returned by this list if you intend to manipulate it, see https://python-gitlab.readthedocs.io/en/stable/faq.html for hints on that.

Feel free to re-open if you still have issues :)

**Comment by panterozo** [comment]
Thank you @nejch.. It works like a charm!

In case of any need, i left the complete implementation [here](https://github.com/panterozo/gitlab-update-ci).

Thanks!
