### ISSUE TITLE
Question: Is Group wikis supported?

### ISSUE THREAD

**Issue by prokher** [python-gitlab/python-gitlab#1224]
Dear Colleagues,

Recently GitLab has [introduced Group wikis](https://about.gitlab.com/releases/2020/10/22/gitlab-13-5-released/#group-wikis). Does `Python GitLab` support it?

Regards,
Alexander.

**Comment by max-wittig** [comment]
I don't have access to EE features, so I'm not implementing them. But I would be happy to review a MR regarding this topic.
