### ISSUE TITLE
/projects/:id/invitations is not supported

### ISSUE THREAD

**Issue by georgescumihai** [python-gitlab/python-gitlab#1229]
## Description of the problem, including code/CLI snippet
I would like to be able to call the `/projects/:id/invitations` endpoint. There is already support for `/projects/:id/members` through `ProjectMemberManager`. The main difference between the APIs is that the invitations can add a user which doesn't have already a Gitlab account.

## Expected Behavior
Being able to call the endpoint, being able to invite a user to the project if he doesn't have a Gitlab account.

## Actual Behavior
Endpoint not exposed in python-gitlab API

## Specifications

  - python-gitlab version: 2.5
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

Thanks for the package, it makes working with Gitlab a lot easier. I am not that proficient with python to create the functionality by myself.
Taking in consideration that there are a lot of examples in code and this is a rather simple API if I get some guidance I can try to do it.

**Comment by georgescumihai** [comment]
If I got it right I should create a class in v4.objects something like 

```

class ProjectInviteManager(CreateMixin, RESTManager):
    _path = "/projects/%(project_id)s/invitations"
    _from_parent_attrs = {"project_id": "id"}
    _create_attrs = (("access_level", "email"), ("expires_at",))
    _update_attrs = (("access_level",), ("expires_at",))
```

Not sure how to handle the response

**Comment by max-wittig** [comment]
I would be happy to review any MRs regarding this feature. Otherwise, when I find the time, I will add this for sure.

**Comment by akhmerov** [comment]
Note: there's an analogous `/groups/:id/invitations` endpoint, which is also missing.
