### ISSUE TITLE
Unable to get page count info when calling commit.diff()

### ISSUE THREAD

**Issue by hungluong5791** [python-gitlab/python-gitlab#1231]
## Description of the problem, including code/CLI snippet

Calling `commit.diff()` to get diff information for a commit only return `per_page` items or 20 by default. It seems `commit.diff()` does not take either `all` or `as_list` and only pagination works, but we don't know how many page there are except by manually checking the returned list size.

## Expected Behavior

Using `commit.diff()` should be able to give us all the diffs in a commit without having to manually checking the returned page size

## Actual Behavior

As described

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by max-wittig** [comment]
Sounds like an upstream issue to me, as python-gitlab is just sending these query parameter. Have you tried it with curl as well?

**Comment by hungluong5791** [comment]
@max-wittig Per this [reference](https://docs.gitlab.com/ee/api/commits.html) I don't think they have an `all` parameter for the diff endpoint. However since python-gitlab have its own generator mechanism (`as_list=False`) for paging convenience, I was thinking of adding it to the `Manager` for commit diffs as well?

I guess this is more like a feature request rather than a bug.
