### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by Erag0n** [python-gitlab/python-gitlab#1232]
Its not a bug in existing documentation but we are missing one information here.

In the "List of Repository Tree" topic, it will be great if we add the below command because the existing command only returns default 20 records as output.

# list all the content of the root directory for the default branch
items = project.repository_tree(all=True)

Happy Coding...

Regards,
Mohamed Alikhan. M
------
In page: gl_objects/projects.rst

**Comment by nejch** [comment]
We now emit a runtime warning when this situation happens. Closing as no longer needed.
