### ISSUE TITLE
Support for the single MR API 

### ISSUE THREAD

**Issue by hoerup** [python-gitlab/python-gitlab#1234]
like #1222 there seems to be a missing option for get single merge request as well

AttributeError: 'MergeRequestManager' object has no attribute 'get'

**Comment by hoerup** [comment]
the MergeRequestManager obtained from project seems to have get but not the one obtained from group ??

**Comment by nejch** [comment]
A "Single Merge Request" API does not exist unfortunately. You can only list them: https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests

What GitLab describes as "get single MR" is still in the context of a project, see https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr.

This is essentially already documented in the first FAQ entry: https://python-gitlab.readthedocs.io/en/stable/faq.html
