### ISSUE TITLE
Wrap resource state events

### ISSUE THREAD

**Issue by hydrargyrum** [python-gitlab/python-gitlab#1236]
## Description of the problem, including code/CLI snippet
Resource state events report changes to state of a MR/issue: when it was opened, when it was closed, when it was reopened, when it was closed again, etc.
Documentation: https://docs.gitlab.com/ce/api/resource_state_events.html

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
I missed this issue, but this was implemented in https://github.com/python-gitlab/python-gitlab/pull/1364.
