### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by lzcawsome** [python-gitlab/python-gitlab#1245]
when i use gl = gitlab.Gitlab(url, private_token=token)  and it raise gitlab.exceptions.GitlabHttpError: 404: <!DOCTYPE html>  
my token and url are find  but it respond uncorrectly

**Comment by max-wittig** [comment]
Have you tried using curl and doing the same thing? I know for sure that this error is not caused by python-gitlab itself.

**Comment by nejch** [comment]
I think this is safe to close since there's no response and this obviously works.
