### ISSUE TITLE
name_regex_keep and name_regex_delete parameters unsupported when deleting registry repository tags in bulk

### ISSUE THREAD

**Issue by jgough** [python-gitlab/python-gitlab#1246]
## Description of the problem, including code/CLI snippet
https://docs.gitlab.com/ce/api/container_registry.html#delete-registry-repository-tags-in-bulk indicates that the parameter _name_regex_ seems to be now deprecated in favour of _name_regex_keep_ and _name_regex_delete_.  These two parameters seem to be currently unsupported by the code.

This seems to be defined here https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/v4/objects/__init__.py#L1849

**Comment by nejch** [comment]
Fixed via https://github.com/python-gitlab/python-gitlab/pull/1537 and https://github.com/python-gitlab/python-gitlab/pull/1536.
