### ISSUE TITLE
Protected-Branches how to update settings without having to delete existing protection?

### ISSUE THREAD

**Issue by hvithval** [python-gitlab/python-gitlab#1247]
I'm trying to change the settings for my current protected-branches rule, so "no-one" can push to master. 
Can the python-gitlab do that? could you provide examples please?

thank you
hvithval.

**Comment by sandeshwani** [comment]
> I'm trying to change the settings for my current protected-branches rule, so "no-one" can push to master.
> Can the python-gitlab do that? could you provide examples please?
> 
> thank you
> hvithval.

Let me know if you found any solution.

**Comment by hvithval** [comment]
@sandeshwani  will do, so far, nothing.

**Comment by JohnVillalovos** [comment]
This is a limitation of the Gitlab API. They don't have an "update" method.

https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches

Recommend this issue is closed.

**Comment by nejch** [comment]
Agreed, @hvithval  or @sandeshwani please open an issue upstream in https://gitlab.com/gitlab-org/gitlab to add a `PUT` verb to this API endpoint and link it back here. 

When it's resolved upstream we can reopen this and implement it on our side.
