### ISSUE TITLE
[Question] How to add a merge request into milestone via python-gitlab

### ISSUE THREAD

**Issue by walker0921** [python-gitlab/python-gitlab#1248]
## Description of the problem, including code/CLI snippet

     How to add a merge request into milestone via python-gitlab? Now I couldn't find the methon to achieve that?

## Specifications

  - python-gitlab version: 2.5
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by JohnVillalovos** [comment]
Did you ever figure this out?

**Comment by walker0921** [comment]
Not yet. Right now I achieve it through seleuim



At 2022-01-08 14:32:51, "John Villalovos" ***@***.***> wrote:

Did you ever figure this out?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JohnVillalovos** [comment]
Okay. I think it might be something like this:

```
gitlab project-merge-request update --project-id 111 --iid 222 --milestone-id 333
```

You will need to figure out the values for `project-id`, `iid`, and `milestone-id` of course.

I have not tested this, so it may not work.

**Comment by nejch** [comment]
Agreed, this should work. Similar with the API, should be something like

```python
mr = projects.mergerequests.get(mr_iid)
mr.milestone = milestone_id
mr.save()
```

(completely untested, just get the right ID vs IID and you should be fine :grin)

**Comment by walker0921** [comment]
> Okay. I think it might be something like this:
> 
> ```
> gitlab project-merge-request update --project-id 111 --iid 222 --milestone-id 333
> ```
> 
> You will need to figure out the values for `project-id`, `iid`, and `milestone-id` of course.
> 
> I have not tested this, so it may not work.
> 
> https://docs.gitlab.com/ee/api/merge_requests.html#update-mr

Thanks. Will try and update later

**Comment by walker0921** [comment]
> 
This doesn't work as expected.

when you get a merge request object, it indeed has a property:milestone, but it's value is type of ProjectMilestone, when try to save, it will raise an error TypeError: Object of type ProjectMilestone is not JSON serializable

`project = gl.projects.get(projectD)
mr = project.mergerequests.get(mr_iid)
milstone = get_milestone(project) # return object
mr.milestone = milstone
mr.save()`

**Comment by JohnVillalovos** [comment]
> ```
> project = gl.projects.get(projectD)
> 
> mr = project.mergerequests.get(mr_iid)
> 
> milestone = get_milestone(project) # return object
> 
> mr.milestone = milstone
> 
> mr.save()
> ```

I believe it needs to be:

```
<snip>
mr.milestone_id = milestone.id
mr.save()
```

See: https://docs.gitlab.com/ee/api/merge_requests.html#update-mr  for more details.

**Comment by walker0921** [comment]
> I believe it needs to be:
> 
> ```
> <snip>
> mr.milestone_id = milestone.id
> mr.save()
> ```
> 
> See: https://docs.gitlab.com/ee/api/merge_requests.html#update-mr for more details.

Works. Really appreciate your kindly help. 

Wish you have a good day.

**Comment by JohnVillalovos** [comment]
Glad to hear it is working. I will go ahead and close this. Thanks.
