### ISSUE TITLE
bugs while using a proxy between the client and gitlab server

### ISSUE THREAD

**Issue by sidey** [python-gitlab/python-gitlab#1254]
## Description of the problem, including code/CLI snippet
The client used LINK filed in a response header as an url to get the next page in every list api.
if there is a proxy(eg nginx) between gitlab server and the client ,there will be a http error.
eg:
- suppose the server api endpoint is  **http://example.com/api/v4** and the enginx proxy address is 
 **http://example.nginx/api/v4**.
- After a request, a **link** in Http response header is **http://example.com/api/v4** ,but I must use **http://example.nginx** as the host.
- anyway,I can add a response Hook to a customized **requests session**，but I wonder if this feature can
be added to this library as a default

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  13.3.5

**Comment by max-wittig** [comment]
I'm not sure that this makes sense in this library as this is the GitLab endpoint and I'm also questioning how many people are gonna use this. I would say this requests possibility is enough in this case. If you like, feel free to add some documentation on how to set this up, but I don't think that other people have this problem.
