### ISSUE TITLE
List groups only skips the last id provided in skip_groups

### ISSUE THREAD

**Issue by schuand** [python-gitlab/python-gitlab#1256]
## Description of the problem, including code/CLI snippet
The get groups endpoint returns a list of projects. When providing the parameter <skip_groups> the ids in the array should be skipped. The problem is that only the LAST id in the array is skipped.

<img width="741" alt="Screenshot 2020-12-17 at 15 25 55" src="https://user-images.githubusercontent.com/76169376/102502500-faa36000-407e-11eb-9b90-006d72960458.png">

## Expected Behavior

All groups that are provided in skip_groups should be skipped.

## Actual Behavior

Only the group related to the last id in skip_groups is skipped.

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): Gitlab server version

**Comment by max-wittig** [comment]
Are you sure that you've provided the groups correctly?

Could you add a little snippet of your code here?

**Comment by schuand** [comment]
![Screenshot 2020-12-17 at 16 36 51](https://user-images.githubusercontent.com/76169376/102509485-e3687080-4086-11eb-8985-2e88bf097087.png)

![Screenshot 2020-12-17 at 16 44 45](https://user-images.githubusercontent.com/76169376/102509769-34786480-4087-11eb-9d09-7d9a57f4b9c9.png)

![Screenshot 2020-12-17 at 16 37 07](https://user-images.githubusercontent.com/76169376/102509518-ee230580-4086-11eb-825e-07c75d527104.png)

**Comment by max-wittig** [comment]
The variable `skipped_projects`, should contain `group ids`, not `project ids`

**Comment by schuand** [comment]
Yes, the naming is bad. The ids are group ids.

**Comment by JohnVillalovos** [comment]
At the moment, `skip_groups` must be a comma-delimited string, or a list of strings. It can't be a list of integers.

The root-cause for this issue is that the Gitlab API doesn't accept a list of integers at this time.

A work-around is being developed and progress tracked in: https://github.com/python-gitlab/python-gitlab/issues/1407
