### ISSUE TITLE
projects.search() doesn't work with special characters

### ISSUE THREAD

**Issue by mbondfusion** [python-gitlab/python-gitlab#126]
This might be an issue with the gitlab API or the way in which the request is built. Using the following to search for projects causes an exception with a "404 page not found" even when the project actually exists.

```
gitlab.projects.search('project.with.periods')
*** gitlab.exceptions.GitlabListError: 404.....
```

The HTTP request path built is: **http://gitlab_server.domain/api/v3/projects/search/project.with.periods**

*Please note that creating projects with periods (and presumably other special characters) is supported and working.

**Comment by gpocentek** [comment]
This seems to be a gitlab API problem. Looks like you reported the issue already: https://gitlab.com/gitlab-org/gitlab-ce/issues/19242

I keep this issue open to track the progress. Thanks.

**Comment by flixr** [comment]
A workaround would be to replace the periods with '%2E' when making the API calls.

**Comment by flixr** [comment]
Also this problem is not limited to searching, but to anything that will issue an API call with some "special" char in the URL...

**Comment by gpocentek** [comment]
This seems fixed upstream with the v4 API and I have been able to make this work with python-gitlab:

```python
>>> list(gl.projects.list(search='project.with.periods'))
[<Project id:52>]
```

This part of the API has not been released yet so I'll keep the issue open for now.
