### ISSUE TITLE
commits.list() does not filter by path

### ISSUE THREAD

**Issue by lu-zero** [python-gitlab/python-gitlab#1264]
## Description of the problem, including code/CLI snippet

https://docs.gitlab.com/ee/api/commits.html

lists the following filters

Attribute | Type | Required | Description
-- | -- | -- | --
id | integer/string | yes | The ID or URL-encoded path of the project owned by the authenticated user
ref_name | string | no | The name of a repository branch, tag or revision range, or if not given the default branch
since | string | no | Only commits after or on this date will be returned in ISO 8601 format YYYY-MM-DDTHH:MM:SSZ
until | string | no | Only commits before or on this date will be returned in ISO 8601 format YYYY-MM-DDTHH:MM:SSZ
path | string | no | The file path
all | boolean | no | Retrieve every commit from the repository
with_stats | boolean | no | Stats about each commit will be added to the response
first_parent | boolean | no | Follow only the first parent commit upon seeing a merge commit
order | string | no | List commits in order. Possible values: default, topo. Defaults to default, the commits are shown in reverse chronological order.

trying to call `list()` with path="some_path" leads to a 
```
gitlab.exceptions.GitlabListError: 404: 404 API Version Not Found
```

## Expected Behavior
Getting a list of commit filtered by path

## Actual Behavior
```
gitlab.exceptions.GitlabListError: 404: 404 API Version Not Found
```

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
Do you have a few lines of code which show the problem?

**Comment by nejch** [comment]
This happens because the `path` argument is used by the python-gitlab library and conflicts with the API parameter. You can use this instead: `project.commits.list(query_parameters={"path": "some_path"})`

See explanation at https://python-gitlab.readthedocs.io/en/stable/api-usage.html#managers

If you have issues with the CLI because of this please reopen/comment here :)
