### ISSUE TITLE
请问这个项目功能是什么？如何运行？

### ISSUE THREAD

**Issue by yearnxiao** [python-gitlab/python-gitlab#1268]
## Description of the problem, including code/CLI snippet

请问这个项目功能是什么？如何运行？搞了一下午build的镜像也没正常运行起来，从没见过项目文档如此粗糙的项目。
## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
English is the language of the Internet. I'm not a chinese speaker, sorry.
