### ISSUE TITLE
Member - group invitation

### ISSUE THREAD

**Issue by nyue** [python-gitlab/python-gitlab#1274]
## Description of the problem, including code/CLI snippet
In the web interface, one can invite group as member of a project/repository, how can I do that programmatically via python-gitlab

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  13.4.4-ee

**Comment by nejch** [comment]
@nyue in case you haven't solved this, see https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-members:

```python
# Share/unshare the project with a group:

project.share(group.id, gitlab.DEVELOPER_ACCESS)
project.unshare(group.id)
```
