### ISSUE TITLE
switch from travis-ci.org to travis.com

### ISSUE THREAD

**Issue by bufferoverflow** [python-gitlab/python-gitlab#1275]
## Description of the problem, including code/CLI snippet

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information. 

see https://travis-ci.org/github/python-gitlab/python-gitlab

## Expected Behavior

- [x] configure travis-ci.com as app at group level
- [ ] use travis-ci.com
- [ ] update badge within README

## Actual Behavior
using travis-ci.org

**Comment by bufferoverflow** [comment]
@max-wittig @nejch I see there is just the travis badge but no .travis-ci.yml anymore, so shall I just remove the badge and forgot about travis-ci the Berlin company?

**Comment by max-wittig** [comment]
Yes Travis seems really unreliable. We've switched to Github actions.
