### ISSUE TITLE
When querying gitlab group, an error is reported

### ISSUE THREAD

**Issue by tanghulu9312** [python-gitlab/python-gitlab#1279]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gitlab/exceptions.py", line 279, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/gitlab/mixins.py", line 141, in list
    obj = self.gitlab.http_list(path, **data)
  File "/usr/local/lib/python3.6/dist-packages/gitlab/__init__.py", line 644, in http_list
    return list(GitlabList(self, url, query_data, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/gitlab/__init__.py", line 855, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/gitlab/__init__.py", line 866, in next
    self._query(self._next_url, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/gitlab/__init__.py", line 784, in _query
    result = self._gl.http_request("get", url, query_data=query_data, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/gitlab/__init__.py", line 570, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 404: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /api/v4/groups/403/projects. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./gitlab-test.py", line 20, in <module>
    for project in group.projects.list(all=True):
  File "/usr/local/lib/python3.6/dist-packages/gitlab/exceptions.py", line 281, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabListError: 404: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /api/v4/groups/403/projects. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>

**Comment by nejch** [comment]
What is the actual code snippet that you use for this?

Are you using Jetty as a reverse proxy? Maybe check the gitlab base URL again, the fact that your 404 error is served by Jetty looks a bit off.

**Comment by tanghulu9312** [comment]
> 您为此使用的实际代码段是什么？
> 
> 您是否正在使用Jetty作为反向代理？也许再次检查gitlab基本URL，Jetty会提供您的404错误，这一事实似乎有点过头了。
gl = gitlab.Gitlab('http://192.168.2.53:8088/', private_token='NuPKvykBgpSC8ZLs-95D')
all_groups = gl.groups.list(all=True)
for group in all_groups:
        print(group.name,group.id)


Execute the above code to throw an exception
When querying the group list

**Comment by tanghulu9312** [comment]
> 您为此使用的实际代码段是什么？
> 
> 您是否正在使用Jetty作为反向代理？也许再次检查gitlab基本URL，Jetty会提供您的404错误，这一事实似乎有点过头了。

It doesn't look like a mistake of python-gitlab.
Maybe it's a problem of my gitlab server

**Comment by max-wittig** [comment]
Yep seems like it. I can help you with the error message. I don't understand Chinese.

**Comment by max-wittig** [comment]
Maybe try the same on gitlab.com?

**Comment by nejch** [comment]
@tanghulu9312 I'd try to reproduce this with `curl` or some other client - and if you get the same issue, it's not python-gitlab.

Otherwise feel free to re-open this:)

**Comment by tanghulu9312** [comment]
Thank you very much. I'm really sorry that the Chinese you see may be my email signature. My English is not good. I use translation tools;

When I deploy gitlab to X86 platform, there is no such problem when I use Python gitlab;




At 2021-02-02 18:57:14, "Max Wittig" <notifications@github.com> wrote:

Yep seems like it. I can help you with the error message. I don't understand Chinese.
