### ISSUE TITLE
how to add two `redirect_uri`s to gitlab application

### ISSUE THREAD

**Issue by dyobj** [python-gitlab/python-gitlab#1280]
------
In page: gl_objects/applications.rst

app = gl.applications.create({'name': 'MatterMost',  'redirect_uri': 'https://mattermost.gitlab.com/signup/gitlab/complete''\n'+ 'https://mattermost.gitlab.com/login/gitlab/complete' , 'scopes': ' '})

**Comment by nejch** [comment]
Looking at https://gitlab.com/gitlab-org/gitlab/-/blob/master/spec/requests/api/applications_spec.rb I'm not sure this is even possible via the API.

Have you found any examples of this in the Gitlab API?

**Comment by JohnVillalovos** [comment]
I don't think we can fix this issue.

Closing as not fixable. If incorrect feel free to re-open.
