### ISSUE TITLE
RFE: Support type hints so mypy and other type checkers can work

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#1294]
It would be nice if this project provided type hints so that programs like mypy could work with it.

Type hints: https://www.python.org/dev/peps/pep-0484/

mypy: http://mypy-lang.org/

**Comment by nejch** [comment]
I agree this makes sense, although first splitting the 6k line giant in `v4/objects` would be helpful https://github.com/python-gitlab/python-gitlab/pull/1288. So in case you're planning/preparing your own PR for this, I'd avoid touching that file until it's merged, just to avoid painful rebasing :)
