### ISSUE TITLE
ProjectMergeRequest.pipelines() returns a 'list' instead of documented 'RESTObjectList'

### ISSUE THREAD

**Issue by beanaroo** [python-gitlab/python-gitlab#1312]
## Description of the problem, including code/CLI snippet

I'm not sure if this is a documentation or API bug.

```
type(merge_request.pipelines(order_by='created_at'))
<class 'list'>
```

Documentation suggests it is `RESTObjectList`

Getting an element in the returned list by index (`pipelines()[0]`) works but produces the following warning.
```
Class 'RESTObjectList' does not define '__getitem__', so the '[]' operator cannot be used on its instances
```

## Specifications

  - python-gitlab version: `2.6.0`
  - API version you are using (v3/v4): `v4`
  - Gitlab server version (or gitlab.com): `gitlab.com`

**Comment by nejch** [comment]
Seems like the MR pipelines endpoint has a custom method that only does `http_get()` at the moment that just serializes the json:

https://github.com/python-gitlab/python-gitlab/blob/338170029c9c8855a6c44de8f3576e8389338652/gitlab/v4/objects/merge_requests.py#L208-L223

Hmm, it's an easy fix but might be better to deprecate this and add proper managers to MRs now that they also have a [create pipeline API endpoint](https://docs.gitlab.com/ee/api/merge_requests.html#create-mr-pipeline) and call them like project pipelines:

`merge_request.pipelines.list()`
`merge_request.pipelines.create()`

**Comment by nejch** [comment]
@beanaroo this should be fixed when https://github.com/python-gitlab/python-gitlab/pull/1323 is merged and released, but then please switch to the `list()` method asap as the old one will be removed.

BTW it will still return a list with this new method, unless you specifically ask for a generator (`as_list=False`), but at least the docstrings will be accurate.

**Comment by msune** [comment]
Hi,

Wondering if what I see is remotely related.

`mr.pipelines()` doesn't seem to honour `all=True` (that particular MR has 140+ pipelines):

```
ipdb> len(mr.pipelines())
20
ipdb> len(mr.pipelines(all=True, lazy=False))
20
```

However, trying directly the REST API with `per_page=100`, which I believe is the max as per Gitlab's docs, returns the first 100 elements:

```
https://gitlab.acme.com/api/v4//projects/59/merge_requests/1307/pipelines?per_page=100`
```

Am I missing something fundamental here? Should I open a separate issue or is it related?

**Comment by nejch** [comment]
@msune yes this is most likely related because `all=True` is implemented via the ListMixin. So this will be fixed after merging the PR linked above.
