### ISSUE TITLE
add usage of  include_retried for getting list of jobs

### ISSUE THREAD

**Issue by wallhided** [python-gitlab/python-gitlab#1354]
After 13.9 retried jobs could be received after setting include_retried to True
Link: https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-jobs

**Comment by JohnVillalovos** [comment]
I'm not 100% sure but you might be able to pass `include_retried=True` in the call. I think it will work.

```
pipelines = project.pipelines.list(include_retried=True)
```

**Comment by wallhided** [comment]
I tried pipeline.jobs.list(include_retried=True) and didn't receive retried job.
python-gitlab           2.6.0
GitLab 13.9.1 (03979b4aaf0)

**Comment by JohnVillalovos** [comment]
> I tried pipeline.jobs.list(include_retried=True) and didn't receive retried job.
> python-gitlab 2.6.0
> GitLab 13.9.1 (03979b4aaf0)

Sorry. I'm not an expert in the code but from my understanding I thought it would work in the API. The CLI program needs a fix for sure.

Hopefully one of the maintainers can help out.

**Comment by nejch** [comment]
This works with the API. I'll push the missing attribute for the CLI in a minute :smile:
