### ISSUE TITLE
Fetching issues with gl.issues.list() or project.issues.list(), its only fetching 20 issues. i need to fetch all issues (more than 100)

### ISSUE THREAD

**Issue by sikandarkhan84** [python-gitlab/python-gitlab#1384]
## Description of the problem, including code/CLI snippet
project = gl.projects.get(91) 
project.issues.list()

closed_issues = project.issues.list(state='closed')
print(len(closed_issues))

open_issues = project.issues.list(state='opened')
print(len(open_issues))

## Expected Behavior
100
40
60

## Actual Behavior
20
20
20

## Specifications

  - python-gitlab version:latest
  - API version you are using (v3/v4):v4
  - Gitlab server version (or gitlab.com):

**Comment by JohnVillalovos** [comment]
As far as I know that is expected behavior. It is the responsibility of the caller to call multiple times.

See: https://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination

**Comment by sikandarkhan84** [comment]
yes it worked , i'm adding updated code here.

   issues = project.issues.list(all=True)                  # Accessing all issues (both opened and closed)
   issues = project.issues.list(all=True,state='opened')   # Accessing all opened issues
   issues = project.issues.list(all=True,state='closed')   # Accessing all closed issues
