### ISSUE TITLE
Support Gitlab releases API

### ISSUE THREAD

**Issue by saied89** [python-gitlab/python-gitlab#1385]
## Support Gitlab [releases API](https://docs.gitlab.com/ee/api/releases/index.html#create-a-release)
Please consider adding support for releases API

**Comment by peter-gy** [comment]
You might want to take a look at this section of the docs: 
https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-releases

**Comment by peter-gy** [comment]
> ## Support Gitlab [releases API](https://docs.gitlab.com/ee/api/releases/index.html#create-a-release)
> Please consider adding support for releases API

You might want to take a look at this section of the docs:
https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-releases

**Comment by zengqingfu1442** [comment]
@peter-gy So from which version, the `python-gitlab` starts to support releases API? thanks. I cannot find the exact link of the page.

**Comment by zengqingfu1442** [comment]
Ok, I find the issue and related PR https://github.com/python-gitlab/python-gitlab/issues/722, it should be `1.9.0`
