### ISSUE TITLE
RFE: Add support to upload generic package

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#1389]
Request to add support for uploading via the packages API a "generic" package.

Documentation about this is here:

https://docs.gitlab.com/ee/user/packages/generic_packages/index.html

**Comment by Sup3rGeo** [comment]
Great to see this was implemented! Any ideas when a release is coming so we can use this without installing from source?

**Comment by max-wittig** [comment]
@nejch What's the status of the automatic release system?

**Comment by nejch** [comment]
@max-wittig it was ready, we just forgot to merge https://github.com/python-gitlab/python-gitlab/pull/1489 :grinning: ran the workflow now and 2.8.0 is released. I hope my inbox doesn't explode in the morning :P
