### ISSUE TITLE
CI_JOB_TOKEN does not allow to access current project

### ISSUE THREAD

**Issue by christophedcpm** [python-gitlab/python-gitlab#1393]
## Description of the problem, including code/CLI snippet

I'm a trying to list all the branch of the current repository from a CI job. To do this I expected to be able to use the CI_JOB_TOKEN present in the environment of the CI jobs, but it turns out it is not possible.

The documentation seems to indicate that it should be possible though: 

> The token has the same permissions to access the API as the user that triggers the pipeline. Therefore, this user must be assigned to a role that has the required privileges.

```python
gitlab_project_id = int(os.environ["CI_PROJECT_ID"])
server_url = os.environ["CI_SERVER_URL"]
job_token = os.environ["CI_JOB_TOKEN"]
gl = gitlab.Gitlab(server_url, job_token=job_token)  
gl_project = gl.projects.get(gitlab_project_id)
```

## Expected Behavior

CI_JOB_TOKEN should let me access the current project.

## Actual Behavior

404 Not found error is raised

## Specifications

  - python-gitlab version: 2.6.0
  - Gitlab server version (or gitlab.com): version: 13.7.4-ee   revision: 368b4fb2eee

**Comment by JohnVillalovos** [comment]
As far as I know that is how the Gitlab API is. The CI_JOB_TOKEN is not allowed to get information on a project if it is private.

https://docs.gitlab.com/ee/api/projects.html#get-single-project.

This has information on what endpoints can be used with the CI_JOB_TOKEN:

https://docs.gitlab.com/ee/api/README.html#gitlab-cicd-job-token

**Comment by christophedcpm** [comment]
In this documentation they also say

> The token has the same permissions to access the API as the user that triggers the pipeline. Therefore, this user must be assigned to a role that has the required privileges.

And my user can access the project detail just fine using a private token, so I would have expected to have the same rights with the JOB_CI_TOKEN.

So do you recommend I move this issue on Gitlab itself ?

**Comment by JohnVillalovos** [comment]
> In this documentation they also say
> 
> > The token has the same permissions to access the API as the user that triggers the pipeline. Therefore, this user must be assigned to a role that has the required privileges.

I think what they are trying to say is that the user who triggered the job must have enough permission to do the action. I agree at first read that it sounds like it should work but it doesn't. I can see why it shouldn't as for example you propose an MR to a project, do you want their CI to be able to go and do everything you can do now that they have a CI_JOB_TOKEN assigned to you?

> So do you recommend I move this issue on Gitlab itself ?

I would. It would be interesting to see their thoughts. I'm guessing it is by design as otherwise it could have security implications.

**Comment by christophedcpm** [comment]
Understood, thanks. I'll move the discussion there.

**Comment by nejch** [comment]
@christophedcpm just FYI before you open a new issue upstream, this is pretty much by design as John said and there are already a lot of upstream issues and discussions ongoing on expanding the permissions of the CI job token in various contexts. Maybe you can find and upvote those ;) But yes, only limited endpoints are accessible with this token.

**Comment by christophedcpm** [comment]
sounds good, thanks ;-)

**Comment by koliyo** [comment]
> In this documentation they also say
> 
> > The token has the same permissions to access the API as the user that triggers the pipeline. Therefore, this user must be assigned to a role that has the required privileges.
> 

This should be added very clearly to [Getting started with the API](https://python-gitlab.readthedocs.io/en/stable/api-usage.html#getting-started-with-the-api)

**Comment by nejch** [comment]
> 
> 
> > In this documentation they also say
> > > The token has the same permissions to access the API as the user that triggers the pipeline. Therefore, this user must be assigned to a role that has the required privileges.
> 
> This should be added very clearly to [Getting started with the API](https://python-gitlab.readthedocs.io/en/stable/api-usage.html#getting-started-with-the-api)

But right above that sentence, the docs also say

> You can use a GitLab CI/CD job token to authenticate with specific API endpoints: 

And then lists what endpoints the job token can actually be used for. So it's sort of assumed the user knows why they are using the job token from the API docs. But yes, maybe a link to this upstream docs section in python-gitlab's docs would help here :) PRs welcome!
