### ISSUE TITLE
Feature request: add search by container path

### ISSUE THREAD

**Issue by ice1x** [python-gitlab/python-gitlab#1394]
## Description of the problem, including code/CLI snippet
Add abbility to search container image by path (fuzzy)

## Expected Behavior

1.  Possible to search container image by path (fuzzy)
2. Also would be good to be able to choose which exactly field is searched, for example if i need to search by name but not by description. (Deny description search)

## Actual Behavior
`client.projects.list(search=image_name_substring)`

1. Right now is possible to search container image by name or description (fuzzy) using 'search' key but there is impossible to search image by path substring. 
2. And also impossible to search by name only (it also searches by description too)

## Specifications

  - python-gitlab version: 2.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Community Edition 13.5.4

**Comment by nejch** [comment]
Hi @ice1x, thanks for the issue. 

Could you please point me to the GitLab API docs where this is documented? I'm struggling to find if this is really implemented on GitLab's side. Please note this library can mostly only wrap what's possible with the API, not add features to the underlying API.

1. you are using the Project list API above (https://docs.gitlab.com/ee/api/projects.html#list-all-projects) but searching by image name (at least the way you describe it, as you say container image). I think this is not even implemented in the GitLab API, it was maybe a coincidence that your image name matches the project name. But the API is not searching by container image names I'm pretty sure.
2. Same with fields, I can't see any options to restrict API search by field in upstream docs, but please correct me if I'm wrong.

So I'd close this issue for now and you can open a new one at https://gitlab.com/gitlab-org/gitlab, then once that's implemented in GitLab we can add it here. If you do open an issue there please link it here so we can re-open later if needed.

Of course feel free to also reopen if I misunderstood and you can actually reproduce the desired behavior with other clients like `curl`. :)

**Comment by ice1x** [comment]
Hello, @nejch ,
thank you for the clarification!
You right this is GitLab's limitations, not a python-api.
I will copy&paste them so.

**Comment by ice1x** [comment]
@nejch https://gitlab.com/gitlab-org/gitlab/-/issues/327573
