### ISSUE TITLE
Inconsistent attributes between objects fetched lazily and non-lazily

### ISSUE THREAD

**Issue by aaronalphonso** [python-gitlab/python-gitlab#1401]
## Description of the problem, including code/CLI snippet
There should not be any inconsistency between the basic attributes/methods on an object fetched with `lazy=True` versus the exact same object fetched with `lazy=False`.  

Fetching a `ProjectIssue` object non-lazily shows that it has `milestone` and `title` attributes, but trying to access the same attributes on a lazily fetched `ProjectIssue` object triggers an `AttributeError`.

```python
project = gl.projects.get(project_id)

issue = project.issues.get(issue_id)
print(issue.title)   # Prints the title

lazy_issue = project.issues.get(issue_id, lazy=True)
print(lazy_issue.title)   # AttributeError
```

Ideally, the only difference between these two objects should be 'the timing of the actual api call that is made to fetch the object data'. 
In case of `lazy=False`, the api call should be made immediately, whereas in case of `lazy=True`, the api call should be deferred until the **object data is actually required** (in this case, when an attribute is accessed).

Attributes/methods should resolve consistently across an object regardless of whether it was fetched lazily and non-lazily.

## Expected Behavior
The following snippet SHOULD work regardless of whether `is_lazy` is `True` or `False`,
```python
issue = project.issues.get(issue_id, lazy=is_lazy)    
print(issue.title)    # Successfully prints title
print(issue.milestone)    # Successfully prints milestone details
```

## Actual Behavior
Attribute errors are observed when the issue object is fetched with `lazy=True`
```python
issue = project.issues.get(issue_id, lazy=True)
print(issue.title)    # AttributeError
print(issue.milestone)    # AttributeError
```
Ideally, attribute access should trigger the object fetching under the hood.

## Specifications

  - python-gitlab version: 2.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Community Edition 13.10.2

**Comment by max-wittig** [comment]
This is expected behavior and that's not something we can fix, because we don't know what attributes exists for every object.

There could be a new attribute, which we don't have in the list yet. Also it would confuse users that are used to the current behavior. If you want to use the attributes, don't use lazy.

**Comment by giraldeau** [comment]
I had a similar problem, but not related to lazy loading. I want to sync issues assignee between two gitlab instances. Reading the attribute `issue.assignee_id` fails with AttributeError: 

```
Traceback (most recent call last):
  File "/home/francisg/git/gitlab-migration/fixuser/venv/lib/python3.6/site-packages/gitlab/base.py", line 77, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'assignee_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francisg/git/gitlab-migration/fixuser/venv/lib/python3.6/site-packages/gitlab/base.py", line 80, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'assignee_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francisg/git/gitlab-migration/fixuser/venv/lib/python3.6/site-packages/gitlab/base.py", line 100, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'assignee_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fixuser.py", line 242, in <module>
    sys.exit(main())
  File "fixuser.py", line 230, in main
    gitlab_sync(gl_src, gl_dst, args)
  File "fixuser.py", line 105, in gitlab_sync
    print(f"isrc.assignee_id: {isrc.assignee_id}")
  File "/home/francisg/git/gitlab-migration/fixuser/venv/lib/python3.6/site-packages/gitlab/base.py", line 102, in __getattr__
    raise AttributeError(name)
AttributeError: assignee_id
```

I took me a while to figure out that we can only write to that attribute. Maybe we can add something in the documentation related to that? Could we add a `getattr()` reading from the attributes dict?

```
read: issue.attributes["assignee"]["id"]
write: issue.assignee_id = 42
```

Cheers!
