### ISSUE TITLE
Trying to Fetch multiple ProjectIssues in a single batch call returns only the last ProjectIssue specified in the list

### ISSUE THREAD

**Issue by aaronalphonso** [python-gitlab/python-gitlab#1407]
## Description of the problem, including code/CLI snippet
According to [Gitlab](https://docs.gitlab.com/ee/api/issues.html#list-project-issues), we can make a batch GET call to fetch multiple issues by passing in the list of issue_ids in parameter `iids`. 

However, while using the library this method call always returns a list with a single element (which happens to be the last element in the `iids` list.

```python
project = gl.projects.get(project_id)
project.issues.list(all=True, iids=[1, 2, 3])   # Returns a list with a single element ProjectIssue[iid=3]
project.issues.list(all=True, iids=[3, 2, 1])   # Returns a list with a single element ProjectIssue[iid=1]

```

Are batch requests not supported yet or is this a bug?  

## Expected Behavior
The batch call should return a list of all ProjectIssues as mentioned in the `iids` field.
```python
project = gl.projects.get(project_id)
project.issues.list(all=True, iids=[1, 2, 3])   # Should return [ProjectIssue(iid=1), ProjectIssue(iid=2), ProjectIssue(iid=3)]
```

## Actual Behavior
Only the ProjectIssue corresponding to the last id in the `iids` list is returned 
```python
project = gl.projects.get(project_id)
project.issues.list(all=True, iids=[1, 2, 3])    # Returns a list with a single element ProjectIssue[iid=3]
```

## Specifications

  - python-gitlab version: 2.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Community Edition 13.10.2

**Comment by nejch** [comment]
This seems related to some other issues where lists aren't passed to query params correctly, I'll check. I think we have a similar issue with scopes.

Out of curiosity, have you tried passing the `iids` as a comma-delimited string? Would need to check what the current state of the gitlab API is with this (see e.g. https://gitlab.com/gitlab-org/gitlab-foss/-/issues/48007)

**Comment by aaronalphonso** [comment]
I just tried passing in `iids` as a comma-delimted string and it gives me the expected results. Thank you very much for the suggestion! :)

**Comment by JohnVillalovos** [comment]
I have proposed a patch for this issue in https://github.com/python-gitlab/python-gitlab/pull/1413

I'm hopeful that it will work though I have not tested it.

**Comment by JohnVillalovos** [comment]
I have left a comment on the MR, which seems to have caused this behavior in Gitlab:

https://gitlab.com/gitlab-org/gitlab/-/merge_requests/33450

**Comment by JohnVillalovos** [comment]
Related issue: https://github.com/python-gitlab/python-gitlab/issues/1256

**Comment by JohnVillalovos** [comment]
@nejch  I think I may have found out our root cause issue.

Had a discussion with a Gitlab developer in: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/33450

From the Gitlab documentation: https://docs.gitlab.com/ee/api/#array

### array

`import_sources` is a parameter of type array:

```
curl --request POST --header "PRIVATE-TOKEN: <your_access_token>" \
-d "import_sources[]=github" \
-d "import_sources[]=bitbucket" \
"https://gitlab.example.com/api/v4/some_endpoint"
```

So it seems for `array` types we need to append `[]` to the variable name.
