### ISSUE TITLE
v2.7.0 breaks when trying to get pathed files

### ISSUE THREAD

**Issue by xgui3783** [python-gitlab/python-gitlab#1416]
## Description of the problem, including code/CLI snippet

when trying to 

```python
from gitlab import Gitlab
project=Gitlab(GITLAB_SRC).projects.get(GITLAB_PROJECT_ID)
project.files.get(file_path=PATH_TO_FILE, ref=GITLAB_REF)
```

where `PATH_TO_FILE` is in the form of `{directory}/{filename}`, client returns not found error. (see github action: https://github.com/xgui3783/python-gitlab-exmaple/actions/runs/786113706)

I suspect this is due to double escaping the `/` character from:
-  `GetMixin.get` (https://github.com/python-gitlab/python-gitlab/blob/8933113/gitlab/mixins.py#L104) and 
- `ProjectFileManager.get` (https://github.com/python-gitlab/python-gitlab/blob/89331131b3337308bacb0c4013e80a4809f3952c/gitlab/v4/objects/files.py#L97)

## Expected Behavior

return file descriptor

## Actual Behavior

not found error

## Specifications

  - python-gitlab version: v2.7.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
This might be related to commit b4dac5ce33843cf52badeb9faf0f7f52f20a9a6a done by @em-

**Comment by JohnVillalovos** [comment]
I do notice that this will happen:

```
path/to/file
path%2fto%2ffile
path%252fto%252ffile
```

With this code:
```
    a = "path/to/file"
    print(a)
    a = a.replace("/", "%2f")
    print(a)
    a = urllib.parse.quote(a, safe="")
    print(a)
```

**Comment by nejch** [comment]
Yes, I think the `get()` override for ProjectFileManager (or at least the extra replace) is unnecessary now that the ID is already url-encoded. @JohnVillalovos are you already working on this? Otherwise I'll be pushing a fix tonight.

**Comment by nejch** [comment]
Related: https://github.com/python-gitlab/python-gitlab/issues/1356

**Comment by JohnVillalovos** [comment]
> @JohnVillalovos are you already working on this? Otherwise I'll be pushing a fix tonight.

@nejch  No. Sorry I am doing my day-job at the moment. So I can't work on it 😢

**Comment by xgui3783** [comment]
Thanks for the quick fix! 👏👏👏
