### ISSUE TITLE
Support for gitlab "iterations"

### ISSUE THREAD

**Issue by bradwood** [python-gitlab/python-gitlab#1417]
Hi,

Are there any plans to add support for gitlab iterations?

thanks
Brad

**Comment by JohnVillalovos** [comment]
Can you provide more detail? What are gitlab iterations? Maybe a link and some other info.

**Comment by nejch** [comment]
I think this is for https://docs.gitlab.com/ee/api/iterations.html.

@bradwood it's a Premium feature so we can't test it in integration tests but we'll get to it at some point. Feel free to give it a shot as well and open a PR ;)

**Comment by alpianon** [comment]
I'm interested in this feature, too. @JohnVillalovos are you planning to work on it? It should not be particularly difficult, API for iteration is very similar to API for milestones...

**Comment by JohnVillalovos** [comment]
> I'm interested in this feature, too. @JohnVillalovos are you planning to work on it? It should not be particularly difficult, API for iteration is very similar to API for milestones...

I don't have plans at this time to work on this. Possibly in the future.

**Comment by alpianon** [comment]
I checked the Gitlab API. Unfortunately, it allows only listing and reading iterations, for now: not very useful.... 

Probably it will be worth it to implement iteration support in python-gitlab when the Gitlab API will be more complete.

**Comment by gabeweaver** [comment]
The REST API currently only supports reading Iterations but the GraphQL has full CRUD support. It's also worth noting [Iteration Cadences are WIP](https://gitlab.com/groups/gitlab-org/-/epics/5077) (available in the GraphQL API currently) that will be an additional wrapper around a set of iterations.

**Comment by nejch** [comment]
> The REST API currently only supports reading Iterations but the GraphQL has full CRUD support. It's also worth noting [Iteration Cadences are WIP](https://gitlab.com/groups/gitlab-org/-/epics/5077) (available in the GraphQL API currently) that will be an additional wrapper around a set of iterations.

@gabeweaver just out of curiosity since you're here, I've noticed recently there's more of a GraphQL push over REST in official docs/release notes also - see e.g. https://about.gitlab.com/releases/2021/05/22/gitlab-13-12-released/#allow-or-prevent-duplicate-generic-package-uploads suggests you can use the GitLab API but only links to GraphQL, not REST.

I know graphql is already used more by the frontend and was always going to be more prominent in the future, but does this mean that REST will now already less likely be included in new features? (sorry for the off-topic. It's something we'd probably want to consider in terms of direction for this library, e.g. https://github.com/python-gitlab/python-gitlab/issues/1357)

**Comment by PPaques** [comment]
I have made several months ago a first implementation [here](https://github.com/PPaques/python-gitlab).

This one is used with an automated script to generate my team sprint reviews [here](https://gitlab.com/ppaques/auto-gitlab).

It is unfortunately not trivial to cherry-pick for now (It was based on 2.5 when all was inside a single file).

If I get time, I can try to update to master and make a PR.

**Comment by wskellenger-intrepid** [comment]
I added *extremely* basic support for iterations here:
https://github.com/wskellenger-intrepid/python-gitlab/tree/iterations_support

Like @PPaques I am also using it to generate data from our sprints.

**Comment by filiplajszczak** [comment]
@PPaques @wskellenger-intrepid Maybe upstream one of those or combination?

**Comment by wskellenger-intrepid** [comment]
@filiplajszczak I read the contribution guidelines, and I'm afraid my implementation is too incomplete to make a PR with it.  Is anyone willing to add some test cases or help push it up the hill?
