### ISSUE TITLE
Arrays are not sent correctly due to not using [] after variable name

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#1419]
Arrays are not sent correctly due to not using `[]` after variable name

GitLab's API documentation: https://docs.gitlab.com/ee/api/#array

### array types

`import_sources` is a parameter of type array:

```
curl --request POST --header "PRIVATE-TOKEN: <your_access_token>" \
-d "import_sources[]=github" \
-d "import_sources[]=bitbucket" \
"https://gitlab.example.com/api/v4/some_endpoint"
```

So when we send _array_ values we most append `[]` to the array's variable name. 

This has caused issues like:
  * https://github.com/python-gitlab/python-gitlab/issues/1407
  * https://github.com/python-gitlab/python-gitlab/issues/1256

**Comment by nejch** [comment]
Thanks for that @JohnVillalovos! I thought it might be something to do with arrays.

So this means we might have to manually maintain a lot of custom `_types` fields :thinking: I'm just not 100% sure that really all GitLab API endpoints take form-encoded arrays in addition to comma-delimited strings. See this upstream from a while ago (probably outdated now) https://gitlab.com/gitlab-org/gitlab-foss/-/issues/48007. I think it's time I added some parametrized integration tests for this.

**Comment by JohnVillalovos** [comment]
@nejch

On the good news, it seems like an `array` can be sent as a comma-delimited string. (https://gitlab.com/gitlab-org/gitlab/-/blob/5ecf69de438d221ed25f5f86756721f5f7b7b389/lib/api/validations/types/comma_separated_to_array.rb#L13)

This is probably the easiest way to make it work with using the `types.ListAtribute`. So then `iids=[1,2,3]` will become `iids=1,2,3` in the HTTP request.

More complicated would be to take a value like: `iids=[1, 2, 3]` and then convert that into `iids[]=1&iids[]=2&iids[]=3` in the HTTP request.

Thoughts?

**Comment by nejch** [comment]
Agreed, if gitlab handles it then this should do for now. I also just did a quick grep and seems like all `GET` params that are arrays get massaged with the above from strings :) If it's a problem later we can convert to an array with urlencode.
