### ISSUE TITLE
users in the project

### ISSUE THREAD

**Issue by volodaiy** [python-gitlab/python-gitlab#1422]
## Description of the problem, including code/CLI snippet
Cannot get a list of all members from the project (inherited users from the group are not transferred)

_projects = list(gl.projects.list(all=True))

for project in projects:
    print(project.id)
    print(project.members.list(all=True))_

## Expected Behavior
Returns all members of the project (request: /api/v4/projects/project_id/members/all?)

## Actual Behavior
Returns members added directly to the project (no group)

## Specifications

  - python-gitlab version: 2.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.6.1-ee

**Comment by JohnVillalovos** [comment]
Привет Vladimir,

You need to use:
https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-members

```
project.members.all()
```

Пока-пока,
John

**Comment by volodaiy** [comment]
Thank you John, my carelessness, sorry)

**Comment by nejch** [comment]
Also if you hit any limitations with `members.all()` please subscribe to https://github.com/python-gitlab/python-gitlab/pull/1376. Once that is merged, the new syntax will take all the usual `list()` arguments and be more flexible.

**Comment by volodaiy** [comment]
Nejc, you are doing a good job, thank you!
