### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace' when doing project.mergerequests.get

### ISSUE THREAD

**Issue by nicoleepp** [python-gitlab/python-gitlab#1425]
## Description of the problem, including code/CLI snippet

```
Traceback (most recent call last):
--
File "/var/task/tagbotgitlab/tagbot.py", line 31, in handler
status, msg = 200, handle_event(json.loads(evt.get("body", "{}")))
File "/var/task/tagbotgitlab/tagbot.py", line 53, in handle_event
return handle_open(payload)
File "/var/task/tagbotgitlab/tagbot.py", line 68, in handle_open
mr = p.mergerequests.get(mr_id, lazy=True)
File "/var/task/gitlab/exceptions.py", line 279, in wrapped_f
return f(*args, **kwargs)
File "/var/task/gitlab/mixins.py", line 46, in get
id = utils.clean_str_id(id)
File "/var/task/gitlab/utils.py", line 51, in clean_str_id
return id.replace("/", "%2F").replace("#", "%23")
AttributeError: 'NoneType' object has no attribute 'replace'
STATUS : 500
ERROR : Runtime error
```

## Expected Behavior
p.mergerequests.get(mr_id, lazy=True) should return an MR instead of throwing an error

## Actual Behavior
AttributeError: 'NoneType' object has no attribute 'replace'

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4 
  - Gitlab server version (or gitlab.com): 13.11.1-ee

**Comment by JohnVillalovos** [comment]
As a note the current version is 2.7.1.  Does the issue occur with that version too?

**Comment by JohnVillalovos** [comment]
I created a Pull Request adding a functional test that shows in the current version that it is working.

https://github.com/python-gitlab/python-gitlab/pull/1426

**Comment by nicoleepp** [comment]
Thanks, after updating to the newest version this works
