### ISSUE TITLE
Changing milestone of issue does not work

### ISSUE THREAD

**Issue by Cynerd** [python-gitlab/python-gitlab#1432]
## Description of the problem, including code/CLI snippet
I am trying to change  milestone of issue. I understand that I should set `milestone_id` with valid ID of milestone (reference https://github.com/python-gitlab/python-gitlab/issues/612 as well as https://docs.gitlab.com/ee/api/issues.html#edit-issue). The problem is that it seems to not work. The code passes without any error or warning but issue still has the old milestone assigned.

```
    project = ctx.projects.get(265)
    issue = project.issues.get(729)
    issue.milestone_id = 1372
    issue.save()
```

I am sure that I am setting correct milestone ID as I am getting it just few lines prior using code:
```
    group = ctx.groups.get(GROUP)
    new_milestone = next(group.milestones.list(title=new_milestone, as_list=False))
    print(new_milestone.id)
```

## Expected Behavior
Milestone changes.

## Actual Behavior
Nothing happens.

## Specifications

  - python-gitlab version: 2.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.10.3

**Comment by Cynerd** [comment]
The same behavior with python-gitlab 2.7.1 and Gitlab 13.11.3.

**Comment by nejch** [comment]
@Cynerd could you check if this might be related to your redirect issue in https://github.com/python-gitlab/python-gitlab/issues/1477? Then we can close at least one of these.

**Comment by Cynerd** [comment]
You are right. With redirect resolution suggested in #1477 it works.
