### ISSUE TITLE
Enable the GitHub "Discussions" feature 

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#1435]
What do people think about enabling the "Discussions" feature for the python-gitlab Github project? An example of the "Discussions" feature is here: https://github.com/beaker-project/beaker/discussions

https://docs.github.com/en/discussions

**Comment by nejch** [comment]
Done! :)

https://github.com/python-gitlab/python-gitlab/discussions

**Comment by JohnVillalovos** [comment]
Thanks @nejch !
