### ISSUE TITLE
No possibility to check if file exists

### ISSUE THREAD

**Issue by valentingregoire** [python-gitlab/python-gitlab#1447]
## Description of the problem, including code/CLI snippet
When wanting to check if a file exists, you either have to get the entire file, the raw file content or the blame history. None of these seem to fit for the purpose to see if a file exists or not.

## Expected Behavior
I am able to check if a file exists by running the `HEAD` method described in the [official GitLab Rest API documentation](https://docs.gitlab.com/ee/api/repository_files.html#get-file-from-repository).

## Actual Behavior
In order not to get the full content of the file, I kind of cheat by fetching the blame history.

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): newset

**Comment by nejch** [comment]
Related to https://github.com/python-gitlab/python-gitlab/issues/682, which already has a HEAD implementation in https://github.com/python-gitlab/python-gitlab/commit/f404d394960683d68ccaf3c129f75a2582a2fb77 (unfinished)

**Comment by JohnVillalovos** [comment]
To fix this we will need to have a method which does a `HEAD` request. Currently we don't have any methods which do a `HEAD` request.

**Comment by valentingregoire** [comment]
> To fix this we will need to have a method which does a `HEAD` request. Currently we don't have any methods which do a `HEAD` request.

If we look at @nejch's answer, there is an issue already being solved with a `HEAD` implementation.
