### ISSUE TITLE
gl.auth() - None

### ISSUE THREAD

**Issue by volodaiy** [python-gitlab/python-gitlab#1453]
## Description of the problem, including code/CLI snippet
Good afternoon!
Is it correct that gl.auth () - returns "None"?

import gitlab
gl = gitlab.Gitlab(url='https://git.domain.com', private_token='*********')
gl.auth()
print(gl.auth())

## Expected Behavior
200 OK

## Actual Behavior
None

## Specifications

  - python-gitlab version: 2.7.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.6.1-ee

**Comment by JohnVillalovos** [comment]
Привет @volodaiy 

So `gl.user` will contain the result of the `gl.auth()` call as an FYI.

It is sort of minimally mentioned in the docs: https://python-gitlab.readthedocs.io/en/stable/api-usage.html#gitlab-gitlab-class

```
# make an API request to create the gl.user object. This is mandatory if you
# use the username/password authentication.
gl.auth()
```

I'm unsure if it should or should not be returned in the call to `gl.auth()`

Пока-пока

**Comment by nejch** [comment]
We have started adding some more returns to methods recently so maybe we could return it, but agreed it's easily accessible already.

Otherwise, python-gitlab will raise a `GitlabAuthenticationError` on 401, rather than return a status code, so you can use this for status checks.

**Comment by volodaiy** [comment]
Good day!
Dear friends, thank you for your answers.
We decided to use the check for reading users from projects.
