### ISSUE TITLE
Linters check does not appear to be required

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#1464]
I see in a pull request the following for the CI:

![image](https://user-images.githubusercontent.com/578155/119232040-8f036a00-bad8-11eb-9f0f-f8b9a8984408.png)

Lint/linters does not say that it is required. Probably it should be.

**Comment by nejch** [comment]
Oops, must be a leftover from when we put them into one job, thanks! I've added it now:

![image](https://user-images.githubusercontent.com/16777978/119236396-77a79980-bb37-11eb-8f3d-9d61f3de11f1.png)

**Comment by JohnVillalovos** [comment]
Awesome. Thank you.
