### ISSUE TITLE
sudo kwarg needs to be capitalized--docs and test project incorrect

### ISSUE THREAD

**Issue by JamesTaliaferro** [python-gitlab/python-gitlab#1466]
# My original assessment of the problem was incorrect, see the coomments 

## Description of the problem, including code/CLI snippet
The [test project](https://github.com/python-gitlab/python-gitlab/blob/b498ebd804461031e2d2d391f77dfbbcf0d2e281/tools/functional/api/test_projects.py) demonstrating the sudo feature has this line:

`sudo_project = gl.projects.create({"name": "sudo_project"}, sudo=user.id)`

This mistake also appears in [tools/functional/api/test_groups.py](https://github.com/python-gitlab/python-gitlab/blob/f35c73e50918e4d55b70323669f394e52e75cde9/tools/functional/api/test_groups.py) 

And the [docs](https://python-gitlab.readthedocs.io/en/stable/api-usage.html?highlight=sudo#sudo) describe the feature as follows:

> Sudo
>If you have the administrator status, you can use sudo to act as another user. For example:
>'p = gl.projects.create({'name': 'awesome_project'}, sudo='user1')'

This is wrong. The sudo kwarg needs to be capitalized, as in

`p = gl.projects.create({'name': 'awesome_project'}, SUDO='user1')`

Otherwise it will raise `gitlab.exceptions.GitlabCreateError: 404: 404 Project Not Found`. This error is also misleading. The project was found just fine, but the whole thing fails if the keyword isn't capitalized.

## Expected Behavior

The docs and example code should have the correct syntax.

## Actual Behavior

See above

## Specifications

  - python-gitlab version: `python-gitlab==2.7.1`
  - API version you are using (v3/v4): `v4`
  - Gitlab server version (or gitlab.com): `13.10`

**Comment by JohnVillalovos** [comment]
That is very odd. The docs say to use `sudo` for a query parameter. And if a header to use `Sudo`

https://docs.gitlab.com/ee/api/README.html#sudo

**Comment by JamesTaliaferro** [comment]
I was incorrect. It doesn't throw the error when you capitalize it (which made me think it was working), but it does not actually sudo.

**Comment by JamesTaliaferro** [comment]
The user I was impersonating didn't have access to the repository I was having them access.
I didn't realize that sudo took on their permissions as well as acting on their behalf--I thought sudo would post with their name, but my permissions.

I gave that user access and now it works.

Sorry for the trouble.

**Comment by JohnVillalovos** [comment]
Glad you figured it out! Thanks.
