### ISSUE TITLE
enabled_git_access_protocol settings missing

### ISSUE THREAD

**Issue by derek-austin** [python-gitlab/python-gitlab#148]
How could I change enabled_git_access_protocol as described in the API https://docs.gitlab.com/ce/api/settings.html ?
Tried in settings http://python-gitlab.readthedocs.io/en/latest/gl_objects/settings.html , with no luck even after applying #147

**Comment by gpocentek** [comment]
You can set 'http' or 'ssh' but it seems that settings both is broken.

`````
s = gl.settings.get()
s.enabled_git_access_protocol = 'ssh'  # or 'http'
s.save()
# Enabling both should work with the following, but it's broken at the moment
# s.enabled_git_access_protocol = None
# s.save()

**Comment by gpocentek** [comment]
I tried a lot of things to make this work but didn't find a solution. It might be a bug on the gitlab side. Issue opened here: https://gitlab.com/gitlab-org/gitlab-ce/issues/24047

**Comment by gpocentek** [comment]
Related to a more generic issue tracked at https://gitlab.com/gitlab-org/gitlab-ce/issues/23149

**Comment by gpocentek** [comment]
This problem has been fixed upstream, and it works fine with the v4 API.
