### ISSUE TITLE
Object deletion from lazy get

### ISSUE THREAD

**Issue by vbisserie** [python-gitlab/python-gitlab#1494]
## Description of the problem, including code/CLI snippet
Lazy objects with name containing http encoded character (like "/") can not be deleted.

## Expected Behavior
```
p = gitlab.projects.get(1)
b = p.branches.get("foo/bar", lazy=True)  # The name shall contain http encoded char like "/"
b.delete()
```
Branch shall be deleted

## Actual Behavior
`b.delete()` will raise an exception 404

## Specifications

  - python-gitlab version: v2.7.1
  - API version you are using (v3/v4): v4

## Suggestion
https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/utils.py#L60
`clean_str_id` seems to be called on an already encoded name.
"foo/bar" -> "foo%2Fbar" -> "foo%252Fbar"

**Comment by nejch** [comment]
Related to https://github.com/python-gitlab/python-gitlab/issues/1356
