### ISSUE TITLE
Suggestion: url encode project paths automatically

### ISSUE THREAD

**Issue by chris-peterson** [python-gitlab/python-gitlab#1498]
## Description of the problem, including code/CLI snippet

Would be nice to not have to url-encode project paths when calling project APIs.  Feels pretty safe to replace `/` with `%2F` and not break folks

## Expected Behavior

Allow project paths to contain `/` without any escaping/encoding

## Actual Behavior

Results in 404s, project not found.  have to url encode and try again.

## Specifications

  - python-gitlab version: 2.7.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.10.3

**Comment by nejch** [comment]
Hi @chris-peterson thanks, can you give some examples of endpoints that don't allow project paths to have `/`?

Things like `gl.projects.get("path/to/project")` should already work. Or did I misunderstand the issue? :)

**Comment by chris-peterson** [comment]
@nejch -- I am grateful that the get function will accept non-encoded project ids.  the suggestion is for other APIs, e.g. updating a project.  here's an example:

works:
`gitlab project update --id 'mygroup%2Fmyproject' --tag-list 'some value'`

fails:
`gitlab project update --id 'mygroup/myproject' --tag-list 'some value'`

my workaround so far has been to either:
1) url encode project ids before calling APIs OR
2) always look up the integer ID first and pass that instead

**Comment by nejch** [comment]
Thanks! I see, so this is mostly an issue with the CLI as with the API you would usually first get the object (even if lazily), but we should update this, it should be a few one-liners. Thanks for the report!

Related to #1356
