### ISSUE TITLE
Handle pagination of results with more than 10,000 results gracefully

### ISSUE THREAD

**Issue by Siyfion** [python-gitlab/python-gitlab#1506]
## Description of the problem, including code/CLI snippet

Currently if you try to get a list with a _lot_ of results, eg. the main GitLab project's issues list

```python
gl = gitlab.Gitlab('https://gitlab.com', private_token='XXXXXXX')
gl.auth()
gitlab_prj = gl.projects.get(278964, lazy=True)
issues = gitlab_prj.issues.list(order_by='updated_at', sort='asc', per_page=100, as_list=False)
```

You'll get an error when you try and use the list:

```
Exception has occurred: TypeError
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Due to the fact that, for performance reasons GitLab don't return certain headers when the responses exceed 10,000: https://docs.gitlab.com/ee/user/gitlab_com/index.html#pagination-response-headers

## Expected Behavior

Gracefully handle this lack of `x-total` and `x-total-pages` header, either by limiting the results to 10,000 responses, or allowing a user to manually set the `_list._total` and `_list._total_pages` values.

## Actual Behavior

Crashes with the above exception.

## Specifications

  - python-gitlab version: `2.7.1`
  - API version you are using (v3/v4): `v4`
  - Gitlab server version (or gitlab.com): `gitlab.com`

**Comment by VenkatsQuest** [comment]
This is the call stack , hope this information is helpful to fix the issue,

/Users/anil/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/gitlab/client.py


    @property
    def total_pages(self) -> int:
        """The total number of pages."""
        if TYPE_CHECKING:
            assert self._total_pages is not None
        return int(self._total_pages)



/Users/anil/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/gitlab/base.py

    @property
    def total_pages(self) -> int:
        """The total number of pages."""
        return self._list.total_pages

/Users/anil/PycharmProjects/pythonProject/main.py
    iterator_projects = gl.projects.list(owned=True, as_list=False , pagination="keyset", order_by="id")

    total_pages = iterator_projects.total_pages
    print(total_pages)

**Comment by nejch** [comment]
Reproduced in https://github.com/python-gitlab/python-gitlab/pull/1788 and fixed in https://github.com/python-gitlab/python-gitlab/pull/1773.
