### ISSUE TITLE
CI builds are failing with Coverage. Error mentions issue with upload token.

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#1508]
Seeing issues in the CI recently.

https://github.com/python-gitlab/python-gitlab/pull/1487/checks?check_run_id=2788591963
```
<snip>
->  Pinging Codecov
https://codecov.io/upload/v4?package=github-action-v1.5.2-1.0.3&token=secret&branch=jlvillal%2Fcheck_attrs&commit=81c8b3f1932d2652f3d70f656034bbc407c5bc7c&build=923354654&build_url=http%3A%2F%2Fgithub.com%2Fpython-gitlab%2Fpython-gitlab%2Factions%2Fruns%2F923354654&name=&tag=&slug=python-gitlab%2Fpython-gitlab&service=github-actions&flags=unit&pr=1487&job=Test&cmd_args=n,F,Q,Z,f,C
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
404
==> Uploading to Codecov
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11114  100   171  100 10943    746  47786 --:--:-- --:--:-- --:--:-- 48532
    {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: Codecov failed with the following error: The process '/usr/bin/bash' failed with exit code 1
```

**Comment by nejch** [comment]
This seems to be related to https://github.com/codecov/codecov-action/issues/330, if it's not resolved quickly we can maybe allow failure for codecov.

**Comment by thomasrockhu** [comment]
@JohnVillalovos Tom from Codecov here. I went to the link you gave but I'm not seeing the error message you posted. Am I looking in the wrong place?

**Comment by JohnVillalovos** [comment]
> @JohnVillalovos Tom from Codecov here. I went to the link you gave but I'm not seeing the error message you posted. Am I looking in the wrong place?

@thomasrockhu 

I'm guessing that Github doesn't keep old logs around. So when a new run happens it seems to disappear. At the time I made the comment it was an error. I copied it as shown above.

**Comment by JohnVillalovos** [comment]
@thomasrockhu 

A screenshot I just made where I still had the tab open:

![image](https://user-images.githubusercontent.com/578155/121585601-a18e0680-c9e7-11eb-8277-9ef9d1227493.png)

**Comment by thomasrockhu** [comment]
Thanks @JohnVillalovos, we were having some issues a few days ago, but things have cleared up since. Have you seen the error yesterday or today?

**Comment by nejch** [comment]
@thomasrockhu I think @JohnVillalovos re-ran the workflow so it went green, but the original run is here https://github.com/python-gitlab/python-gitlab/runs/2788591963?check_suite_focus=true.

We ran a few more actions and I haven't seen any issues. I guess we can close this if no one else is reporting issues? We only pin the action at `@v1` so we already got the updates.

**Comment by JohnVillalovos** [comment]
I think the issue has been resolved. Thanks!
