### ISSUE TITLE
API docs missing for main Gitlab class

### ISSUE THREAD

**Issue by TheFriendlyCoder** [python-gitlab/python-gitlab#1509]
The latest version of the [API docs](https://python-gitlab.readthedocs.io/en/stable/api/gitlab.html) do not include docs for the main gitlab.Gitlab class. This prevents projects from leveraging intersphinx (the documentation plugin for Sphinx) to cross reference docs with this library. This should be fixed.

For testing purposes you can use the sphobjinv tool to query for the class in the object inventory, by doing something like this:

```
pip install sphobjinv
sphobjinv suggest -au https://python-gitlab.readthedocs.io/en/stable/objects.inv Gitlab | grep gitlab\.Gitlab
```

The expected output from this command should be something like:

```
:py:class:`gitlab.Gitlab`
```

**Comment by nejch** [comment]
By latest version do you mean that it used to work and it's now broken or was that just a general comment?

Sorry can't check, typing from my phone here :)
