### ISSUE TITLE
The branch name containing "#" needs to be transcoded by urlencode

### ISSUE THREAD

**Issue by XuHandsome** [python-gitlab/python-gitlab#1510]
## Description of the problem
The "protect/unprotect" interface cannot be used when the branch name contains "#"

## Expected Behavior
`test.py`
```python
#!/usr/bin/env python

import sys
import gitlab
url = 'http://192.168.104.186/'
token = 'bA3inGgz77LBPNdLwCxp'

gl = gitlab.Gitlab(url, private_token=token)

project_id=28
project = gl.projects.get(project_id)

new_br = sys.argv[1]

project.branches.create({'branch': new_br, 'ref':'master'}).protect()
```
```bash
python test.py ohh#yes
```
The branch "ohh#yes" should be created and set to protect the branch

## Actual Behavior
But，get http error：
![image](https://user-images.githubusercontent.com/57780281/121667468-e5166c80-cadc-11eb-80bd-50ebba38d9fa.png)

on project, branch created, but not set protect
![image](https://user-images.githubusercontent.com/57780281/121667603-0bd4a300-cadd-11eb-9eb9-df2d02943870.png)

## Specifications

  - python-gitlab version: 2.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): local version 12.10.12

## The solution
Modify the _build_url function in "gitlab/client.py"
replace "#" in path with "%23" :
![image](https://user-images.githubusercontent.com/57780281/121668115-8dc4cc00-cadd-11eb-8b5d-8fd2bc82f6f1.png)

## Conclusion
![image](https://user-images.githubusercontent.com/57780281/121668493-ed22dc00-cadd-11eb-8243-6630e10dc36e.png)

Get what I want：
![image](https://user-images.githubusercontent.com/57780281/121668509-f57b1700-cadd-11eb-8efd-f6fc72d384c8.png)

So far, only "#" has been found to be problematic. Other special symbols, such as "!" "@" "&" "-" No problem
Can I submit a Merge Request？

**Comment by JohnVillalovos** [comment]
> Can I submit a Merge Request？

Of course!
