### ISSUE TITLE
Deprecate tag.set_release_description and remove it from docs

### ISSUE THREAD

**Issue by PPaques** [python-gitlab/python-gitlab#1521]
## Description of the problem, including code/CLI snippet
It seems that the code we use to create a release from a tag [here](https://github.com/python-gitlab/python-gitlab/blob/8753add72061ea01c508a42d16a27388b1d92677/gitlab/v4/objects/tags.py#L19) has been deprecated and removed

We should update to use the new release API

I'll try to investigate a little later tonight as it is blocking my team for some automated release tools.

## Expected Behavior
- set_release_description() create or update a release

## Actual Behavior
- 404 error

## Specifications

  - python-gitlab version: 2.8 (and 2.5)
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
`python-gitlab` already supports the new API, which has been around for a while: https://python-gitlab.readthedocs.io/en/stable/gl_objects/releases.html

So please just use the Releases API as the official upstream docs deprecated using the tags API a long time ago.

**Comment by PPaques** [comment]
I was thinking to update the function to make it use the new API that is indeed already implemented.  This allows previous scripts to work and keep backward compatibility with python-gitlab.

I agree it is probably a better approach to stick as much as possible to the GitLab  API and therefore remove completely the function.

Can you at least remove it from the python-gitlab doc (or mark it as deprecated)? 
  - I used it 3 months ago for a new project without knowing it was deprecated.  
  - And this is annoying

**Comment by nejch** [comment]
Yes, already edited the issue title to reflect that :)

Removing it completely also makes sense as this was kind of a special/custom method that did more than just wrap the gitlab API (it idempotently created/updated the notes), something we've said we probably don't want for this library.

**Comment by PPaques** [comment]
I also see another issue: With the Release API, I cannot anymore update the content.

There is another issue here: 
 - With the current implementation, the Release Manager is using `NoUpdateMixin`
 - This prevents editing a release note.
    - while it is [supporter](https://docs.gitlab.com/ee/api/releases/#update-a-release) on gitlab API

That's a little annoying as previous the function `set_release_description` which is a "regression" in terms of possibilities of python-gitlab.

**Comment by JohnVillalovos** [comment]
> I was able to make it work.
> 
> I can create a Pull Request if you want

A PR would be great! Thanks 😊

**Comment by PPaques** [comment]
Done: https://github.com/python-gitlab/python-gitlab/pull/1522. I hope I've not made too many mistakes.
