### ISSUE TITLE
Service integration is broken

### ISSUE THREAD

**Issue by hoerup** [python-gitlab/python-gitlab#1523]
## Description of the problem, including code/CLI snippet

Gitlab service integration has changed so list only returns the active and get by name will fail if the service is not enabled

service = project.services.get('jira') #if jira service is not enabled then this will fail

## Actual Behavior

Traceback (most recent call last):
  File "/home/toh/.local/lib/python3.7/site-packages/gitlab/exceptions.py", line 304, in wrapped_f
    return f(*args, **kwargs)
  File "/home/toh/.local/lib/python3.7/site-packages/gitlab/mixins.py", line 112, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/home/toh/.local/lib/python3.7/site-packages/gitlab/client.py", line 630, in http_get
    "get", path, query_data=query_data, streamed=streamed, **kwargs
  File "/home/toh/.local/lib/python3.7/site-packages/gitlab/client.py", line 598, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 404: 404 Service Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./config_integrations.py", line 126, in <module>
    jira = project.services.get('jira')
  File "/home/toh/.local/lib/python3.7/site-packages/gitlab/v4/objects/services.py", line 273, in get
    obj = super(ProjectServiceManager, self).get(id, **kwargs)
  File "/home/toh/.local/lib/python3.7/site-packages/gitlab/exceptions.py", line 306, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Service Not Found

## Specifications
  - python-gitlab version: 2.8
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.12.3

**Comment by nejch** [comment]
This is by design now in the GitLab API, see https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61646. "This MR changes that endpoint to return a 404 response when a project does not have the service."

It seems like they want to treat "inactive" services as "non-existent" now - the same way as other non-existent resources like projects, and return a 404, which is something you also have to handle yourself in a try/except in python-gitlab already.

**Comment by hoerup** [comment]
Yeah im aware of all that. But this mens that python-gitlab cant be used to enable a service

**Comment by nejch** [comment]
See https://github.com/python-gitlab/python-gitlab/blob/c3ddae239aee6694a09c864158e355675567f3d2/tests/functional/api/test_projects.py#L216-L218 for a workaround, but we should probably create a custom `create()` for this one. Services are a bit special in the API 🤔

**Comment by nejch** [comment]
I think documenting something like this might be better than figuring out what causes a justified 404 vs. a non-activated service:

```python
mattermost = project.services.get("mattermost", lazy=True)
mattermost.webhook = "http://mattermost_host/hooks/blabla"
mattermost.save()
```
