### ISSUE TITLE
(cli) (feature request) - Verbose Output of HTTP interactions

### ISSUE THREAD

**Issue by chris-peterson** [python-gitlab/python-gitlab#1530]
## Description of the problem, including code/CLI snippet

It would be nice if `--verbose` showed the HTTP request and response from the gitlab server.

## Expected Behavior

Recently, while debugging #1529, I had to consult server-side access logs to examine the posted URL.  It would be nice if `--verbose` emitted the HTTP requests and responses as they occur.

## Actual Behavior

`--verbose` doesn't seem to have an effect on many commands. 

## Specifications

  - python-gitlab version: 2.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.x

**Comment by JohnVillalovos** [comment]
If using the API you can call the Gitlab method `enable_debug`

```
gl = gitlab.Gitlab(url="SOMETHING")
gl.enable_debug()
```

In the CLI it supports the `--debug` flag.

**Comment by chris-peterson** [comment]
nice!

tested again with `--debug` and 👍
