### ISSUE TITLE
pre-commit hook for mypy fails

### ISSUE THREAD

**Issue by antti-mikael** [python-gitlab/python-gitlab#1539]
## Description of the problem, including code/CLI snippet

```sh
$ git status --short
M  gitlab/v4/objects/container_registry.py
$ git commit
black....................................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

gitlab/v4/objects/ldap.py:20: error: Function is missing a type annotation
gitlab/v4/objects/repositories.py:15: error: Function is missing a type annotation
gitlab/v4/objects/repositories.py:38: error: Function is missing a type annotation
...
```

Maybe the mypy hook could be configured to ignore missing annotations or warn instead of erring -- at least until the annotations are in place:

```patch
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 80c8fb8..c69e125 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -24,3 +24,4 @@ repos:
     rev: v0.812
     hooks:
       - id: mypy
+        args: ["--allow-untyped-defs"]
```

## Expected Behavior

I'm able to make commits for files that don't have type annotations.

## Actual Behavior

mypy fails for missing function annotations.

## Specifications

  - python-gitlab version: master (85713bb)
  - API version you are using (v3/v4): N/A
  - Gitlab server version (or gitlab.com): N/A

**Comment by nejch** [comment]
Thanks for opening the issue, we already had this reported but i forgot to open one!

Yeah, that would help although then people might get CI failures because pre-commit wouldn't catch issues in files where it already should check for it.

I think a better solution would be to replace the `files` list in our config with an `exclude` pattern because currently the pre-commit hook is probably overriding the default files list and hence fails.

https://mypy.readthedocs.io/en/stable/config_file.html#confval-files

https://github.com/python-gitlab/python-gitlab/blob/85713bbbecdcec577a72749d2e495f823791b00f/.mypy.ini#L1-L2

I will test this tonight but feel free to already open a PR if you get it to work :)

**Comment by antti-mikael** [comment]
Sorry, I totally missed the `.mypy.ini`. I'll see if I have the time to fiddle with this.

**Comment by antti-mikael** [comment]
> I think a better solution would be to replace the `files` list in our config with an `exclude` pattern because currently the pre-commit hook is probably overriding the default files list and hence fails.

After some some digging around it seems that `exclude` has the same problem as `files`: positional command line arguments will override the configuration. From [mypy's docs](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-exclude):

> Note that [`--exclude`] flag only affects recursive discovery, that is, when mypy is discovering files within a directory tree or submodules of a package to check. If you pass a file or module explicitly it will still be checked.

One solution would be to mirror the `files` pattern in the pre-hook config. It's not a nice solution but only one I have managed to come up with so far.

**Comment by nejch** [comment]
I have something in https://github.com/python-gitlab/python-gitlab/pull/1562, not the prettiest either but it should now take whatever args `pre-commit` throws at it and ignore errors where needed.
