### ISSUE TITLE
Feature request: create access token for another user

### ISSUE THREAD

**Issue by t0ny-peng** [python-gitlab/python-gitlab#1540]
## Description of the problem, including code/CLI snippet

Hi there. I'm trying to use python-gitlab to realize the credential rotation, and one task is to create an access token of a user. I notice that there's a [RESTful api](https://docs.gitlab.com/ee/api/users.html#create-a-personal-access-token) for that purpose. However, this API seems to be missing in python-gitlab package. It would be helpful if it can be implemented. 

## Expected Behavior

There should be a way to programmatically create a personal access token with given name and permission scope. 

## Specifications

  - python-gitlab version: v2.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): v14.0ee

**Comment by nejch** [comment]
Thanks @t0ny-peng. The `create()` method wasn't originally implemented because GitLab forgot to add the API when they first added the endpoint :rofl: But then we forgot to follow up

This should be an easy addition.

**Comment by t0ny-peng** [comment]
@nejch Thanks for the reply😂 Do you think it easy enough to be part of the next release?
