### ISSUE TITLE
Can't get pipelines test_report

### ISSUE THREAD

**Issue by davbr** [python-gitlab/python-gitlab#1551]
## Description of the problem, including code/CLI snippet
I'm trying to get a pipline's test report but i get the error seen below under Actual Behaviour. 

## Expected Behavior

`test_report = pipeline.test_report.get() `

where pipeline is of type `gitlab.v4.objects.ProjectPipeline`
returns test report of pipeline

## Actual Behavior

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dban/.local/lib/python3.8/site-packages/gitlab/base.py", line 62, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'test_report'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dban/.local/lib/python3.8/site-packages/gitlab/base.py", line 82, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'test_report'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dban/repos/api-gitlab/test.py", line 22, in <module>
    test_report = pipeline.test_report.get() # does not work
  File "/home/dban/.local/lib/python3.8/site-packages/gitlab/base.py", line 84, in __getattr__
    raise AttributeError(name)
AttributeError: test_report
```

## Specifications

  - python-gitlab version: 2.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.0.5

**Comment by JohnVillalovos** [comment]
Can you please provide a small snippet of code which demonstrates this issue?

**Comment by davbr** [comment]
sure :)

I have created this https://gitlab.com/davbr1/api_test_report which shows my issue.

just clone the repo, setup python and run the script

**Comment by JohnVillalovos** [comment]
Can you try using `pipelines = project.pipelines.get()` instead of `list`?

**Comment by davbr** [comment]
i tied this:
```
pipeline = project.pipelines.get("339877782")
test_report = pipeline.test_report.get()
```
but unfortunately it gave the same error as before

**Comment by JohnVillalovos** [comment]
As a note, strange errors can occur when using 'http' instead of 'https' for specifying the Gitlab server. Shouldn't affect this case, but anything that causes a `PUT` or `POST` action will have errors.

**Comment by davbr** [comment]
weird! Are you using 2.9.0 from pypi?

**Comment by JohnVillalovos** [comment]
```
$ pip freeze | grep python-gitlab
python-gitlab==2.9.0
```

```
$ python
Python 3.9.6 (default, Jul 16 2021, 00:00:00)
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> print(gitlab.__version__)
2.9.0
```

**Comment by davbr** [comment]
this is a bit embarrassing then...but I found the issue. 

Even though I where in my .venv vscode was still using an old version of the python-gitlab package (2.6.0). 

Thank you for helping be out @JohnVillalovos and sorry for the noise.

**Comment by JohnVillalovos** [comment]
Oh. Glad you figured it out! 😊
