### ISSUE TITLE
commit misses stats attribute

### ISSUE THREAD

**Issue by felixwang0617** [python-gitlab/python-gitlab#1572]
## Description of the problem, including code/CLI snippet
I try to get code statistic of a commit.

~~~ python
commits = project.commits.list()
for commit in commits:
   print(commit.stats)
~~~

## Expected Behavior
 {'additions': 1, 'deletions': 1, 'total': 2}

## Actual Behavior
AttributeError: stats

## Specifications

  - python-gitlab version: 2.10.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.5.2

**Comment by nejch** [comment]
`project.commits.list()` returns what the commit list API provides - stats is not included. You need to call the "get single commit" endpoint after, to get all the details.

```python
commits = project.commits.list()
for c in commits:
   commit = project.commits.get(c.id)
   print(commit.stats)
```

This is similar to the issue/MR situation shown in the FAQ. https://python-gitlab.readthedocs.io/en/stable/faq.html#faq

Feel free to reopen or submit a PR to the docs to clarify this!
