### ISSUE TITLE
Access to a member's expiry date after sharing a project 

### ISSUE THREAD

**Issue by SebastienMorais** [python-gitlab/python-gitlab#1582]
Hi, i've looked around to see if what i'm describing was normal or not but didn't found anything.
Sorry in advance if what i'm requesting is against expected behavior.

## Description of the problem, including code/CLI snippet

When one shares a project with a group and specifies some expiration date, the new members don't have the associated expiration date that can be accessed through `expires_at`.

```python
import gitlab
import datetime

gl = gitlab.Gitlab(gitlab_url, private_token=token)
date = datetime.datetime.now() + datetime.timedelta(days=1)
date_fmted = date.strftime("%d-%m-%Y")

user_name = "user"
user = gl.users.create({'email': f'{user_name}@test.com', 'password': 's3cur3s3cr3T', 'username': f'{user_name}', 'name': f'{user_name}', 'skip_confirmation': True})

group_name = "group"
group = gl.groups.create({'name': '{}'.format(group_name), 'path': '{}'.format(group_name), 'visibility': "private"})
group.members.create({'user_id': user.id, 'access_level': 20})

project_name = "project"
project = gl.projects.create({'name': '{}'.format(project_name), 'path': '{}'.format(project_name), 'visibility': "private"})

# Prints empty list
print([(member.username, member.expires_at) for member in project.members.all(all=True)])

project.share(group.id, 30, expires_at=date_fmted)

# Prints [('user', None)]
print([(member.username, member.expires_at) for member in project.members.all(all=True)])
```

## Expected Behavior

I would expect that the expiration date of a new member that got access through project `share` would be the same as the expiration date of the group sharing.

## Actual Behavior

When one wants to access the member's `expires_at` attribute, the returned value is `None`.

## Specifications

  - python-gitlab version: 2.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): Gitlab server through docker gitlab/gitlab-ee:latest

**Comment by JohnVillalovos** [comment]
At first glance this doesn't seem like a python-gitlab issue, but ...

Without investigating, you may need to do a `.get` on the member. Results returned from list type methods often do not contain all the data.

So something like this completely untested code:
```
for member in project.members.all(all=True):
    member = project.members.get(member.id)
    print(member.username, member.expires_at)
```

If that is not the issue then you likely will have to investigate how the API works https://docs.gitlab.com/ce/api/projects.html#share-project-with-group

**Comment by SebastienMorais** [comment]
I did a minor change `member = project.members_all.get(member.id)` otherwise the member was not found.

Unfortunately it was not due to that :(

Before posting I had already looked at the documentation but had not managed to find any information. It is likely that this is nominal behavior.

Sorry for the inconvenience and thanks for your feedback!
