### ISSUE TITLE
Is /projects/:id/groups implemented

### ISSUE THREAD

**Issue by linceaerian** [python-gitlab/python-gitlab#1590]
## Description of the problem, including code/CLI snippet

Following official documentation below:
https://docs.gitlab.com/ee/api/projects.html#list-a-projects-groups

I would expect to have a way to list the groups currently added on 
project, but I do not find the way to do it and I'm not able to see if it's implemented in a sub function (I don't think so, but I'm never too sure :) ).

## Expected Behavior

A cli function / args is available either in :

`gitlab project-group`

or in:

`gitlab project group`

## Actual Behavior

```
gitlab: error: argument what: invalid choice: 'project-group' 
```

and

```
gitlab project: error: argument whaction: invalid choice: 'group'
```

And nothing in `--help` seems relevant.

## Specifications

  - python-gitlab version: python-gitlab-2.10.1
  - API version you are using (v3/v4): v4 
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
This is not currently implemented, we must've missed that one if it's been recently added to the API. Thanks for the report! :)
