### ISSUE TITLE
Feature Request: Support promoting project labels

### ISSUE THREAD

**Issue by StingRayZA** [python-gitlab/python-gitlab#1602]
## Description of the problem, including code/CLI snippet

This request is for supporting the ability to 'promote' a project label to a group one. This exists in the Gitlab API.

Specifically, https://docs.gitlab.com/ee/api/labels.html#promote-a-project-label-to-a-group-label

## Expected Behavior

`project.labels.promote(label_id)`
or 
`gitlab project-label promote` (CLI)

## Actual Behavior

Promotion not supported

## Specifications

  - python-gitlab version: Latest
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): Any

**Comment by StingRayZA** [comment]
I'd like to work on this issue - if you could assign it to me, that'd be great! 😁

**Comment by max-wittig** [comment]
@StingRayZA Thanks 👍
