### ISSUE TITLE
Can't save existing group hooks

### ISSUE THREAD

**Issue by sjadema** [python-gitlab/python-gitlab#1607]
## Description of the problem, including code/CLI snippet

In #1496 support for group hooks was introduced. Deleting and adding hooks works as expected but i can't update a hook. When calling the `GroupHook.save()` method, the GitLab API responds with a `500`. After debugging, i found out that the payload sent by the client is invalid. The `group_id` attribute should not be send with the body parameters.

## Expected Behavior

It should be possible to save existing group hooks using `GroupHook.save()`.

## Actual Behavior

GitLab API returns a `500`.

## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.2.4-ee

**Comment by JohnVillalovos** [comment]
Would be useful to see an example of the code that is failing.

**Comment by nejch** [comment]
Probably a duplicate of https://github.com/python-gitlab/python-gitlab/issues/987. I guess the same goes for project hooks and others. We might need to `pop()` some arguments in the mixins.
