### ISSUE TITLE
Cant query current ldap groups

### ISSUE THREAD

**Issue by andrewlarssen** [python-gitlab/python-gitlab#1609]
## Description of the problem, including code/CLI snippet
There are methods to both add and remove ldap links on groups but not to query the existing ldap links

## Expected Behavior
There should be a method on group to query the currently linked ldap groups hitting "https://gitlab.example.com/api/v4/groups/:id/ldap_group_links"

## Actual Behavior
No method exists

## Specifications

  - python-gitlab version: latest
  - API version you are using (v3/v4): 4
  - Gitlab server version (or gitlab.com): latest

**Comment by max-wittig** [comment]
That's an EE feature. As I have no EE instance to test with, this is not really a priority for the project.

But we're very open to MRs, so if you want to contribute that I would be happy to review it.

**Comment by andrewlarssen** [comment]
Thanks @max-wittig for the reply. Happy to create MR. I have already been having a play. There are a couple of things that may need to discuss like the inconsistency of the API. Other api calls return an empty list if there are no elements found where as this returns a 404 and a message. Once I have an MR I will add another comment

**Comment by andrewlarssen** [comment]
@max-wittig created https://github.com/python-gitlab/python-gitlab/pull/1612

**Comment by nejch** [comment]
Now done in https://github.com/python-gitlab/python-gitlab/pull/2371
