### ISSUE TITLE
mr.merge()  status:404 cannot get merge request id,it got None

### ISSUE THREAD

**Issue by comk88** [python-gitlab/python-gitlab#1627]
## Description of the problem, including code/CLI snippet
mr = project.mergerequests.create({'source_branch': source_branch,'target_branch': target_branch,\
                                       'title': tittle,'labels': labels})
mr.merge()
response status_code 406
then: I check the log of gitlab:
PUT /api/v4/projects/306/merge_requests/**None/**merge HTTP/1.1" 404 27

the  str None suprised me,why merge request id is None,

## Actual Behavior

then I write a new function to get merge request id,and everything is ok

## Specifications

  - python-gitlab version:2.10.1
  - API version you are using (v3/v4):v4
  - Gitlab server version (or gitlab.com):GitLab Community Edition 13.11.3

**Comment by nejch** [comment]
Hi @comk88, could you paste the exact/full snippet that you use (redact as necessary)?

We have functional tests where this works so I'd just like to understand
