### ISSUE TITLE
Access token support

### ISSUE THREAD

**Issue by Moezen** [python-gitlab/python-gitlab#163]
I use oauth2 to authorize gitlab and get the access token which use to call gitlab apis. But gitlab.Gitlab only support for email/password and private token.

**Comment by gpocentek** [comment]
Hi,

I pushed https://github.com/gpocentek/python-gitlab/tree/oauth with a possibly working oauth2 support. I don't have a server set up to properly test this. Could you give it a try?

Thank you!

**Comment by deanrock** [comment]
Hi,

I submitted a pull request #174 that correctly works with oauth2 tokens.

**Comment by boer0924** [comment]
@gpocentek  why the master branch not oauth2, why not merage oauth into master?

**Comment by gpocentek** [comment]
@boer0924 because last time I checked it didn't work. There are some PR to fix the branch but they need to be updated.

This is not a priority for me at the moment, but I'd be happy to review patches.

Thanks!

**Comment by boer0924** [comment]
@gpocentek  thanks replay!

Yestoday, when I clone the oauth branch and use it, It's not work, error 401.

My gitlab version 9.4.2, help me!
