### ISSUE TITLE
Duplicate Projects - it appears that some projects have multiple group ownership

### ISSUE THREAD

**Issue by LiamInJapan** [python-gitlab/python-gitlab#1644]
## Description of the problem, including code/CLI snippet

It is hard to tell at this point if this is a python-gitlab issue or an upstream gitlab API issue, but I am reporting it here and there too: https://gitlab.com/gitlab-org/gitlab/-/issues/343071

For the following code:

```

def getAllProjectsForGroup(group_name):
    groups = gl.groups.list(search=group_name)
	
    for group in groups:
        print(group)
        
    return gl.groups.get(group_id).projects.list()

```

I appear to get duplicate projects, as in, the API believes the project has multiple group ownership.
However, I see nothing in the gitlab interface that shows this multiple ownership.

It should probably be pointed out that:
- The projects that are experiencing this have all recently had a change in group ownership, executed via the gitlab web UI
- Gitlab does offer multiple group ownership as paid functionality. However we use a free account

My suspicion is that it is a gitlab.com issue with the transfer of ownership functionality... But I thought it best to report it here too as it's hard to tell at this point.

## Expected Behavior

These projects belong to one group only

## Actual Behavior

These projects belong to multiple groups for some reason
## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
Questions in the code-snippet.

> ```
> 
> def getAllProjectsForGroup(group_name):
>     groups = gl.groups.list(search=group_name)
> 	
>     for group in groups:
>         print(group)
>  # Is this just for debugging? 
>         
>     return gl.groups.get(group_id).projects.list()
> # Where does group_id come from?
> ```
