### ISSUE TITLE
Unable to get the the image size from the container registry

### ISSUE THREAD

**Issue by adeptg** [python-gitlab/python-gitlab#1657]
## Description of the problem, including code/CLI snippet
gitlab project-registry-tag get --project-id 207 --repository-id 66 --name 7.6.5

It returns only the name of the tag

## Expected Behavior

It would be good to have the tag size and upload time

## Actual Behavior

It returns only the name of the tag

## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.1.3

**Comment by JohnVillalovos** [comment]
Looking at `gitlab --help` makes me think you might want to check-out the `--fields` option and `--output` option.

Not sure though.

**Comment by nejch** [comment]
Exactly, as @JohnVillalovos says you just need a more verbose output. This will give you all the fields for example:
```shell
gitlab -v project-registry-tag get --project-id 207 --repository-id 66 --name 7.6.5
```

I'll close this as I just tried it and it works, but feel free to reopen if you have issues.

**Comment by adeptg** [comment]
Yes, you all are right - it works. Sorry for the false alert.
The root cause why I didn't get it - I've got a weird gitlab bug about 0 bytes images:

gitlab project-registry-tag list --project-id 207 --repository-id 161 --all |grep 6.8.5.168245.feature
name: 6.8.5.168245.feature

gitlab project-registry-tag get --project-id 207 --repository-id 161 --name 6.8.5.168245.feature
Impossible to get object (404: 404 Tag Not Found)

But it's something with the gitlab itself, python-gitlab works like a charm.
Thanks!
