### ISSUE TITLE
Use another augmented assignment statement

### ISSUE THREAD

**Issue by elfring** [python-gitlab/python-gitlab#1658]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/gitlab/v4/cli.py b/gitlab/v4/cli.py
index 6986552..769d3a7 100644
--- a/gitlab/v4/cli.py
+++ b/gitlab/v4/cli.py
@@ -53,7 +53,7 @@ class GitlabCLI(object):
         # the class _path attribute, and replace the value with the result.
         if TYPE_CHECKING:
             assert self.mgr_cls._path is not None
-        self.mgr_cls._path = self.mgr_cls._path % self.args
+        self.mgr_cls._path %= self.args
         self.mgr = self.mgr_cls(gl)
 
         if self.mgr_cls._types:
```

**Comment by JohnVillalovos** [comment]
I don't see any benefit to this. Would need more information on why this is a benefit.

Personally I find it harder to read and goes against how I have learned to read the `%` operator.

**Comment by elfring** [comment]
Can you accept [the explanation from the Python documentation](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements")?

“…
In the augmented version, `x` is only evaluated once. Also, when possible, the actual operation is performed _in-place_, meaning that rather than creating a new object and assigning that to the target, the old object is modified instead.
…”

:thought_balloon: Do you accordingly expect positive effects for the software run time characteristics?

**Comment by JohnVillalovos** [comment]
No that doesn't give me good reason to make changes. Please provide a better reason how it improves things for the python-gitlab project. I am failing to see a benefit.

**Comment by elfring** [comment]
:thought_balloon: Will the chances grow for another application of [functionality which became generally available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")?

**Comment by JohnVillalovos** [comment]
At this time no desire or plan to implement this. Closing.

**Comment by nejch** [comment]
@elfring we'll be replacing the old % operator for string formatting with python3 string formatting and f-strings in the near future, so this likely isn't worth it at this point as John mentioned.
