### ISSUE TITLE
Changing Gitlab User Password

### ISSUE THREAD

**Issue by zeynepkoyun** [python-gitlab/python-gitlab#1663]
Hi @nejch 

When I change the password of the non-root user in Gitlab, it asks for password confirmation again when I log in again. How can I get past this situation?

**Comment by JohnVillalovos** [comment]
I don't believe there is any way to resolve this as Gitlab docs says this is the way it is:

https://docs.gitlab.com/ee/api/users.html#user-modification

At the bottom of the API docs for "User Modification" it states: On password update, the user is forced to change it upon next login.

**Comment by JohnVillalovos** [comment]
Feel free to re-open if think there is a `python-gitlab` issue.

**Comment by zeynepkoyun** [comment]
Hi @JohnVillalovos 
There is no such confirmation when I change the root user's password.
I also want to do it without approval for normal users.
I would be glad if you can help with this.

**Comment by JohnVillalovos** [comment]
Sorry. You can file an issue with Gitlab about it. There is nothing I (or python-gitlab) can do about it because it is a Gitlab issue.
