### ISSUE TITLE
incremental package

### ISSUE THREAD

**Issue by snails-za** [python-gitlab/python-gitlab#1664]
Hello, how do I get the incremental package? Thank you so much

**Comment by JohnVillalovos** [comment]
I don't understand. Please provide more details.

**Comment by nejch** [comment]
Do you just need the latest development version? You can follow the instructions at https://python-gitlab.readthedocs.io/en/latest/install.html for installs from the git repo.

**Comment by snails-za** [comment]
Thank you everyone~ I have solved it! You can directly take the update incremental package with two commit ids! Thanks again!

**Comment by nejch** [comment]
Thanks @snails-za I still don't quite understand your question but I guess you were looking for the `repository_compare` functionality :) I'll close this if you've managed to solve it.
