### ISSUE TITLE
Group and Project audit_events list results in "AttributeError: audit_events"

### ISSUE THREAD

**Issue by geekusa** [python-gitlab/python-gitlab#1690]
## Description of the problem, including code/CLI snippet
Trying to use audit_events.list() for both group and project, whenever this is done it results in an AttributeError like so:
```
group.audit_events.list()
Traceback (most recent call last):
  File "gitlab/base.py", line 59, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'audit_events'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gitlab/base.py", line 62, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'audit_events'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gitlab/base.py", line 82, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'audit_events'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "gitlab/base.py", line 84, in __getattr__
    raise AttributeError(name)
AttributeError: audit_events
```
Also noticed that doing a dir() of either the group or project object that `audit_events` is not listed and I can confirm the URLs result in events using curl. 

## Expected Behavior
return a list of audit events for group or project

## Actual Behavior
returns an error AttributeError: audit_events

## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
Where did `group` come from?

**Comment by geekusa** [comment]
sorry about that, here you go:
```
import gitlab

global_base_url = "https://gitlab.com"
api_param = ...redacted
group_id = ...redacted
gl = gitlab.Gitlab(global_base_url, private_token=api_param)
group = gl.groups.get(group_id)
group.audit_events.list()
```

**Comment by JohnVillalovos** [comment]
I am unable to reproduce this. I don't have any events but I don't get a traceback.

I am assuming the code you posted is how you are doing it. That you are not using `gl.groups.list()` which could cause an issue.

**Comment by geekusa** [comment]
Interesting that it doesn't error for you, does `dir(group)` have `audit_events` show up? Yes the code posted is how I am doing it and getting the error.

**Comment by geekusa** [comment]
Crud, sorry I just realized that my import of gitlab was being overwritten from a local import so I was getting an older version that I expected. Thanks for your help though!

**Comment by JohnVillalovos** [comment]
Hehe. I was just going to ask you to do:

```
print("gitlab version:", gitlab.__version__)
print("gitlab file:", gitlab.__file__)
print("type:", type(group))
print("dir:", pprint.pformat(dir(group)))
```
