### ISSUE TITLE
Tests need to be implemented for tests/unit/test_projects.py

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#1708]
Currently we have a lot of unimplemented tests in tests/unit/test_projects.py.

Adding these tests would be a good first issue for someone to work on.

Comment below if you would like to work on this issue.

**Comment by vishalpandeyvip** [comment]
I would like to work on this @JohnVillalovos .

**Comment by nejch** [comment]
That's amazing @vishalpandeyvip. I've assigned this to you for now, feel free to reach out if you have any issues/questions.

As we add new resources, we sometimes split modules to keep them a sane size, so it's possible some of those tests will eventually belong in a separate module, but up to you.

**Comment by vishalpandeyvip** [comment]
Thanks for assigning this to me @nejch . I am new to the project so once going through documentation and codebase. I will try to create a PR very soon.

**Comment by rnoberger** [comment]
Hello, I tried to implement some tests for the easy list functions in projects. Can you take a quick look into and give me some feedback? I pushed it to a forked Repository: [rnoberger/python-gitlab](https://github.com/rnoberger/python-gitlab/commit/0ba035b661c7b4c1ad1ee835452f87f5b44fd338)

The fixtures are getting quickly big. Do you prefere to use the `assert_all_requests_are_fired=False` flag?

**Comment by nejch** [comment]
That looks good @rnoberger, thanks for taking a look at this! It's best to open a draft pull request so we can discuss it there :)

It looks mature enough for a PR already IMO. I think we can reduce the size of fixtures by using `lazy=True` in the initial project get() call (or even using a project fixture, I'll give you a suggestion), so we only need to mock the final request.

@vishalpandeyvip are you still interested in covering some of the other missing tests or should I unassign you from here?

**Comment by rnoberger** [comment]
I opened a [PR](https://github.com/python-gitlab/python-gitlab/pull/2012). Would be nice if you @nejch could make the suggestion how to stomp the fixtures.

**Comment by nejch** [comment]
Unassigning this as we had some initial contributions already but this issue still could use quite a bit of help for any readers here :)

If you're new and reading this, feel free to get in touch or open a PR, you can take a look at https://github.com/python-gitlab/python-gitlab/pull/2012 for an example.

**Comment by nejch** [comment]
That's awesome @antoineauger, thanks! Maybe one day we get to that magical 100% then :grin:
