### ISSUE TITLE
Self-test failures on Fedora 35 (python 3.10)

### ISSUE THREAD

**Issue by jarodwilson** [python-gitlab/python-gitlab#1713]
## Description of the problem, including code/CLI snippet

rpmbuild of a python-gitlab package on Fedora 35 (python 3.10) fails, with the following:

```
+ /usr/bin/pytest gitlab
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.10.0, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/jwilson/rpmbuild/BUILD/python-gitlab-2.9.0, configfile: tox.ini
collected 0 items

============================================================================ warnings summary =============================================================================
../../../../../usr/lib/python3.10/site-packages/_pytest/config/__init__.py:1233
  /usr/lib/python3.10/site-packages/_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: script_launch_mode

    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================================================================== 1 warning in 0.02s ============================================================================
error: Bad exit status from /var/tmp/rpm-tmp.0OnLs0 (%check)

```
Saw this initially trying to build a 2.10.1 package, but the same happens with a 2.9.0 package that built fine on Fedora 34 (python 3.9).

## Specifications

  - python-gitlab version: 2.9 through 2.10.1, and maybe earlier
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
Thanks for the bug report. I have proposed a fix for this. As a note we aren't planning our next release (3.0.0) until after Python 3.6 is officially EoL (sometime in December 2021).

I'm not sure if we have a **stable** branch concept to release an update just to 2.10.1.
