### ISSUE TITLE
Need help to figure out if artifacts() is working right or not...

### ISSUE THREAD

**Issue by BuhtigithuB** [python-gitlab/python-gitlab#1724]
## Description of the problem, including code/CLI snippet

My question concern the artifacts() here :
https://github.com/python-gitlab/python-gitlab/blob/64f2360aecb082baac09cac716f88bd8cc6b443b/gitlab/v4/objects/projects.py#L548

Here how I use it:

```python
def unzip_artifacts(path):
    with zipfile.ZipFile(path, 'r') as zip_obj:
        zip_obj.extractall()
    return

artifact_file = 'artifacts.zip'
with open(artifact_file, 'wb') as release_package:
    build_or_job.artifacts(streamed=True, action=release_package.write)
# unzip_artifacts(path=artifact_file)
```

## Expected Behavior

./artifacts.zip (uncompress eventually)

## Actual Behavior

./artifacts.zip **(containing artifacts.zip)**

## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.1.5-ee

**Comment by BuhtigithuB** [comment]
There is also "artifact()"... 

This way it works fine:

```python
    with open(artifact_file, 'wb') as release_package:
        build_or_job.artifact(path='artifacts.zip', streamed=True, action=release_package.write)
    unzip_artifacts(path=artifact_file)
```

Thanks

**Comment by JohnVillalovos** [comment]
Related: https://python-gitlab.readthedocs.io/en/stable/gl_objects/pipelines_and_jobs.html#streaming-example

**Comment by BuhtigithuB** [comment]
Yep, my eyes were not seeing the "s"...

:D
