### ISSUE TITLE
Add fetching LFS files

### ISSUE THREAD

**Issue by olimjon-ibragimov** [python-gitlab/python-gitlab#1745]
## Description of the problem, including code/CLI snippet
When LFS is enabled in the project and a certain file is tracked as LFS file, fetching that file returns only the pointer file.

```
gl = gitlab.Gitlab('https://gitlab.com', private_token=access_token, api_version='4')
gl.auth()
project = gl.projects.get('path/to/your/github/repo')
fetched_file = project.files.raw('path/to/a/file/in/that/repo', ref='branch_name')
f = open('path/to/output/file', "wb")
f.write(fetched_file)
f.close()
```

## Expected Behavior
Returned file is an actual file not a pointer.

## Actual Behavior
Returned file is a pointer and contains file metadata:
```
version https://git-lfs.github.com/spec/v1
oid sha256:8dd88201cfc911bddd5d3b12066054d7e76215e26965159cac553492789db2ca
size 1456
```

## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): 4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
Hi @olimjon-ibragimov, sadly there is nothing python-gitlab can do here as the GitLab API does not support it.

But you can follow and upvote the upstream issue for updates: https://gitlab.com/gitlab-org/gitlab/-/issues/27892
Once that's implemented in GitLab we can have it here as well.

**Comment by nejch** [comment]
I'll close this for now as it's probably best to just use git for this at the moment, similar to nr.2 in https://python-gitlab.readthedocs.io/en/stable/faq.html. Feel free to reopen this though!

**Comment by nejch** [comment]
@olimjon-ibragimov just FYI this is now supported upstream with the `lfs` parameter, so python-gitlab should automatically get you the right content if you pass it to the API.

**Comment by olimjon-ibragimov** [comment]
@nejch thank you for the heads up! I will give it a try.
