### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by gthieleb** [python-gitlab/python-gitlab#1748]
Regarding the example from the examples page:

```
repository.tags.delete_in_bulk(older_than="1m")
```

The example implies that image tags older then 1 month are deleted.
When running this example in a test environment it deletes all image tags. 

An information should visible for the enduser that points out the impact of this method or the example should be removed.

------
In page: gl_objects/repository_tags.rst

**Comment by JohnVillalovos** [comment]
My guess is that GitLab interprets `1m` as "one minute". If you want one month then have to use `1month`

https://docs.gitlab.com/ee/api/container_registry.html#delete-registry-repository-tags-in-bulk

**Comment by nejch** [comment]
If the parsing is the same as expire_in and time tracking, that seems right.
https://docs.gitlab.com/ee/user/project/time_tracking.html#configuration

I don't think we should be duplicating all of GitLab's documentation though. The values are the same from python-gitlab or curl.

**Comment by gthieleb** [comment]
Ok, thanks for clarifying the unit and for the link to the units. This is really hard to find. If its not part of the documentation yet we should add this link there.

**Comment by JohnVillalovos** [comment]
There should be a link to the GitLab documentation at the top of every API page.

There is for: https://python-gitlab.readthedocs.io/en/stable/gl_objects/repository_tags.html

To use python-gitlab users should read both the python-gitlab documentation but also GitLab's API documentation. I agree with @nejch in that it is not realistic for us to re-document the API in python-gitlab and attempt to keep it in sync.

But if you have a suggestion for a documentation improvement please consider submitting a pull-request.

**Comment by nejch** [comment]
I agree. We provide examples of using the API but for the actual _values_ of parameters passed to the API, it is in GitLab's API docs as that can change upstream without affecting `python-gitlab`, which is just a wrapper for making the API calls.

@gthieleb IMO the best place to clarify would be to open an MR upstream to more explicitly list what human-readable formats are allowed in https://docs.gitlab.com/ee/api/container_registry.html#delete-registry-repository-tags-in-bulk. This is linked at the top of the page from our registry tags docs already. So I'll close this for now but please re-open if you disagree! :)
