### ISSUE TITLE
`retry_transient_errors` does not work since 2.7.0

### ISSUE THREAD

**Issue by carlfriedrich** [python-gitlab/python-gitlab#1749]
## Description of the problem, including code/CLI snippet

I just updated from python-gitlab 2.5.0 to 2.10.1 and noticed that `retry_transient_errors` does not work anymore. The parameter ist just silently ignored. I checked all the versions in between and found out that the change was introduced in 2.7.0.

Reproducible example:

```python
#!/usr/bin/env python3
from gitlab import Gitlab

gitlab = Gitlab("https://gitlab.com")
gitlab.enable_debug()

p = gitlab.projects.get(id=278964, retry_transient_errors=True)
```

## Expected Behavior

This was the request with python-gitlab 2.6.0:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.com:443
send: b'GET /api/v4/projects/278964?retry_transient_errors=True HTTP/1.1\r\nHost: gitlab.com\r\nUser-Agent: python-gitlab/2.6.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-type: application/json\r\n\r\n'
```

## Actual Behavior

This happens in python-gitlab >= 2.7.0:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.com:443
send: b'GET /api/v4/projects/278964 HTTP/1.1\r\nHost: gitlab.com\r\nUser-Agent: python-gitlab/2.10.1\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-type: application/json\r\n\r\n'
```

The `retry_transient_errors` argument is missing in the actual HTTP request.

## Specifications

  - python-gitlab version: 2.7.0 - 2.10.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
@carlfriedrich thanks for the report. `retry_on_transient_errors` is not something that should be sent as a parameter to the API, it's an internal python-gitlab parameter for retrying HTTP requests. So the behavior starting from 2.7.0 is actually correct and the behavior before was erroneously sending extra args to the server.

See https://github.com/python-gitlab/python-gitlab/commit/b9ecc9a8c5d958bd7247946c4e8d29c18163c578 and its associated pull request for more details.

So I'm going to close this but if you disagree and you see that the argument actually doesn't work (e.g. failures are not retried), feel free to reopen. We have tests to prove it so this _should_ work already, but we can investigate if needed. :)

**Comment by carlfriedrich** [comment]
@nejch Ah, I see, thanks for the quick clarification. I updated the issue title accordingly, because I indeed did not verify whether it does not actually work, but I just stumbled upon the changed request by accident and simply assumed that this would be an error.

So if I got this right, I would leave my code as it is (including the `retry_on_transient_errors=True` arguments on my calls) and the retrying should still work because it is handled by `python-gitlab` internally?

**Comment by nejch** [comment]
@carlfriedrich exactly.

In fact I/we should probably check at some point if there are still any arguments that might be getting sent to the API but shouldn't..

**Comment by carlfriedrich** [comment]
@nejch Alright, thanks a lot!

**Comment by twil69** [comment]
The documentation still lists this argument in the **Transient errors** section. If it is really no longer supported, please do remove it from there as well to avoid confusion.

 But honestly, I think this is a step backwards. Being able to set this on the connection is very convenient. The alternative is that the user has to implement retry functionality, wrap each API call in its own helper function that can then be decorated with the retry wrapper.

**Comment by nejch** [comment]
@twil69 I think you might have understood this issue. It has not been removed from the library, it is _consumed_ by the library instead of getting sent to the server API, which has no effect as it is not a valid parameter in any of the server endpoints (you can confirm that by searching for it in the upstream API docs).

Previously, it was erroneously passed on to the server as well. But it was never meant to do that, it was just a bug with little to no side effect.

So the documentation should still be accurate. But let us know if you find any issues.

**Comment by twil69** [comment]
You are right. I was on an older version in a venv, inspected the source code, did not find the parameter, googled for it, landed in this issue and there you go.... 
All good now, sorry for the noise :)
