### ISSUE TITLE
Bug in project.files.create docs ?

### ISSUE THREAD

**Issue by gitshashwat** [python-gitlab/python-gitlab#1751]
## Description of the problem, including code/CLI snippet

On going through the docs, I found this for creating a text file in a branch in a gitlab project

```
f = project.files.create({'file_path': 'testfile.txt',
                          'branch': 'master',
                          'content': file_content,
                          'author_email': 'test@example.com',
                          'author_name': 'yourname',
                          'encoding': 'text',
                          'commit_message': 'Create testfile'})
```

## Expected Behavior
The expected behaviour should have been creation of the file
`<class 'gitlab.v4.objects.files.ProjectFile'> => {'file_path': 'testfile.txt'', 'branch': 'master'}
`
## Actual Behavior
`GitlabCreateError: 400: encoding does not have a valid value`

However, on removing encoding: 'text', the execution is alright. Would you like me to edit the doc?/Can you let me know the use-case of the encoding parameter?

## Specifications

 - python: 3.8
  - python-gitlab version: stable

**Comment by JohnVillalovos** [comment]
Thanks. Yes a PR would be great to fix the docs.

See the upstream docs on what `encoding` can be: https://docs.gitlab.com/ee/api/repository_files.html#create-new-file-in-repository

Sounds like the default is `text` but they don't let you use `text` 😕

**Comment by gitshashwat** [comment]
@JohnVillalovos True. It's mentioned as default is `text` which means you don't have to specify that parameter itself when you are creating a text file.

The example given in the upstream doc does not specify encoding in the curl request. They have also mentioned 
**required=no** for encoding in these docs.

```
curl --request POST --header 'PRIVATE-TOKEN: <your_access_token>' \
     --header "Content-Type: application/json" \
     --data '{"branch": "master", "author_email": "author@example.com", "author_name": "Firstname Lastname",
               "content": "some content", "commit_message": "create a new file"}' \
     "https://gitlab.example.com/api/v4/projects/13083/repository/files/app%2Fproject%2Erb"
     
```

No worries, I'll create a PR to fix this.
