### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by hailianghe** [python-gitlab/python-gitlab#1777]
Hello. the content  below looks  error.
![image](https://user-images.githubusercontent.com/29939806/147384879-a46a23f2-e269-48df-b880-b9fb4c1c90e8.png)
note_id = discussion.attributes['note'][-1]['id'] shoud be 
note_id = discussion.attributes['notes'][-1]['id']
------
In page: gl_objects/discussions.rst

**Comment by JohnVillalovos** [comment]
Thanks. Would you like to propose a PR with a suggested fix?
