### ISSUE TITLE
Wrong return type annotation in ProjectCommit.refs()

### ISSUE THREAD

**Issue by robertschweizer** [python-gitlab/python-gitlab#1805]
## Description of the problem, including code/CLI snippet

`ProjectCommit.refs()` returns `List[Dict[str, Any]]`, but the type annotations say it returns `Union[Dict[str, Any], requests.Response]`.

## Specifications

  - python-gitlab version: 3.0.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  -

**Comment by nejch** [comment]
Thanks for the report @robertschweizer. Looking at the endpoint, the method currently used is wrong anyway, because we might get a paginated response so we should be doing an `http_list()` instead. So we should revamp this a little.

**Comment by nejch** [comment]
We probably also have the same issue with `ProjectCommit.diff()` and `ProjectCommit.merge_requests()` at least for typing, and not sure about pagination yet as it is not documented upstream.

**Comment by JohnVillalovos** [comment]
Ah. I had assumed every API call returned a `Dict[str, Any]`. Okay will need to change things to handle this. Thanks for the report!
