### ISSUE TITLE
Edit pipeline settings

### ISSUE THREAD

**Issue by sscherfke** [python-gitlab/python-gitlab#182]
It would be cool if we could edit a project's pipeline settings, e.g. to bulk-set the *Test coverage parsing* Regex.

**Comment by sscherfke** [comment]
It looks like the GitLab API does not expose this functionality.  I create [an issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/24362) for this.

**Comment by gpocentek** [comment]
Thanks for the report! I use the upstream label to indicate we need to wait for GitLab changes.

**Comment by gpocentek** [comment]
I'm closing this for now as there is no indication that GitLab is working on implementing this feature. We can reopen when things get moving upstream.
