### ISSUE TITLE
Feature request: List environments for a project using search

### ISSUE THREAD

**Issue by isuftin** [python-gitlab/python-gitlab#1826]
## Description of the problem, including code/CLI snippet

Add ability to search project environments by name

## Expected Behavior

Get an environment list by adding the search field to the url via a flag that currently does not exist:

https://docs.gitlab.com/ee/api/environments.html#list-environments

## Actual Behavior

There is no way to provide a search field to the environment list command

## Specifications

  - python-gitlab version: 3.0.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.6.0

**Comment by nejch** [comment]
@isuftin you are using the CLI, I assume? It works with the API, we just need to add the list attributes to the CLI.

```python
>>> gl = gitlab.Gitlab(private_token=os.getenv("GITLAB_PRIVATE_TOKEN"))
>>> project = gl.projects.get("gitlab-org/gitlab")
>>> project.environments.list(search="review")
[<ProjectEnvironment id:312841>, <ProjectEnvironment id:7098283>, <ProjectEnvironment id:7863072>, <ProjectEnvironment id:7890915>, <ProjectEnvironment id:7918465>, <ProjectEnvironment id:7963575>, <ProjectEnvironment id:8076124>, <ProjectEnvironment id:8107556>, <ProjectEnvironment id:8107588>, <ProjectEnvironment id:8124603>, <ProjectEnvironment id:8171128>, <ProjectEnvironment id:8192681>, <ProjectEnvironment id:8210178>, <ProjectEnvironment id:8224683>, <ProjectEnvironment id:8229127>, <ProjectEnvironment id:8229486>, <ProjectEnvironment id:8230939>, <ProjectEnvironment id:8232626>, <ProjectEnvironment id:8240806>, <ProjectEnvironment id:8243021>]
```

**Comment by isuftin** [comment]
@nejch  I'm glad that the python library does have the capability already, and yes what I'm looking for is the addition of the capability into the cli portion

**Comment by JohnVillalovos** [comment]
@isuftin If you are interested to create a PR

Example of `_list_filters`: https://github.com/python-gitlab/python-gitlab/blob/4a000b6c41f0a7ef6121c62a4c598edc20973799/gitlab/v4/objects/projects.py#L93-L109

Would need to be added around here: https://github.com/python-gitlab/python-gitlab/blob/4a000b6c41f0a7ef6121c62a4c598edc20973799/gitlab/v4/objects/environments.py#L50

Look at: https://docs.gitlab.com/ee/api/environments.html#list-environments

For what variables should be in the list filters.  Looks like `name`, `search`, and `states`
