### ISSUE TITLE
Group is not getting deleted

### ISSUE THREAD

**Issue by kartikeyangupta** [python-gitlab/python-gitlab#1849]
## Description of the problem, including code/CLI snippet
After running the code presented below, the expected behaviour is the group get deleted, instead None is returned and the group remains intact.
```
import gitlab
  
gl = gitlab.Gitlab('<Gitlab_hostname>', private_token=<Private_Token>)
group_name = 'just-for-testing'
group_id = gl.groups.list(search=group_name)[0].id
gl.groups.delete(id = group_id, sudo=<user_name>
```

## Expected Behavior
Group should be deleted. 

## Actual Behavior
Group is not deletd

## Specifications

  - python-gitlab version: 3.1.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.3.6-ee

**Comment by nejch** [comment]
Hi @kartikeyangupta are you on GitLab EE by any chance?

If so, the default behavior is to mark it for deletion and gets deleted in 7 days. See upstream docs:
https://docs.gitlab.com/ee/api/groups.html#remove-group

I don't see any flags in the docs to override this, so it seems like you might have no other options.

**Comment by nejch** [comment]
Ok, I just noticed you are on GitLab EE, sorry I missed that initially.

So basically this is the behavior of GitLab EE, nothing python-gitlab can do about it. You'll need to wait for 7 days. But please re-open if it's still unclear :)

**Comment by kartikeyangupta** [comment]
HI @nejch ,
I checked in our gitlab instance we have not set any delay in deletion of an entity.
This should trigger the deletion immediately, while using the same code I am able to delete a project immediately.
If EE is out of scope I can understand.

**Comment by nejch** [comment]
Hmm, I don't think that's the case. See:

> By default, a project marked for deletion is permanently removed with immediate effect. See delayed project deletion to learn more. By default, a group marked for deletion is permanently removed after seven days. 

https://docs.gitlab.com/ee/user/admin_area/settings/visibility_and_access_controls.html#default-deletion-delay

So if you have access to the admin panel, I think you need to set it explicitly to `0` for group-level deletion for it to have an effect.
