### ISSUE TITLE
Allow to access Releases API via CI_JOB_TOKEN

### ISSUE THREAD

**Issue by MRigal** [python-gitlab/python-gitlab#1850]
## Description of the problem, including code/CLI snippet

Thanks to #746 we have support for the releases.
Unfortunately we have to load a project to create a release, but getting a project (event its own project like #1393 reported it) is not possible with CI_JOB_TOKEN.

I have made a work-around for this, by creating a fake Project object, but it's not very nice. Maybe we could have a way to use the Releases API with CI_JOB_TOKEN:

```
# fails with CI_JOB_TOKEN
gitlab_project = client.projects.get(id=1)
# So this work as we aren't querying
gitlab_project = client._objects.Project(client.projects, attrs={"id": 1})
# To be able to do
release = gitlab_project.releases.create({"name": "Supa name"})
```

## Expected Behavior

Not sure... Maybe something like this?

```
release = client.releases.create({"project_id": 1, "name": "Supa name"})
```

## Actual Behavior

See description above

## Specifications

  - python-gitlab version: ALL until at least 3.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13/14.x

**Comment by MRigal** [comment]
Also please note that for server versions <14.5, many operations on the Releases API were not supported CI_JOB_TOKEN, despite the docs saying the opposite. See https://gitlab.com/gitlab-org/gitlab/-/merge_requests/72448 and notes at https://docs.gitlab.com/ee/api/releases/#list-releases

**Comment by max-wittig** [comment]
You can always use `lazy=True` to avoid actual server requests.

```python
gitlab_project = client.projects.get(id=1, lazy=True)
release = gitlab_project.releases.create({"name": "Supa name"})
```

It's also in the docs somewhere, if you search for `lazy`. Does that help you?

**Comment by nejch** [comment]
> Also please note that for server versions <14.5, many operations on the Releases API were not supported CI_JOB_TOKEN, despite the docs saying the opposite. See https://gitlab.com/gitlab-org/gitlab/-/merge_requests/72448 and notes at https://docs.gitlab.com/ee/api/releases/#list-releases

I'm not sure we exactly claim the opposite, it's just that we're not able to keep up with all the version compatibilities in our own docs and it makes more sense to link to upstream docs and people can check that as the single source of truth. You'd have the same issue with curl (assuming you use `lazy` here as shown above). Does that make sense?

If you'd like to add some clarification in the docs with a PR though, that would be awesome!

**Comment by MRigal** [comment]
Thanks guys for your fast and precise feedback! Sorry I had missed the 'lazy' attribute in the docs. 

I may try a small docs PR :-)
