### ISSUE TITLE
`has_conflicts` returning incorrect value

### ISSUE THREAD

**Issue by squidgegmc** [python-gitlab/python-gitlab#1851]
## Description of the problem, including code/CLI snippet
On creating an MR, the API returns False on `has_conflicts`.
MR has been created specifically to test this

Conflicts show in the GitLab web UI (self hosted)

![image](https://user-images.githubusercontent.com/23266123/150312129-ec07af09-090b-431d-addc-173c68c50c1e.png)

```python
print(getattr(mr, 'has_conflicts'))
print(mr.attributes)
```

## Expected Behavior
With conlicts clearly showing in GitLab UI, i would expect this to return `True`

## Actual Behavior
Returning False

## Specifications

  - python-gitlab version: 3.1.0 (py3.8) & 1.15.0 (py2.7)
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  13.11.3-ee (self hosted)

**Comment by max-wittig** [comment]
Did you try with `curl` and get a different result?. 

I don't think that this is the fault of python-gitlab, but rather of the GitLab API.

**Comment by squidgegmc** [comment]
@max-wittig 
Thank you for getting back.
I can confirm the curl call does return the correct value:

![image](https://user-images.githubusercontent.com/23266123/150319774-24b30dbe-8263-45a8-8e05-ab7c6a37bfe4.png)

**Comment by max-wittig** [comment]
Are you sure that this is not a timing issue. Can you try again with python-gitlab? It might take some time for `gitlab.com` to reflect the changes.

**Comment by squidgegmc** [comment]
ok, rerunning the python call once the MR is created I do get the correct return.
perhaps this is a timing issue.
I guess i will have to call back to the MR to check its status somehow

**Comment by max-wittig** [comment]
yeah maybe wait a bit or something.

**Comment by nejch** [comment]
I think it's also documented upstream that MR operations are async so seems normal to me :)

**Comment by JohnVillalovos** [comment]
As a note, you man want to check `merge_status` first. As `has_conflicts` is only set if `merge_status` == `cannot_be_merged` but in my usage I have for sure seen `merge_status` == `can_be_merged` but then after 10 seconds or so it gets switched to `cannot_be_merged`. So unfortunately in my code I have to do a `time.sleep(SOME_VALUE)` 😟 I see this after I call `mr.rebase()` so I now sleep for 5 seconds, then start iterating over the value of of `mr_status` until it no longer is either `unchecked` or `checking`. Before trying to figure out the status.

See the top of the docs which sort-of describes this.

https://docs.gitlab.com/ee/api/merge_requests.html
