### ISSUE TITLE
Hard deleting a user from gitlab

### ISSUE THREAD

**Issue by Balasundaram** [python-gitlab/python-gitlab#1853]
## Description of the problem, including code/CLI snippet
I am wondering if there is a way to have the hard delete user behavior in gitlab user deletion api.

## Specifications

  - python-gitlab version: latest
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  14.1.1-ee

**Comment by JohnVillalovos** [comment]
You can do it like this:

https://github.com/python-gitlab/python-gitlab/blob/ff4b1cc70910b5c45df96547815390736a550b54/tests/functional/conftest.py#L48
