### ISSUE TITLE
[Docs] Can't create masked project variable via cli

### ISSUE THREAD

**Issue by christophlehmann** [python-gitlab/python-gitlab#1883]
## Description of the problem, including code/CLI snippet

Hi, how to pass the value of `--masked` correctly?

```shell
gitlab -v -o json project-variable create --project-id my/project --key FOO --value BAR --masked
usage: gitlab project-variable create [-h] [--sudo SUDO] --project-id PROJECT_ID --key KEY --value VALUE [--protected PROTECTED] [--variable-type VARIABLE_TYPE] [--masked MASKED]
                                      [--environment-scope ENVIRONMENT_SCOPE]
gitlab project-variable create: error: argument --masked: expected one argument

gitlab -v -o json project-variable create --project-id my/project --key FOO --value BAR --masked 1
Impossible to create object (400: {'value': ['is invalid']})

gitlab -v -o json project-variable create --project-id my/project --key FOO --value BAR --masked true
Impossible to create object (400: {'value': ['is invalid']})

gitlab -v -o json project-variable create --project-id my/project --key FOO --value BAR --masked yes
Impossible to create object (400: {'value': ['is invalid']})

gitlab -v -o json project-variable create --project-id my/project --key FOO --value BAR --masked 'true'
...
```

## Expected Behavior

One of the above commands create a masked variable

## Actual Behavior

Variable is not created.

## Specifications

  - python-gitlab version: 3.1.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.7.1

**Comment by christophlehmann** [comment]
Btw. 🚀 Nice project 🚀

**Comment by nejch** [comment]
@christophlehmann thanks for the report, nice to see you're able to use the CLI despite its quirks :) In your case, you're likely just not meeting the requirements for masked variables:

https://docs.gitlab.com/ee/ci/variables/#mask-a-cicd-variable

It must be at least 8 characters and essentially only use character from base64 (it is all listed there).

I tried locally and can reproduce it when the variable does not meet GitLab's requirements but works with a proper value. So I'll close this for now but please reopen if you can't get it to wrok!

**Comment by nejch** [comment]
PS: I have to say that error message is a bit cryptic.. but that is the raw response we get from gitlab's API. To improve that, it would be best to open an upstream issue to have GitLab's error messages be a bit more descriptive, IMO. python-gitlab does not attempt to understand those error messages, it just passes them on to the user.

**Comment by christophlehmann** [comment]
Thanks for pointing me to the important part of the docs 👍 I just read https://docs.gitlab.com/ee/api/project_level_variables.html and tried to interpret it.
