### ISSUE TITLE
retry_transient_errors should retry 520's as well

### ISSUE THREAD

**Issue by Sineaggi** [python-gitlab/python-gitlab#1886]
## Description of the problem, including code/CLI snippet
Any gitlab call has a low chance to respond with a 520 that should be retryable

## Expected Behavior

It (optionally?) retries 520 and other exceptions from requests.exceptions just like the lower 50x error codes.

## Actual Behavior

It fails intermittently.

## Specifications

  - python-gitlab version: latest
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

## Notes

We currently have tenacity retry logic to retry our calls, but that means we have both this libraries retry logic as well as our own.

```
  File "/usr/local/lib/python3.9/site-packages/gitlab/exceptions.py", line 313, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabListError: 520: <!DOCTYPE html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
  <title>500 Error - GitLab</title>
  <style>cut</style>

</head>

<body>
  <h1>
    <img cut/><br />
  </h1>
  <div class="container">
    <div class="cf-error-details cf-error-520">
  <h1>Web server is returning an unknown error</h1>
  <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
  <ul>
    <li>Ray ID: cut</li>
    <li>Your IP address: cut</li>
    <li>Error reference number: 520</li>
    <li>Cloudflare Location: cut</li>
  </ul>
</div>


    <hr />
    <p>Please see our <a href="https://status.gitlab.com">status page</a> for more information.</p>
  </div>
</body>
</html>

```

**Comment by nejch** [comment]
Thanks @Sineaggi, this is a bit unofficial/specific to cloudflare but since it powers gitlab.com I guess it makes sense. Maybe we can collect a few more cloudlfare status codes then that should be retried? Have you experienced any others?

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Unofficial_codes

**Comment by Sineaggi** [comment]
@nejch Many other codes, I'll gather a list of what failures we see the most.

**Comment by nejch** [comment]
I guess for cloudflare any of  `520 <= status_code <= 530` would actually apply. :thinking:

**Comment by Sineaggi** [comment]
A few notes we've taken over the past few weeks, I'll try to collect full stacktraces for these to verify where they're coming from.

Another cloudflare exception.
```
gitlab.exceptions.GitlabGetError: 524
```
Also saw this one in our logs.
```
ConnectionResetError: [Errno 104] Connection reset by peer
```

Another one from requests
```
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by nejch** [comment]
Done with https://github.com/python-gitlab/python-gitlab/pull/1904.

**Comment by AndrianStoikov** [comment]
Hi @nejch,

When is this fix planned for release?

**Comment by max-wittig** [comment]
@AndrianStoikov We release every month automatically on the 28th.

**Comment by AndrianStoikov** [comment]
@max-wittig Thanks for the fast reply.
