### ISSUE TITLE
Set specific Merge Requests to draft/mark as ready via API not possible

### ISSUE THREAD

**Issue by SteveJos** [python-gitlab/python-gitlab#1893]
## Description of the problem, including code/CLI snippet
While trying to set a specific MR to "mark as ready" or draft state via the API, I did not found neither a corresponding call function nor it was possible to update the MR with the mergerequest manager.

## Expected Behavior
1. either call a function (not existing now): mr.draft() / mr.ready() 
2. update key in MR dict(also not supported): 
        `update_data = mr.manager.update(mr.get_id(), {'draft': True})`
         `mr._update_attrs(update_data)`

## Actual Behavior
```
mr.draft = False
mr.save()
```
output:
`gitlab.exceptions.GitlabHttpError: 400: assignee_id, assignee_ids, reviewer_ids, description, labels, add_labels, remove_labels, milestone_id, remove_source_branch, allow_collaboration, allow_maintainer_to_push, squash, target_branch, title, state_event, discussion_locked are missing, at least one parameter must be provided`

## Specifications

  - python-gitlab version: '3.1.0'
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com): Gitlab Enterprise Premium

**Comment by JohnVillalovos** [comment]
I agree with @nejch  See: https://docs.gitlab.com/ee/api/merge_requests.htm they don't offer a way to switch the draft status from what I see.

**Comment by SteveJos** [comment]
Thank you for the quick response @nejch! I can confirm that there is no specific function or API call in order to change the draft state. The only possible solution is to change the title of the MR either with or without the prefix 'Draft: '. This changes the corresponding state of the MR. 
Way too easy xD
