### ISSUE TITLE
 'NoneType' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by nise** [python-gitlab/python-gitlab#1903]
## Description of the problem, including code/CLI snippet
```
import gitlab
URL = ''https://gitlab.somewhere.de' # a valid URL of a GitLab
gl = gitlab.Gitlab(url, private_token=args.private_token)
```

## Expected Behavior
Initiate object for further processing.

## Actual Behavior
$gitlab/__init__.py", line 88, in __init__
    self._base_url = url.rstrip("/")
AttributeError: 'NoneType' object has no attribute 'rstrip'

## Specifications

  - python-gitlab version: 3.9
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Community Edition [13.12.15]

**Comment by JohnVillalovos** [comment]
The code-snippet looks wrong in multiple ways.

Two single-quotes in a row. `URL` vs `url`

Can you update the snippet so we can test it?

**Comment by nise** [comment]
I fixed it. The problem was not related to the python-gitlab code.
