### ISSUE TITLE
Why does project-service require id on the CLI?

### ISSUE THREAD

**Issue by jurgenhaas** [python-gitlab/python-gitlab#191]
Using `gitlab project-service get --project-id 111 --service-name=slack` returns with an error that `--id` is a required parameter but when using that parameter with the correct ID, GitLab responds with a 404.

When using the library and calling `g.project_services.get(service_name='slack', project_id=project.id)` there is no id required and we get the correct result. Any ideas why?

**Comment by gpocentek** [comment]
ProjectService is a bit special and should probably be handled differently in the CLI code. I'll look into it.

Thanks for the report.
