### ISSUE TITLE
How to make project.deploytokens.list() return active tokens only?

### ISSUE THREAD

**Issue by zx1986** [python-gitlab/python-gitlab#1943]
## Description of the problem, including code/CLI snippet

Using `project.deploytokens.list()` always return all tokens, 
I had search and read the docs, got nothing :-(   

- https://python-gitlab.readthedocs.io/en/stable/gl_objects/deploy_tokens.html
- https://github.com/python-gitlab/python-gitlab/blob/main/tests/unit/objects/test_deploy_tokens.py

According to https://docs.gitlab.com/ee/api/deploy_tokens.html#list-all-deploy-tokens ,   
it seems could pass an argument `active` to the API call, I had try those but not work:

```
project.deploytokens.list(active=1)
project.deploytokens.list(attrs={"active": 1})
project.deploytokens.list(attrs: {"active": 1})
project.deploytokens.list({"active": 1})
```

## Expected Behavior

Pass `active` argument, and return active deploy tokens only.

## Actual Behavior

Return all deploy tokens (do not know how to pass the `active` argument).

## Specifications

  - python-gitlab version: latest
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.9.1 

Any ideas or clues or searching keywords?

**Comment by nejch** [comment]
@zx1986 have you tried `project.deploytokens.list(active=True)` or simply `project.deploytokens.list(active="true")`? REST APIs generally don't take 0/1 for booleans.

**Comment by zx1986** [comment]
My colleague had tried `curl` with Gitlab API v4, it return the same result:

```
curl --header "PRIVATE-TOKEN: secret" "https://our.gitlab.server/api/v4/projects/424/deploy_tokens?active=true"
```

**Comment by nejch** [comment]
@zx1986 just to clarify, you're saying the curl call works, but the python-gitlab code does not work (with active=true) ?
