### ISSUE TITLE
Stop download early when streaming

### ISSUE THREAD

**Issue by rossburton** [python-gitlab/python-gitlab#1944]
I've a tool which analyses the build log for every job in a pipeline.  The line I need to extract is in the first few of lines of output, but it's perfectly possible for the full log to be tens of megabytes long.

Is it/would it be possible to add a way to 'cancel' a download in the streaming action so I don't need to download the entire log once the section I'm after has been found?

**Comment by nejch** [comment]
Hey @rossburton sorry for the late response. I think this should now be possible by passing `iterator=True` to the method thanks to @TCatshoek's contribution, giving you direct access to the iterator and you can loop over the chunks manually. I haven't tried this myself but please let us know ;)

Look for `iterator=True` in the docs:
https://python-gitlab.readthedocs.io/en/stable/gl_objects/pipelines_and_jobs.html

I'll close this for now but please reopen if it doesn't work as expected!
