### ISSUE TITLE
Project Access Token : How to use it, any example code ?

### ISSUE THREAD

**Issue by nyue** [python-gitlab/python-gitlab#1966]
I wish to perform operation on a repo that has a project access token.

Any example python code on how to create the Gitlab() object using a project access token?

Cheers

**Comment by nejch** [comment]
@nyue you can use a project access token just like any personal access token, it's just limited to that specific project.

But this is really a question for GitLab and not this library - the library is not aware of whether you are giving it a personal or project access token. The server will either let you perform calls or not.

See https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html.
