### ISSUE TITLE
Get existence of a namespace

### ISSUE THREAD

**Issue by AliMirlou** [python-gitlab/python-gitlab#1972]
## Description of the problem, including code/CLI snippet

This is a feature request.

There is an endpoint in the Gitlab API for checking the existence of a namespace but it's not implemented in the Python client.
I know that I can check the existence by using the `get` method of namespace manager but it would be more efficient to have a `exists` method as well.

## Specifications

  - python-gitlab version: 3.2.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.7.0

**Comment by nejch** [comment]
@max-wittig it seems there is a GET endpoint for this now in the upstream API, I wasn't aware of it either but I think this is what they're referring to:
https://docs.gitlab.com/ee/api/namespaces.html#get-existence-of-a-namespace

**Comment by max-wittig** [comment]
Ahh nice. Sorry, then it's fine.
