### ISSUE TITLE
Warn user when detecting misconfigured server `external_url`?

### ISSUE THREAD

**Issue by nejch** [python-gitlab/python-gitlab#1978]
As seen in https://github.com/python-gitlab/python-gitlab/issues/1977, https://github.com/python-gitlab/python-gitlab/issues/1934 and older issues, paginated `list()` calls will fail when the server's external URL is not configured properly because we trust the `links` headers returned by the GitLab server:

https://github.com/python-gitlab/python-gitlab/blob/d27cc6a1219143f78aad7e063672c7442e15672e/gitlab/client.py#L1060

Maybe we should warn (or fail explicitly) if we detect the base url differs from the URL advertised back by the server?

(Just to avoid new issues popping up every now and then)

**Comment by JohnVillalovos** [comment]
Sounds like a good idea. Maybe create an FAQ item to point to.

**Comment by nejch** [comment]
User error in URL config could also potentially be detected by this, which is what seems to have happened in https://github.com/python-gitlab/python-gitlab/issues/2130 where a gitlab instance is served in a subdirectory on the domain.
