### ISSUE TITLE
mr commit not found on source project

### ISSUE THREAD

**Issue by cosven** [python-gitlab/python-gitlab#198]
ipython repl input and ouput.

```python
In [41]: mr = p.mergerequests.list()[1]

In [42]: commit = mr.commits()[0]

In [43]: commit.statuses.create({'status': 'success'})
GitlabCreateError                         Traceback (most recent call last)
...
...
GitlabCreateError: 404: 404 References for commit Not Found
```

##### background
I submit a merge request from `username/project/master` to `teamname/project/master`. The Error happened.

If I submit from `teamname/project/dev` to `teamname/project/master`, the code works properly.

I think this maybe a **bug** of `python-gitlab` library.

**Comment by gpocentek** [comment]
Could you enable the debug output and test again?

`````
gl.enable_debug()
`````

If possible could you try the same action using the gitlab API, without python-gitlab? The bug might be on the server side.

**Comment by davidarcher** [comment]
This is a known issue with GitLab: https://gitlab.com/gitlab-org/gitlab-ce/issues/24696

**Comment by gpocentek** [comment]
I'm closing this issue since this is a GitLab problem. Feel free to reopen if needed when GitLab provides a fix.
