### ISSUE TITLE
Filter Branches by Status (I.e Merged)

### ISSUE THREAD

**Issue by ed11e** [python-gitlab/python-gitlab#202]
This is probably more of a feature request, but it would be useful to have a way of filtering branches by status (I.e merged). This would allow the bulk deletion of merged branches which haven't been deleted for whatever reason.

**Comment by gpocentek** [comment]
This is an interesting feature that would need to be implemented on the gitlab side first, I don't think this is supported by the API yet.

**Comment by ed11e** [comment]
I don't think it is either but it would be brilliant if it could be implemented at some point!

**Comment by gpocentek** [comment]
Closing this issue since this is not implemented upstream, and I couldn't find any bug reports asking for this feature in GitLab.
