### ISSUE TITLE
Retry mechanism doesn't catch CloudFlare 520 error

### ISSUE THREAD

**Issue by ronlib** [python-gitlab/python-gitlab#2026]
## Description of the problem, including code/CLI snippet
We're passing the parameter `retry_transient_errors=True` to the GitLab client to ensure the retry mechanism kicks in for transient errors. One error that is not covered by the mechanism is 520 from Cloudflare. When fetching paginated data, there's no way to retry.

```
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 1074, in __next__
    return self.next()
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 1085, in next
    self._query(self._next_url, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 990, in _query
    result = self._gl.http_request("get", url, query_data=query_data, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 727, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 520: <!DOCTYPE html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
  <title>500 Error - GitLab</title>
  <style>body{align-items:center;color:#666;display:flex;flex-direction:column;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-size:14px;justify-content:center;margin:auto;text-align:center}hr{border:0;border-bottom:1px solid #fff;border-top:1px solid #eee;margin:18px auto;max-width:800px}img{max-width:40vw}.container{margin:auto 20px}.cferror_details{list-style-type:none}.cf-error-details h1{color:#456;font-size:20px;font-weight:400;line-height:28px}</style>

...
<body>
...
  <div class="container">
    <div class="cf-error-details cf-error-520">
  <h1>Web server is returning an unknown error</h1>
  <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
  <ul>
    <li>Ray ID: 710f017d8be0c170</li>
    <li>Your IP address: 20.120.60.175</li>
    <li>Error reference number: 520</li>
    <li>Cloudflare Location: Ashburn</li>
  </ul>
</div>

    <hr />
    <p>Please see our <a href="https://status.gitlab.com">status page</a> for more information.</p>
  </div>
</body>
</html>
```

## Expected Behavior
520 error should result in retries, or there should be an option to control this behavior for the caller.

## Actual Behavior
An exception is raised without a retry.

## Specifications

  - python-gitlab version: 3.1.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
The code appears to retry 520

https://github.com/python-gitlab/python-gitlab/blob/792cee939843d8df4c87bb8068be147ec97fabac/gitlab/client.py#L39

https://github.com/python-gitlab/python-gitlab/blob/792cee939843d8df4c87bb8068be147ec97fabac/gitlab/client.py#L722-L725

Is it possible that it is retrying but the maximum number of retries has been exceeded?

You can try changing the `max_retries` value: https://python-gitlab.readthedocs.io/en/main/api-usage.html?highlight=max_retries#rate-limits

**Comment by nejch** [comment]
@ronlib I see you're using v3.1.1. You'll just need to upgrade, Cloudflare status codes were added to retryable codes in 3.4.0:

https://github.com/python-gitlab/python-gitlab/releases/tag/v3.4.0

Please reopen if you still see issues with 3.4.0 :)
