### ISSUE TITLE
Git lfs support

### ISSUE THREAD

**Issue by ateymour** [python-gitlab/python-gitlab#2027]
Based of lack of mentions in the docs, it seems like lfs is not supported. And this is confirmed with a test commit:

```
gitlab.exceptions.GitlabHttpError: 400: File "my_file.bin" is larger than the allowed size of 5 MB - use LFS
```

Without it, it blocks adoption from people who need to push/pull larger files because they would have to build a whole new pipeline for larger files. If you you need a separate solution with lfs, why not just use that solution for all files. It quickly devolves into not using python-gitlab at all.  

Is it currently supported? If so how can it be enabled? And/or is the support it planned?

**Comment by JohnVillalovos** [comment]
Is there any support in the GitLab API for LFS? I did a very quick search for "LFS" and "large" and didn't notice anything.

https://docs.gitlab.com/ee/api/api_resources.html

**Comment by ateymour** [comment]
Yea it may not be. I just brough this up in the gitlab repo as well to confirm:
https://gitlab.com/gitlab-org/gitlab/-/issues/363606

**Comment by nejch** [comment]
See also https://github.com/python-gitlab/python-gitlab/issues/1745 for a bit more context. python-gitlab can really only do what the GitLab API already supports.

**Comment by nejch** [comment]
Hey @ateymour let's close this one for now as there's not much we can do on our side.

If GitLab decides to implement this at some point, let's revisit this later! :)

**Comment by JohnVillalovos** [comment]
@adholmgren posted the following in #2778

I just wanted to let you and anyone else know that it is now possible to get a file that is stored as lfs because the API enabled it 6ish months ago.

```
gl = gitlab.Gitlab('https://your.gitlab.server.com', private_token="t0k3n1d3nt1ty")
gl.auth()
project_id = 12345
project = gl.projects.get(id=project_id)
fm = project.files
file = fm.raw('path/to/file.ext', ref='master', lfs=True)
```

works as expected to give the raw lfs file.

**Comment by qiangxinglin** [comment]
After serveral trials, you can push/update LFS files by using [Commits API](https://docs.gitlab.com/ee/api/commits.html#create-a-commit-with-multiple-files-and-actions) in the following manner:
- `action: delete` the LFS files first (if you want to update rather than newly create)
- `action: create` the files you needed  

So, the actual request payload would like:
```
{
   "branch": "main",
   "commit_message": "msg",
   "actions": [
      {
         "action":"delete",
         "file_path":"YOUR_LFS_PATH"
      },
      {
         "action":"create",
         "file_path":"YOUR_LFS_PATH",
         "content": LFS_CONTENT_IN_BASE64_ENCODED
         "encoding":"base64"
      }
   ]
}
```
