### ISSUE TITLE
Get the path to repository storage

### ISSUE THREAD

**Issue by fmdaboville** [python-gitlab/python-gitlab#2028]
## Description of the problem, including code/CLI snippet

Add the ability to get the repository storage : https://docs.gitlab.com/ee/api/projects.html#get-the-path-to-repository-storage

Is it possible to add this to get the hashed path of the project ?

## Specifications

  - python-gitlab version: v3.4.0
  - API version you are using (v3/v4): 4
  - Gitlab server version (or gitlab.com): 14.8.2

**Comment by nejch** [comment]
You're in luck @fmdaboville, there's a release scheduled for tonight so you should have this tomorrow morning :)

**Comment by fmdaboville** [comment]
Wow thank you for your quick work !
