### ISSUE TITLE
Labels and boards are not copied from custom project template

### ISSUE THREAD

**Issue by sw-dbrown** [python-gitlab/python-gitlab#2038]
## Description of the problem, including code/CLI snippet

I am trying to automatically create projects using python-gitlab based on custom project templates. I have defined custom project templates on a group-level and I can use python-gitlab to create projects based on these templates.

## Expected Behavior

The labels and boards associated with the project template should be copied when creating a new project from the template via python-gitlab. The labels and boards are present when I use the "Create from template" function in the GitLab web application.

This is the code that I am using. I have removed the variable parts for brevity:

```
def create_project(self):
    args={}
    args["name"] = "tmpl9"
    args["path"] = "tmpl9"
    args["namespace_id"] = 2480

    args["template_project_id"] = 1987
    args["use_custom_template"] = "true"
    args["group_with_project_templates_id"] = 2464
    args["namespace_id"] = 2480

    self.gl.projects.create(args)
```

The IDs would normally be derived from programmatically.

This is the request that is triggered via the web application, for completeness sake:

```
POST /projects HTTP/2
Host: [...]
Cookie: [...]
Content-Type: application/x-www-form-urlencoded
[...]

authenticity_token=[...]&
project%5Btemplate_project_id%5D=1987&
project%5Buse_custom_template%5D=true&
project%5Bgroup_with_project_templates_id%5D=2464&
project%5Bci_cd_only%5D=false&
project%5Bname%5D=tmpl8&
project%5Bselected_namespace_id%5D=2480&
project%5Bnamespace_id%5D=2480&
project%5Bpath%5D=tmpl8&
project%5Bdescription%5D=&
project%5Bvisibility_level%5D=0
```

## Actual Behavior

The labels and boards are not copied when creating the project via the API. The labels and boards are only copied when using the web application.

## Specifications

  - python-gitlab version: `3.5.0`
  - API version you are using (v3/v4): v4 (I think)
  - Gitlab server version (or gitlab.com): `14.10.2-ee`

**Comment by JohnVillalovos** [comment]
@sw-dbrown  Please provide a code example to explain the issue better.

**Comment by sw-dbrown** [comment]
> @sw-dbrown Please provide a code example to explain the issue better.

Hello @JohnVillalovos, I have updated the issue description.

**Comment by nejch** [comment]
I think this might be an upstream issue, but hard to say as I don't have access to Premium features:

https://gitlab.com/gitlab-org/gitlab/-/issues/349629#note_821043988

Does the same happen if you use curl or another http client?

**Comment by sw-dbrown** [comment]
Yes, it does appear to be an upstream issue. When I create a project using the follow curl command, the project is also created without labels:

```
curl --request POST --header "PRIVATE-TOKEN: [...]" --header "Content-Type: application/json" \
--data '{"name":"tmpl10","path":"tmpl10","namespace_id":"2480","template_project_id":"1987",'\
'"use_custom_template":"true","group_with_project_templates_id":"2464","selected_namespace_id":"2480"}' \
--url 'https://[...]/api/v4/projects/'
```

However, I am not sure that the issue you referenced is actually related since the commenter said that "Issues are successfully created".

**Comment by sw-dbrown** [comment]
Thank you for your time. Feel free to close this issue at your discretion.
