### ISSUE TITLE
Specify CA certificate

### ISSUE THREAD

**Issue by cmr** [python-gitlab/python-gitlab#204]
In `requests`, one can set `verify` to the path of a CA certificate used to verify the the connection. This is really useful for CE instances when orgs run their own CA (ie, "self-signed").  This feature would allow me to not have to use ssl_verify=False.

**Comment by gpocentek** [comment]
Definitely an interesting feature to implement. Thanks for the suggestion :)

**Comment by mdhausman** [comment]
It looks like this has been implemented? When I set `ssl_verify='path/to/my/signed/cert.pem'`, it uses that cert appropriately, with no InsecureRequestWarnings. Exception being when I try to set ssl_verify from a config file as documented in #270

**Comment by mdhausman** [comment]
Finally getting around to looking into this.

Yeah, it looks like under the hood this is already [exactly what requests does](https://github.com/requests/requests/blob/master/requests/sessions.py#L468) and that we should be able to use it that way. Furthermore, this can be done safely as this behavior appears [even in the earliest version of requests supported by python-gitlab](https://github.com/requests/requests/blob/b30b09e84c5709149e796af5cb07671db823af53/requests/sessions.py#L231).

**Comment by gpocentek** [comment]
Fixed by @mdhausman in #294.
