### ISSUE TITLE
Need documented procedure for achieving an authenticated session

### ISSUE THREAD

**Issue by eric-s-raymond** [python-gitlab/python-gitlab#2122]
## Description of the problem, including code/CLI snippet

Can't get authenticated access using the code snippet attached to issue #380.

Please add to the documentation a Python code snippet showing how to achieve an authenticated session.   Note, authentication from within CI/CD is not sufficient, I need to be able to write an extractor that can analyze issue boards.

## Expected Behavior

Expected to achive Gitlab session with authenticated access

## Actual Behavior

Instead of a sign-in page, I got the Cloudflare "Checking your browser" page with no authentication token.

## Specifications

  - python-gitlab version: 3.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
I personally have never tried username/password authentication. In my use I am always using a `private_token`.

For your use case of trying to access issue boards. I think would be best to use a project access token [1], or a group access token [2], or finally a personal access token. I would recommend to use them in that order as they go in order of least privilege.  These can be created in the Web UI.

If desired to use them in the CI then can add the token value into the CI/CD variables. Preferably as a "protected" variable that can only be used when run from a protected branch.

[1] https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html
[2] https://docs.gitlab.com/ee/user/group/settings/group_access_tokens.html

**Comment by eric-s-raymond** [comment]
I successfully generated a personal access token and used it, thanks.

But please don't just give me advice on an issue board, *put this procedure in the docs*. Because right now they are worse than merely useless, they are actively wrong - pointing at a code example that fails.

**Comment by nejch** [comment]
@eric-s-raymond those docs were valid for older versions of GitLab and maintainers here joined the project after those docs were written, so we rely on community feedback and contributions to update docs. I've opened #2127 to stop recommending password-based flows.
