### ISSUE TITLE
gl.projects.get() fails when provided "namespace/project_name"

### ISSUE THREAD

**Issue by walterrowe** [python-gitlab/python-gitlab#2130]
## Description of the problem, including code/CLI snippet

In project-status.py ...

```python
    for this_project in options.project:
        this_project = my_gitlab.projects.get(this_project)
        print("Adding project:", this_project.path_with_namespace)
        projects = projects + [this_project]
```

- when this_project provided in "namespace/project_name" format, projects.get() fails with 404 error.
- when this_project specified in project_id format, projects.get() succeeds.
- same API access token for both forms of request.
- access token is a project level token with full rights.

## Expected Behavior

this_project = my_gitlab.projects.get("namespace/project_name") succeeds

## Actual Behavior

this_project = my_gitlab.projects.get("namespace/project_name") fails with 404 error

```shell
% ./project-status.py --config ~/.python-gitlab.cfg --section gitlab-https --project https-phase2/ha-proxy-migration
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gitlab/exceptions.py", line 330, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/mixins.py", line 139, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 790, in http_get
    result = self.http_request(
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 756, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wrowe/git-repos/python-gitlab/./project-status.py", line 139, in <module>
    this_project = my_gitlab.projects.get(this_project)
  File "/usr/local/lib/python3.10/site-packages/gitlab/v4/objects/projects.py", line 775, in get
    return cast(Project, super().get(id=id, lazy=lazy, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/gitlab/exceptions.py", line 332, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Not Found
```

```shell
% ./project-status.py --config ~/.python-gitlab.cfg --section gitlab-https --project 3894 
Adding project: https-phase2/ha-proxy-migration
Scanning issues for ha-proxy-migration ...
Building report for ha-proxy-migration ...
Writing report file ...
```

## Specifications

  - python-gitlab version: 3.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.0.12 Community Edition

**Comment by walterrowe** [comment]
Don't know if this is also helpful.

```shell
% gitlab -c ~/.python-gitlab.cfg -g gitlab-https project-notification-settings get --project-id https-phase2/ha-proxy-migration
Impossible to get object (gitlab.v4.objects.notification_settings.NotificationSettingsManager.get() got multiple values for keyword argument 'id')
```

**Comment by JohnVillalovos** [comment]
Hi @walterrowe 

I know that it does work to get by the path as I use that often. So this is odd.

Can you add a print statement so we see the name of the project?
```
    for this_project in options.project:
        print(f"Project: {this_project!r}")
        this_project = my_gitlab.projects.get(this_project)
        print("Adding project:", this_project.path_with_namespace)
        projects = projects + [this_project]
```

**Comment by walterrowe** [comment]
See the first line of output for the failure. The last command line arg is the project with name space.

**Comment by JohnVillalovos** [comment]
> See the first line of output for the failure. The last command line arg is the project with name space.

But can you print the value that you are sending to the `get` command please.

**Comment by walterrowe** [comment]
```shell
% ./project-status.py --config ~/.python-gitlab.cfg --section gitlab-https --project https-phase2/ha-proxy-migration

Looking for project: 'https-phase2/ha-proxy-migration' (type: <class 'str'>)

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gitlab/exceptions.py", line 330, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/mixins.py", line 139, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 790, in http_get
    result = self.http_request(
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 756, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wrowe/git-repos/python-gitlab/./project-status.py", line 140, in <module>
    this_project = my_gitlab.projects.get(this_project)
  File "/usr/local/lib/python3.10/site-packages/gitlab/v4/objects/projects.py", line 775, in get
    return cast(Project, super().get(id=id, lazy=lazy, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/gitlab/exceptions.py", line 332, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Not Found
```

```python
group1.add_argument(
    "--project",
    dest="project",
    type=str,
    help="list of one or more project paths or ids",
    nargs="+",
    action="extend",
)
```

**Comment by walterrowe** [comment]
Looking in MixIns.py I see that GetMixin calls utils.EncodedID which has this line.

```python
        if isinstance(value, str):
            value = urllib.parse.quote(value, safe="")
```

https://github.com/python-gitlab/python-gitlab/blob/d5de4b1fe38bedc07862bd9446dfd48b92cb078d/gitlab/utils.py#L127-L128

**Comment by JohnVillalovos** [comment]
Very odd 😕

You can do:
```
gl.enable_debug()
```

And the quoting is working as I expected:
```
>>> import gitlab.utils as utils
>>> a = "https-phase2/ha-proxy-migration"
>>> utils.EncodedId(a)
'https-phase2%2Fha-proxy-migration'
```

This will output the data that is being sent to the server.

**Comment by JohnVillalovos** [comment]
> Looking in mixins.py I see that GetMixin calls utils.EncodedID.
> 
> https://github.com/python-gitlab/python-gitlab/blob/d5de4b1fe38bedc07862bd9446dfd48b92cb078d/gitlab/mixins.py#L130-L131
> 


The quoting is working as I expected:
```
>>> import gitlab.utils as utils
>>> a = "https-phase2/ha-proxy-migration"
>>> utils.EncodedId(a)
'https-phase2%2Fha-proxy-migration'
```

**Comment by walterrowe** [comment]
with debug enabled ...

```shell
% ./project-status.py --config ~/.python-gitlab.cfg --section gitlab-https --project https-phase2/ha-proxy-migration

Looking for project: 'https-phase2/ha-proxy-migration' (type: <class 'str'>)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): my.gitlab.server:443
send: b'GET /api/v4/projects/https-phase2%2Fha-proxy-migration HTTP/1.1\r\nHost: my.gitlab.server\r\nUser-Agent: python-gitlab/3.6.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nPRIVATE-TOKEN: S16WFZm7fShRyaVAKkDd\r\nContent-type: application/json\r\n\r\n'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Server: nginx
header: Date: Wed, 06 Jul 2022 17:07:29 GMT
header: Content-Type: application/json
header: Content-Length: 25
header: Connection: keep-alive
header: Cache-Control: no-cache
header: Vary: Origin
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-Request-Id: 01G7A7P9ERX4PV59KBYQF1SZ17
header: X-Runtime: 0.008983
DEBUG:urllib3.connectionpool:https://my.gitlab.server:443 "GET /api/v4/projects/https-phase2%2Fha-proxy-migration HTTP/1.1" 404 25

[ the rest of the traceback is the same as above ]
```

**Comment by walterrowe** [comment]
Would love the interactive help but I can't connect to the gitter.im channel from this restricted network.

**Comment by JohnVillalovos** [comment]
One thing I was reading was this:
https://docs.gitlab.com/ee/api/#namespaced-path-encoding

A project’s path isn’t necessarily the same as its name. A project’s path is found in the project’s URL or in the project’s settings, under General > Advanced > Change path.

But it looks like it is correct 😕

Can you try this?

```
this_project = my_gitlab.projects.get(3894 )
print(f"{this_project.path_with_namespace!r}")
```

Want to make sure there isn't some extra unseen characters in the path.

Another possibility is that Gitlab 14.0 has a bug, but I wouldn't think so.

**Comment by JohnVillalovos** [comment]
> with debug enabled ...
> 
> ```shell
> % ./project-status.py --config ~/.python-gitlab.cfg --section gitlab-https --project https-phase2/ha-proxy-migration
> 
> Looking for project: 'https-phase2/ha-proxy-migration' (type: <class 'str'>)
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): my.gitlab.server:443
> send: b'GET /api/v4/projects/https-phase2%2Fha-proxy-migration HTTP/1.1\r\nHost: my.gitlab.server\r\nUser-Agent: python-gitlab/3.6.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nPRIVATE-TOKEN: my_private_token\r> ```

The path being sent to Gitlab looks correct to me.

`send: b'GET /api/v4/projects/https-phase2%2Fha-proxy-migration`

**Comment by walterrowe** [comment]
The program does that.

```shell
% ./project-status.py --config ~/.python-gitlab.cfg --section gitlab-https --project 3894

Looking for project: '3894' (type: <class 'str'>)

Adding project: https-phase2/ha-proxy-migration
Scanning issues for ha-proxy-migration ...
Building report for ha-proxy-migration ...
Writing report file ...
```

**Comment by walterrowe** [comment]
Yes.

```shell
% ./project-status.py --config ~/.python-gitlab.cfg --section gitlab-https --project 3894

Looking for project: '3894' (type: <class 'str'>)

Adding project: 'https-phase2/ha-proxy-migration'
Scanning issues for ha-proxy-migration ...
Building report for ha-proxy-migration ...
Writing report file ...
```

**Comment by JohnVillalovos** [comment]
Sadly I don't know. It seems like python-gitlab is sending the correct path to the Gitlab server based on the debug output.

The only other shot in the dark I have is to also print the url-encoded ID form.

```
encoded_id = gitlab.utils.EncodedId(this_project.path_with_namespace)
print(f"{encoded_id!r}")
```

**Comment by JohnVillalovos** [comment]
> is it possible this is a bug in the 14.0.12 CE API? we are upgrading to 15.x over time. gitlab upgrades require iterating over each version unfortunately.

Possible yes. I don't know though. I would think it isn't as it seems like a big bug. But not sure.

**Comment by JohnVillalovos** [comment]
Also. Is this failing for all/other projects when doing a get using a path?

**Comment by walterrowe** [comment]
RESOLVED:

On this specific gitlab instances, I had to use `https://my.gitlab.server/toplevel_entrypath` in ~/.python-gitlab.cfg

We don't have this "**toplevel_entrypath**" layer in our paths on our other gitlab instances. I need to talk to her gitlab admin about that.

**Comment by JohnVillalovos** [comment]
Just curious. Does the `web_url` attribute show the correct path? Maybe next time I will ask to see that value too 🤓

Also confusing to me why the integer ID worked. Weird.

**Comment by JohnVillalovos** [comment]
> The integer ID probably worked because gitlab searches a different field in the database for an ID versus for a namespace/project_name.
> 
> and since you asked ...
> 
> ```shell
> Adding project: 'https-phase2/ha-proxy-migration' ('https://my.gitlab.server/gitlab/https-phase2/ha-proxy-migration')
> ```
> 
> definitely worth also asking for the web_url in the future.

Thanks. I'll try to remember that!
