### ISSUE TITLE
Progress bars for http requests

### ISSUE THREAD

**Issue by pltrdy** [python-gitlab/python-gitlab#2143]
Hi,

Do you consider adding a (optionnal) progress bar on `client.http_request`. 
After minutes of research it seems quite easy to introduce with `requests` and `tqdm`.
Are you open for such PR ?

**Comment by max-wittig** [comment]
I'm not sure that is really needed. Yet another dependency for marginal benefit. Also this will destroy any terminal output in non-interactive terminals such as CI.

**Comment by JohnVillalovos** [comment]
You might be able to do this yourself. As `http_request` does have a `streamed` parameter.

I agree with Max, as I am also in favor in keeping external library dependencies to a minimum.

Off topic, I use to know a different "ptardy", but his name was Pierre and he was from Toulouse 😊
