### ISSUE TITLE
How to "Disable group runners" through the API?

### ISSUE THREAD

**Issue by camilstaps** [python-gitlab/python-gitlab#2148]
## Description of the problem, including code/CLI snippet

When you have (1) a group with CI/CD runners set up in the group and (2) a project in that group, the project has the option in Settings / CI/CD to enable/disable these group runners:

![2022-07-15-090655_757x191](https://user-images.githubusercontent.com/1202754/179170610-1b1cb8b2-6ae5-4c2d-b495-8164cb906205.png)

I can't find how to do this with python-gitlab. I can see these group runners in `project.runners.list()` (they have `runner_type = group_type`), but don't see how to enable/disable group runners.

There is a setting `shared_runners_enabled` on projects, but this is for runners shared across the GitLab instance, not group runners.

## Expected Behavior

There is a way to specify on the project whether group runners are enabled/disabled.

## Actual Behavior

I cannot find this property.

I also cannot find how to do this on the GitLab API docs (https://docs.gitlab.com/ee/api/runners.html), so it may be that this is just not implemented on their side. I looked through there issues but could not find anything about this. I'd be happy to create an issue over there, but thought I'd check here first.

As an aside, trying to delete an individual runner gives a 404 error. This is expected as the UI does not give a way to disable individual group runners, but it's the only thing I could think of that might work:

```
>>> from gitlab import Gitlab
>>> gl = Gitlab('https://gitlab.com', private_token='REDACTED')
>>> p = gl.projects.get('namespace')
>>> p.runners.list()
[<ProjectRunner id:XXXX>, <ProjectRunner id:YYYY>, <ProjectRunner id:ZZZZ>]
>>> r = p.runners.list()[0]
>>> r.attributes
{'id': XXXX, 'description': 'my runner', 'ip_address': 'REDACTED', 'active': True, 'paused': False, 'is_shared': False, 'runner_type': 'group_type', 'name': 'gitlab-runner', 'online': True, 'status': 'online', 'project_id': REDACTED}
>>> p.runners.delete(XXXX)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gitlab/exceptions.py", line 330, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gitlab/mixins.py", line 444, in delete
    self.gitlab.http_delete(path, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gitlab/client.py", line 1043, in http_delete
    return self.http_request("delete", path, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gitlab/client.py", line 756, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 Runner Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/gitlab/exceptions.py", line 332, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabDeleteError: 404: 404 Runner Not Found
```

## Specifications

  - python-gitlab version: 3.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com ('15.2.0-pre', '932b4ee7ae0')

**Comment by nejch** [comment]
@camilstaps interesting, it seems this is not implemented at all in the API - the setting is also not exposed in the projects GET API. If it were implemented, it should behave the same as the `shared_runners_enabled` toggle in the projects API.

Like the example given here:
https://docs.gitlab.com/ee/api/projects.html#edit-project

If you find or post an issue upstream, please link it here!

**Comment by nejch** [comment]
Ah, the delete error might be a separate issue that I completely skimmed over, we can take a look at that separately if needed, I have to check what runners are returned etc :)

**Comment by camilstaps** [comment]
@nejch thanks for confirming! I have opened an issue upstream: https://gitlab.com/gitlab-org/gitlab/-/issues/367982. I will report back here when it is resolved.

As for the delete error, it could be that I simply don't have the required permissions to delete the runner in this case, and I don't have a personal runner and group to test with. 404 seems to be the error for unauthorized deletes: https://gitlab.com/gitlab-org/gitlab/-/issues/29161. And like I said, the UI does not give this option for group runners from a project's settings page anyway, so it might be by design. So for me you don't need to look into this any further!

**Comment by nejch** [comment]
@camilstaps I've started implementing this upstream, so I'm going to close this here as it'll be available via python-gitlab as soon as the API exposes it. Feel free to follow along at https://gitlab.com/gitlab-org/gitlab/-/merge_requests/111197.

**Comment by camilstaps** [comment]
That's great, thank you!
