### ISSUE TITLE
Need to require CI job `api_func_v4` to pass in order to merge.

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#2155]
@nejch Creating this issue so that we don't forget.

PR #2147 was merged. So the project settings need to be updated to require the `api_func_v4` CI job to pass before a PR is merged.

**Comment by nejch** [comment]
Sounds good, will do as soon as we have some of the currently active external PRs merged here https://github.com/python-gitlab/python-gitlab/pulls :+1:

**Comment by nejch** [comment]
Added the required check and enabled the `Update branch` button on PRs so people can get up to date if their PR gets stuck.
