### ISSUE TITLE
from_config should offer being more strict about sections

### ISSUE THREAD

**Issue by quazgar** [python-gitlab/python-gitlab#2164]
## Description of the problem, including code/CLI snippet

I just had the problem that a user of my software had forgotten to create their `~/.python-gitlab.cfg`. My program tells python-gitlab to take the connection setting from a specific config section, but because that did not exist, it defaulted to the gitlab.com server. Further down the code this resulted in some seemingly unrelated errors (pagination overflow because too many issues were found). Failing fast and hard at an earlier point would have helped and made the code more robust.

## Expected Behavior

The following code should fail fast:
```python
gitlab.Gitlab.from_config("does not exist")
```

Alternatively, there should be an optional argument like for example:
```python
gitlab.Gitlab.from_config("does not exist either", strict=True)
```

## Actual Behavior

Currently the above code example just works without any warnings or exceptions and takes the default connection values. In the worst case this could lead to data loss (if stuff from the wrong repositories is deleted) or data leakage (if data is sent to the wrong server). A non-existing config file is not the only possible reason, there could also be a simple typo in the section name.

## Specifications

  - python-gitlab version: 3.3.0
  - API version you are using (v3/v4): 
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
Good catch @quazgar, we should probably raise if the user provides a `gitlab_id` and we don't collect any config files.

**Comment by quazgar** [comment]
Thanks! :heart:
