### ISSUE TITLE
path parameter for the list method of ProjectCommitManager is broken

### ISSUE THREAD

**Issue by tyates-indeed** [python-gitlab/python-gitlab#2185]
## Description of the problem, including code/CLI snippet
https://docs.gitlab.com/ee/api/commits.html#list-repository-commits shows that `path` is a valid parameter when listing commits for a repository. However, when trying to use this parameter within the python-gitlab library:
```
commits = gitlab_project.commits.list(path="file.txt")
```

An error is returned because of a bug within the the mixin code:
```
gitlab.exceptions.GitlabListError: 404: 404 API Version Not Found
```

Digging into the code, we can see that within the mixin, `path` is being used to alter the URL that we call:
<img width="460" alt="Screen Shot 2022-07-25 at 4 40 10 PM" src="https://user-images.githubusercontent.com/57921587/180878609-ee498869-9759-4005-a6a9-1fc3c55b85c3.png">

This URL is clearly wrong and will break. You can see that the `file.txt` string has been added directly after the API version.

## Expected Behavior
I should be able to use `path` as a parameter for the `list` method of ProjectCommitManager.

## Actual Behavior
The `path` parameter clobbers the GitLab URL which breaks the call.

## Specifications

  - python-gitlab version: 3.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by JohnVillalovos** [comment]
You probably need to use

```
commits = gitlab_project.commits.list(query_parameters={path="file.txt"})
```

See https://python-gitlab.readthedocs.io/en/main/api-usage.html#managers

**Comment by tyates-indeed** [comment]
Perfect! Thank you for linking those docs. My apologies for not seeing that. This resolved the issue.

**Comment by davidcharles008** [comment]
> You probably need to use
> 
> ```
> commits = gitlab_project.commits.list(query_parameters={path="file.txt"})
> ```
> 
> See https://python-gitlab.readthedocs.io/en/main/api-usage.html#managers

Is this working still.? I get below error

`>>> commits = project.commits.list(query_parameters={path="ui"})
  File "<stdin>", line 1
    commits = project.commits.list(query_parameters={path="ui"})
                                                     ^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?`

**Comment by nejch** [comment]
There was a small syntax error in the suggestion there. It's a normal dict, so that should be:

`query_parameters={"path": "ui"}`
