### ISSUE TITLE
gl.projects.list (..., all=True) fails.

### ISSUE THREAD

**Issue by kgk** [python-gitlab/python-gitlab#2190]
## Description of the problem, including code/CLI snippet
from gitlab import Gitlab
gl = Gitlab ("http://gitlab.com",  private_token="<private>")
gl.projects.list(visibility="private", all=True)

## Expected Behavior
[<Project id:38036132 path:tutorial>,
 <Project id:37950395 path:snowboard>,
 <Project id:37590316 path:terraform-gitlab-runner>,
 <Project id:37222088 path:auto_hcs>,
...
]

## Actual Behavior
---------------------------------------------------------------------------
GitlabHttpError                           Traceback (most recent call last)
~/.virtualenvs/viqi1/lib/python3.9/site-packages/gitlab/exceptions.py in wrapped_f(*args, **kwargs)
    329             try:
--> 330                 return f(*args, **kwargs)
    331             except GitlabHttpError as e:

~/.virtualenvs/viqi1/lib/python3.9/site-packages/gitlab/mixins.py in list(self, **kwargs)
    257             assert self._obj_cls is not None
--> 258         obj = self.gitlab.http_list(path, **data)
    259         if isinstance(obj, list):

~/.virtualenvs/viqi1/lib/python3.9/site-packages/gitlab/client.py in http_list(self, path, query_data, as_list, iterator, **kwargs)
    887         if get_all is True:
--> 888             return list(GitlabList(self, url, query_data, **kwargs))
    889 

~/.virtualenvs/viqi1/lib/python3.9/site-packages/gitlab/client.py in __next__(self)
   1178     def __next__(self) -> Dict[str, Any]:
-> 1179         return self.next()
   1180 

~/.virtualenvs/viqi1/lib/python3.9/site-packages/gitlab/client.py in next(self)
   1189         if self._next_url and self._get_next is True:
-> 1190             self._query(self._next_url, **self._kwargs)
   1191             return self.next()

~/.virtualenvs/viqi1/lib/python3.9/site-packages/gitlab/client.py in _query(self, url, query_data, **kwargs)
   1096         query_data = query_data or {}
-> 1097         result = self._gl.http_request("get", url, query_data=query_data, **kwargs)
   1098         try:

~/.virtualenvs/viqi1/lib/python3.9/site-packages/gitlab/client.py in http_request(self, verb, path, query_data, post_data, raw, streamed, files, timeout, obey_rate_limit, retry_transient_errors, max_retries, **kwargs)
    755 
--> 756             raise gitlab.exceptions.GitlabHttpError(
    757                 response_code=result.status_code,

GitlabHttpError: 502: <!DOCTYPE html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
  <title>500 Error - GitLab</title>
  <style>body{align-items:center;color:#666;display:flex;flex-direction:column;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-size:14px;justify-content:center;margin:auto;text-align:center}hr{border:0;border-bottom:1px solid #fff;border-top:1px solid #eee;margin:18px auto;max-width:800px}img{max-width:40vw}.container{margin:auto 20px}.cferror_details{list-style-type:none}.cf-error-details h1{color:#456;font-size:20px;font-weight:400;line-height:28px}</style>

</head>

<body>
  <h1>
    <img src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE5MiIgdmlld0JveD0iMCAwIDI1IDI0IiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogIDxwYXRoIGQ9Im0yNC41MDcgOS41LS4wMzQtLjA5TDIxLjA4Mi41NjJhLjg5Ni44OTYgMCAwIDAtMS42OTQuMDkxbC0yLjI5IDcuMDFINy44MjVMNS41MzUuNjUzYS44OTguODk4IDAgMCAwLTEuNjk0LS4wOUwuNDUxIDkuNDExLjQxNiA5LjVhNi4yOTcgNi4yOTcgMCAwIDAgMi4wOSA3LjI3OGwuMDEyLjAxLjAzLjAyMiA1LjE2IDMuODY3IDIuNTYgMS45MzUgMS41NTQgMS4xNzZhMS4wNTEgMS4wNTEgMCAwIDAgMS4yNjggMGwxLjU1NS0xLjE3NiAyLjU2LTEuOTM1IDUuMTk3LTMuODkuMDE0LS4wMUE2LjI5NyA2LjI5NyAwIDAgMCAyNC41MDcgOS41WiIKICAgICAgICBmaWxsPSIjRTI0MzI5Ii8+CiAgPHBhdGggZD0ibTI0LjUwNyA5LjUtLjAzNC0uMDlhMTEuNDQgMTEuNDQgMCAwIDAtNC41NiAyLjA1MWwtNy40NDcgNS42MzIgNC43NDIgMy41ODQgNS4xOTctMy44OS4wMTQtLjAxQTYuMjk3IDYuMjk3IDAgMCAwIDI0LjUwNyA5LjVaIgogICAgICAgIGZpbGw9IiNGQzZEMjYiLz4KICA8cGF0aCBkPSJtNy43MDcgMjAuNjc3IDIuNTYgMS45MzUgMS41NTUgMS4xNzZhMS4wNTEgMS4wNTEgMCAwIDAgMS4yNjggMGwxLjU1NS0xLjE3NiAyLjU2LTEuOTM1LTQuNzQzLTMuNTg0LTQuNzU1IDMuNTg0WiIKICAgICAgICBmaWxsPSIjRkNBMzI2Ii8+CiAgPHBhdGggZD0iTTUuMDEgMTEuNDYxYTExLjQzIDExLjQzIDAgMCAwLTQuNTYtMi4wNUwuNDE2IDkuNWE2LjI5NyA2LjI5NyAwIDAgMCAyLjA5IDcuMjc4bC4wMTIuMDEuMDMuMDIyIDUuMTYgMy44NjcgNC43NDUtMy41ODQtNy40NDQtNS42MzJaIgogICAgICAgIGZpbGw9IiNGQzZEMjYiLz4KPC9zdmc+Cg==" alt="GitLab" /><br />
  </h1>
  <div class="container">
    <div class="cf-error-details cf-error-502">
  <h1>Bad gateway</h1>
  <p>The web server reported a bad gateway error.</p>
  <ul>
    <li>Ray ID: 73136192ef7f7ec0</li>
    <li>Your IP address: 98.173.202.46</li>
    <li>Error reference number: 502</li>
    <li>Cloudflare Location: Los Angeles</li>
  </ul>
</div>

    <hr />
    <p>Please see our <a href="https://status.gitlab.com">status page</a> for more information.</p>
  </div>
</body>
</html>

The above exception was the direct cause of the following exception:

GitlabListError                           Traceback (most recent call last)
<ipython-input-13-fc45c9bae5dc> in <module>
----> 1 gl.projects.list(visibility="private", all=True)

~/.virtualenvs/viqi1/lib/python3.9/site-packages/gitlab/exceptions.py in wrapped_f(*args, **kwargs)
    330                 return f(*args, **kwargs)
    331             except GitlabHttpError as e:
--> 332                 raise error(e.error_message, e.response_code, e.response_body) from e
    333 
    334         return cast(__F, wrapped_f)

GitlabListError: 502: <!DOCTYPE html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
  <title>500 Error - GitLab</title>
  <style>body{align-items:center;color:#666;display:flex;flex-direction:column;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-size:14px;justify-content:center;margin:auto;text-align:center}hr{border:0;border-bottom:1px solid #fff;border-top:1px solid #eee;margin:18px auto;max-width:800px}img{max-width:40vw}.container{margin:auto 20px}.cferror_details{list-style-type:none}.cf-error-details h1{color:#456;font-size:20px;font-weight:400;line-height:28px}</style>

</head>

<body>
  <h1>
    <img src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE5MiIgdmlld0JveD0iMCAwIDI1IDI0IiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogIDxwYXRoIGQ9Im0yNC41MDcgOS41LS4wMzQtLjA5TDIxLjA4Mi41NjJhLjg5Ni44OTYgMCAwIDAtMS42OTQuMDkxbC0yLjI5IDcuMDFINy44MjVMNS41MzUuNjUzYS44OTguODk4IDAgMCAwLTEuNjk0LS4wOUwuNDUxIDkuNDExLjQxNiA5LjVhNi4yOTcgNi4yOTcgMCAwIDAgMi4wOSA3LjI3OGwuMDEyLjAxLjAzLjAyMiA1LjE2IDMuODY3IDIuNTYgMS45MzUgMS41NTQgMS4xNzZhMS4wNTEgMS4wNTEgMCAwIDAgMS4yNjggMGwxLjU1NS0xLjE3NiAyLjU2LTEuOTM1IDUuMTk3LTMuODkuMDE0LS4wMUE2LjI5NyA2LjI5NyAwIDAgMCAyNC41MDcgOS41WiIKICAgICAgICBmaWxsPSIjRTI0MzI5Ii8+CiAgPHBhdGggZD0ibTI0LjUwNyA5LjUtLjAzNC0uMDlhMTEuNDQgMTEuNDQgMCAwIDAtNC41NiAyLjA1MWwtNy40NDcgNS42MzIgNC43NDIgMy41ODQgNS4xOTctMy44OS4wMTQtLjAxQTYuMjk3IDYuMjk3IDAgMCAwIDI0LjUwNyA5LjVaIgogICAgICAgIGZpbGw9IiNGQzZEMjYiLz4KICA8cGF0aCBkPSJtNy43MDcgMjAuNjc3IDIuNTYgMS45MzUgMS41NTUgMS4xNzZhMS4wNTEgMS4wNTEgMCAwIDAgMS4yNjggMGwxLjU1NS0xLjE3NiAyLjU2LTEuOTM1LTQuNzQzLTMuNTg0LTQuNzU1IDMuNTg0WiIKICAgICAgICBmaWxsPSIjRkNBMzI2Ii8+CiAgPHBhdGggZD0iTTUuMDEgMTEuNDYxYTExLjQzIDExLjQzIDAgMCAwLTQuNTYtMi4wNUwuNDE2IDkuNWE2LjI5NyA2LjI5NyAwIDAgMCAyLjA5IDcuMjc4bC4wMTIuMDEuMDMuMDIyIDUuMTYgMy44NjcgNC43NDUtMy41ODQtNy40NDQtNS42MzJaIgogICAgICAgIGZpbGw9IiNGQzZEMjYiLz4KPC9zdmc+Cg==" alt="GitLab" /><br />
  </h1>
  <div class="container">
    <div class="cf-error-details cf-error-502">
  <h1>Bad gateway</h1>
  <p>The web server reported a bad gateway error.</p>
  <ul>
    <li>Ray ID: 73136192ef7f7ec0</li>
    <li>Your IP address: 98.173.202.46</li>
    <li>Error reference number: 502</li>
    <li>Cloudflare Location: Los Angeles</li>
  </ul>
</div>

    <hr />
    <p>Please see our <a href="https://status.gitlab.com">status page</a> for more information.</p>
  </div>
</body>
</html>

## Specifications

  - python-gitlab version:3.6
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
@kgk 502 looks more like an intermittent server availability issue. Do you get this consistently or only sometimes?

**Comment by kgk** [comment]
Issue at gitlab

https://gitlab.com/gitlab-com/gl-infra/production/-/issues/7516
