### ISSUE TITLE
Support approvals_before_merge when creating merge requests

### ISSUE THREAD

**Issue by 56KBs** [python-gitlab/python-gitlab#2192]
## Description of the problem, including code/CLI snippet
I'd like to set `approvals_before_merge` when creating merge requests

## Expected Behavior
```python
project.mergerequests.create({
    'source_branch': 'source',
    'target_branch': 'main',
    'title': 'Example',
    'description': 'Example',
    'approvals_before_merge': 0
    })
```

## Actual Behavior
Currently unsupported

## Specifications

  - python-gitlab version: v3.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 15.0.1-ee

**Comment by nejch** [comment]
@56KBs python-gitlab simply sends the attributes to the server, so this should be supported.
https://docs.gitlab.com/ee/api/merge_requests.html#create-mr

Did you make sure you follow the upstream docs?

> If approvals_before_merge is not provided, it inherits the value from the target project. If provided, the following conditions must hold for it to take effect:
> 
>     The target project’s approvals_before_merge must be greater than zero. A value of zero disables approvals for that project.
>     The provided value of approvals_before_merge must be greater than the target project’s approvals_before_merge.

Otherwise if that doesn't help, maybe paste a debug log (`gl.enable_debug()`) with your token masked. But I'm pretty sure this should work on the client side at least.

**Comment by 56KBs** [comment]
Thanks! I looked through the code to see if it did support it and didn't see it listed in https://github.com/python-gitlab/python-gitlab/blob/0daec5fa1428a56a6a927b133613e8b296248167/gitlab/v4/objects/merge_requests.py#L401-L414 so assumed it was something the library needed to support - But it does look to be working now I've done it properly!

**Comment by nejch** [comment]
Those are mostly used for our CLI help and argument parsing, and are almost always out of date unfortunately :smile_cat:
