### ISSUE TITLE
Make Sphinx v5 work

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#2193]
We have an automated PR https://github.com/python-gitlab/python-gitlab/pull/2153 to update to Sphinx v5.

But as @nejch says, "This breaks our API reference docs, need to check the breaking changes."

**Comment by nejch** [comment]
Some of our sphinx config is from 2014 or so - might be worth recreating some of that napoleon/googledocstring templating from scratch, instead of trying to figure out the compatibilities :rofl:
