### ISSUE TITLE
Type hinting using gitlab library does not work (or is not properly documented)

### ISSUE THREAD

**Issue by tuergeist** [python-gitlab/python-gitlab#2213]
## Description of the problem, including code/CLI snippet

Using the gitlab objects for type hinting is not possible or not documented how to use them

e.g. I have a method finding a project and returning the object. 
The following definition fails due to 

```
.venv/lib/python3.10/site-packages/gitlab/__init__.py:53: in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
E   AttributeError: module gitlab has no attribute v4
```

```python
def get_project() -> gitlab.v4.objects.projects.Project:
```

## Expected Behavior

Defined objects can be used for type hinting in code using this library.

## Actual Behavior

Cannot access (internal) objects for type hinting.

## Specifications

  - python-gitlab version: 3.7.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
I guess you just need to shift your imports a bit, since it's not exported to the root module (not sure we want to do that)

This should work for example: 
```python
from gitlab.v4.objects import Project


def get_project() -> Project:
```

But agreed we can maybe document this a bit.

**Comment by JohnVillalovos** [comment]
Took me awhile to reproduce this because I have the following in all my code:

```
from __future__ import annotations
```

Not exactly sure why but with that line no error, but without it get the error.

**Comment by nejch** [comment]
> Took me awhile to reproduce this because I have the following in all my code:
> 
> ```
> from __future__ import annotations
> ```
> 
> Not exactly sure why but with that line no error, but without it get the error. 

I guess those are stringized annotations then and you don't need any importing at all. `def get_project() -> "gitlab.v4.objects.projects.Project":` does the trick as well.

> Since [PEP 563](https://peps.python.org/pep-0563) stringizes their annotations, it allows them to leave these circular dependencies in place, and they can sidestep the circular import problem by never importing the module that defines the types used in the annotations.

**Comment by tuergeist** [comment]
@JohnVillalovos Thanks, this solved the problem.
