### ISSUE TITLE
Epic notes list returns 404 error

### ISSUE THREAD

**Issue by jacche** [python-gitlab/python-gitlab#2234]
Tried using epic.notes.list() but it's returning 404 error, this matches the behavior described in https://docs.gitlab.com/ee/api/notes.html#list-all-epic-notes when **epic IID** is used.

So guessing these need to change to epic ID instead?
https://github.com/python-gitlab/python-gitlab/blob/3f91d2455657c570851f625c0d80c685d9393cbb/gitlab/v4/objects/notes.py#L52
https://github.com/python-gitlab/python-gitlab/blob/3f91d2455657c570851f625c0d80c685d9393cbb/gitlab/v4/objects/notes.py#L54

**Comment by nejch** [comment]
Thanks for the catch @jacche that seems correct. That's...strange, I don't really understand the rationale for that in the upstream API :)
Yes, changing the parent attributes should be enough, would you like to open a PR yourself?

**Comment by jacche** [comment]
Thanks for validating @nejch , I'm new here so not too sure about the process, but this seems like a good one to get started :-) I'll open a PR myself then.
cheers

**Comment by nejch** [comment]
Thanks @jacche just read the contributing guide to get some tips when the linters start to complain. If you have `tox` installed, just run `tox` after committing and before pushing and it will run all the basic checks :)
