### ISSUE TITLE
Support Managing Project Topics

### ISSUE THREAD

**Issue by mitchellmaler** [python-gitlab/python-gitlab#2235]
## Description of the problem, including code/CLI snippet
Would like to use this library to manage the project topics. It supposed managing the global topics https://python-gitlab.readthedocs.io/en/stable/gl_objects/topics.html?highlight=topic#examples but not at the project level where they can be applied in the settings.

## Expected Behavior
Support project.topics api to list, append, delete, etc. topics on a project.

## Actual Behavior
Not supported as I can tell

**Comment by nejch** [comment]
@mitchellmaler topics are mostly an admin-only endpoint, but at the project-level, `topics` is simply an attribute supported by methods described in the upstream API docs. So you can use it like any other project attribute supported, e.g.

```python
gl = gitlab.Gitlab(private_token=token)

project = gl.projects.get("your/projects")
project.topics
# ["python", "docker"]

project.topics = [] # clear the topics
project.save()
```

See https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html for similar examples. Please reopen if any of this doesn't work :)

**Comment by mitchellmaler** [comment]
@nejch Thank you for the quick reply. I wasn't able to see the topics property on the projects object when looking through them. I guess I didn't just try it thinking it could be dynamic. That did work, thanks!

**Comment by nejch** [comment]
Yes, most are dynamic and even depend on the server version as that affects what is returned. Glad you got it to work!
