### ISSUE TITLE
Can't create masked variable via CLI

### ISSUE THREAD

**Issue by yurrriq** [python-gitlab/python-gitlab#2242]
## Description of the problem, including code/CLI snippet

```bash
$ gitlab --debug project-variable create --project-id my-project --key example --value example --masked true
...
send: b'{"key": "example", "value": "example", "masked": "true"}'
...
Impossible to create object (400: {'value': ['is invalid']})
```

## Expected Behavior

Create a masked variable.

## Actual Behavior

400

## Specifications

  - python-gitlab version: 3.4.0 (Python 3.9.12)
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): [14.10.5-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v14.10.5-ee)

**Comment by JohnVillalovos** [comment]
In the web UI it won't let me mask a variable with a value of "value".

Have you tried a more unique value for the variable?

In the Web UI it let me use this value: `alskfopqweiaasjsfjfslfjsalfjlsajflsjf`

**Comment by yurrriq** [comment]
That works when I use the Python API, thanks, but the CLI still false as it treats the boolean as a string.

**Comment by yurrriq** [comment]
Well, I've lied. The CLI works too with a unique enough value, thanks.
