### ISSUE TITLE
project.default_branch is not in project.branches.list()

### ISSUE THREAD

**Issue by dazza-codes** [python-gitlab/python-gitlab#2249]
## Description of the problem, including code/CLI snippet

```python

>>> type(project)
<class 'gitlab.v4.objects.projects.Project'>

>>> project.default_branch
'main'

>>> project.branches.list(all=True)
[]

>>> project.branches.get('main')
Traceback (most recent call last):
  File "/opt/conda/envs/gitlab-tools/lib/python3.7/site-packages/gitlab/exceptions.py", line 325, in wrapped_f
    return f(*args, **kwargs)
  File "/opt/conda/envs/gitlab-tools/lib/python3.7/site-packages/gitlab/mixins.py", line 122, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/opt/conda/envs/gitlab-tools/lib/python3.7/site-packages/gitlab/client.py", line 833, in http_get
    "get", path, query_data=query_data, streamed=streamed, **kwargs
  File "/opt/conda/envs/gitlab-tools/lib/python3.7/site-packages/gitlab/client.py", line 801, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 404: 404 Branch Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/conda/envs/gitlab-tools/lib/python3.7/site-packages/gitlab/v4/objects/branches.py", line 28, in get
    return cast(ProjectBranch, super().get(id=id, lazy=lazy, **kwargs))
  File "/opt/conda/envs/gitlab-tools/lib/python3.7/site-packages/gitlab/exceptions.py", line 327, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Branch Not Found

```

## Expected Behavior

The default_branch name is among the branches

## Actual Behavior

See above

## Specifications

  - python-gitlab version: 3.8.1
  - API version you are using (v3/v4): v4 ?
  - Gitlab server version (or gitlab.com):  gitlab.com

```
$ poetry show python-gitlab
name         : python-gitlab
version      : 3.8.1
description  : Interact with GitLab API

dependencies
 - argcomplete >=1.10.0,<3
 - PyYaml >=5.2
 - requests >=2.25.0
 - requests-toolbelt >=0.9.1
```

**Comment by JohnVillalovos** [comment]
It makes me think the project has no branches from what I see. Which is weird unless the project was created but doesn't yet have any content.

In the WebUI do you see any branches listed?

**Comment by dazza-codes** [comment]
Exactly, it appears that this is a bare repository.  In this case, the behavior could be correct.

Somehow it has a `project.default_branch != None` (ie. `main`), which does not exist (yet).  This could be a conceptual error on my part, about how the system works.  I suppose the desired behavior for the API response might be `project.default_branch == None` whenever there is no default branch that exists, but that behavior could conflict with other use cases that require a default name for a default branch, whether it exists or not, in order to be able to create it.  Similar considerations might apply to whether or not `project.default_branch` is just a string (name) or a branch object (possibly with an object attribute to indicate whether it exists or not, and that opens pandora's box about orphaned branches etc.).

**Comment by JohnVillalovos** [comment]
We (python-gitlab) try to only return back what GitLab gives us. And that is intentional, we only want to be a relatively thin wrapper around the API.

If you feel that they (GitLab) should return `None` in this case you might want to search and/or file an issue at GitLab about it.

If the goal is to determine if it is a bare-repository then maybe if listing the branches returns an empty list then that might be a good check.
