### ISSUE TITLE
Upload attachement to Wiki

### ISSUE THREAD

**Issue by lhausermann** [python-gitlab/python-gitlab#2258]
## Description of the problem, including code/CLI snippet

Gitlab API support to attach a file to a wiki page which is nice for bot generating wiki page such as dashboard.
See : https://docs.gitlab.com/ee/api/wikis.html#upload-an-attachment-to-the-wiki-repository

## Expected Behavior

Something like `proj.wikis.upload(id,file,branch)` would be ideal

## Actual Behavior

The API is not reflected in python-gitlab

_If I am missing something, tell me, but I havent found that API call_

**Comment by nejch** [comment]
Thanks for the report @lhausermann. You're right this needs to be implemented still. We can probably reuse the project upload and make an `UploadMixin` or so.

**Comment by nejch** [comment]
In the meantime you can make use of the raw `http_post()` methods as a workaround.

**Comment by lhausermann** [comment]
You mean, there is a way to reuse the HTTP REST session from the Gitlab object directly ? (and so don't bother to reimplement everything using requests module)

**Comment by nejch** [comment]
Exactly - we'll soon have this documented a bit better on RTD but you can already take a peek at https://github.com/python-gitlab/python-gitlab/pull/2230/files.

**Comment by lhausermann** [comment]
Thanks for the support. It works well

Below the code snippet I used. You can add it to the doc for `http_post` !

```python
filename = "myfile.png"
with open(filename,"rb") as f:
        filedata = f.read()
   url = "/projects/%d/wikis/attachments"%prj_id 
    file_info = {"file": (filename, filedata)}
    ans = gl.http_post(url, files=file_info)

    if 'link' in ans and 'markdown' in ans['link']:
        daily = daily + "\n" + ans['link']['markdown']
```

**Comment by Lhenzo** [comment]
Hello! Up, very interesting feature if anyone has time for this :)

**Comment by TigreModerata** [comment]
Hi, I could give this a shot, if it's still open. I've taken a look, it seems there are other places one could use an UploadMixin, e.g. group wikis, maybe more (I'm still going through the gitlab docs)...

**Comment by nejch** [comment]
Done with https://github.com/python-gitlab/python-gitlab/pull/2722.

**Comment by lhausermann** [comment]
Thanks!
