### ISSUE TITLE
CL lint on a .gitlab-ci.yml file for a new branch

### ISSUE THREAD

**Issue by dazza-codes** [python-gitlab/python-gitlab#2259]
## Description of the problem, including code/CLI snippet

https://python-gitlab.readthedocs.io/en/stable/gl_objects/ci_lint.html does not have any examples of how to use a non-default branch to validate a `.gitlab-ci.yml` file - is this possible?

## Expected Behavior

For example, lint a `.gitlab-ci.yml` file for a branch in a new MR

```python
lint_result = project.ci_lint.get(branch="feature/gitlab-ci-updates")
```

## Actual Behavior

```python
# does this only allow a default branch (by default)?
lint_result = project.ci_lint.get()
```

## Specifications

  - python-gitlab version: latest
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
See https://docs.gitlab.com/ee/api/lint.html#validate-a-projects-ci-configuration for the docs.

Most likely need to use the `ref`  argument.

**Comment by dazza-codes** [comment]
Does everything in python-gitlab for CI lint send data to a gitlab server, or is there a lint engine in the python package that operates locally?

**Comment by JohnVillalovos** [comment]
> Does everything in python-gitlab for CI lint send data to a gitlab server, or is there a lint engine in the python package that operates locally?

python-gitlab goal is to be a wrapper around the GitLab API. So it basically does almost nothing locally.
