### ISSUE TITLE
When use api to close a mr. two push web hook events triggered!!

### ISSUE THREAD

**Issue by YanceyWang** [python-gitlab/python-gitlab#226]
When i use api to close a mr.
My push events webhook triggered two posts. one action type is  'close' and another is 'update' why?

**Comment by gpocentek** [comment]
I am not sure if this is a gitlab or python-gitlab issue, but python-gitlab for API v4 (in master) is doing a better job at doing only what's necessary.

Could you try again with master/API v4, if your server uses Gitlab >= 9.0?

Thanks

**Comment by gpocentek** [comment]
@YanceyWang closing this issue since I didn't get a reply, feel free to reopen if the problem still happens.
