### ISSUE TITLE
Deprecation warning due to requests-toolbelt dependency

### ISSUE THREAD

**Issue by robsan00** [python-gitlab/python-gitlab#2263]
## Description of the problem, including code/CLI snippet
(I thought it is not a bad idea to open a ticket here as this is a pretty active project while requests-toolbelt is everything but, i.e. it is not impossible that requests will kick out the deprecated module before requests-toolbelt will update, i.e. this project might become unusable.)
If you use python-gitlab with the latest urllib3 version (and pyopenSSL and cryptography installed), you get a deprecation warning.

Virtualenv:
```
(gitlab_req) C:\work\dev\venv>pip freeze
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==37.0.4
idna==3.3
pycparser==2.21
pyOpenSSL==22.0.0
python-gitlab==3.9.0
requests==2.28.1
requests-toolbelt==0.9.1
urllib3==1.26.12
```

Weirdly, the warning seems to be swallowed somewhere along the way, but if I try to use gitlab within pytest for example, I get the message. Consider the following dummy test:
```
import gitlab

def test_hugo():
    pass
```
Executing this test results in the warning:
```
(gitlab_req) C:\work>pytest test.py -v -s
================================================= test session starts =================================================
platform win32 -- Python 3.8.8, pytest-7.1.2, pluggy-1.0.0 -- c:\work\dev\venv\gitlab_req\scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\work
collecting ... 1
collected 1 item

test.py::test_hugo PASSED

================================================== warnings summary ===================================================
dev\venv\gitlab_req\lib\site-packages\requests_toolbelt\_compat.py:56
  c:\work\dev\venv\gitlab_req\lib\site-packages\requests_toolbelt\_compat.py:56: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
    from requests.packages.urllib3.contrib.pyopenssl \

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================ 1 passed, 1 warning in 0.20s =============================================
```

Here the related issue at requests-toolbelt:
https://github.com/requests/toolbelt/issues/331

## Expected Behavior

no deprecation warning shown

## Actual Behavior

deprecation warning shown

## Specifications

  - python-gitlab version: 3.9.0
  - API version you are using (v3/v4): not relevant
  - Gitlab server version (or gitlab.com): not relevant

**Comment by nejch** [comment]
Thanks for the report! I see the last PR merged was in August 2021 so I don't expect this to change on the requests-toolbelt side any time soon.

However I wonder if there's something we should do on our side at the moment, or if that's just pytest behavior exposing warnings following the advice in https://peps.python.org/pep-0565/#recommended-filter-settings-for-test-runners.

For now, I think you can follow https://docs.pytest.org/en/latest/how-to/capture-warnings.html#deprecationwarning-and-pendingdeprecationwarning, perhaps with a specific regex if needed. For us I think the best option might be to wait and bump the minimum toolbelt version eventually? Not sure if suppressing on our side will help, but we can take another look.

**Comment by robsan00** [comment]
Ignoring the error in the pytest.ini is actually what I did on our side, but thanks anyway for the hint. ;-)

**Comment by nejch** [comment]
@robsan00 toolbelt 0.10.1 was released which fixes this it seems, maybe we can bump on our side.

**Comment by robsan00** [comment]
Looking at the toolbelt changelog, there should be nothing preventing that, yes. On my side, I have removed the suppression of the warning in the pytest.ini file and pinned toolbelt to >= 0.10.1.
