### ISSUE TITLE
Add application statistics

### ISSUE THREAD

**Issue by gbonnefille** [python-gitlab/python-gitlab#2264]
## Description of the problem, including code/CLI snippet

The Gitlab provides some general statistics via `/application/statistics`.
See https://docs.gitlab.com/ee/api/statistics.html

## Expected Behavior

These data are available via `gitlab.statistics()`.

## Actual Behavior

Nothing.

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by Shreya-7** [comment]
@JohnVillalovos is this issue up for grabs? I see the `help wanted` label but I'm not sure if we're missing any details?

**Comment by JohnVillalovos** [comment]
> @JohnVillalovos is this issue up for grabs? I see the `help wanted` label but I'm not sure if we're missing any details?

Feel free to work on it. If you are able to assign it to yourself. If you can't do that reply here and we can assign it to you.

**Comment by nejch** [comment]
@JohnVillalovos I assigned @Shreya-7  as I think only we can (https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)

You can take a look at https://github.com/python-gitlab/python-gitlab/blob/main/gitlab/v4/objects/appearance.py for something similar :)
