### ISSUE TITLE
Add support for API Endpoint for SAML Group Sync

### ISSUE THREAD

**Issue by Jerez007** [python-gitlab/python-gitlab#2270]
## Description of the problem, including code/CLI snippet
GitLab added the API Endpoint for SAML Group Sync in 15.3. Please add support for this new API endpoint.

## Expected Behavior
Supports SAML Group Sync

## Actual Behavior
Not yet supported

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by raykarim93** [comment]
please add support for this.

**Comment by JohnVillalovos** [comment]
@Jerez007 A link to the API endpoint would be useful for anyone who wants to work on this.

**Comment by gokeefe** [comment]
[GET /groups/:id/saml_group_links](https://docs.gitlab.com/ee/api/groups.html#saml-group-links)

**Comment by Jerez007** [comment]
Sorry for the late reply. Thanks to @gokeefe for posting the endpoint! 

https://docs.gitlab.com/ee/api/groups.html#add-saml-group-link
