### ISSUE TITLE
project.commits.list(get_all=True, all=True) only lists commits from default branch

### ISSUE THREAD

**Issue by rhowell7** [python-gitlab/python-gitlab#2277]
## Description of the problem, including code/CLI snippet
According to [the docs](https://python-gitlab.readthedocs.io/en/stable/gl_objects/commits.html), `project.commits.list(get_all=True, all=True)` should list all commits from all branches, but it only lists commits from the default branch.

Here is a snippet showing that there are 36 commits in `main` and 25 commits in `deploy-locally`, but `project.commits.list(get_all=True, all=True)` only lists the 36 commits from `main`:
```
ipdb> len(project.commits.list(ref_name='main'))                                                                                                                                          
36
ipdb> len(project.commits.list(ref_name='deploy-locally'))                                                                                                                                
25
ipdb> len(project.commits.list(get_all=True, all=True))                                                                                                                                   
36
```

## Expected Behavior
`project.commits.list(get_all=True, all=True)` should list all commits from all branches.

## Actual Behavior
`project.commits.list(get_all=True, all=True)` only lists commits from the default branch.

## Specifications

  - python-gitlab version: 1.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
1.15.0 is an extremely old version where this was not supported. You'll need to upgrade to the latest version, i recommend you use pip in case you installed it with a different method.
