### ISSUE TITLE
Support for GitLab API v4

### ISSUE THREAD

**Issue by GhostLyrics** [python-gitlab/python-gitlab#228]
https://about.gitlab.com/2017/02/22/gitlab-8-17-released/

This blog post announces the fourth version of the API to be introduced as of March 22nd, GitLab 9.0 and the v3 to be removed with 9.3 (that's about three months).

**Comment by artbycrunk** [comment]
the changes between v3 to v4 can be found here
https://docs.gitlab.com/ce/api/v3_to_v4.html
this is a good guideline to decompose the work required to support API v4.

**Comment by gpocentek** [comment]
Definitely something to implement, thank you for the reminder and the info.

**Comment by GhostLyrics** [comment]
There's an update in the latest blog post. 

>We will continue to support v3 of the API until **August 2017** and so we encourage you to make any necessary changes to applications that use the v3 API.

**Comment by albfan** [comment]
@gpocentek We are using this to migrate bugzilla issues from GNOME to gitlab. But Our instance is on v4

If you need help we can join efforts.

https://gitlab.com/aruiz/gitlab-gnome-tools/issues/4

**Comment by gpocentek** [comment]
@albfan v4 support is a WIP on my side.

V3 is still available on gitlab.com and gitlab community edition AFAIK. If you really need v4 quickly you can try this trick with python-gitlab:

`````python
gl = gitlab.Gitlab(...)
gl._url = 'https://gitlab.gnome.org/api/v4'
`````

Most of the API calls are identical so this should work, although I can't guaranty it.

**Comment by albfan** [comment]
Oh great! We can start from that. Let me try. We can provide patches. 

Any wip branch avaliable? (We expect dragons there so don't mind to publish if you rebase, squash or whatever)

**Comment by gpocentek** [comment]
No WIP branch yet, but I'll be sure to push something somewhat testable ASAP :)
Thanks!

**Comment by albfan** [comment]
It mostly works.

Just need a few hint. with v4 it can only resolve project by id, not by userspace/project name

># Get a project by ID
>project = gl.projects.get(10)
># Get a project by userspace/name
>project = gl.projects.get('myteam/myproject')

makes sense? I dig into BaseManager to understand the get call but didn't find where it translates userspace/project name to project id, or whatever black magic it does inside

**Comment by gpocentek** [comment]
Resolving by name works for me (python 2.7, gitlab 9.1.2, python-gitlab master):
`````python
>>> import gitlab
>>> gl = gitlab.Gitlab.from_config('ol')
>>> gl._url = 'https://gitlab.objectif-libre.com/api/v4'
>>> gl.projects.get('openstack/playbook')
<Project id:152>
`````

There's no translation in the code involved, the API supports both integers and strings.

You can try the search method (``gl.projects.search()``).

**Comment by albfan** [comment]
If this adds noise I can delete comments and open another issue:

Really don't know what's happening:

$ bz2gl --target gitlab --token blablabla --product gnome-todo --bz-user albertofanjul@gmail.com --bz-password blablabla --target-product alberto/gnome-todo
Connecting to https://gitlab.gnome.org/
Traceback (most recent call last):
  File "/home/alberto/bin/bz2gl", line 182, in <module>
    main()
  File "/home/alberto/bin/bz2gl", line 164, in main
    target.connect()
  File "/home/alberto/bin/bz2gl", line 50, in connect
    self.id = self.gl.projects.get(self.target_product).id
  File "/usr/local/lib/python2.7/dist-packages/gitlab/objects.py", line 104, in get
    return self.obj_cls.get(self.gitlab, id, **args)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/objects.py", line 279, in get
    return cls(gl, id, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/objects.py", line 388, in __init__
    data = self.gitlab.get(self.__class__, data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 437, in get
    raise_error_from_response(r, GitlabGetError)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/exceptions.py", line 188, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabGetError: 404: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/v4/projects/alberto/gnome-todo was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at gitlab.gnome.org Port 443</address>
</body></html>

After check the project id (9) this works:

$ bz2gl --target gitlab --token blablabla --product gnome-todo --bz-user albertofanjul@gmail.com --bz-password blablabla --target-product 9

https://gitlab.gnome.org/albfan/gnome-todo/issues

**Comment by comel** [comment]
@albfan You are using Apache, make sure you have `AllowEncodedSlashes NoDecode` in the configuration.

https://github.com/gitlabhq/gitlab-recipes/blob/master/web-server/apache/gitlab-apache22.conf#L20

**Comment by albfan** [comment]
@comel that makes sense, I send to sysadmin

**Comment by gpocentek** [comment]
FYI I've pushed https://github.com/python-gitlab/python-gitlab/tree/v4_support which sets up some required changes for v4 support. At the moment it works for the API calls that haven't changed since v3 (a big part of the API is compatible).

I'll push updates in the coming days to implement the v4 specific APIs.

**Comment by albfan** [comment]
Great. We use you module succesfully with the _url trick anyway. If is there any big task to do please write it down and we can help

**Comment by gpocentek** [comment]
@albfan Good to know it's working for you. There's no really big task to tackle, the v4 branch "just" need some testing and probably some fixes. Bug reports are very welcome at this point :)

Thanks for your feedback.

**Comment by k1-hedayati** [comment]
Waiting for v4 support :pray:

**Comment by gpocentek** [comment]
@k1-hedayati  v4 support is already available in 0.21.1, although I consider it still experimental. See http://python-gitlab.readthedocs.io/en/stable/api-usage.html

**Comment by gpocentek** [comment]
FYI I've been working on some important changes in the python-gitlab API for v4 support. The new API is mostly compatible with the "old" one, but I had to break a few things (hopefully to get a smarter and more maintainable software).

If you're interested in testing these changes, please have a look at the doc: https://github.com/python-gitlab/python-gitlab/blob/rework_api/docs/switching-to-v4.rst. Feedback will be greatly appreciated, please comment on issue #274.

Thanks!

**Comment by k1-hedayati** [comment]
@gpocentek I'm gonna use some of API calls for my application, If I encounter bugs I'll report them to that issue

**Comment by gpocentek** [comment]
Better support for v4 has been added to the master branch. This implies a few changes in the API, tests and bug reports are welcome (please open new issues to make tracking easier).
