### ISSUE TITLE
extending create MR cli options

### ISSUE THREAD

**Issue by ramarro123** [python-gitlab/python-gitlab#2281]
standing to doc located here
https://docs.gitlab.com/ee/api/merge_requests.html#create-mr

there are some parameter that aren't mapped on gitlab-cli

a (not compensive) list of what i found will be helpful is

allow_collaboration | boolean | No | Allow commits from members who can merge to the target branch.
approvals_before_merge | integer | No | Number of approvals required before this can be merged (see below).
assignee_id | integer | No | Assignee user ID.
assignee_ids | integer array | No | The ID of the users to assign the MR to. Set to 0 or provide an empty value to unassign all assignees.

any plan to support them?

**Comment by JohnVillalovos** [comment]
Happy to accept a PR on this if you have time. Otherwise will have to wait for someone to have some time to do this.
