### ISSUE TITLE
Support for GitLab's access_raw_diffs parameter when getting a MR

### ISSUE THREAD

**Issue by BancarelValentin** [python-gitlab/python-gitlab#2282]
When getting a merge request, the diffs are limited to the same limitation sthe UI has. To overcome this the API supports a parameter to retrieve those from the Gitaly server; it's described [here](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr-changes).

I found nothing in the doc mentioning this so I assume it is not present; is there any way to add support for this ?

**Comment by JohnVillalovos** [comment]
You probably can do do:
```
mr.changes(access_raw_diffs=True)
```

**Comment by nejch** [comment]
See @JohnVillalovos's  answer above. Most methods making `GET` requests accept arbitrary API attributes so just follow the API docs there.

But we've added a PR to make this available in the CLI as well now, in case you use it.
