### ISSUE TITLE
Misleading documentation: `mr_id` instead of `mr_iid`

### ISSUE THREAD

**Issue by stdedos** [python-gitlab/python-gitlab#2295]
## Description of the problem, including code/CLI snippet

https://github.com/python-gitlab/python-gitlab/blob/88693ff2d6f4eecf3c79d017df52738886e2d636/docs/gl_objects/merge_requests.rst?plain=1#L93-L119

"Most probably", here the author meant `mr_iid` and **not** `mr_id` (i.e. the project-agnostic ID).

If those are the only two instances, I'd open an MR to fix them now - but I'm thinking whether this a more widespread issue that I wouldn't know how to fix 😕 

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
Thanks @stdedos - I think this is just a poorly named variable in the examples, and it's fine to just fix it in the docs. Would be great if you open a PR for the fix!

It's possible we have something similar in `issues.rst`, but even this little fix would do.

**Comment by stdedos** [comment]
There you go ^^ 😄
