### ISSUE TITLE
Gitlab("http://mysite.com:1234", access_token) still connect to port 80 but not 1234

### ISSUE THREAD

**Issue by ruanjianhui** [python-gitlab/python-gitlab#2327]
## Description of the problem, including code/CLI snippet
gl = gitlab.Gitlab("http://mysite.com:1234", access_token) #still connect to port 80 but not 1234

## Expected Behavior
I need it connect to the port 1234 of mysite.com

## Actual Behavior
It connects to 80 port of mysite.com

## Specifications

  - python-gitlab version: 3.10
  - API version you are using (v3/v4): v3
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
@ruanjianhui I cannot reproduce this. The following will attempt to connect to port 1234:

```python
>>> import gitlab
>>> gl = gitlab.Gitlab("http://gitlab.example.com:1234")
>>> gl.enable_debug()
>>> gl.auth()
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): gitlab.example.com:1234
```

Please add `gl.enable_debug()` and paste some minimal logs here (redact your token first). But this should work, IMO.

**Comment by ruanjianhui** [comment]
> 

Very helpful debug info!
This is my private gitlab, I config the wrong port in server!
Thank you!
