### ISSUE TITLE
Documentation is incorrect for variable to disable pagination

### ISSUE THREAD

**Issue by securitybryan** [python-gitlab/python-gitlab#2329]
## Description of the problem, including code/CLI snippet

The [documentation](https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html) for disabling pagination appears to be incorrect.  The example for projects is: 

`projects = gl.projects.list(get_all=True)`

however the variable should be "all=True"

`projects = gl.projects.list(all=True)`

## Expected Behavior

Return the complete result set

## Actual Behavior

`get_all=True` returns the default number of entries (20).

## Specifications

  - python-gitlab version: 3.6.9
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  gitlab.com

**Comment by nejch** [comment]
@securitybryan the stable docs are currently at python-gitlab v3.10.0, where this is definitely accurate.

3.6.9 is not a valid python-gitlab version, so maybe you were thinking 3.6.0. Docs for those do state `all=True` as you describe above:
https://python-gitlab.readthedocs.io/en/v3.6.0

But I recommend upgrading to the latest stable version.

**Comment by securitybryan** [comment]
Apologies for getting the version incorrect.  I am looking at the docs for v3.10.0 and the syntax in the [examples ](https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#examples)is `get_all=True`.

**Comment by nejch** [comment]
@securitybryan - I'm guessing you're using an old version of python-gitlab, before `get_all=True` was added. Make sure you have the latest version. Or alternatively if you cannot upgrade, find the version and look for the docs that are applicable to your version (e.g. with `gitlab --version` or in python with `import gitlab; gitlab.__version__`).

**Comment by securitybryan** [comment]
OK.  Thanks.  What I hear you saying is that `get_all=True` _is_ the correct syntax and my version must be older.

**Comment by nejch** [comment]
Exactly :)
