### ISSUE TITLE
Unable to run functional tests using `podman`

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#2330]
No longer able to run the functional tests using `podman` based systems such as Fedora and RHEL 8 (and clones).

**Comment by lmilbaum** [comment]
Hey @JohnVillalovos, Is that something I can help with? For what it worth, I am a Red Hatter.

**Comment by JohnVillalovos** [comment]
Sure! If you want to work on it that would be great 👍

**Comment by lmilbaum** [comment]
Cool. Feel free to re-assign it to me. BTW, does it make sense to add run the functional tests on a Fedora based system in CI?

**Comment by JohnVillalovos** [comment]
> Cool. Feel free to re-assign it to me. BTW, does it make sense to add run the functional tests on a Fedora based system in CI?

I'm not sure about that. Maybe @nejch has thoughts?

**Comment by nejch** [comment]
> > Cool. Feel free to re-assign it to me. BTW, does it make sense to add run the functional tests on a Fedora based system in CI?
> 
> I'm not sure about that. Maybe @nejch has thoughts?

Ah, this might be overlapping with #2331 now that I started that PR, so feel free to chime in there as well.

For simplicity's sake we've just been using the Actions runners and these happen to come with ubuntu (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). I think it might be overkill to do multiple distros here, but if there's something simple I'm open as well. On GitLab we would just be using `services:` and wouldn't have this discussion :grin:

**Comment by lmilbaum** [comment]
Yeah. Gitlab.com has runners which provide dind capabilities. I am checking if Github.com has a similar capability.

**Comment by lmilbaum** [comment]
> Yeah. Gitlab.com has runners which provide dind capabilities. I am checking if Github.com has a similar capability.

Apparently, Github.com hosted runners infra is based on VMs (Gitlab.com shared runners infra is based on containers). With that, CI can spin containers based on the desired set of Linux distros.
