### ISSUE TITLE
`author` and `assignee` dicts are missing for some merge requests

### ISSUE THREAD

**Issue by neocorp** [python-gitlab/python-gitlab#2344]
## Description of the problem, including code/CLI snippet

It's expected to have same attributes for every merge request. Although all the fields are set, author or assignee information on some merge requests cannot be retrieved. Inspecting the network XHR shows that this is returned by the API used at the Gitlab UI.

**To reproduce:**

get a project with potentially dozens of merged merge requests with various different authors
`project = self.client.projects.get(id=project_id)`
get the merged merge requests between some dates
```
merge_requests = project.mergerequests.list(state="merged",
                                                        updated_after=from_date,
                                                        updated_before=to_date,
                                                        order_by="updated_at")
```

## Expected Behavior
All merge requests should return `author` and `assignee` information.

## Actual Behavior
Some merge requests are missing `author` and `assignee` information.

## Specifications

  - python-gitlab version: 3.10.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): [15.4.1-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v15.4.1-ee)

**Comment by JohnVillalovos** [comment]
My initial feeling is that I doubt this is a python-gitlab issue. As python-gitlab is a relatively thin layer around the GitLab API and should just put the values it receives from GitLab into the object. But of course not out of the realm of possibility that it is an issue with python-gitlab.

To help debug you can do this:

```
gl = gitlab.Gitlab(... your options here ...)
gl.enable_debug()

# Do the rest of your processing here.
```

This should allow you to see what GitLab is returning from the API call.

**Comment by neocorp** [comment]
thank you for tip @JohnVillalovos ! That helped a lot and I've realised that weirdly enough, with the same permissions and credentials (nothing changed at all), I can get all the merge requests now.
For the time being, I think it's safe to close this as I no longer can reproduce it.
