### ISSUE TITLE
Add `/projects/:id/pipeline_schedules/:pipeline_schedule_id/pipelines`

### ISSUE THREAD

**Issue by rossburton** [python-gitlab/python-gitlab#2354]
The `/projects/:id/pipeline_schedules/:pipeline_schedule_id/pipelines` endpoint to get all pipelines triggered by a schedule ([REST reference](https://docs.gitlab.com/ee/api/pipeline_schedules.html#get-all-pipelines-triggered-by-a-pipeline-schedule
)) doesn't appear to be mapped.

**Comment by nejch** [comment]
Thanks for the report @rossburton. We already have a community contribution in progress for this by @svermeulen in https://github.com/python-gitlab/python-gitlab/pull/2342.

**Comment by nejch** [comment]
Done in https://github.com/python-gitlab/python-gitlab/pull/2342.
