### ISSUE TITLE
Expose call to change the default MR target project on the CLI

### ISSUE THREAD

**Issue by romain-dartigues** [python-gitlab/python-gitlab#2360]
## Description of the problem, including code/CLI snippet

Since [GitLab 13.11](https://gitlab.com/gitlab-org/gitlab/-/blob/v13.11.0-ee/doc/user/project/merge_requests/creating_merge_requests.md#new-merge-request-from-a-fork) it is possible to change the default target project for a merge request in a non-private forked project ([#58093](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/58093)) and documented in [v14.7](https://gitlab.com/gitlab-org/gitlab/-/blob/v14.7.0-ee/doc/api/projects.md#get-single-project) (look for `mr_default_target_self`).

I have not been able to find a way to do it with the CLI; but it works fine with:

```python
project = gl.projects.get(project_id)
project.mr_default_target_self = True
project.save()
```

## Expected Behavior

Be able to use the CLI to set the target; i.e.: `gitlab project update --merge-requests-default-target <self | upstream>` or `gitlab project update --merge-requests-default-target-self <true | false>`.

## Actual Behavior

Not available?

## Specifications

  - python-gitlab version: 3.11.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.10.5-ee and GitLab.com

**Comment by nejch** [comment]
Hey @romain-dartigues thanks for the report!

Currently, we don't accept arbitrary CLI arguments so we have to explicitly define them in code. It just needs to be added here:

https://github.com/python-gitlab/python-gitlab/blob/892281e35e3d81c9e43ff6a974f920daa83ea8b2/gitlab/v4/objects/projects.py#L704-L773

Would you be interested in opening a small PR for this? :)
