### ISSUE TITLE
group.pushrules.get() should return None not 404.

### ISSUE THREAD

**Issue by dreaquil** [python-gitlab/python-gitlab#2368]
## Description of the problem, including code/CLI snippet

According to the documentation, if pushrules are missing from a group, the function `group.pushrules.get()` should return None. 
## Expected Behavior

According to the documentation, if pushrules are missing from a group, the function `group.pushrules.get()` should return None. 
## Actual Behavior

It is raising the following error: 

`gitlab.exceptions.GitlabHttpError: 404: 404 Not Found`
## Specifications

  - python-gitlab version: 3.11.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
Thanks for the report. I have submitted a documentation update for this.
