### ISSUE TITLE
create group return 403

### ISSUE THREAD

**Issue by ayunwSky** [python-gitlab/python-gitlab#2372]
## Description of the problem, including code/CLI snippet
```python
git_url = "http://aa.bb.com/"
git_private_token = "xxxxxxxxx"
gl = gitlab.Gitlab(git_url, private_token=git_private_token)
group = gl.groups.create({"name": "ayunwSky", "path": "ayunwSky"})
print(group)
```

## Expected Behavior
return 200

## Actual Behavior
return gitlab.exceptions.GitlabHttpError: 403: 403 Forbidden

## Specifications

  - python-gitlab version: 3.11.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): sameersbn/gitlab:14.1.3
  
In gitlab document,i've got this: On GitLab SaaS, you must use the GitLab UI to create groups without a parent group. You cannot use the API to do this.
Is group can not create without parent group by gitlab library?Or only subgroup can be create with gitlab library?

But in this document: https://python-gitlab.readthedocs.io/en/stable/gl_objects/groups.html, it show anyone can use  `gl.groups.create` to create group.
![image](https://user-images.githubusercontent.com/28972707/200987064-526baea2-e387-4aaf-bc9b-d7c111bcde35.png)

**Comment by JohnVillalovos** [comment]
Probably the documentation should be updated with the note from the upstream API.

python-gitlab is just a wrapper around the GitLab API. So anything that applies to the GitLab API will apply to python-gitlab.

Note for doc update: https://docs.gitlab.com/ee/api/groups.html#new-group

**Comment by JohnVillalovos** [comment]
So if this isn't working on a private instance of GitLab, then I would assume it is a permissions issue with the token being used. But I'm not sure.

**Comment by nejch** [comment]
I agree, likely a token permission issue or trying to create a top-level gitlab.com group. But that's probably prominent enough that we should add a little sentence just to avoid new issues like this.

**Comment by ayunwSky** [comment]
@nejch Yes, I'm trying to create a top-level gitlab.com group,not a subgroup.
And I use root user to login my gitlab,use root user to create token and the token permission have all Scopes here:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/28972707/201504917-89bf30cd-ee12-4ff3-809c-f1f069b0ff35.png">
