### ISSUE TITLE
Allow update of protected branches

### ISSUE THREAD

**Issue by hoerup** [python-gitlab/python-gitlab#2390]
In gitlab 15.6 gitlab finally added api support to update protected branch settings, so ProjectProtectedBranch should be updated accordingly

https://gitlab.com/gitlab-org/gitlab/-/issues/20229/

**Comment by nejch** [comment]
Sadly a premium feature and we'll need to add a `http_patch` method for this as well.

**Comment by JohnVillalovos** [comment]
Link to the API docs:

https://docs.gitlab.com/ee/api/protected_branches.html#update-a-protected-branch

**Comment by Hokwang** [comment]
I think free version will have this endpoint. We know gitlab developers, right?
How about provide `.save()` or `.update()` anyway?
