### ISSUE TITLE
Do we need the first PR workflow run approval thing?

### ISSUE THREAD

**Issue by nejch** [python-gitlab/python-gitlab#2394]
I just noticed a few PRs had pending runs and it's a hassle for both contributors and us, takes longer to get PRs in etc. Especially if runners are having issues or flaky functional tests.

It was added by GitHub due to CI abuse for crypto IIRC but we haven't really seen any here and we can re-add if we see it later. 

I think we can remove it. I'll change the setting this week unless anyone here disagrees :)

**Comment by JohnVillalovos** [comment]
Makes sense to me.

**Comment by nejch** [comment]
Thanks for the thumbs-up, changed :grinning: 

Can't remove it completely, but this is a nice compromise:

![image](https://user-images.githubusercontent.com/16777978/203936707-42afb6f2-501f-4de1-9308-e7ce5cc4f4f1.png)
