### ISSUE TITLE
Invite members via mail

### ISSUE THREAD

**Issue by larsklitzke** [python-gitlab/python-gitlab#2405]
## Description of the problem, including code/CLI snippet

Trying to invite new members to a group via e-mail fails because the `user_id` attribute is mandatory. 

The API documentation, however, states that adding members via 

```
POST /groups/:id/invitations
```

using the `email` attribute should be possible if the `user_id` is not available (which is the case for non-existing users). Note, that this was added with  GitLab version 14.10 (according to the documentation).

## Expected Behavior

Sending an invitation to the users via their specified e-mails.

## Actual Behavior

If I try to invite a yet non-existent user via mail to a `group` with 

```python
group.members.create({
            'email': 'some mail address',
            'access_level': some_access_level
        })
```

fails due to the following error:

```python
AttributeError: Missing attributes: user_id
```

Don't know exactly what the problems is, but maybe the definition of  the `_create_attrs`  attribute is the cause of this? The `user_id` is defined as `required_field`. 

```python
class GroupMemberManager(CRUDMixin, RESTManager):
    _path = "/groups/{group_id}/members"
    _obj_cls = GroupMember
    _from_parent_attrs = {"group_id": "id"}
    _create_attrs = RequiredOptional(
        required=("access_level", "user_id"),
        optional=("expires_at", "tasks_to_be_done"),
    )
```

## Specifications

  - python-gitlab version: 3.12.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 15.6.1

**Comment by nejch** [comment]
Hi @larsklitzke! Invitations are a separate endpoint unrelated to the members API. For email invitations see our docs here:

https://python-gitlab.readthedocs.io/en/stable/gl_objects/invitations.html

This should handle the exclusive arguments properly. Let us know/re-open if you still have issues with this.

**Comment by larsklitzke** [comment]
Hi @nejch, thanks for the quick reply and the hint to the invitations endpoints! I will give it a try - but that endpoint  looks promising.
