### ISSUE TITLE
Can not list all gitlab members information?

### ISSUE THREAD

**Issue by ayunwSky** [python-gitlab/python-gitlab#2431]
## Description of the problem, including code/CLI snippet
Can the gitlab library list all members of gitlab instead of all members of a group or project?

I want to get the information of all GitLab member users through the GitLab API, then get the user ID I need, and then assign the user to a group maintainer rights. However, there seems to be no way to get information about all GitLab member users, only by getting information about a group or getting information about a project first.

## Expected Behavior
There is an API that lists information about all gitlab members, including the user_id of the member.  Rather than getting a member of a group or project and getting the user_id, then using the user_id to add that member to another group or another user.  Because this would be a lot of work, he would need to traverse many groups or many projects throughout gitlab to get the required user_id.

Or is there a more convenient way to get the user_id?

## Actual Behavior
There is no library to list all gitlab members info contains user_id.

## Specifications

  - python-gitlab version: 3.11.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.1.3
  - Python version: 3.11.1

Document: https://docs.gitlab.com/14.10/ee/api/members.html#add-a-member-to-a-group-or-project

snapshot:
![image](https://user-images.githubusercontent.com/28972707/208364054-98f788d6-a79c-4de2-a31c-de29da481f62.png)

**Comment by nejch** [comment]
You are most likely confusing the Users API endpoint and the Members API. Members will always be for projects and groups. You need to use the Users API to list them instance-wide, then you can add members based on that.

https://python-gitlab.readthedocs.io/en/stable/gl_objects/users.html
