### ISSUE TITLE
No way to update an attribute

### ISSUE THREAD

**Issue by mdeering24** [python-gitlab/python-gitlab#2432]
Api does not support updating a project's attributes. Below are the is the code I have tried 
```
project: Project = gl.projects.get(namespace)

#project._update_attrs({"builds_access_level": 'disable'})
# project.attributes.update({"builds_access_level": False})
# project.attributes.update({"builds_access_level": 0})
project.attributes.update({"builds_access_level": 'disabled'})
project.save()
```

## Expected Behavior
- `attribute.update()` would update the attribute you select
- `attribute.update()` returns more than `None`. Was I successful? Did I pass in a bad attribute name?

## Actual Behavior
Nothing happens. Nothing is updated.

## Specifications

  - python-gitlab version: 3.12
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 15.6.2-ee

**Comment by nejch** [comment]
Simply edit the Python object attribute. `.attributes` is a dictionary with a copy of the original attributes. 

```python
project: Project = gl.projects.get(namespace)

project.builds_access_level = "disabled"
project.save()
```

If you're not familiar with the docs, you can take a look at https://python-gitlab.readthedocs.io/en/stable/api-usage.html#gitlab-objects.
