### ISSUE TITLE
Create CI/CD variable with "raw=true" parameter raises error, update works

### ISSUE THREAD

**Issue by rabbagliettiandrea** [python-gitlab/python-gitlab#2444]
## Description of the problem, including code/CLI snippet
If you try to create a project or group variables with "raw" parameter set to True it raises error (see below)
```
def set_cicd_variable(project_or_group, key, value, is_file=False, raw=True):
    try:
        project_or_group.variables.create(
            {'key': key, 'value': value},
            variable_type='file' if is_file else 'env_var',
            raw=raw
        )
    except GitlabCreateError:
        project_or_group.variables.update(
            id=key,
            new_data={
                'value': value, 'variable_type': 'file' if is_file else 'env_var', 'raw': raw
            }
        )
```

## Expected Behavior
creation of the CI/CD variable with "raw" parameter set to "true"

## Actual Behavior
CREATE raises:
`The provided content-type 'application/octet-stream' is not supported gitlab python`

UPDATE actually works

## Specifications

  - python-gitlab version: 3.12.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 15.7

**Comment by JohnVillalovos** [comment]
This is a situation where there is a conflict between the `python-gitlab` arguments and what is supported by GitLab's API.

The `raw` parameter means one thing in `python-gitlab` and is not passed through to the GitLab API call.

In this case use the `query_parameters` parameter to pass a dictionary of what you want to pass to GitLab.

See: https://python-gitlab.readthedocs.io/en/main/api-usage.html#managers and search for `query_parameters` to see how to do it.

**Comment by rabbagliettiandrea** [comment]
It works indeed, thank you so much @JohnVillalovos :)

**Comment by JohnVillalovos** [comment]
If that is the case, I (without doing any investigation at all) think that is probably an upstream GitLab issue.
