### ISSUE TITLE
restore() method is not implemented for Group

### ISSUE THREAD

**Issue by mkarthiatgithub** [python-gitlab/python-gitlab#2453]
Reference : https://github.com/python-gitlab/python-gitlab/issues/2070 

## Description of the problem, including code/CLI snippet

https://docs.gitlab.com/ee/api/groups.html#restore-group-marked-for-deletion 
is not available 

## Expected Behavior

group.restore should be available

## Actual Behavior
group restore not available

## Specifications

  - python-gitlab version: 3.12.0
  - API version you are using (v3/v4): v4

**Comment by nejch** [comment]
Done with https://github.com/python-gitlab/python-gitlab/pull/2454, thanks @mkarthiatgithub!
