### ISSUE TITLE
user information in pipeline object

### ISSUE THREAD

**Issue by baturorkun** [python-gitlab/python-gitlab#2461]
hi

I could not find User infirmation in the pipeline object. So I had to get the Jobs list and extract it from the first job item. why?

**Comment by nejch** [comment]
@baturorkun please keep the issue description from the template so we can see what version you use :)

And please post a snippet or we can't really help you.

But most likely you used `project.pipelines.list()` which calls this endpoint - https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines.

That does not return any user information. python-gitlab only has information that the server provides. See this FAQ entry:

https://python-gitlab.readthedocs.io/en/latest/faq.html#attributeerror-when-accessing-object-attributes-retrieved-via-list

**Comment by nejch** [comment]
@baturorkun I think the FAQ and docs should have enough info for you to fix this but please reopen if you have issues still. We need more details to be able to help you.
