### ISSUE TITLE
RFE: support for `allow_force_push` in  ProjectProtectedBranchManager

### ISSUE THREAD

**Issue by nickbroon** [python-gitlab/python-gitlab#2466]
## Description of the problem, including code/CLI snippet

Allow setting the `allow_force_push` boolean attribute when creating protected branches.

Attribute is documented here:
https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches

And is missing from here:
https://github.com/python-gitlab/python-gitlab/blob/main/gitlab/v4/objects/branches.py#L35

## Specifications

  - python-gitlab version: 3.13.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
As a note, this is only an issue for the CLI. Users of the API can pass this parameter in the call.
