### ISSUE TITLE
Renovate doesn't seem to be updating requirements-* files

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#2482]
Last updates from renovate for `requirements-lint.txt` and `requirements-test.txt` are from Oct 2022.

**Comment by JohnVillalovos** [comment]
I don't think this is fixed. Looking in `requirements-test.txt` I see:

  build==0.9.0 but on PyPI it is 0.10.0
  pytest==7.1.3 but on PyPI it is 7.2.1
  PyYaml==5.4.1 but on PyPI it is 6.0

**Comment by JohnVillalovos** [comment]
But now I'm vaguely remembering the job running once a week...  Let's leave this open until we see a PR generated to update things.

**Comment by nejch** [comment]
@JohnVillalovos I think we should be ok once the jobs hit the matching renovate schedule. If you have access take a look at https://app.renovatebot.com/dashboard#github/python-gitlab/python-gitlab/1001322619, specifically the `newVersion` value for each `deps` entry. Let's see on Sunday though :)

**Comment by nejch** [comment]
Looks like at least the update part works: https://github.com/python-gitlab/python-gitlab/pull/2493
