### ISSUE TITLE
Documentation wrong on page for "badges"

### ISSUE THREAD

**Issue by stuff2use** [python-gitlab/python-gitlab#2485]
## Description of the problem, including code/CLI snippet

Documentation seems to be wrong here:
https://python-gitlab.readthedocs.io/en/stable/gl_objects/badges.html#examples
-> "Update a badge"

## Expected Behavior
Update a badge:
badge.image_url = new_image_url
badge.link_url = new_link_url
badge.save()

## Actual Behavior
Update a badge:
badge.image_link = new_link
badge.save()

## Specifications

  - python-gitlab version: documentation issue only
  - API version you are using: documentation issue only
  - Gitlab server version: documentation issue only

**Comment by nejch** [comment]
Nice catch @stuff2use! I think those docs might be so old it might still have attributes from API v3..

If you'd like to open a PR with a fix, the docs are here:  
https://github.com/python-gitlab/python-gitlab/blame/main/docs/gl_objects/badges.rst#L41

The upstream docs are here: 
https://docs.gitlab.com/ee/api/project_badges.html#edit-a-badge-of-a-project

**Comment by Soumya-Kushwaha** [comment]
I'd like to work, please..

**Comment by nejch** [comment]
@Soumya-Kushwaha feel free to open a PR :)
