### ISSUE TITLE
414 Request-URI Too Large when updating snippet

### ISSUE THREAD

**Issue by mathieures** [python-gitlab/python-gitlab#2499]
## Description of the problem, including code/CLI snippet

I have encountered several problems when working on snippets with `python-gitlab` (I think the documentation is out of date), but I believe this one is a bug that should be fixed. I have seen online that this error usually occurs when the data is passed through the URL. Apparently, it’s a matter of using the right request method ([the official Gitlab documentation uses PUT](https://docs.gitlab.com/ee/api/snippets.html#update-snippet)). However, `http_put` is present in the error log.  
Minimal reproducible example:

```python
import gitlab

gl = gitlab.Gitlab(private_token=<token>)
gl.auth()

gl.snippets.update(<snippet_id>, content=" "*10000)
```

## Expected Behavior

The snippet should be updated with the specified content.

## Actual Behavior

An error occurs:
```python
Traceback (most recent call last):
  File "<path_to_venv>\Lib\site-packages\gitlab\exceptions.py", line 337, in wrapped_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "<path_to_venv>\Lib\site-packages\gitlab\mixins.py", line 368, in update
    result = http_method(path, post_data=new_data, files=files, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path_to_venv>\Lib\site-packages\gitlab\client.py", line 1078, in http_put
    result = self.http_request(
             ^^^^^^^^^^^^^^^^^^
  File "<path_to_venv>\Lib\site-packages\gitlab\client.py", line 796, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 414: <html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

## Specifications

  - python-gitlab version: 3.13.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
Hi @mathieures, could you elaborate more on the outdated docs as well, other than the issue you described above? We haven't touched those docs in years I think.

Regarding your error, while your example should work for smaller payloads, I assume the problem is that setting this as a plain argument sends the attribute via query parameters. If you explicitly send it as a payload, it should be fine I think. Most likely this will already do the job:

```python
import gitlab

gl = gitlab.Gitlab(private_token=<token>)
gl.auth()

gl.snippets.update(<snippet_id>, new_data={"content": " "*10000})
```

So maybe we can update our docs to reflect that (PRs welcome as well :)). And potentially we could automate this for `optional` args in the `save()` method so they get converted to payload as well, but need to check this. Although you don't really use the attribute `save()` approach above. 
https://github.com/python-gitlab/python-gitlab/blob/1da7c53fd3476a1ce94025bb15265f674af40e1a/gitlab/mixins.py#L469-L477

**Comment by mathieures** [comment]
Using the code you gave:
> ```python
> gl.snippets.update(<snippet_id>, new_data={"content": " "*10000})
> ```

Raises an exception, saying the content is empty:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path_to_venv>\problem.py", line 11, in <module>
    gl.snippets.update(2315525, new_data={"content": " "*10000})
  File "<path_to_venv>\Lib\site-packages\gitlab\exceptions.py", line 339, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabUpdateError: 400: content is empty
```

I don’t really know how to solve this, as setting the `content` parameter doesn’t seem to work (tried with `" "*10000`, `True` and "aaaa").

---

Regarding the old documentation, here is what I found.

The example given to create a snippet raised an exception in my case. Apparently Gitlab assumes an internal visibility when nothing is specified. Parts of the error are in French, so I don’t know what the exact error would look like on your side though:
```python
Traceback (most recent call last):
  File "<path_to_venv>\Lib\site-packages\gitlab\exceptions.py", line 337, in wrapped_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "<path_to_venv>\Lib\site-packages\gitlab\mixins.py", line 300, in create
    server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path_to_venv>\Lib\site-packages\gitlab\client.py", line 1026, in http_post
    result = self.http_request(
             ^^^^^^^^^^^^^^^^^^
  File "<path_to_venv>\Lib\site-packages\gitlab\client.py", line 796, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 403: {'error': 'Niveau de visibilité interne has been restricted by your GitLab administrator'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path_to_venv>\problem.py", line 13, in <module>
    snippet = gl.snippets.create({'title': 'snippet_name',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path_to_venv>\Lib\site-packages\gitlab\exceptions.py", line 339, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabCreateError: 403: {'error': 'Niveau de visibilité interne has been restricted by your GitLab administrator'}
```

Specifying the `visibility` parameter for a private snippet works though:
```python
snippet = gl.snippets.create({'title': 'snippet_name',
                              'file_name': 'file.txt',
                              'content': "test content"},
                              visibility=gitlab.const.VISIBILITY_PRIVATE)
                              # equivalent to 'visibility=gitlab.const.Visibility.PRIVATE'
```
It works the same way for public snippets.

Somewhat related, the next example code where `visibility_level` is used doesn’t do anything, without any exception being raised:
```python
snippet.visibility_level = gitlab.const.Visibility.PUBLIC
snippet.save()
```
Although using `visibility` instead works:
```python
snippet.visibility = gitlab.const.Visibility.PUBLIC
snippet.save()
```

There is a typo in the example given to edit a snippet:
```python
snippet = gl.snippets.get(snippet_id)
project = gl.projects.get(snippet.projec_id, lazy=True)
                                         ^
```
But correcting it doesn’t solve the problem (at least for me), as through my testing `snippet.project_id` is always `None` anyway. Using `snippet.id` instead gives a `gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found`.

Until some time ago, I had been using a weird hacky workaround where I changed the `snippet.code` attribute to `True` and used `snippet.save(content=new_content)` to save the changes, but it works unreliably.

The solution I had come up with, `gl.snippets.update(snippet.id, content=new_content)` was my way to go after that.

**Comment by nejch** [comment]
Thanks for expanding on the original issue @mathieures! This seems like our docs are super old, probably from the times of GitLab API v3. I'll rework some of this and take a look at the behavior myself.

Also, need to expand our functional tests a little to cover this, https://github.com/python-gitlab/python-gitlab/blob/main/tests/functional/api/test_snippets.py#L4-L23.

I assume it's unreliable for you when the content you're updating is too large and can no longer be passed as query params (and in any case, it probably shouldn't be). I'll

**Comment by mathieures** [comment]
A friend and I came up with a solution!  
First of all, my minimal reproducible example is a bad one. Maybe GitLab considers an all-spaces file illegal, but when testing with a pure `requests.put()` and some random character, we started to have good results.  
Here is the full code to update the content of a snippet with a `request.put()`:
```python
from requests import put
import gitlab


gitlab_token = "<gitlab_token>"
snippet_id = "<snippet_id>"
new_content = "a" * 10000

gl = gitlab.Gitlab(private_token=gitlab_token)
gl.auth()

snippet = gl.snippets.get(snippet_id)

r = put(
    f'https://gitlab.com/api/v4/snippets/{snippet.id}',
    headers={"PRIVATE-TOKEN": gitlab_token},
    json={
        "files": [
            {
                "action": "update",
                "file_path": snippet.file_name,
                "content": new_content
            }
        ]
    },
    timeout=2
)

print(r.json())
```
