### ISSUE TITLE
`project.save` redundantly updates too many properties, causing 403 Forbidden error

### ISSUE THREAD

**Issue by colin-nolan** [python-gitlab/python-gitlab#250]
I am using this library to update a single property of a project:
```python
project = connector.projects.get("my_project")
project.shared_runners_enabled = False
project.save()
```

I would expect the library to do something similar to this (which works fine):
```bash
curl --header "PRIVATE-TOKEN: $TOKEN" --header "CONTENT-TYPE: application/json" --request PUT -d '{"shared_runners_enabled": false}' $URL/v3/projects/388
```

However, I have observed (by looking at what's happening here: https://github.com/gpocentek/python-gitlab/blob/master/gitlab/__init__.py#L565) that it is instead updating everything about the project:
```json
{
    "container_registry_enabled": true,
    "snippets_enabled": false,
    "only_allow_merge_if_build_succeeds": false,
    "merge_requests_enabled": true,
    "wiki_enabled": true,
    "visibility_level": 20,
    "name": "my-project",
    "issues_enabled": true,
    "path": "my-project",
    "description": "",
    "public": true,
    "default_branch": "master",
    "public_builds": true,
    "lfs_enabled": true,
    "request_access_enabled": true,
    "shared_runners_enabled": false,
    "only_allow_merge_if_all_discussions_are_resolved": false,
    "builds_enabled": true
}
```

One of the issues with doing this (I can think of a few more!) is that the account may not have enough privilege to update all of these properties. In my case, for whatever reason, I can't update any of the following:
```json
{
    "name": "my-project",
    "public": true,
    "visibility_level": 20
}
```
If I try, I get a 403 Forbidden error. Therefore, when trying to update the `shared_runners_enabled` property via this library, I also hit this error.

**Comment by gpocentek** [comment]
The ``save()`` method doesn't have the intelligence to detect what has been changed so it sends everything.

Changing this behavior implies changes in how attributes are handled, which is intrusive but necessary.

Thank you for the report, I'll see what I can do.

**Comment by colin-nolan** [comment]
A workaround for the time being is to crudely delete properties that cause problems before calling `save`, e.g.:
```python
project = connector.projects.get("my_project")
del project.name
del project.public
del project.visibility_level
project.shared_runners_enabled = False
project.save()
```

**Comment by gpocentek** [comment]
The v4 API now only sends updated attributes to the server, so this problem should not happen anymore.

The behavior is unchanged for v3 though, and will stay as is.
