### ISSUE TITLE
Client not parsing json response when "; charset=utf-8 " in `Content-Type` header

### ISSUE THREAD

**Issue by gg-mmill** [python-gitlab/python-gitlab#2503]
## Description of the problem, including code/CLI snippet

When performing a graphql query, with `gitlab.client.http_post` , the result is not parsed as json.

I believe this is because the content type we receive is 
```
      Content-Type:
      - application/json; charset=utf-8
```
while the client check for equality with `application/json` in https://github.com/python-gitlab/python-gitlab/blob/main/gitlab/client.py#L1036

## Expected Behavior

The result is parsed as json

## Actual Behavior

The raw response is returned.

## Specifications

  - python-gitlab version: `python-gitlab==3.13.0`
  - API version you are using (v3/v4): graphql api
  - Gitlab server version (or gitlab.com): 14.10

**Comment by nejch** [comment]
Hehe @gg-mmill this must be the first time I see someone use the client for graphql like that ;) See also https://github.com/python-gitlab/python-gitlab/issues/1357 for progress there.

Yes, that seems to be it. We should probably get the content type in a more robust way with something like `email.message.Message.get_content_type()` according to
https://peps.python.org/pep-0594/#cgi at least. Thanks for the report!

But please keep in mind that `http_post` was really meant to be part of the REST client. We'll probably create a separate `gitlab.GraphQL` client I assume at some point.

**Comment by gg-mmill** [comment]
Hello, thanks for the quick reply. We will be monitoring the progress for the graphql client :)
