### ISSUE TITLE
keepalive for cli

### ISSUE THREAD

**Issue by ramarro123** [python-gitlab/python-gitlab#2504]
hello,

using curl to interact with gitlab server, the connection get recycled and reused with keepalive
on output of curl we can see "connection XXX left intact" (normally a few connections)

i am curious, does gitlab cli support the same feature? can i check how it work or can i configure it somehow?

**Comment by nejch** [comment]
@ramarro123: just wanted to clarify the curl behavior first.

It does not actually stay intact after curl exits despite the misleading message, only if it does multiple requests in a single invocation. That is my understanding at least - see the answer here https://stackoverflow.com/a/72045706.

python-gitlab does also have keep-alive per invocation, like curl. So if you're using `gitlab <something> list --get-all` that will make multiple requests for pagination, the session will have keep-alive by default. But if you call the `gitlab` CLI multiple times it will not be reused.

Does that answer your question? I haven't checked how feasible it would be to actually attempt to keep the connection open between multiple invocations though.

**Comment by nejch** [comment]
@ramarro123 just following up to see if that answers your question or what exactly you had in mind.

**Comment by nejch** [comment]
I'll close this and I hope it answers your question.

To recap, yes we have keepalive for the duration of a CLI invocation, but not between separate subprocess calls - same behavior as curl. Please reopen if you have more questions :)
