### ISSUE TITLE
Incorrect value for `blocking_discussions_resolved` in `ProjectMergeRequest`

### ISSUE THREAD

**Issue by LOMS** [python-gitlab/python-gitlab#2505]
## Description of the problem, including code/CLI snippet

I have this simple test, which retrieves MR with iid `596` with `list`, and then with `get`, just to check their attributes.
MR `596` has 15 blocking threads right now.

```python
from gitlab.v4.objects import Project

from constants import gl

p: Project = gl.projects.get(86)

for list_mr in p.mergerequests.list(state="opened"):
    if list_mr.iid != 596:
        continue
    print(f"{list_mr.iid=}")
    print(f"{list_mr.blocking_discussions_resolved=}")
    print(f"{list_mr._created_from_list=}")

print("=" * 40)

get_mr = p.mergerequests.get(596)
print(f"{get_mr.iid=}")
print(f"{get_mr.blocking_discussions_resolved=}")
print(f"{get_mr._created_from_list=}")
```

## Expected Behavior
`ProjectMergeRequest`, "created from list", has correct value for `blocking_discussions_resolved` attribute.

## Actual Behavior
MR, "created from list", has incorrect value for "blocking_discussions_resolved" attribute, while same MR, retrieved with "get", has it correct.

Output for test is:
```text
list_mr.iid=596
list_mr.blocking_discussions_resolved=True
list_mr._created_from_list=True
========================================
get_mr.iid=596
get_mr.blocking_discussions_resolved=False
get_mr._created_from_list=False
```

## Specifications

  - python-gitlab version: 3.13.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): [15.9.2](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v15.9.2)

**Comment by nejch** [comment]
Hey @LOMS, thanks for the report.

It seems to me that the GitLab API simply returns different values for the 2 different endpoints so this should be reported upstream instead. python-gitlab only returns what it gets in the response from the server. 

Just to confirm this, could you see what the results are if you use a plain `curl` call or `requests.get()` to those endpoints? You can use `gl.enable_debug()` to output the exact URLs and then you can try to reproduce it with curl/requests. Thanks!

**Comment by LOMS** [comment]
@nejch You know what, that's probably some kind of cache.
I just added `gl.enable_debug()` to my test script, and everything become predictable - `blocking_discussions_resolved` is `false` for both methods, list and get.
And it didn't reproduce even after I remove "enable_debug()" from script. I hadn't touch anything (nobody did, because it's friday and workday is over).

I'm closing issue for now.
