### ISSUE TITLE
cli: Can't escape initial at (@) in parameter

### ISSUE THREAD

**Issue by pyhedgehog** [python-gitlab/python-gitlab#2511]
## Description
Symbol "`@`" in all parameter values parsed as file reference, and I found no way to override this behaviour.

https://github.com/python-gitlab/python-gitlab/blob/9c2465759386b60a478bd8f43e967182ed97d39d/gitlab/cli.py#L274-L285

## Expected Behavior
```
gitlab project-tag delete --project-id somenamespace/myproject --name '@at-started-tag'
```
Command executed without errors and tag is deleted.

## Actual Behavior
```console
$ gitlab project-tag delete --project-id somenamespace/myproject --name '@at-started-tag'
[Errno 2] No such file or directory: 'at-started-tag'
```

**Comment by JohnVillalovos** [comment]
Yes that does seem like a use-case not considered before. I'm not sure the best way to fix that.

My initial thought would be to be able to do:  `\@at-started-tag` and the code could check for content starting with `\@` and if so return back the value without the backslash.

@nejch Do you have any ideas?

**Comment by pyhedgehog** [comment]
@JohnVillalovos as soon as this is place-specific escape (i.e. it should not be replaced anywhere else except string start) I'd prefer `@@`.

**Comment by nejch** [comment]
A bit late to the party here sorry folks! :) @JohnVillalovos @pyhedgehog I like the idea with an escape character and `\` is more standard. Although `@@` does look a bit more pleasing visually and is consistent with GitLab's double-escaping dollar signs in variables (https://docs.gitlab.com/ee/ci/variables/#use-the--character-in-cicd-variables). So maybe we could go with that.

**Comment by pyhedgehog** [comment]
@nejch It's in line with `$$` in gitlab CICD, docker-compose.yml, and `''` in SQL strings. :-)
If you like this, you can just approve my PR. If you prefer backslash tell me, i'll change my PR.

**Comment by JohnVillalovos** [comment]
I'm perfectly fine with `@@`
