### ISSUE TITLE
ProjectPipelineJob attribute `status` isn't updated to reflect a job's `after_script`

### ISSUE THREAD

**Issue by davedog8** [python-gitlab/python-gitlab#2512]
## Description of the problem, including code/CLI snippet
`gitlab.v4.objects.pipelines.ProjectPipelineJob` attribute `status` isn't updated when code is run in the `after_script` of a job.

## Expected Behavior
Code running in the `after_script` is expected to have a `status` of `success` or `failed` and not `running`, which is reflected in the (equivalent) CI env var `CI_JOB_STATUS`.

## Actual Behavior
The job`.attributes.get(status)` is `running` when run in the `after_script` section.

## Specifications

  - python-gitlab version: v3.13.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 15.9.1

**Comment by JohnVillalovos** [comment]
At first glance this sounds like an issue with upstream GitLab. python-gitlab only returns what GitLab provides.

**Comment by davedog8** [comment]
Is the job's status attribute supposed to match the CI_JOB_STATUS env var? Because the CI_JOB_STATUS env var is correct.

**Comment by JohnVillalovos** [comment]
> Is the job's status attribute supposed to match the CI_JOB_STATUS env var? Because the CI_JOB_STATUS env var is correct.

I'm sorry but I don't know. That sounds like a question for GitLab.

Have you looked at the upstream documentation?

Here is probably a place to start:
https://docs.gitlab.com/ee/api/pipelines.html

**Comment by nejch** [comment]
@davedog8 @JohnVillalovos I'm afraid this is not possible at all with the current GitLab architecture, so definitely an upstream issue.

`CI_JOB_STATUS` as exposed in `after_script` is a gitlab-runner implementation and the GitLab API does not really see that. See the code here:

https://gitlab.com/gitlab-org/gitlab-runner/-/blob/main/common/build.go#L507-518

The API can respond with the appropriate state once the runner reports back to the GitLab instance, I'm not sure if this already happens in `after_script` but you could potentially try with some wait times.

Either way, please open an upstream issue at GitLab as this behavior will happen with any kind of API client :bow:
