### ISSUE TITLE
Documentation bug # Active projects projects = gl.projects.list()

### ISSUE THREAD

**Issue by steve100** [python-gitlab/python-gitlab#252]
Not exactly a bug.. but perhaps others are running into this.
It works, it returns projects.  The Active projects do not equal all projects.

Try as I might - I cannot find what an Active Project is as shown in the examples.
In our system there are no archived projects
And one of the systems that doesn't show 'active' had a push about 6 hours ago.
thanks.
Steve

-----
In page: gl_objects/projects.rst

**Comment by gpocentek** [comment]
Thanks for your report.

Does the user with which you're doing the request have permission to see the missing project?
