### ISSUE TITLE
gitlab project-push-rules get --project-id returns empty output

### ISSUE THREAD

**Issue by w7089** [python-gitlab/python-gitlab#2522]
## Description of the problem, including code/CLI snippet

`gitlab project-push-rules get --project-id [id]` returns empty output while there are push rules set in UI.

## Expected Behavior

`gitlab project-push-rules get --project-id [id]` should return existing push rules or specific ones similar to `gitlab project-push-rules update` behaviour

## Actual Behavior

empty output returned 

## Specifications

  - python-gitlab version: `3.13.0`
  - API version you are using (v3/v4): `v4`
  - Gitlab server version (or gitlab.com): `15.8.1-ee`

**Comment by w7089** [comment]
yes, it worked, if that's the expected behaviour, i'll close it

**Comment by w7089** [comment]
by the way, selecting fields doesn't work as well:

`gitlab -f id project-push-rules get --project-id [id]` shows empty output

**Comment by nejch** [comment]
Sorry, the `--fields` flag doesn't work with the default formatter, you'll need to use json or yaml (`-o json`).

https://python-gitlab.readthedocs.io/en/stable/cli-usage.html#optional-arguments
