### ISSUE TITLE
Need support to [...]/personal_access_tokens/self Gitlab API

### ISSUE THREAD

**Issue by bertrand-benoit** [python-gitlab/python-gitlab#2537]
## Description of the problem, including code/CLI snippet
So far, I'm unable to get scopes information from the 'personal access token' used to authenticate to Gitlab API.
Ofc, it is easy to get the list of the personal access token of the authenticated user, but I see no way to get the link with the one really used to authenticate.

It seems the dedicated Gitlab API entrypoint for that is [...]/personal_access_tokens/self which is not actually supported by python-gitlab.

Context: the idea is to check with efficiency some required scopes/permissions/rights, instead of trying an operation (like download repository tarball) because it could be time consuming although a simple check could be immediate.

## Expected Behavior

Get scopes (and roles ?) information of the 'personal access token' currently used to authenticate to Gitlab API.

## Actual Behavior

Unable to get this information.

## Specifications

  - python-gitlab version: 3.13.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
Hi @bertrand-benoit this is supported by supplying `self` as the ID, so I'd personally say it's not worth implementing a custom method for it. We document it for delete but not get.. sorry about that:

https://python-gitlab.readthedocs.io/en/stable/gl_objects/personal_access_tokens.html?highlight=self#examples

This should do the trick:

```python
token = gl.personal_access_tokens.get("self")
```

Let me know if that works for you.

**Comment by nejch** [comment]
@bertrand-benoit should be available now, https://github.com/python-gitlab/python-gitlab/releases/tag/v3.14.0.

**Comment by bertrand-benoit** [comment]
> The `role` is only relevant during creation of the group/project tokens as far as I know, so not sure it would help you there.

The idea is to check with efficiency some required scopes/permissions/rights and role, instead of trying an operation (like download repository tarball) because it could be time consuming although a simple check could be immediate.

The fact is that even with the good scope on token, if the user needs to have specific role:
 - at least REPORTER role to get access to repository metadata (name, tags, branches ...)
 - at least DEVELOPER role to be able to pull the repository (the read_repository scope is NOT enough here)
 - at least MAINTAINER role to get access to project statistics (to be confirmed)

So, in addition to token scope, I'd like to check user role on specific project; ideally without having to start downloading the thing (to optimize check time).


> How about checking for `if desired_project in gl.projects.list(min_access_level=desired_role)` for project tokens and `if desired_group in gl.groups.list(min_access_level=desired_role)` for group tokens? This should only ever return one single item or none, depending on whether you find a match.

But we would have no guarantee it is the token used to authenticate, right?
