### ISSUE TITLE
Doc example to update or change one setting of a Protected Branch?

### ISSUE THREAD

**Issue by mbanders** [python-gitlab/python-gitlab#2545]
## Description of the problem, including code/CLI snippet

The examples on [this page](https://python-gitlab.readthedocs.io/en/stable/gl_objects/protected_branches.html) show how to create and delete a protected branch.

Is it possible to change one setting of an existing protected branch and update? Can an example be shown?

Or currently do we have to delete a protected branch and re-create it with the new setting?

## Expected Behavior

Example showing how to update an existing protected branch.

## Actual Behavior

No example

## Specifications

  - python-gitlab version: v3.13.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
Hi @mbanders, are you talking about the GitLab Premium feature or updating protected branches on GitLab Free?

If you mean Premium, we already have an issue tracking this, so we can close it as a duplicate: https://github.com/python-gitlab/python-gitlab/issues/2390

If you mean GitLab Free.. unfortunately, there is no PUT request for the REST API on GitLab Free at the moment, so python-gitlab also cannot do this. The way I do it currently:
1. Get a protected branch (to save all the details)
2. Delete (unprotect)  the protected branch
3. Re-create the protected branch with updated settings.

Please upvote this upstream issue if you can though, we need that first if we want it in python-gitlab ;) https://gitlab.com/gitlab-org/gitlab/-/issues/383614

**Comment by mbanders** [comment]
Thanks I will follow https://github.com/python-gitlab/python-gitlab/issues/2390
