### ISSUE TITLE
Support of CRUD Operations for Issue of type 'Task' 

### ISSUE THREAD

**Issue by adrian-gonzalez** [python-gitlab/python-gitlab#2550]
# Description of the problem, including code/CLI snippet

GitLab v15.10.1-ee has the notion of "Tasks" tied to an Issue of type "task". Similar to other resources (Projects, Groups, Issues, Labels, etc.), having support to CRUD "Tasks" is missing.

Requests to support:
- Retrieve issues by type (issue, task, etc.)
- Retrieve an issue of type task by issue_id
- Create an issue of type task providing properties such as status, labels, start_date, due_date, milestone, weight, iteration, description
- Update an issue of type task based on the above properties

# Expected Behavior

# Actual Behavior

# Specifications

python-gitlab version:
API version you are using (v3/v4): v4
Gitlab server version (or gitlab.com): 15.10.0

**Comment by nejch** [comment]
At the moment we cannot do this as GitLab has no REST API for tasks.

https://gitlab.com/gitlab-org/gitlab/-/issues/366197
https://gitlab.com/groups/gitlab-org/-/epics/9673
https://gitlab.com/gitlab-org/gitlab/-/issues/368055

Once GitLab has support for this we can start working on it. But maybe we can keep this open for now?

**Comment by adrian-gonzalez** [comment]
Hi @nejch  that sounds good, and thank you for sharing those links so I can track that progress

**Comment by nejch** [comment]
I'll close this one here as we fully depend on upstream to implement this, but I'm subscribed to https://gitlab.com/gitlab-org/gitlab/-/issues/368055, let's see if they make it any time soon. @adrian-gonzalez feel free to reopen this once or open a new issue if you see it done upstream but missing here in the future. :bow:

**Comment by yakobowski** [comment]
There's been a bit of progress regarding this (AFAIU) in https://gitlab.com/gitlab-org/gitlab/-/merge_requests/126398
