### ISSUE TITLE
gitlab project-label output mismatch

### ISSUE THREAD

**Issue by ramarro123** [python-gitlab/python-gitlab#2555]
hello 

running 

gitlab project-label list a node have
{
  "id": 13176,
  "name": "OriginMR::4782",
  "description": null,
  "description_html": "",
  "text_color": "#FFFFFF",
  "color": "#84462c",
  "subscribed": false,
  "priority": null,
  "is_project_label": true
}

but via api i see

  {
    "id": 7,
    "name": "bug",
    "color": "#FF0000",
    "text_color" : "#FFFFFF",
    "description": null,
    "description_html": null,
    "open_issues_count": 0,
    "closed_issues_count": 0,
    "open_merge_requests_count": 0,
    "subscribed": false
  },

seems there are missing values

**Comment by nejch** [comment]
Hi @ramarro123! Could you please provide a bit more info, e.g. the exact CLI and API calls you make and their responses. Otherwise it's a bit hard to debug here. Feel free to redact any sensitive info.

**Comment by ramarro123** [comment]
you need what command?
if is the command you mean is 

gitlab project-label list
