### ISSUE TITLE
AttributeError: module 'gitlab' has no attribute '__version__'

### ISSUE THREAD

**Issue by weijiang1994** [python-gitlab/python-gitlab#2576]
## Description of the problem, including code/CLI snippet
from gitlab.v4.objects.projects import Project

## Expected Behavior
AttributeError                            Traceback (most recent call last)
<ipython-input-1-ef5dd35fc255> in <module>
----> 1 from gitlab.v4.objects.projects import Project

~/.local/lib/python3.8/site-packages/gitlab/v4/objects/__init__.py in <module>
----> 1 from .access_requests import *
      2 from .appearance import *
      3 from .applications import *
      4 from .artifacts import *
      5 from .audit_events import *

~/.local/lib/python3.8/site-packages/gitlab/v4/objects/access_requests.py in <module>
----> 1 from gitlab.base import RESTManager, RESTObject
      2 from gitlab.mixins import (
      3     AccessRequestMixin,
      4     CreateMixin,
      5     DeleteMixin,

~/.local/lib/python3.8/site-packages/gitlab/base.py in <module>
     11 from gitlab.exceptions import GitlabParsingError
     12 
---> 13 from .client import Gitlab, GitlabList
     14 
     15 __all__ = [

~/.local/lib/python3.8/site-packages/gitlab/client.py in <module>
     24 # https://docs.gitlab.com/ee/api/#offset-based-pagination
     25 _PAGINATION_URL = (
---> 26     f"https://python-gitlab.readthedocs.io/en/v{gitlab.__version__}/"
     27     f"api-usage.html#pagination"
     28 )

AttributeError: module 'gitlab' has no attribute '__version__'

## Specifications

  - python-gitlab version: 3.14.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
@weijiang1994 most likely you have a script named `gitlab.py` or a package/folder named `gitlab` where you execute your script, and this clashes with python-gitlab's namespace. Try to rename that if that's the case.

**Comment by weijiang1994** [comment]
Thank you for your answer. I executed `pip3 uninstall gitlab`, and the issue was solved.

**Comment by weijiang1994** [comment]
I installed python-gitlab inside a Docker container, but encountered this error when executing it in the Python interactive environment.
![image](https://github.com/python-gitlab/python-gitlab/assets/53400477/add51ab4-4cf0-4d6b-8af3-1966761a888f)

**Comment by nejch** [comment]
Most likely you have a folder or module named `gitlab` @weijiang1994. Hard to say without seeing your structure, but please check https://stackoverflow.com/questions/55657036/importerror-cannot-import-name-app-from-mypackage-unknown-location.
