### ISSUE TITLE
Support for the rotate API endpoint (Project Access Token, Personal Access Token, Group Access Token)

### ISSUE THREAD

**Issue by mrLarbi** [python-gitlab/python-gitlab#2589]
## Description of the problem, including code/CLI snippet

Since Gitlab 16.0, Gitlab introduced an API endpoint to rotate tokens. Here are the endpoints :

Project Access Token : https://docs.gitlab.com/ee/api/project_access_tokens.html#rotate-a-project-access-token
Personal Access Token : https://docs.gitlab.com/ee/api/personal_access_tokens.html#rotate-a-personal-access-token
Group Access Token : https://docs.gitlab.com/ee/api/group_access_tokens.html#rotate-a-group-access-token

As of now (Apologies if I am mistaken), it seems that these calls are not supported yet by python-gitlab. It would be great to be able to rotate these tokens using python-gitlab.

## Expected Behavior

The ability to rotate Project Access Tokens, Personal Access Tokens and Group Access Tokens with python-gitlab

## Actual Behavior

None.

## Specifications

  - python-gitlab version: latest
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 16.0 (gitlab.com)

**Comment by nejch** [comment]
Thanks for the report @mrLarbi, this is definitely on my radar as I also want to use it, so will start working on it soon

**Comment by mrLarbi** [comment]
Hello @nejch oh that's nice. Thanks for the info and for the feature
