### ISSUE TITLE
'ProjectFile' object has no attribute 'content'

### ISSUE THREAD

**Issue by mattholy** [python-gitlab/python-gitlab#2594]
## Description of the problem, including code/CLI snippet
```
import os
import gitlab

GITLAB_TOKEN = 'xxx' or os.environ.get('GITLAB_TOKEN')
GITLAB_URL = 'xxx' or os.environ.get('GITLAB_URL')

gl = gitlab.Gitlab(url=GITLAB_URL, private_token=GITLAB_TOKEN)
project = gl.projects.get(1750)

file = project.files.create({
    'file_path': 'test.md',
    'content': '''| header | header |\n| ------ | ------ |\n| cell | cell |\n| cell | cell |''',
    'branch':'master',
    'commit_message':'update'
})

file.decode().decode()
```

## Expected Behavior
Get the file content.

## Actual Behavior
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[183], line 1
----> 1 file.decode().decode()

File ~/.local/lib/python3.10/site-packages/gitlab/v4/objects/files.py:50, in ProjectFile.decode(self)
     44 def decode(self) -> bytes:
     45     """Returns the decoded content of the file.
     46 
     47     Returns:
     48         The decoded content.
     49     """
---> 50     return base64.b64decode(self.content)

File ~/.local/lib/python3.10/site-packages/gitlab/base.py:134, in RESTObject.__getattr__(self, name)
    128 elif self._lazy:
    129     message = f"{message}\n\n" + textwrap.fill(
    130         f"If you tried to access object attributes returned from the server, "
    131         f"note that {self.__class__!r} was created as a `lazy` object and was "
    132         f"not initialized with any data."
    133     )
--> 134 raise AttributeError(message)

AttributeError: 'ProjectFile' object has no attribute 'content'
```

## Specifications

  - python-gitlab version:3.15.0
  - API version you are using (v3/v4):don't know what is this
  - Gitlab server version (or gitlab.com):GitLab Community Edition [14.0.11](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v14.0.11)

**Comment by JohnVillalovos** [comment]
It doesn't look like the GitLab API returns back the content:

https://docs.gitlab.com/ee/api/repository_files.html#create-new-file-in-repository

If you really want to get the content from the file you just created most likely will need to do like this:
https://python-gitlab.readthedocs.io/en/main/gl_objects/projects.html#project-files

**Comment by nejch** [comment]
@mattholy you're calling `file.decode().decode()` after a POST call with `create()`. Does that really make sense as you just created it from local content? Note that the responses between POST and GET calls may be different.

I think what you'd usually be doing is fetch the actual file:

```python
file = project.files.get(file_path="test.md", ref="main")
file.decode().decode()
```

Let me know if that works. Otherwise inspect what the content returned by the content on create is.

**Comment by nejch** [comment]
@mattholy Glad you got it to work.

The client is just sending requests to the server and returns whatever the server returns. It would be wasteful to always add another GET API call to a POST call.

But you can definitely wrap that logic in your own application to make it more intuitive for high-level usage!
