### ISSUE TITLE
Personal Access Tokens with some special characters cause 401 errors

### ISSUE THREAD

**Issue by nelsonda** [python-gitlab/python-gitlab#263]
When a generated personal access token contains a leading hyphen (ex. -aaaaaaa) then attempts to perform actions using both the gitlab module and directly via the cli will result in 401 unauthorized errors.

**Comment by gpocentek** [comment]
I've not been able to generate a token with special chars so far...

Could you enable the debug (``gl.enabled_debug()``) and send me the output? Make sure to hide the sensitive data (edit the token)!

Thanks.

**Comment by nelsonda** [comment]
I don't have access to the underlying server, and in the interim the admin team has upgraded the GitLab server to Community Edition 9.0.5. Now I can't generate problematic tokens anymore, so they may be a problem that is already solve, one way or another, so I am going to close it.

**Comment by gpocentek** [comment]
Thank you for your feedback. Feel free to reopen if you face the issue again.
