### ISSUE TITLE
Add support for compliance_frameworks

### ISSUE THREAD

**Issue by coffeecoco** [python-gitlab/python-gitlab#2630]
## Description of the problem, including code/CLI snippet
Please add support for compliance_frameworks

https://docs.gitlab.com/ee/api/projects.html

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
Hi @coffeecoco, the REST API in the projects endpoint already returns the project's current list of compliance frameworks, so you can access that directly.

For updating compliance frameworks, this is sadly not possible upstream in GitLab's REST API. You can use the GraphQL API to do this programmatically:

https://docs.gitlab.com/ee/user/group/compliance_frameworks.html#graphql-api

You can follow our issue at #1357 if you're interested in GraphQL, or if you'd like to have this in the REST API please open an issue upstream with GitLab and then we can reopen this issue to implement it here when it's available in GitLab. In the meantime you can use the `gql` library for GraphQL.
