### ISSUE TITLE
Changing security_and_compliance_enabled gives a 400 on save

### ISSUE THREAD

**Issue by t794104** [python-gitlab/python-gitlab#2638]
## Description of the problem, including code/CLI snippet
Changing the security_and_compliance_enabled setting and then saving the project results in a 400 with the text :'gitlab.exceptions.GitlabUpdateError: 400: allow_merge_on_skipped_pipeline, analytics_access_level,... are missing, at least one parameter must be provided

## Expected Behavior
No error

## Actual Behavior
Big error

## Specifications

  - python-gitlab version: 3.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
@t794104 `security_and_compliance_enabled` is only returned by the GET call, but it is not a valid API parameter for creating or editing a project.

Instead, use `security_and_compliance_access_level`. Please always consult the upstream API documentation for which parameters are available. Thanks! See also previous discussions at https://gitlab.com/gitlab-org/gitlab/-/issues/348368.

From https://docs.gitlab.com/ee/api/projects.html#edit-project:
![image](https://github.com/python-gitlab/python-gitlab/assets/16777978/20ccdff3-9b0e-4ed4-8d7f-6ee3b73615c3)
