### ISSUE TITLE
Docs website doesn't seem to be getting updated

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#2652]
I went to: https://python-gitlab.readthedocs.io/en/main/index.html

In particular here: https://python-gitlab.readthedocs.io/en/main/gl_objects/runners.html

When I was trying to find this line:
https://github.com/python-gitlab/python-gitlab/blob/e4a1f6e2d1c4e505f38f9fd948d0fea9520aa909/docs/gl_objects/runners.rst#L80

**Comment by JohnVillalovos** [comment]
It still doesn't seem to be working. So I will re-open this.

**Comment by nejch** [comment]
Yeah I noticed. seems like we need to explicitly set the OS :sweat_smile:

**Comment by nejch** [comment]
Seems to be a bit happier now: https://readthedocs.org/projects/python-gitlab/builds/21757506/
