### ISSUE TITLE
Allow negating terms in IssuableFinder

### ISSUE THREAD

**Issue by tafkey** [python-gitlab/python-gitlab#2662]
## Description of the problem, including code/CLI snippet

The Python API currently doesn't support the "not" operator, see: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/16748

## Expected Behavior

Being able to filter issues that do not have a specific label.

## Actual Behavior

This is not supported from the python api, while it's supported by Gitlab API.

## Specifications

  - python-gitlab version: v3.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
I agree with @JohnVillalovos this is already supported out of the box by python-gitlab, but maybe not well documented (as it is also not really documented in detail upstream).

Something like this should work, getting issues that are not assigned to user ID 123 in `gitlab-org/gitlab`:
```python
import gitlab

gl = gitlab.Gitlab()

project = gl.projects.get("gitlab-org/gitlab", lazy=True)
issues = project.issues.list(query_parameters={"not": {"assignee_id": 123}})                                                                
```

If this doesn't work feel free to reopen the issue @tafkey.
