### ISSUE TITLE
CLI command glab ci lint not working

### ISSUE THREAD

**Issue by sessl3r** [python-gitlab/python-gitlab#2666]
## Description of the problem, including code/CLI snippet

When executing `glab ci lint` command in a repository against a Gitlab Server running Gitlab version 16.0.0 a failure occures.
The used API-Endpoint is deprecated with version 16.0.0 of Gitlab (as described [here](https://docs.gitlab.com/ee/update/deprecations.html#post-cilint-api-endpoint-deprecated).
Not tested with versions >16.0.0 but it is obvious the same error would occur.

## Expected Behavior

Getting the ci lint result

## Actual Behavior

```
$ glab ci lint
Getting contents in .gitlab-ci.yml
Validating...
POST <url-to-gitlab-16.0.0-server>/api/v4/ci/lint: 410 {message: 410 Gone}
```

## Specifications

  - python-gitlab version: 3.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 16.0.0

**Comment by sessl3r** [comment]
Used wrong command/version

**Comment by nejch** [comment]
@sessl3r `glab` is gitlab's golang CLI, a different tool, not python-gitlab's CLI. I assume you've already figured that out ;) otherwise feel free to reopen.

**Comment by sessl3r** [comment]
correct. for the reference the python-gitlab command working is:

`gitlab project-ci-lint validate --project-id '<project-name/id>' --content @.gitlab-ci.yml`

Hint: `gitlab ci-lint` obviosly is outdated with 16.0.0

**Comment by nejch** [comment]
Thanks for the update @sessl3r and yes, we're actually removing this subcommand/functionality with v4.0.0 :) glad you got it to work!
