### ISSUE TITLE
Add Merge Request merge_status and detailed_merge_status constants

### ISSUE THREAD

**Issue by valentingregoire** [python-gitlab/python-gitlab#2698]
## Description of the problem, including code/CLI snippet

There are a bunch of possible `merge_status` and `detailed_merge_status` values for a Merge Request. Add these as constants.

## Expected Behavior

You can find the possible values in the `const` module.

## Actual Behavior

The values are not to be found in the library.

## Specifications

  - python-gitlab version: 3.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): n/a

**Comment by nejch** [comment]
Hi @valentingregoire, thanks for the report.

Most of the Enums in the constants module were provided by community members who thought it was important to have that available for their use case. If you think it makes sense to add the status as well I'd be happy to review a community PR!

**Comment by valentingregoire** [comment]
@nejch, I am preparing a PR.

**Comment by nejch** [comment]
Done with https://github.com/python-gitlab/python-gitlab/pull/2699 :+1:
