### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlencode' (Python 3, repository_blob)

### ISSUE THREAD

**Issue by mdhausman** [python-gitlab/python-gitlab#271]
Getting an issue in python 3.6 with the `project.repository_blob` function.
```
File "[blah blah blah]/lib/python3.6/site-packages/gitlab/v3/objects.py", line 1885, in repository_blob
    url += '?%s' % (urllib.urlencode({'filepath': filepath}))
AttributeError: module 'urllib' has no attribute 'urlencode'
```

urlencode was moved in py3 to `urllib.parse.urlencode` (https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode). For maintaining compatibility across python 2 and 3, consider six's [six.moves.urllib](https://pythonhosted.org/six/#module-six.moves) instead of urllib itself.

**Comment by anthrotype** [comment]
Fixed in master
https://github.com/python-gitlab/python-gitlab/pull/268

@gpocentek would be nice to get a new release on PyPI as well :)

**Comment by mdhausman** [comment]
Hah, I was just about to come back and close this 'cause yeah, definitely fixed on master.

**Comment by gpocentek** [comment]
0.21.2 has the fix.
