### ISSUE TITLE
Unauthorized error when using lower level api for http requests

### ISSUE THREAD

**Issue by Feleuxens** [python-gitlab/python-gitlab#2711]
## Description of the problem, including code/CLI snippet

I tried querying the endpoints regarding [Terraform modules.](https://docs.gitlab.com/ee/api/packages/terraform-modules.html) I've generated a personal access token with read_api permission. curl works, but using gl.http_get() fails. However, other endpoints do work with http_get.

```Bash
curl --header "Authorization: Bearer <TOKEN>" "https://gitlab.com/api/v4/packages/terraform/modules/v1/<group>/<module>/<provider>
```

```Python
gl = Gitlab(private_token=<token>)
gl.http_get("/packages/terraform/modules/v1/<group>/<module>/<provider>")
```

## Expected Behavior

It should return the information about the Terraform module.

## Actual Behavior

Returns exception: "401 Unauthorized"

## Specifications

  - python-gitlab version: 3.15
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
@Feleuxens you're using an unofficial endpoint that is not meant to be consumed manually as described upstream:

> This API is used by the [Terraform CLI](https://www.terraform.io/) and is generally not meant for manual consumption. Undocumented authentication methods might be removed in the future.

As you see in the docs, you need to use Bearer token authentication for this endpoint, not the private token header. And even this is not officially supported for tools other then the terraform CLI, as described above.

That said, coincidentally providing OAuth token auth will set the Bearer authorization header and this should get you started *for now*:

```python
gl = Gitlab(oauth_token=<token>)
gl.http_get("/packages/terraform/modules/v1/<group>/<module>/<provider>")
```

However, this is mostly a hack and we don't officially support this, so YMMV. Feel free to reopen if you have any other questions though!

**Comment by Feleuxens** [comment]
Thanks for the fast reply!
