### ISSUE TITLE
Versions 4.x not available on pypi

### ISSUE THREAD

**Issue by lgatellier** [python-gitlab/python-gitlab#2713]
## Description of the problem, including code/CLI snippet
Recently published 4.x versions are not available on [pypi.org](https://pypi.org/project/python-gitlab/).
Maybe related with the switch to OIDC for pypi publishing #2554 #2559 ?

## Expected Behavior
python-gitlab `4.0.0` & `4.1.0` should be available from pypi using command `pip install --upgrade python-gitlab`.

## Actual Behavior
Only versions up to `3.15.0` are available.
```
❯ pip3 install --upgrade 'python-gitlab>=4'
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement python-gitlab>=4 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.9.1, 0.9.2, 0.10, 0.11, 0.11.1, 0.12.1, 0.12.2, 0.13, 0.14, 0.15, 0.15.1, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.21.1, 0.21.2, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.14.0, 1.15.0, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.7.1, 2.8.0, 2.9.0, 2.10.0, 2.10.1, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.8.1, 3.9.0, 3.10.0, 3.11.0, 3.12.0, 3.13.0, 3.14.0, 3.15.0)
ERROR: No matching distribution found for python-gitlab>=4
```

## Specifications
- pip 23.2.1 (python 3.10)

**Comment by nejch** [comment]
@lgatellier the v4 packages have been pushed now, sorry about that.

Yes, there was typo in the action step, but I'm also not too happy with the current generated changelogs :sweat_smile:
