### ISSUE TITLE
GitlabGetError: 404 Not Found

### ISSUE THREAD

**Issue by Rodrigo-Rios** [python-gitlab/python-gitlab#2725]
## Description of the problem, including code/CLI snippet

The issue arises when attempting to retrieve information regarding a project's service/integration. The used URL doesn't align with the GitLab server version, and here's what I mean:

The GitLab server being utilized is private, and I don't have management access, but I suspect its version is pre-13.12. The correct URL for the environment should be /api/v4/projects/26787/services/asana since there's no redirection to /api/v4/projects/26787/integrations/asana.

A point to note is that when using python-gitlab version 3.6.0, this issue doesn't occur, allowing all methods to be executed. However, in versions above, a persistent 404 error is encountered.

I believe that addressing this within the integrations could resolve the issue by attempting alternative routes if the primary route returns a 404 error.

code:
```python
with Gitlab(url=URL, private_token=GITLAB_TOKEN) as gl:
    gl.enable_debug()
    project = gl.projects.get(26787)
    asana = project.integrations.get('asana')
    print(asana)
```

## Expected Behavior

```
<class 'gitlab.v4.objects.services.ProjectService'> => {'id': 51601, 'title': 'Asana', 'slug': 'asana', 'created_at': '2023-11-11T11:05:06.793-03:00', 'updated_at': '2023-11-16T15:04:56.293-03:00', 'active': True, 'commit_events': True, 'push_events': True, 'issues_events': True, 'confidential_issues_events': True, 'merge_requests_events': True, 'tag_push_events': True, 'note_events': True, 'confidential_note_events': True, 'pipeline_events': True, 'wiki_page_events': True, 'job_events': True, 'comment_on_event_enabled': True, 'properties': {'restrict_to_branch': ''}}
```

## Actual Behavior

```
    asana = project.integrations.get('asana')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodrigo.rios/Library/Caches/pypoetry/virtualenvs/gflow-tests-nS4K1n8a-py3.11/lib/python3.11/site-packages/gitlab/v4/objects/integrations.py", line 271, in get
    return cast(ProjectIntegration, super().get(id=id, lazy=lazy, **kwargs))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodrigo.rios/Library/Caches/pypoetry/virtualenvs/gflow-tests-nS4K1n8a-py3.11/lib/python3.11/site-packages/gitlab/exceptions.py", line 338, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Not Found
```

## Specifications

  - python-gitlab version: 4.1.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
Hi @Rodrigo-Rios, this was a deliberate change to align with the new GitLab API endpoint, which has been available since 14.4.

We tend not to support extremely old GitLab versions so we don't have multiple code paths. 13.12 is really really old and full of vulnerabilities, and shouldn't run in production environments. I'd suggest you either upgrade your GitLab instance or if you don't have that option, use an older version of python-gitlab for this endpoint :bow: 

I'll close this one but please reopen if you have any other questions!
