### ISSUE TITLE
repository_raw_blob returns 404

### ISSUE THREAD

**Issue by mdhausman** [python-gitlab/python-gitlab#273]
I'm having trouble getting file contents through api v4 now, and I think it's a problem with the url that the library is hitting.

https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/v4/objects.py#L1878

`url = "/projects/%s/repository/raw_blobs/%s" % (self.id, sha)`

This doesn't seem to match the [Gitlab API specifications](https://docs.gitlab.com/ee/api/repositories.html#raw-blob-content):

>`GET /projects/:id/repository/blobs/:sha/raw`

Sure enough, when I try to hit the endpoint in postman only the latter route returns file contents, whereas `GET /projects/:id/repository/raw_blobs/:sha` consistently returns a 404.

**Comment by mdhausman** [comment]
Not sure if it's worth making a separate issue for this, but the `repository_blob` function doesn't appear to be accessible via api v4 either. Attempting to use it on an api 4 project object throws AttributeErrors, but [the endpoint](https://docs.gitlab.com/ee/api/repositories.html#get-a-blob-from-repository) doesn't appear to be deprecated in api 4.

**Comment by gpocentek** [comment]
Thanks for reporting this issue. Indeed th blobs methods are currently broken or unimplemented for v4.

I've updated the methods in commit 3488c5cf. I will probably merge this branch for the next release but there's a few things I need to do first.

**Comment by gpocentek** [comment]
I believe this is fixed in the master branch now. Could you give it a try?

Thanks.
