### ISSUE TITLE
syntax errors

### ISSUE THREAD

**Issue by GrahamLab** [python-gitlab/python-gitlab#275]
Using python 2.6 and python-gitlab 0.21.2

Whatever I try results in a syntax error - for example a simple script
`import gitlab
gl = gitlab.Gitlab('http://<Myipaddresshere',email='<Myeamiladdress>',password='<myPassword')`

Results in the following stack trace

`Traceback (most recent call last):
  File "getTest.py", line 1, in <module>
    import gitlab
  File "/usr/lib/python2.6/site-packages/python_gitlab-0.21.2-py2.6.egg/gitlab/__init__.py", line 35, in <module>
    from gitlab.v3.objects import *  # noqa
  File "/usr/lib/python2.6/site-packages/python_gitlab-0.21.2-py2.6.egg/gitlab/v3/objects.py", line 2094
    form = {r'variables[%s]' % k: v for k, v in six.iteritems(variables)}
                                      ^
SyntaxError: invalid syntax`

I get the same error if I run from the command line

here is my config file
`[global]
default = somewhere
sl_verify = true
timeout = 5
api_version = 3

[somewhere]
url = http://<myIp>
private_token = my token`

I am not certain where I obtain the private token so have created a personal access token got gitlab

Any help appreciated
```

**Comment by gpocentek** [comment]
AFAIK python 2.6 has reached end of life, and I don't have the time or resources to support this version in python-gitlab.

Could you try on a more recent version of python (2.7 or >= 3.4)?

**Comment by GrahamLab** [comment]
Hi thanks for your quick response
I am runniong on a CentOs machine which I believe relies on python 2.6
I know I can install another version of python but how would I install python-gitlab to use the new version of python?

Thanks again

**Comment by gpocentek** [comment]
You can probably install pip for the new python version and use ``pip-pythonVERSION``. Another solution is to use a virtualenv.

**Comment by GrahamLab** [comment]
Hi
I have installed python 2.7 and have it running alongside the default version of 2.6

Thanks for your help

**Comment by gpocentek** [comment]
Thanks for your feedback!

**Comment by max-wittig** [comment]
@dagwieers From my point of view no. It's no longer supported and we don't want to support it either. Python2 will die on 31.12.2019. Doesn't make sense to support a dead language.

**Comment by dagwieers** [comment]
@max-wittig I have been doing Linux for 20+ years and legacy stuff will still be around for years. RHEL6 is supported until 2024, RHEL7 likely until 2028. And these will still be supported by Red Hat (and other vendors). Sure the Python Foundation will end supporting Python2, but that doesn't mean people will stop using it, the reality unfortunately is a bit more complicated than people's wishlists.

**Comment by gpocentek** [comment]
@dagwieers I agree with you that old systems will be around for a while.

But the thing is, companies like RedHat has paid manpower to support their systems, python-gitlab dev team is 2 unpaid contributors working on their free time (you can see that most of the changes on this project happen on weekends).

Python 2.6 is not something we want to support. We prefer to spend time fixing bugs and improving the project.

**Comment by max-wittig** [comment]
@dagwieers Python3 has evolved so much. We need to actively discourage people from using python2. People, who rely on python2 had enough time to switch, even enterprise consumers. Python3 has been around for over 10 years and the switch is not that hard for most things. Some big projects already dropped python2 support: https://python3statement.org/. We need to stop supporting old systems to evolve and thrive, not hold onto the past.

**Comment by dagwieers** [comment]
@max-wittig Enterprise distributions were composed 4 to 8 years ago, the whole point of Enterprise systems is that they don't swap parts that are incompatible during their lifetime. So no, they did not have enough time to switch (and if they did they would be running Python 3.1 maybe). In those days a lot of software didn't work with Python3, so it is not that simple.

I don't mind that you don't want to do the effort (but would allow others to spend the effort), or you have technical reasons to drop Python 2.6 support. But the "we should actively discourage people from using python 2" is an activistic fantasy, not based on realism.

**Comment by dagwieers** [comment]
> But the thing is, companies like RedHat has paid manpower to support their systems, python-gitlab dev team is 2 unpaid contributors working on their free time (you can see that most of the changes on this project happen on weekends).

I am proposing to make the necessary changes, nobody is expecting to put the burden on someone else. Hence the question:

> Would changes that add Python 2.6 support be accepted ?

**Comment by gpocentek** [comment]
@dagwieers thanks for proposing to make the changes, but these changes also need to be maintained in the long run, and that most likely means that @max-wittig and I will have to take care of it. I'm not willing to do this.

I completely understand what you are saying about enterprise distributions, but it's asking too much from us to do the same thing.

**Comment by dagwieers** [comment]
@gpocentek @max-wittig Thanks, this couldn't be more clearly answered :-)
