### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by xiangfei** [python-gitlab/python-gitlab#277]
[code.txt](https://github.com/python-gitlab/python-gitlab/files/1090195/code.txt)
[errorstack.txt](https://github.com/python-gitlab/python-gitlab/files/1090196/errorstack.txt)
![gitlabpage](https://user-images.githubusercontent.com/1134979/27364662-6f57708e-566e-11e7-94da-35101ce2c67f.PNG)
![gitlabpagetwo](https://user-images.githubusercontent.com/1134979/27364661-6f56d8ea-566e-11e7-8c66-536c71a15652.PNG)

python commit  diff error

**Comment by gpocentek** [comment]
Hi,

Looks like you have a problem on the server: ``GitlabGetError: 500: {"message"=>"500 Internal Server Error"}``

The server logs should give you information about what happened.
