### ISSUE TITLE
Get file LFS

### ISSUE THREAD

**Issue by adholmgren** [python-gitlab/python-gitlab#2778]
Not trying to do duplicate issues, but the other issue was closed until further notice. Anyway, I just wanted to let you and anyone else know that it is now possible to get a file that is stored as lfs because the API enabled it 6ish months ago.

```
gl = gitlab.Gitlab('https://your.gitlab.server.com', private_token="t0k3n1d3nt1ty")
gl.auth()
project_id = 12345
project = gl.projects.get(id=project_id)
fm = project.files
file = fm.raw('path/to/file.ext', ref='master', lfs=True)
```

works as expected to give the raw lfs file.

https://github.com/python-gitlab/python-gitlab/issues/2027

**Comment by JohnVillalovos** [comment]
So is this an issue or just an FYI?

**Comment by adholmgren** [comment]
I haven't done thorough testing, so there could be a true issue, but mostly a FYI that you open and likely quickly close the other issue.

**Comment by JohnVillalovos** [comment]
> I haven't done thorough testing, so there could be a true issue, but mostly a FYI that you can reopen and likely quickly close the issue https://github.com/python-gitlab/python-gitlab/issues/2027. Sorry, this probably could have been in a discussion. I'm clearly used to gitlab and not GitHub these days 😃 

I unlocked the other issue if you want to comment over there.
