### ISSUE TITLE
Wrong type on `job.trace()`?

### ISSUE THREAD

**Issue by stdedos** [python-gitlab/python-gitlab#2808]
https://github.com/python-gitlab/python-gitlab/blob/04c569a2130d053e35c1f2520ef8bab09f2f9651/gitlab/v4/objects/jobs.py#L242-L244

```py
In [3]: type(job.trace())
Out[3]: bytes
```

**Comment by nejch** [comment]
This might be the case, as we were probably applying typing across dozens of endpoints at the time.

If we consistently get `bytes` regardless of the `streamed` argument we can change that easily.

**Comment by stdedos** [comment]
Oh ... Haven't tried the `streamed=` 😅 

Then, _at least_ ` | bytes` is also needed?

**Comment by stdedos** [comment]
Actually ... even worse? 😅 😅 

```
In [4]: a = job.trace(streamed=True)
b'\x1b[0KRunning with gitlab-runner ...ERROR: Job failed: command terminated with exit code 1\n\x1b[0;m\n'

In [5]: repr(a)
Out[5]: 'None'
```

Have I messed up something? I am **pretty sure** that there's no excuse for a "blanket" `print` to the terminal 😕

_Full disclosure, I'm running against [15.10.2-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v15.10.2-ee) - but I don't think that that should affect_

Would you kindly check from your end?

**Comment by JohnVillalovos** [comment]
So when using `streamed=True` it will by default just `print()` the data. If that is not desired, then the `action` argument must specify a function to call that accepts the streamed data.
