### ISSUE TITLE
Missing `latest()` method on `ProjectPipelineManager`

### ISSUE THREAD

**Issue by TheDJVG** [python-gitlab/python-gitlab#2809]
## Description of the problem, including code/CLI snippet

The API describes a way to get the latest pipeline for a `ref`: https://docs.gitlab.com/ee/api/pipelines.html#get-the-latest-pipeline
Currently it does not seem to be implemented in the manager:
https://github.com/python-gitlab/python-gitlab/blob/04c569a2130d053e35c1f2520ef8bab09f2f9651/gitlab/v4/objects/pipelines.py#L94-L140

## Expected Behavior

We can get the latest pipeline for a `ref` by calling `latest()` on an instance of `ProjectPipelineManager`

## Actual Behavior

 `ProjectPipelineManager` has no `latest()` method.

## Specifications

  - python-gitlab version: 4.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 16.7.6-ee

**Comment by nejch** [comment]
@TheDJVG you can just do this:

```python
project = gl.projects.get("gitlab-org/gitlab")
pipeline = project.pipelines.get("latest")
```

Or are you saying you want an alias for this call?

**Comment by TheDJVG** [comment]
How would I specify the `ref` (main) in our case in that way?

I expected more something like:
```python
project = gl.projects.get("gitlab-org/gitlab")
pipeline = project.pipelines.latest(ref="main")
```

That's how I understood the docs.

**Comment by nejch** [comment]
python-gitlab doesn't provide any `latest()` methods currently, but since it's a simple get call, this should work:

```python
pipeline = project.pipelines.get("latest", ref="main")
```

We could potentially look at adding aliases for a few endpoints, if GitLab has a consistent `/latest` pattern.
