### ISSUE TITLE
dots replaced by hyphens

### ISSUE THREAD

**Issue by guyzmo** [python-gitlab/python-gitlab#281]
cf guyzmo/git-repo#167

the create code is really straightforward: https://github.com/guyzmo/git-repo/blob/devel/git_repo/services/ext/gitlab.py#L38,L44

so I don't think I'm guilty of the translation. Any ideas?

**Comment by gpocentek** [comment]
Just tested, this is a Gitlab server behavior. If you want to keep the dot in the url, you need to pass the ``path`` argument to the create() method

```python
>>> p = gl.projects.create({'name': 'bar.baz'})
>>> p.web_url
u'http://gitlab.lxd/root/bar-baz'
>>> p = gl.projects.create({'name': 'bar.baz2', 'path': 'bar.baz2'})
>>> p.web_url
u'http://gitlab.lxd/root/bar.baz2'

**Comment by guyzmo** [comment]
👌 thank you!
