### ISSUE TITLE
Add group.shared_with_groups.list()

### ISSUE THREAD

**Issue by TimKnight-DWP** [python-gitlab/python-gitlab#2813]
## Description of the problem, including code/CLI snippet
Groups have a [share/unshare](https://python-gitlab.readthedocs.io/en/stable/gl_objects/groups.html#) functionality defined on the api, but no get for the `shared_with_groups` parameter defined in gitlab api [groups/:id](https://docs.gitlab.com/ee/api/groups.html#details-of-a-group)

## Expected Behavior
group.shared_with_groups.list() should return an array of groups a group has been shared with

```
 "shared_with_groups": [
    {
      "group_id": 28,
      "group_name": "H5bp",
      "group_full_path": "h5bp",
      "group_access_level": 20,
      "expires_at": null
    }
  ],
```

## Actual Behavior
No such api is available

## Specifications

  - python-gitlab version: 4.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
@TimKnight-DWP to my knowledge `shared_with_groups` is an attribute returned by the single group GET call, not an additional nested endpoint. So you should be able to just do:

```python
group = gl.groups.get(123)
print(group.shared_with_groups) # [] or [{"id": 124,...}]
```

At least that's how I've been using it at work for a while.

**Comment by TimKnight-DWP** [comment]
@nejch perfect, I couldn't see any docs or closed issues/discussions on it but had assumed it must be somewhere on the api since GL returns it.

I'll implement
