### ISSUE TITLE
const module not exposed

### ISSUE THREAD

**Issue by valentingregoire** [python-gitlab/python-gitlab#2819]
## Description of the problem, including code/CLI snippet

The `const` module is not exported, therefore, one cannot access any const properly.

## Expected Behavior

One can simply access the consts

## Actual Behavior

Right now, it is possible to access the consts with `gitlab.const.XYZ`, but this is not the most ideal situation I believe.

## Specifications

  - python-gitlab version: 4.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): most recent

**Comment by nejch** [comment]
As discussed in #2820 we'll keep this as is - it's expected that the constants aren't exposed at the root package level.
