### ISSUE TITLE
Feature: add `pages` support in `project`

### ISSUE THREAD

**Issue by Karreg** [python-gitlab/python-gitlab#2832]
## Description of the problem, including code/CLI snippet

I was not able to determine how to access to [`/api/v4/projects/:id/pages`](https://docs.gitlab.com/ee/api/pages.html) with python-gitlab. I'm not sure to have searched well, but the [`Project`object](https://python-gitlab.readthedocs.io/en/stable/api/gitlab.v4.html#gitlab.v4.objects.Project) does not seem to provide such access.

Would it be possible to add it?

The use case behind is I want to provide a public script to add a badge linking to the deployed pages, which requires such API access.

## Specifications

  - python-gitlab version: 4.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 16.9.2

Thanks for you great API wrapper, it's a real improvement over standard GitLab API!

**Comment by nejch** [comment]
@Karreg thanks for the report! This is available now in https://github.com/python-gitlab/python-gitlab/releases/tag/v4.13.0.
