### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by hmliu6** [python-gitlab/python-gitlab#284]
I have created object users = gl.users.list()
Then users object consists numbers of <class 'gitlab.v3.objects.User'>
so, user = users[0] should be in <class 'gitlab.v3.objects.User'>
I followed the example to find users' email "emails = user.emails.list()"
However, it gave "gitlab.exceptions.GitlabGetError: 404: {"error":"404 Not Found"}" error

After that, I have tried another method.
I get single user directly by using "user = gl.users.get(1)"
But still not working when I call functions "email = user.emails.get(1)" or "emails = user.emails.list()"

Finally, I found out that email can be retrieved by "email = user.email" instead of documentation stated
OR email = gl.users.list()[1].email

------
In page: gl_objects/users.rst

**Comment by gpocentek** [comment]
Hi,

I have not been able to reproduce the problem here. Could you tell me which version of Gitlab and python-gitlab you are using?

Thank you.
