### ISSUE TITLE
project.commits.list(path=some/path.txt) fails because "path" param is used to override path in ListMixin.list

### ISSUE THREAD

**Issue by dlachica** [python-gitlab/python-gitlab#2840]
## Description of the problem, including code/CLI snippet
`
gl.projects.get(1234).commits.list(path="some/path.txt", ref_name="some_branch")
`
## Expected Behavior
Should properly create URL
`
https://giltab.instance.com/api/v4/projects/1234/repository/commits?path=some%2Fpath.txt&ref_name=some_branch
`
## Actual Behavior
Generated URL
`
https://giltab.instance.com/api/v4some/path.txt?ref_name=some_branch
`

Caused by  ListMixin.list
`
        path = data.pop("path", self.path)
`

"path" should be supported as the API allows it
https://docs.gitlab.com/ee/api/commits.html#list-repository-commits

## Specifications

  - python-gitlab version: 4.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  16.9.1

**Comment by JohnVillalovos** [comment]
You will need to use `query_parameters` as discussed in https://python-gitlab.readthedocs.io/en/stable/api-usage.html

**Comment by dlachica** [comment]
Thanks!

**Comment by kcatabui** [comment]
This issue also happens with gitlab cli. I can't find the cli counterpart for query parameters. It seems like the other commands with list use some version of "filepath" so they don't have this issue. Is it worth opening a ticket to have path changed to filepath? Or perhaps change ListMixin's path to something else like api_path?
