### ISSUE TITLE
Merge request note update appends instead of replaces

### ISSUE THREAD

**Issue by Flamefire** [python-gitlab/python-gitlab#2870]
## Description of the problem, including code/CLI snippet

I want to update a comment on a merge request. For that I use:

```
    mr = gitlab_project.mergerequests.get(mr_iid)
    match_str = find_comment_match(comment)
    try:
        existing_note = None
        for note in mr.notes.list():
            if find_comment_match(note.body) == match_str:
                existing_note = note
        if existing_note:
            existing_note.body = comment
            existing_note.save()
```

## Expected Behavior

Comment gets replaced by the new text

## Actual Behavior

New comment is appended to the text of the old comment

## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): ?
  - Gitlab server version: v16.10.5

**Comment by JohnVillalovos** [comment]
Can you try with the latest version of python-gitlab?

**Comment by Flamefire** [comment]
Looks like it was a mistake on my side. Tried to reproduce it in a small testcase but failed
