### ISSUE TITLE
JSONDecodeError when getting file contents of a file ending with '.txt' using APIv4

### ISSUE THREAD

**Issue by linuxdaemon** [python-gitlab/python-gitlab#288]
### Steps to Reproduce
1. Have a file in a gitlab repository with a '.txt' extension
2. Get a v4 Project object from python-gitlab
3. Attempt to retrieve the contents of the file with `project.files.get("path/to/file.txt", ref="master")`

The `_sanitize` function ( [\_\_init\_\_.py#L48](https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/__init__.py#L48) ) only replaces `/` characters in the file path, but `.` characters must also be sanitized.

**Comment by linuxdaemon** [comment]
I have also opened an [issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/34963) for GitLab as `.` is not escaped by most HTTP libraries since it is unreserved.

**Comment by Cord-Thomas** [comment]
I am not sure why that would work with all other files and not .txt files.  I am getting the same error on text files.  i have traced the difference down the models.json() where all other files do not appear to have an encoding and are then passed into the guess_json_utf method and then on to the complexjson.loads() whereas the .txt files appear to report a ISO-8859-1 encoding with an ultimate error of "Expecting property name enclosed in double quotes: line 1 column 2 (char 1)" from the encoder.  

I pasted the API call request and got what appears to be a valid response from gitlab. 

    /api/v4/projects/1373/repository/files/analyses%2FYear1%2Fempty.txt?ref=master

returns 

    {:file_name=>"empty.txt", :file_path=>"analyses/Year1/empty.txt", :size=>4, :encoding=>"base64", :content=>"TlVMTA==", :ref=>"master", :blob_id=>"fe3a0735d98b88f091b15ff86c2dc7a167bef217", :commit_id=>"1649264a195658455bc762ff597c8e4083ca905d", :last_commit_id=>"898e5dfdc229105e68f839577f1d16413aaaa66c"}

**Comment by Cord-Thomas** [comment]
I see it's not a valid response - valid data, not valid json...  my bad

**Comment by linuxdaemon** [comment]
The issue itself appears to be an issue on Gitlab's side, `.` is expected to be escaped, but it works without being escaped in most cases, but certain extensions are changing the output format for some reason

**Comment by gpocentek** [comment]
Hello,

Thank you for your report. I workaround this error in the master branch, on the v4 API. I've successfully manipulated files containing a `.` in their name.

Could you test with the master? Note that there are significant changes in the python-gitlab API, you might want to have a look at http://python-gitlab.readthedocs.io/en/master/switching-to-v4.html#changes-between-v3-and-v4-api

**Comment by linuxdaemon** [comment]
I have written up a test case using my test repo made for the gitlab bug report and run in to a new error.
[Test case](https://gist.github.com/linuxdaemon/9e0717073f7b824c8c53a02a3de5c70b) (error traceback in second file)
Tested against the master branch on python 3.5

**Comment by gpocentek** [comment]
You used `https://gitlab.com/api` as endpoint, it should be `https://gitlab.com/`.

I could not reproduce the problem using the correct URL.

**Comment by linuxdaemon** [comment]
Yeah, I missed that. It works properly with the correct endpoint, so this issue seems to be resolved.
