### ISSUE TITLE
GitLab mirror of python-gitlab is out of date

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#2884]
https://gitlab.com/python-gitlab/python-gitlab

https://gitlab.com/python-gitlab/python-gitlab/-/commits/main/?ref_type=HEADS

Last commit was in February. I wonder if the token has expired?

**Comment by nejch** [comment]
We need to renew the open source program subscription so we can mirror. I'll look at this now, I have last year's template still I think.

**Comment by nejch** [comment]
I applied again yesterday but will be going through verification for a few days it seems.

**Comment by JohnVillalovos** [comment]
> I applied again yesterday but will be going through verification for a few days it seems.

Thanks @nejch for working on this!

**Comment by nejch** [comment]
Just got the renewal so this is mirroring again now :+1:

**Comment by JohnVillalovos** [comment]
Thanks @nejch !!
