### ISSUE TITLE
Struggling with pulling project files - v4 API

### ISSUE THREAD

**Issue by Cord-Thomas** [python-gitlab/python-gitlab#289]
I've read the [docs](http://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#files) and am successfully pulling a lot of useful information from our GitLab environment.  BTW, my end game is to use [Linguist](https://github.com/douban/linguist) to identify our use of languages as it has changed over time - so, what I am looking for is latest timestamps which I'd get from commits.

Using this code, 

    fileobj = gl.project_files.get(file_path=path, ref='master', project_id=projectid)

I have validated that path and projectid, e.g., 

    File path projectid 1362: code_from_iva/originals/prevaltab_2012.txt

Error reported:

    Error in processing 1119: The id argument must be defined.

I am sure this is user error.  From reading the ProjectFileManager class, it says ref is "ref (str): ID of the commit" - do i need a commit ID?

**Comment by linuxdaemon** [comment]
When retrieving files from the project_files submanager, it appears you have to specify the file path as the `id` arguemnt.
Something like this should work in your case:
`fileobj = gl.project_files.get(path, ref='master', project_id=projectid)`
or
`fileobj = gl.project_files.get(id=path, ref='master', project_id=projectid)`

**Comment by Cord-Thomas** [comment]
Yes, the later works.  The former does not.  I will add this as an example to the documentation which i believe to be incomplete if not inaccurate at this point.  Thank you.

**Comment by gpocentek** [comment]
Hi,

Are you using this with the v3 or the v4 API?

Thanks.

**Comment by tmuguet** [comment]
Hi,

I encountered the same issue when using the v4 API with python-gitlab 0.21.2.
Based on https://python-gitlab.readthedocs.io/en/latest/gl_objects/projects.html#project-files, the following code should work:

    f = project.files.get(file_path='README.rst', ref='master')

But fails with `The id argument must be defined.`

However, that works:

    f = project.files.get(id='README.rst', ref='master')
