### ISSUE TITLE
Cant get ProjectRegistryRepository size

### ISSUE THREAD

**Issue by LiberBear** [python-gitlab/python-gitlab#2898]
## Description of the problem, including code/CLI snippet
In [documentation](https://docs.gitlab.com/ee/api/container_registry.html#get-details-of-a-single-repository) we have to pass _size=true_ in args to get repository total size (without needing to parse all tags). And it works in python-gitlab for _tags_count_ arg, but when i pass _size=True_, nothing happens. 

b.t.w size arg works in raw query that i made by CURL 
## Expected Behavior

When i call something like this ```project.repositories.list(iterator=True, tags_count=True, size=True)``` i got repository size in response fields.
## Actual Behavior

No size field in object

## Specifications

  - python-gitlab version: name = "4.6.0"
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): [v16.7.7-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v16.7.7-ee)

**Comment by nejch** [comment]
@LiberBear the documentation you linked to is for the single repository endpoint.

So the `size` parameter is only available if you do something like `project.repositories.get(your_repo_id, tags_count=True, size=True)` after collecting the repo IDs.

BTW looking at the upstream documentation, there's a little caveat, so you may also be affected even if you switch to `get()`:

> This field is only available on GitLab.com for repositories created after 2021-11-04.

https://docs.gitlab.com/ee/api/container_registry.html#get-details-of-a-single-repository

I'll close this as I think you should be able to get this to work but feel free to reopen!

**Comment by LiberBear** [comment]
> So the `size` parameter is only available if you do something like `project.repositories.get(your_repo_id, tags_count=True, size=True)` after collecting the repo IDs.

`  logging.info(project.repositories.get(repo.id, tags_count=True, size=True))
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ProjectRegistryRepositoryManager' object has no attribute 'get'`

**Comment by nejch** [comment]
@LiberBear sorry, I gave you the wrong syntax. Assuming `gl` is your Gitlab instance it should be like this:

```python
gl.registry_repositories.get(repo.id, tags_count=True, size=True)
```

let me know if that works.

**Comment by LiberBear** [comment]
@nejch Yeah, it works!!!
