### ISSUE TITLE
Support the approvalrules option "applies_to_all_protected_branches" 

### ISSUE THREAD

**Issue by boricm** [python-gitlab/python-gitlab#2899]
## Description of the problem, including code/CLI snippet
I would like to set the optional attribute `applies_to_all_protected_branches `when creating an approval rule with the `ProjectApprovalRuleManager`.

## Expected Behavior
Please add `applies_to_all_protected_branches `to the optional attributes of the `ProjectApprovalRuleManager`.

It would be great if I can set the following approval rule:
```python
project.approvalrules.create(
        {'name': 'Test Rule', 'approvals_required': 2, 'user_ids': someUserIds, 'applies_to_all_protected_branches': True}
```

## Actual Behavior
`applies_to_all_protected_branches` is not supported by the `ProjectApprovalRuleManager`.

## Specifications

  - python-gitlab version: 4.3.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Enterprise Edition [v16.10.2-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v16.10.2-ee)
  
  Thanks for your awesome work! :-)

**Comment by JohnVillalovos** [comment]
Are you saying it doesn't work? If it doesn't work do you have some error message you can share?

**Comment by boricm** [comment]
Oh, I'm sorry! I just discovered, that the issue was somewhere in our GitLab instance. We moved to another GitLab instance and now the feature works flawlessly with the same lines of code.

**Comment by JohnVillalovos** [comment]
> Oh, I'm sorry! I just discovered, that the issue was somewhere in our GitLab instance. We moved to another GitLab instance and now the feature works flawlessly with the same lines of code.

Glad you got it figured out 👍
