### ISSUE TITLE
Can't assign milestone to an issue

### ISSUE THREAD

**Issue by ilesser** [python-gitlab/python-gitlab#290]
When I run the following code I'd expect the issue to be created with a milestone but it never gets assigned.

```python
gl = gitlab.Gitlab.from_config('myrepo')
p = gl.projects.get(26)
m = p.milestones.get(124)
m.issues()
p.issues.create({'title': 'test', 'description': 'aaaaaaaa', 'milestone': 124})
m.issues()
````

The console doesn't return any error or warning.
I am using GitLab Community Edition 9.3.5 0c9ceb3 and tested this with both api version 3 and 4.
Python 3.6.1 (default, Apr 20 2017, 16:46:54)
IPython 6.1.0 
gitlab.__version__ = 0.21.2

~/.python-gitlab.cfg
```
[global]
default = myrepo
ssl_verify = true
timeout = 15
api_version = 4

[myrepo]
url = http://path.to.my.repo
private_token = <MY PRIVATE TOKEN>
```

**Comment by gpocentek** [comment]
Hi,

Thank you for your detailed report!

You need to use `milestone_id`, not `milestone` to set the milestone for an issue: http://python-gitlab.readthedocs.io/en/stable/api/gitlab.html#gitlab.v3.objects.ProjectIssueManager.create
