### ISSUE TITLE
Can't create projects in v4 API

### ISSUE THREAD

**Issue by alexwidener** [python-gitlab/python-gitlab#291]
Hey! Running 0.21.2 for this question.

I'm in the middle of trying to switch us over to using v4, and I'm hitting an issue with trying to create a project. I'm using this right now like this: 

```
    def create_project(self):
        description = self.description if self.description else ''

        # Grab the group's configurations, make a copy of it, update the copy.
        project = self.group_configuration.get('attributes', {})

        project.update({
            'name': self.project_name,
            'namespace_id': self.group.id,
            'description': description,
        })

        self.project = self.gitlab.projects.create(project)
```

And I'm getting a response that I never saw on v3 and doesn't make sense, because I'm the owner of the group: 

`[u'visibilitylevel|private has been restricted by your GitLab administrator'], u'limit_reached': []}`

I also tried blocking out the visibility_level attribute in the project, as I was reading up on [this merge request](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8736) on the [changelist](https://docs.gitlab.com/ce/api/v3_to_v4.html) on Gitlab's v3 to v4 API, but that just gave the same thing. 

I'm curious if I'm doing something wrong - I see in [here, you mention list() and create() 'should not be used anymore for v4'](https://github.com/python-gitlab/python-gitlab/blob/rework_api/docs/switching-to-v4.rst) but as you mention, this is on the Gitlab object and not the Projects. 

Thanks for the help! 

Here's a cleaned-up traceback: 

```
 File "\my_project\main.py", line 162, in create_project
    self.project = self.gitlab.projects.create(project)
  File "\site-packages\gitlab\base.py", line 139, in create
    return self.obj_cls.create(self.gitlab, data, **args)
  File "\site-packages\gitlab\base.py", line 358, in create
    obj.save()
  File "\site-packages\gitlab\base.py", line 328, in save
    self._create(**kwargs)
  File "\site-packages\gitlab\base.py", line 313, in _create
    json = self.gitlab.create(self, **kwargs)
  File "\site-packages\gitlab\__init__.py", line 559, in create
    raise_error_from_response(r, GitlabCreateError, 201)
  File "\site-packages\gitlab\exceptions.py", line 204, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabCreateError: 400: {u'visibility_level':[u'visibilitylevel|private has been restricted by your GitLab administrator'], u'limit_reached': []} 
```

**Comment by gpocentek** [comment]
Hi,

From what I understand you need to explicitly define the `visibility_level` attribute when creating your project. This seems to be a restriction configured on the server side.

**Comment by gpocentek** [comment]
@alexwidener Did you get a chance to test with the `visibility_level` attribute defined?

Thanks.

**Comment by alexwidener** [comment]
@gpocentek - I get the same result with the visibility_level defined or not existing. 

I checked with the administrator and we looked through settings, there's nothing that's restricting 'Internal' on the visibility_level - Private and Public are restricted, but we're only trying to make repositories Internal.

Thanks,
Alex

**Comment by gpocentek** [comment]
This is a surprising behavior. Could you tell me the gitlab version you're using? I'll try to reproduce the problem.

Thanks.

**Comment by alexwidener** [comment]
It's an auto-updating instance - I'll post back on Monday morning when I get back in to work.

**Comment by alexwidener** [comment]
9.4.4-ee c7bc62c

**Comment by alexwidener** [comment]
I'm getting the same message with api v3 now - I'm going to contact Gitlab Support and inquire further, I'll go ahead and close this issue for you. Thanks! I'll report back if I find anything.
