### ISSUE TITLE
gitlab merge request participants list

### ISSUE THREAD

**Issue by pkp124** [python-gitlab/python-gitlab#2912]
## Description of the problem, including code/CLI snippet
Hello,

I am trying to get a participants list for merge requests from python API. There is an undocumented API present, `mr.participants()` .
This currently gives a different set of participants than what gitlab shows in its web ui for the MR.

## Expected Behavior
Python API should  provide the same list of participants as what is shown in the web UI.

  - python-gitlab version: 4.7.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): v16.11.3-ee

Could you please help me with this. Thanks

**Comment by JohnVillalovos** [comment]
More details would be useful. Examples of the code you are using. What the code returns. What you are expecting.
