### ISSUE TITLE
List of users who approved MR is not returned

### ISSUE THREAD

**Issue by FeNix784** [python-gitlab/python-gitlab#2947]
## Description of the problem, including code/CLI snippet
I use approvals.get().attributes at ProjectMergeRequest to get a list of users who approved MR but an empty list is returned

## Expected Behavior
List of users who approved MR

## Actual Behavior
Empty list is always returned - approved_by: []

## Specifications

  - python-gitlab version: 4.9.0
  - API version you are using (v3/v4): v4

**Comment by JohnVillalovos** [comment]
Are you using a paid version of GitLab? Self-hosted or gitlab.com?

Can you provide a code sample?

Also you may want to do:

```
gl.enable_debug()
```

So you can see what is sent to GitLab and what is returned.

**Comment by FeNix784** [comment]
We use GitLab Enterprise, code sample:
```python
@dataclass
class MergeRequest:
    project_name_with_namespace: str
    number: int

class GitlabService:
    def __init__(self, config: GitlabConfig):
        self.gl = gitlab.Gitlab(url=config.server, private_token=config.token)

    def get_gitlab_mrs(self, mr_urls: List[MergeRequest]) -> List[ProjectMergeRequest]:
        mrs: List[ProjectMergeRequest] = []

        for project_id, urls_in_project in groupby(mr_urls, lambda mr_url: mr_url.project_name_with_namespace):
            project = self.gl.projects.get(project_id)
            for mr_url in urls_in_project:
                mrs.append(project.mergerequests.get(mr_url.number))
        return mrs

gitlab_service = GitlabService(cnf)

gitlab_mr = gitlab_service.get_gitlab_mrs(mrs)[0]
approvals = gitlab_mr.approvals.get().attributes
```

**Comment by nejch** [comment]
@FeNix784 I'd try to enable debug on your instance as John suggested above and post the HTTP requests here (you can redact the URLs if you like).

If the requests and paramers are sent correctly, then it's probably a different issue.

Related: this could probably use an update:   
https://github.com/python-gitlab/python-gitlab/blob/main/tests/functional/api/test_merge_requests.py#L118

**Comment by FeNix784** [comment]
```
DEBUG:http.client:send: b'GET /api/v4/projects/.../merge_requests/.../approvals HTTP/1.1\r\nHost: ...\r\nUser-Agent: python-gitlab/4.9.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-type: application/json\r\nPRIVATE-TOKEN: [MASKED]\r\n\r\n'

DEBUG:http.client:reply: 'HTTP/1.1 200 OK\r\n'
DEBUG:http.client:header: cache-control: max-age=0, private, must-revalidate
DEBUG:http.client:header: content-type: application/json
DEBUG:http.client:header: date: Thu, 08 Aug 2024 09:21:29 GMT
DEBUG:http.client:header: etag: W/"91a83a470bb5fffc1a8d5cfe2f9c455b"
DEBUG:http.client:header: referrer-policy: strict-origin-when-cross-origin
DEBUG:http.client:header: server: nginx
DEBUG:http.client:header: strict-transport-security: max-age=63072000
DEBUG:http.client:header: vary: Origin
DEBUG:http.client:header: x-content-type-options: nosniff
DEBUG:http.client:header: x-frame-options: SAMEORIGIN
DEBUG:http.client:header: x-request-id: 6ce8f32f-d68b-4124-9667-a167ca1b35d5
DEBUG:http.client:header: x-runtime: 0.049820
DEBUG:http.client:header: transfer-encoding: chunked
DEBUG:http.client:header: vary: Accept-Encoding
DEBUG:http.client:header: content-encoding: gzip
DEBUG:urllib3.connectionpool:https://... "GET /api/v4/projects/.../merge_requests/.../approvals HTTP/11" 200 None

{'project_id': '...', 'mr_iid': '...', 'user_has_approved': False, 'user_can_approve': True, 'approved': False, 'approved_by': []}
```

**Comment by nejch** [comment]
@FeNix784 the request looks completely OK to me:

`GET /api/v4/projects/./merge_requests/.../approvals`

documented API endpoint for `api/v4`:

`GET /projects/:id/merge_requests/:merge_request_iid/approvals`

See https://docs.gitlab.com/ee/api/merge_request_approvals.html#merge-request-level-mr-approvals

So IMO python-gitlab makes the correct request but for whatever reason the server returns an empty list. Maybe you can try to debug the same endpoint with curl or other client e.g.

```
curl -H "private-token: your-token" https://gitlab.your-host.com/api/v4/projects/./merge_requests/.../approvals`
```

If that also returns an empty array in the JSON, you'll have to see why the server returns an empty response. It could be that your token doesn't have the right permissions or so.

**Comment by nejch** [comment]
Also, I just noticed you get an `'approved': False,` attributed, so it seems obvious there would be an empty list for that MR. I think you'll want to double check that you're really listing MRs that have been explicitly approved.

**Comment by FeNix784** [comment]
Yeah, apparently problem is that there are not enough accesses, thanks for help)

**Comment by nejch** [comment]
Alright, thanks for the update. I'll close this issue then, feel free to reopen if you disagree:)
