### ISSUE TITLE
Update assignee of a merge request not possible

### ISSUE THREAD

**Issue by drdude1** [python-gitlab/python-gitlab#297]
Hi,
I'm trying to update the assignee of a merge request with the following command:

gl = Gitlab('http://serveraddress', 'XXXXXX')
projectlist = gl.projects.search(project_name)     #APIv3
#projectlist= gl.projects.list(search='project_name')     #APIv4
project = projectlist[0]
mr = gl.project_mergerequests.create({'source_branch': 'dev', 'target_branch': 'master', 'title': 'merge dev feature'}, project_id=project.id)
**mr.assignee = gl.users.get(2)
mr.save()**

this does not change anything regarding the assignee. mr.assigne=None afterwards and changes are not recognized by the server. But there is no error message.
python-gitlab 0.21.2
GitLab 9.4.1

**Comment by gpocentek** [comment]
Hi,

The correct way to set the assignee is:
```
mr.assignee_id = gl.users.get(2).id
```

**Comment by drdude1** [comment]
Thanks, that worked!

**Comment by purrplingcat** [comment]
It's not working, I got error:

```
Traceback (most recent call last):
  File "submit_ticket.py", line 177, in <module>
    submit_tickets()
  File "submit_ticket.py", line 172, in submit_tickets
    reviewer=reviewer,
  File "submit_ticket.py", line 49, in submit_merge_request
    mr.assignee_id = mr_data['assignee_id']
```
