### ISSUE TITLE
`project-pipeline-schedule-pipeline` does not list all active schedules

### ISSUE THREAD

**Issue by stdedos** [python-gitlab/python-gitlab#2974]
## Description of the problem, including code/CLI snippet

```console
$ gitlab project-pipeline-schedule-pipeline list --project-id "group/project" --get-all
usage: gitlab project-pipeline-schedule-pipeline list [-h] [--sudo SUDO] --project-id PROJECT_ID --pipeline-schedule-id PIPELINE_SCHEDULE_ID [--page PAGE] [--per-page PER_PAGE]
                                                      [--get-all | --no-get-all]
gitlab project-pipeline-schedule-pipeline list: error: the following arguments are required: --pipeline-schedule-id
```

I don't know the `--pipeline-schedule-id`, and hence I want them all.

There is no other "verb" in 

```console
$ gitlab -o json project-pipeline-schedule-pipeline -h
usage: gitlab project-pipeline-schedule-pipeline [-h] {list} ...

optional arguments:
  -h, --help  show this help message and exit

action:
  {list}      Action to execute on the GitLab resource.
    list      List the GitLab resources
```

## Expected Behavior

I am able to get all the schedules listed

## Actual Behavior

```
gitlab project-pipeline-schedule-pipeline list: error: the following arguments are required: --pipeline-schedule-id
```

## Specifications

  - python-gitlab version: 4.10.0
  - API version you are using (v3/v4): 4
  - Gitlab server version (or gitlab.com): 16._latest_

**Comment by nejch** [comment]
@stdedos the command you're trying to use here will "list all pipelines triggered by a particular pipeline schedule" (https://docs.gitlab.com/ee/api/pipeline_schedules.html#get-all-pipelines-triggered-by-a-pipeline-schedule). This is why it's asking for an ID.

If you want to list the actual schedules, what you're looking for is `gitlab project-pipeline-schedule list`.

**Comment by stdedos** [comment]
... I should've thought to pick the shortest one 😓 

It was hard to find what I was looking for, even after coming up with `gitlab -h |& grep pipeline`.

Thank you for the support 🙃
