### ISSUE TITLE
ProjectFileManager does not implement head method to meet API spec

### ISSUE THREAD

**Issue by holysoles** [python-gitlab/python-gitlab#2976]
## Description of the problem, including code/CLI snippet

Attempting to use a HEAD request to retrieve file metadata from a project repository ([Gitlab REST API docs](https://docs.gitlab.com/ee/api/repository_files.html#get-file-metadata-only)) fails with a 404

```python
dest_file_get_args = {
  'file_path': file_def['dest_filepath'],
  'ref': 'HEAD',
}
existing_file = project.files.head(**dest_file_get_args)
```

## Expected Behavior

Should return 200 and file metadata. The same request as a GET request returns 200, and they follow the same URL path and parameter requirements. Sending a GET request logs this URL path:

`
DEBUG:urllib3.connectionpool:https://gitlab.com:443 "GET /api/v4/projects/1/repository/files/somefile.txt?ref=HEAD HTTP/11" 200 418
`

## Actual Behavior

A HTTP HEAD request is sent with the following URL path:
`DEBUG:urllib3.connectionpool:https://gitlab.com:443 "HEAD /api/v4/projects/1/repository/files?file_path=somefile.txt&ref=HEAD HTTP/11" 404 0
`

## Specifications

  - python-gitlab version: ~~3.1.43~~ 4.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): [v16.7.4-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v16.7.4-ee)

**Comment by JohnVillalovos** [comment]
That doesn't seem to be a `HEAD` request. It is a `GET` request that is asking for the ref called `HEAD`

**Comment by holysoles** [comment]
@JohnVillalovos its a HEAD request asking for the HEAD ref. I can generate additional logs for other refs.

**Comment by holysoles** [comment]
Working GET for master ref
`DEBUG:urllib3.connectionpool:https://gitlab.com:443 "GET /api/v4/projects/1/repository/files/somefile.txt?ref=master HTTP/11" 200 417`

Failing HEAD for master ref
`DEBUG:urllib3.connectionpool:https://gitlab.com:443 "HEAD /api/v4/projects/1/repository/files?file_path=somefile.txt&ref=master HTTP/11" 404 0`

**Comment by holysoles** [comment]
I'm pretty sure this is because `GetMixin` is inheriting `HeadMixin` and in `ProjectFileManager` we are overriding the `get` method, but that wouldn't override the default `head` method as far as I'm aware

**Comment by JohnVillalovos** [comment]
As a note. Your python-gitlab version is fairly old.

This almost seems like an issue with GitLab. But not sure. Would be interesting to try a `curl` test using both GET and HEAD. If only HEAD fails then something wrong with GitLab. If they both work then something happening with python-gitlab.

**Comment by holysoles** [comment]
@JohnVillalovos  i can update my version and test again, but I've tested [this commit](https://github.com/python-gitlab/python-gitlab/compare/main...holysoles:python-gitlab:main) and it works. Happy to open a PR if appropriate

Wasnt sure if i should explicitly inherit `HeadMixin` or not in it.

**Comment by holysoles** [comment]
Also apologies, my version is 4.9.0, i grabbed the wrong dependency version from my requirements file

**Comment by JohnVillalovos** [comment]
> @JohnVillalovos i can update my version and test again, but I've tested [this commit](https://github.com/python-gitlab/python-gitlab/compare/main...holysoles:python-gitlab:main) and it works. Happy to open a PR if appropriate
> 
> Wasnt sure if i should explicitly inherit `HeadMixin` or not in it.

PR sounds like a good idea. Thanks.

**Comment by nejch** [comment]
@JohnVillalovos @holysoles might also be a good idea to not inherit from GetMixin in that case if we're overriding it, to avoid this kind of confusion in the future. Not sure if there's any other implication there.

**Comment by holysoles** [comment]
I should be able to get the PR opened tomorrow after I functionally test my update, but its passing unit tests
