### ISSUE TITLE
Protect branches based on regex

### ISSUE THREAD

**Issue by arnaudgelas** [python-gitlab/python-gitlab#299]
I would like to protect branches `*-stable`, but I do not see how to proceed?

**Comment by gpocentek** [comment]
Hi,

You need to loop through the list of branches, test if the name matches your pattern, then protect the branch. There is no existing API for doing what you want automatically.

```python
for branch in project.branches.list():
    if (test the name here):
        branch.protect()
```

**Comment by arnaudgelas** [comment]
Hi,
is there any plan to support this?

Note that gitlab api supports this:

https://docs.gitlab.com/ce/api/protected_branches.html#protect-repository-branches

**Comment by gpocentek** [comment]
Looks like I missed this Gitlab API, but it's quite new (9.5 has not been released yet AFAIK).

I'll add support for this for the v4 API. Thanks!

**Comment by arnaudgelas** [comment]
Awesome :+1:

**Comment by AlexanderLill** [comment]
That would be really great. Is there work in progress already?
