### ISSUE TITLE
Support for Related Issues in Python-GitLab Merge Requests API

### ISSUE THREAD

**Issue by kkc-tonywu** [python-gitlab/python-gitlab#3001]
## Description of the problem, including code/CLI snippet

According to the documentation on the [Merge requests API | GitLab](https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-related-to-the-merge-request), it supports finding related issues through merge requests. However, I confirmed that the [Merge requests - python-gitlab v4.11.1](https://python-gitlab.readthedocs.io/en/v4.11.1/gl_objects/merge_requests.html) documentation does not support this feature. Is there any expectation for support in the future?

## Specifications

  - python-gitlab version: 4.11.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 17.3

**Comment by nejch** [comment]
As stated in the release notes, this was released in v4.12.0 so it's expected that it's not present in 4.11.1 yet.

See https://python-gitlab.readthedocs.io/en/v4.12.0/gl_objects/merge_requests.html. I'll close this but let us know if there are any other issues with the docs!
