### ISSUE TITLE
Python 3.14 breaks unit tests

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#3013]
See https://docs.python.org/3.14/whatsnew/3.14.html on how to resolve this.

Due to how Python 3.14 is doing annotations and in particular being able to inspect `__annotations__` we will need to make changes to fix it.

The one line which seems to be causing the failures is:
https://github.com/python-gitlab/python-gitlab/blob/1a68f1c5ff93ad77c58276231ee33f58b7083a09/gitlab/base.py#L204

Example error:
```
AttributeError: 'FakeParent' object has no attribute '__annotations__'. Did you mean: '__annotate__'?
```

**Comment by JohnVillalovos** [comment]
@nejch I discovered this when trying to do this PR: https://github.com/python-gitlab/python-gitlab/pull/3012

**Comment by nejch** [comment]
From the looks of it, I hope they provide an annotationlib backport for older pythons as we kind of rely on this for the managers. Would be a shame to go back to adding more bloat unless there's another way 🙇
