### ISSUE TITLE
Support Creating "Hidden" CICD Variables (brand-new gitlab.com feature)

### ISSUE THREAD

**Issue by twoodhouse** [python-gitlab/python-gitlab#3016]
## Description of the problem, including code/CLI snippet
ProjectVariableManager does not support using GitLab's new "Hidden" feature which makes CICD variables so that they cannot be viewed after creation.

![image](https://github.com/user-attachments/assets/114b8480-1002-4e5b-aee4-647ed557e50b)

See "optional" section below. I'm pretty sure that needs a new field called "hidden"

```
class ProjectVariableManager(CRUDMixin, RESTManager):
    _path = "/projects/{project_id}/variables"
    _obj_cls = ProjectVariable
    _from_parent_attrs = {"project_id": "id"}
    _create_attrs = RequiredOptional(
        required=("key", "value"),
        optional=("protected", "variable_type", "masked", "environment_scope"),
    )
```

I'd expect to be able to use it like this:

```
target_project.variables.create(
                {
                    "key": cicd_var_name,
                    "value": value,
                    "hidden": True,
                    "raw": False,
                    "protected": True,
                    "description": ""
                }
            )
```

## Expected Behavior
Gitlab-python should support using the new feature

## Actual Behavior
Seemingly, no support for new feature

## Specifications

  - python-gitlab version: 4.13.0
  - API version you are using (v3/v4): (not sure)
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
I don't see any such `hidden` attribute in the GitLab docs: https://docs.gitlab.com/ee/api/project_level_variables.html#create-a-variable

Probably should file an issue with GitLab to expose this setting via the REST API.

**Comment by nejch** [comment]
It's not documented at all, maybe because it was behind a feature flag for a while, but the API seems to return `hidden`. 

Annoyingly, it seems like the create argument is actually `masked_and_hidden`:

https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/api/ci/variables.rb#L63

@twoodhouse so you should be able to use that on creation. No change is needed on the python-gitlab side. Just let us know if that doesn't work.

**Comment by twoodhouse** [comment]
Thank you! I will try that and report back.

**Comment by nejch** [comment]
Hey @twoodhouse I documented this in https://gitlab.com/gitlab-org/gitlab/-/merge_requests/170131. If there's anything else that's missing please let me know and we can reopen this :bow:

**Comment by twoodhouse** [comment]
Thank you! I did end up confirming this works.
