### ISSUE TITLE
Release with non-experimental v4 support?

### ISSUE THREAD

**Issue by kjwilcox** [python-gitlab/python-gitlab#302]
Hi, this library looks awesome, but I've been hesitant to start using it since v4 support was experimental, and all of my current hand-rolled api code runs against the v4 API. I've been following the commit history and it looks like v4 support is no longer experimental in master. Any chance of a release soon so I can take advantage of that?

Thanks!

**Comment by witten** [comment]
I would also like to see a release with API v4 support!

**Comment by gpocentek** [comment]
Hi,

Yes I should definitely release a stable version. I would like to tackle one last problem related to the CLI first.

I'll do my best to do this release soon but can't give you a date for the release.

Thanks!

**Comment by kjwilcox** [comment]
Thanks for the response, sounds good!
