### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by axelfauvel** [python-gitlab/python-gitlab#303]
Create a repository branch:

```
branch = gl.project_branches.create({'branch_name': 'feature1',
                                     'ref': 'master'},
                                    project_id=1)
# or
branch = project.branches.create({'branch_name': 'feature1',
                                  'ref': 'master'})
```
is incorrect, 

Create a repository branch:
```
branch = gl.project_branches.create({'branch': 'feature1',
                                     'ref': 'master'},
                                    project_id=1)
# or
branch = project.branches.create({'branch': 'feature1',
                                  'ref': 'master'})
```
is correct

------
In page: gl_objects/branches.rst

**Comment by gpocentek** [comment]
Hi,

Thank you for reporting this. The currently version of the doc is correct if you use the v3 API.

This change is documented in the master branch: http://python-gitlab.readthedocs.io/en/latest/gl_objects/branches.html

**Comment by axelfauvel** [comment]
you're right, i'm using v4 API

**Comment by gpocentek** [comment]
The doc has been updated with the 1.0.0 release, both v3 and v4 versions are documented now.
