### ISSUE TITLE
RFC: Should we get rid of the respx library?

### ISSUE THREAD

**Issue by JohnVillalovos** [python-gitlab/python-gitlab#3058]
The respx project hasn't had any commits for 9 months as of today: https://github.com/lundberg/respx/  Also I don't see the maintainer interacting with the project in issues for a long time.

Currently it doesn't work with the new version of httpx: https://github.com/lundberg/respx/issues/277

This is blocking us from moving forward with updating httpx.

Another option could be we fork the project and bring it under our namespace here, and then fix the issue we have and then publish a version ourselves.

**Comment by nejch** [comment]
There's also https://colin-b.github.io/pytest_httpx/ with a similar API but also seems to be a one-man show and could easily have the same problem in the future so I'd prefer if we could avoid the ping-pong of switching libraries, let's maybe see what happens upstream - I'll comment as well.

Maybe just moving to an organization where a few other maintainers are present to merge basic things like deps and fixes would be enough.

**Comment by nejch** [comment]
I think we're ok now that it was released. Let's hope it stays maintained, there was no follow-up on adding more maintainers.


See #3068

**Comment by JohnVillalovos** [comment]
> I think we're ok now that it was released. Let's hope it stays maintained, there was no follow-up on adding more maintainers.

He did say that sounded like a good idea.
