### ISSUE TITLE
Add avatar for a user with python

### ISSUE THREAD

**Issue by Starfight** [python-gitlab/python-gitlab#308]
I try to add an avatar to a user but I don't understand which format to use. I have try:
* base64 (raw and with mimetype)
* binary
* path

Nothings seem to work, [Gitlab API](https://docs.gitlab.com/ee/api/users.html#user-creation) do not specify format here and in Gitlab code repository, they use ruby method [`fixture_file_upload`](https://gitlab.com/gitlab-org/gitlab-ce/commit/2923a0c8fede436fd407b76537fee963a13ac3ea)

**Comment by gpocentek** [comment]
Thanks for your report.

To be honest I haven't tested this feature, but from what you describe and what I gathered it needs file upload features, which are not supported by python-gitlab at the moment. So this needs a bit of work on our side.
