### ISSUE TITLE
gitlab.exceptions.GitlabError switched fields error_message and response_code

### ISSUE THREAD

**Issue by tomascapek** [python-gitlab/python-gitlab#313]
I recently updated to version 1.0.0 and was surprised by fact, that suddenly fields `error_message` and `response_code` of `gitlab.exceptions.GitlabError` are switched for no apparent reason. 

I found out, when I tried to use `gitlab.v4.objects.Project.branches.list(all = True)` on repository without access to it (403 followed). I didn't test, if this error happen anywhere else.

Could you switch them back? Current state seems counterintuitive.

**Comment by gpocentek** [comment]
Thanks for reporting this! Could you test with the master branch? I believe this has been fixed.

**Comment by tomascapek** [comment]
Wow, thanks for fast reply! I tried it on my default branch (not named "master") in my testing repository and I was able to list only 20 files (from 1300 I pushed there). Side note: I don't use `recursive` option and I use this:

    def list_files(path = ''):
        for blob in self._repo.repository_tree(path, branch, all = True):
            if blob['type'] == 'blob':
                yield blob['path']
            elif blob['type'] == 'tree':
                yield from list_files(blob['path'])

`recursive` option didn't work for me a while back, when I wrote this. Should I use it?

**Comment by tomascapek** [comment]
I think I don't understand your question - how do I test it with the master branch?

**Comment by tomascapek** [comment]
Tried, but got same result.

**Comment by gpocentek** [comment]
Thanks, I'll take care of this ASAP.

**Comment by tomascapek** [comment]
Thanks!!!

**Comment by gpocentek** [comment]
Looks fixed in master. With v1.0.0 here is what I have (`e` is a GitlabException):
`````python
{'error_message': 404,
 'response_body': None,
 'response_code': '{"message":"404 Project Not Found"}'}
`````

Using the master (current development):
```python
In [11]: vars(e)
Out[11]: 
{'error_message': '{"message":"404 Project Not Found"}',
 'response_body': '{"message":"404 Project Not Found"}',
 'response_code': 404}
```

The error_message is not correct thought, it should not be the complete json string. Fix coming up.

**Comment by tomascapek** [comment]
I believe you, but I still got the same wrong results. I cloned repository, created package myself and reproduce the bug using `gitlab.v4.objects.Project.branches.list(all = True)` to get 403 and just to be sure, I even tried to get 404 using `gitlab.Gitlab.projects.get(name)`, but both, with wrong results, different from yours. What should I do to help you solve this problem? May it be in version of Gitlab instance? I am running version 9.5.1

**Comment by gpocentek** [comment]
@tomascapek maybe you have 2 versions installed on your system (in `/usr` and `/usr/local)?

Could you test using a virtualenv?

Thanks for your feedback.

**Comment by tomascapek** [comment]
Seems to be working now (version 1.0.1), thanks for you great work!
