### ISSUE TITLE
Listing all files from repository fails because of pagination

### ISSUE THREAD

**Issue by tomascapek** [python-gitlab/python-gitlab#314]
I was trying to list all files on given branch in given repository using `gitlab.v4.objects.Project.repository_tree(path, branch_name, all = True)`, but result was truncated, because of Gitlab pagination. 

From your docs, I thought, that `all = True` should work on any type of "request". I looked into the code and find out, that this isn't implemented.

Should this be implemented in your package or am I approaching this task in a wrong way?

**Comment by gpocentek** [comment]
Indeed `all = True` is not supported on `Project.repository_tree()`. It needs to be explicitly added, and a few other methods have the same problem.

You can still use the pagination options for now (`page` and `per_page` arguments).

Thanks for reporting this issue.

**Comment by tomascapek** [comment]
Thanks for quick reply. I used those options

**Comment by gpocentek** [comment]
`all = True` should work as expected now.

**Comment by tomascapek** [comment]
Thanks for your great work!
