### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by juliandavidmr** [python-gitlab/python-gitlab#318]
I need create a connection with gitlab, but I dont know as configure a `url` server, the examples show `http://10.0.0.1`, I tested with `https://gitlab.anlijudavid.com/api/v4/projects` and others urls but not work. 

are there some example?

Thanks

**Comment by ViachaslauKabak** [comment]
just server name and port if needed
Do you have any error?
what is your connection parameters?

**Comment by gpocentek** [comment]
Hi @juliandavidmr,

What you're asking for is probably this: http://python-gitlab.readthedocs.io/en/stable/api-usage.html#gitlab-gitlab-class

Let me know if it helps.

**Comment by melMass** [comment]
I had the same issue. If you are using gitlab.com:

```python
# private token authentication

gl = gitlab.Gitlab('https://gitlab.com', '<YOUR-PRIVATE-TOKEN>', api_version=4)
```
