### ISSUE TITLE
Question about application-settings

### ISSUE THREAD

**Issue by smutel** [python-gitlab/python-gitlab#319]
Hello,

I tried this command line to disable signup function:
gitlab application-settings update --id 6 --signup-enabled false

I received error message: Impossible to get object (get() got multiple values for keyword argument 'id')
What's wrong?

I don't think so that it's a bug. Is another place to ask question (forum, slack, ...)?

Thanks.

**Comment by gpocentek** [comment]
Hi @smutel 

This looks like a problem in python-gitlab, `--id`` shouldn't be needed here.
