### ISSUE TITLE
PR approvals

### ISSUE THREAD

**Issue by Divailo** [python-gitlab/python-gitlab#323]
Since gitlab 8.9 there is a support for approvals information for PRs

https://docs.gitlab.com/ee/api/merge_requests.html#merge-request-approvals

However, the library atm doesn't support that feature. It would be amazing if by calling 

> merge_request.approvals

 to retrieve all the information of approvals of the repo

**Comment by gpocentek** [comment]
Hi @Divailo, This feature is indeed missing, because it's only available in Gitlab EE. I don't have access to an EE installation, so I can't properly test and support this feature.

I'll see what I can do though, but cannot guarantee that this feature will be implemented.

**Comment by jogu** [comment]
Just FYI, merge requests approvals are also available to any 'public' visibility project on gitlab.com (I believe all GitLab EE features are), so you can likely test by simply creating a free gitlab.com account and public project to test? Just enable 'Merge request approvals' in Settings->General->Merge requests settings.

**Comment by gpocentek** [comment]
Partially implemented in #515
