### ISSUE TITLE
 'Gitlab' object has no attribute 'user_projects'

### ISSUE THREAD

**Issue by ektich** [python-gitlab/python-gitlab#324]
Documentation on readthedocs for version 1.0.1 suggests using `user_projects.create` call to create project on behalf of a user, but trying to do it results in `AttributeError: 'Gitlab' object has no attribute 'user_projects'`.  I can see references to `UserProjectManager` in the code, but I cannot figure out how to create user projects. In any case documentation has to be updated.

**Comment by gpocentek** [comment]
Thanks for reporting this issue @ektich.

I've updated the docs. You need to create a user object first, then user the `projects` manager to create the project. If the user already exists you can do something like `gl.users.get(user_id, lazy=True).projects.create(project_data)`.
