### ISSUE TITLE
Missing API for accessing project users

### ISSUE THREAD

**Issue by mschmieder** [python-gitlab/python-gitlab#328]
The API for accessing all users of a project is missing. See 
https://docs.gitlab.com/ce/api/projects.html#get-project-users

I did not find another way using the python-gitlab api to query for project users (not members)

**Comment by gpocentek** [comment]
Hi @mschmieder,

You're right, this API feature is not implemented in python-gitlab. A solution until the feature becomes available is to use the `http_*` method of the Gitlab object to perform raw HTTP requests.
