### ISSUE TITLE
User() does not list all users

### ISSUE THREAD

**Issue by marcolefo** [python-gitlab/python-gitlab#33]
Hello

I am trying to list my gitlab users. So I do :

``` shell
Python 2.7.3 (default, Jan  2 2013, 13:56:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gl = gitlab.Gitlab('http://gitlab.domain/gitlab',"admin_token")
>>> gl.auth()
>>> for u in gl.User():
...     print u.username
```

But, this only list the 20 first users. Is there a way to bypass this limit ?
Thanks

GitLab 6.9.2
GitLab Shell 1.9.4
GitLab API v3
Ruby 2.1.2p95
Rails 4.0.5

**Comment by Asher256** [comment]
Is it possible to list all users without specifying the per page parameter?

If I put all=True in the arguments, it could show all users?
