### ISSUE TITLE
Automatic pagination support

### ISSUE THREAD

**Issue by tardyp** [python-gitlab/python-gitlab#331]
Using python-gitlab, I often end-up having to write the same boilerplate code in order to handle paging, e.g:
```
    def getAllProjects(self):
        """get all projects, dealing with paging"""
        page = 1
        while True:
            projects = self.gl.projects.list(per_page=100, page=page)
            if not projects:
                break
            for project in projects:
                yield project
            page += 1
```

I think this would make sense to add that generator into the python-gitlab api:

something like:
```
self.gl.projects.generator()
# or
self.gl.projects.list(generator=True)
```

thoughts?

Any tips to guide me how to properly implement that?

**Comment by tardyp** [comment]
Sorry for the noise.

following works as intented:
```
gl.projects.list(as_list=False)
```

as per doc http://python-gitlab.readthedocs.io/en/stable/switching-to-v4.html?highlight=as_list

**Comment by gpocentek** [comment]
@tardyp no problem, glad you found what you were looking for!
