### ISSUE TITLE
Can't create GitLab tag release API v4

### ISSUE THREAD

**Issue by mzimandl** [python-gitlab/python-gitlab#332]
I'm trying to create GitLab release like that:
```
tag = self._gitlab_project.tags.get(tag_name)
tag.set_release_description(release_note)
```
but all I get is 404
```
gitlab.exceptions.GitlabHttpError: 404: b'{"error":"404 Not Found"}'
```
The tag is returned correctly but I can't create or update GitLab releases. Using clients method `http_put ` manually works fine as well as using `requests` module.

**Comment by gpocentek** [comment]
Hi @mzimandl,

Is there a special character in your tag (`/` or `.`) ?

**Comment by mzimandl** [comment]
@gpocentek Thank you, that's exactly my case :+1:
