### ISSUE TITLE
Does python-gitlab work through a proxy?

### ISSUE THREAD

**Issue by mgoodhand** [python-gitlab/python-gitlab#341]
I sometimes connect to GitLab through an SSH tunnel.

When I use `requests` directly, I find that it respects the `https_proxy` environment variable (or I can set `proxies` on each request).

`python-gitlab` seems not to pick up on `https_proxy`, and I haven't found a way to specify a proxy explicitly.

Is this a known issue, or am I just failing to find the appropriate option?

**Comment by mgoodhand** [comment]
I managed to get it working by creating a `requests.Session()`, setting the proxy on it, and instantiating GitLab with the (undocumented) `session` argument.

```
session = requests.Session()
session.proxies = {
                    "https": os.environ.get("https_proxy"),
                    "http": os.environ.get("http_proxy"),
                  }
gl = gitlab.Gitlab(args.base_url,
                            args.token,
                            api_version=4,
                            session=session)
```

**Comment by gpocentek** [comment]
Using the requests session is the way to go. I'll add your sample to the docs if that's OK with you.

**Comment by mgoodhand** [comment]
Sounds good. Thanks.
