### ISSUE TITLE
Next patch/version?

### ISSUE THREAD

**Issue by tomascapek** [python-gitlab/python-gitlab#344]
Hello! When do you plan to release next patch/version? My project is depending on one fix that is already done. I am not trying to create pressure on you, I just wanna know

**Comment by gpocentek** [comment]
Hi @tomascapek,

There are a few simple issues waiting to be fixed, I'd like to tackle them before doing a release. If I can't manage it soon enough I'll do a micro release by the end of next week.

**Comment by gpocentek** [comment]
Version 1.1.0 has been released.
