### ISSUE TITLE
python-gitlab objects are not pickle-able

### ISSUE THREAD

**Issue by lnenov** [python-gitlab/python-gitlab#345]
Starting with support for Gitlab API v4, the following classes gitlab.Gitlab, base.GitlabObject and base.RESTObject are not pickle-able because of the references to modules they keep as properties (_module and _objects).

I run into the issue when I use a  multiprocessing.Pool and [tqdm](https://pypi.python.org/pypi/tqdm) to run git operations in parallel and show a progress bar.

I created and am currently using a small patch at https://github.com/python-gitlab/python-gitlab/commit/a8f149392edc8e6a2cf0629878e873dbd271be4e. If the issue and a possible approach are approved I have some time to invest to create a proper PR.

**Comment by gpocentek** [comment]
Hi @lnenov,

I guess serialization should be supported, and your patch looks OK to me. Do you think you could add some basic unit tests for your PR?

Thanks!

**Comment by lnenov** [comment]
Thanks for the quick merge and release
