### ISSUE TITLE
problems setting release notes for a tag containing a "/"

### ISSUE THREAD

**Issue by ksuruliz** [python-gitlab/python-gitlab#347]
Hello,

I'm having trouble changing the release notes of a tag whose name is "release/1.0.0" - I do

mytag = project.tags.get('release/1.0.0')
mytag.set_release_description('Test description')

This fails with a GitlabCreateError: 404: {"error": "404 Not Found"}

On the other hand, it works fine for a tag named e.g. "v1". Any idea what the problem might be?

Cheers

Kerim

**Comment by gpocentek** [comment]
Hi @ksuruliz 

Thank for taking the time to report the issue!

This problem is already fixed (see #332), and the change be part of the next python-gitlab release, which should happen sometime next week.

**Comment by ksuruliz** [comment]
Hi @gpocentek,

Many thanks for the prompt response. I look forward to the new release!
