### ISSUE TITLE
Adding SSH keys not supported with latest GitLab API?

### ISSUE THREAD

**Issue by max-wittig** [python-gitlab/python-gitlab#351]
It seems like adding SSH keys via API for Gitlab API 4 is not supported, yet.
Is that right or am I missing something?

> From gitlab/__init__.py
``` python
...
self.users = objects.UserManager(self)
        self.todos = objects.TodoManager(self)
        if self._api_version == '3':
            self.keys = objects.KeyManager(self)
            self.teams = objects.TeamManager(self)
        else:
            self.dockerfiles = objects.DockerfileManager(self)

        # build the "submanagers"
        for parent_cls in six.itervalues(vars(objects)):
...
```

**Comment by gpocentek** [comment]
@max-wittig in v4 the keys manager has been renamed ``deploykeys``. Is that what you are looking for?

**Comment by max-wittig** [comment]
Yes. I somehow didn't find that in the documentation. Thanks.
But there is no support for GPG keys, yet right?

**Comment by gpocentek** [comment]
I don't think deploykeys are what you're looking for.

The `Gitlab` object holds a `user` attribute which represents the current user (make sure to call `gl.auth()` to create this object). You can create SSH keys for this user using its `keys` manager:

```python
gl = gitlab.Gitlab(...)
gl.auth()  # required if you use private_token authentication
gl.user.keys.create({'title': 'mykey', 'key': the_key})
```

You can also create SSH keys for other users if your current user is an admin: `gl.users.get(user_id).keys.create({...})`

GPG key are not yet supported in python-gitlab (#355).
