### ISSUE TITLE
AttributeError on getting users' keys or emails

### ISSUE THREAD

**Issue by BancarelValentin** [python-gitlab/python-gitlab#354]
When trying to retrieve user ssh keys or emails, I got an AttributeError saying that keys (or emails) attribute does not exists.

Error occured on line 8 (and 10 if executed first) of this code)

The `masterPrivateToken`  variable is created on an admin account, and is granted for everything (api, user_info, registry)

```
gitlabInstance = gitlab.Gitlab(gitlabUrl, masterPrivateToken, api_version=4)
gitlabInstance.auth()

for project in gitlabInstance.projects.list(all=True):
    if project.environments.list(all=True):
        for user in project.members.list(all=True):
            if user.access_level==gitlab.OWNER_ACCESS or user.access_level==gitlab.MASTER_ACCESS:
                for email in user.emails.list():
                    print(email)
                for key in user.keys.list():
                    print(key)
    else:
        print("\tNo environement configured.")

    print("")
    print("==================================")
    print("")
```

**Comment by gpocentek** [comment]
Hello @BancarelValentin,

This is the expected behavior. your `user` is a `ProjectMember`, which doesn't expose methods to access the user emails and keys. python-gitlab reproduces the Gitlab API: https://docs.gitlab.com/ce/api/members.html

If you want to access the emails and keys you need to build a `User` object (setting `lazy` to `True` avoids an API call):

```python
>>> project = projects.members.list()[0]
>>> user = project.members.list()[0]
>>> type(user)
<class 'gitlab.v4.objects.ProjectMember'>
>>> real_user = gl.users.get(user.id, lazy=True)
>>> type(real_user)
<class 'gitlab.v4.objects.User'>
>>> real_user.emails.list()
[]
>>> real_user.keys.list()
[]
```

**Comment by BancarelValentin** [comment]
Hello, 

Ok thanks a lot for those clarifications. I didn't understood that correctly from the doc (which is still great BTW).

Thanks for the awesome work!

**Comment by gpocentek** [comment]
Thanks for your feedback :)

I'll try to improve the docs to make things clearer.
