### ISSUE TITLE
Python-gitlab to return archive URL

### ISSUE THREAD

**Issue by atrisovic** [python-gitlab/python-gitlab#356]
Hi there,

Is it possible to retrieve a link of a repository archive, eg: `link = repo.get_archive_link("tarball")` with python-gitlab?

I know about `tgz = repo.repository_archive()` which returns the tarball, but getting the link would be much better in our use case.

Can this be a new feature?

Thank you,
Ana

**Comment by atrisovic** [comment]
Hi!
Thank you for the prompt reply!
Yes, that is true (and I can use it as our current solution). However, we would like to get the URL through the API, so if there are any changes in gitlab, they are taken care of in the package update :)

**Comment by gpocentek** [comment]
I understand, but unfortunately there's nothing I can do on the python-gitlab side.

You should probably report the issue on the Gitlab tracker if you would like to see this feature implemented: https://gitlab.com/gitlab-org/gitlab-ce/issues.

**Comment by atrisovic** [comment]
Ok thank you!

**Comment by vikramuk** [comment]
Dated Reply but you could try
  Instructions for Downloading the List of Repository per project could be listed from this API: https://docs.gitlab.com/ee/api/repositories.html#get-file-archive


1.	Send API call with http://git.code.hcvpc.io/api/v4/projects/<PROJECTID>/repository/archive.zip.
2.	Save the Archive file to Storage location
