### ISSUE TITLE
Cannot retieve group milestones

### ISSUE THREAD

**Issue by BancarelValentin** [python-gitlab/python-gitlab#366]
As the [doc states:](http://python-gitlab.readthedocs.io/en/stable/gl_objects/milestones.html)  `myGroup.milestones.list()` should return a list of milestones present in myGroup (myGroup being a <class 'gitlab.v4.objects.Group'>). 

But in the reference, the Group object ([v3](http://python-gitlab.readthedocs.io/en/stable/api/gitlab.v3.html#gitlab.v3.objects.Group), [v4](http://python-gitlab.readthedocs.io/en/stable/api/gitlab.v4.html#gitlab.v4.objects.Group)) has no attribute `milestones`. 

And s excepted when the above code run I get an attribute error :/

````python
group = gitlabInstance.groups.get(namespace)
print group.milestones.list()
````

**Comment by gpocentek** [comment]
Hello @BancarelValentin,

Can you make sure that you are running the latest python-gitlab?

Thanks.

**Comment by BancarelValentin** [comment]
Hello @gpocentek, 

That solved the problem. Thanks one more time 👍

**Comment by LiamInJapan** [comment]
I seem to also be getting this as of 2.10.1

```
def listAllMilestonesAndRelevantDates():
	groups = gl.groups.list()

	for group in groups:
		g_milestones = group.milestones.list(all=True)
		print(group.milestones) # <gitlab.v4.objects.milestones.GroupMilestoneManager object at 0x10a30a730>
		print(g_milestones) # empty
		for milestone in g_milestones:
			print(milestone.name) # empty
```
