### ISSUE TITLE
context for gitlab.Gitlab

### ISSUE THREAD

**Issue by gsemet** [python-gitlab/python-gitlab#371]
Hello. It would be appreciable to have a context manager for `Gitlab()` class, and so be able to do:

```
with gitlab.Gitlab(gitlab_url, gitlab_token) as gl:
   ...
```

**Comment by gpocentek** [comment]
This should not be to complex to implement but I'm not sure I see the point. Could you describe a use case?

Thanks!

**Comment by Stibbons** [comment]
Like the [Session api](http://docs.python-requests.org/en/master/user/advanced/) of request. No other advanced use case

**Comment by gsemet** [comment]
thx !
