### ISSUE TITLE
provide list of task of an issue

### ISSUE THREAD

**Issue by goern** [python-gitlab/python-gitlab#375]
I want to retrieve task lists from an issue. A task list is a special formatted text of the issue description. See https://about.gitlab.com/2014/10/22/gitlab-7-4-released/ for a detailed description.

**Comment by gpocentek** [comment]
@goern The task list is just part of the issue description (`issue.description`). As far as I know there is no Gitlab API to extract the tasks lists automatically. You need to parse the description if you need to do something with the list.

Feel free to reopen the issue if such an API exists.
