### ISSUE TITLE
Failed to save issue

### ISSUE THREAD

**Issue by stratosgear** [python-gitlab/python-gitlab#376]
Trying a simple:

```
$ python
Python 3.6.3 (default, Oct 24 2017, 14:48:20)                                                                                                                                             
[GCC 7.2.0] on linux                                                                                                                                                                      
Type "help", "copyright", "credits" or "license" for more information.                                                                                                                    
>>> import gitlab
>>> gl = gitlab.Gitlab('http://gitlab.com', 'XXXXXXXXXXXXX', api_version=4)
>>> i = gl.projects.get(XXXXXX).issues.get(XXXX)
>>> i.save()
Traceback (most recent call last):
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/exceptions.py", line 239, in wrapped_f
    return f(*args, **kwargs)
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/mixins.py", line 222, in update
    return self.gitlab.http_put(path, post_data=data, **kwargs)
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/__init__.py", line 834, in http_put
    post_data=post_data, **kwargs)
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/__init__.py", line 713, in http_request
    response_body=result.content)
gitlab.exceptions.GitlabHttpError: 400: b'{"error":"title, description, assignee_ids, assignee_id, milestone_id, labels, created_at, due_date, confidential, state_event, weight, discussion_locked are missing, at least one parameter must be provided"}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/mixins.py", line 281, in save
    server_data = self.manager.update(obj_id, updated_data, **kwargs)
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/exceptions.py", line 241, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabUpdateError: 400: b'{"error":"title, description, assignee_ids, assignee_id, milestone_id, labels, created_at, due_date, confidential, state_event, weight, discussion_locked are missing, at least one parameter must be provided"}'
>>> i.title
'Sample issue'
>>> i.description
'Sample description'
```

fails on the current 10.1.3-ee version of gitlab.com.

**Comment by stratosgear** [comment]
Using `http_put` fails too:

```
>>> i_json = json.dumps(i._attrs)
>>> gl.http_put('/projects/XXXXX/issues/XXXX', post_data=i_json)
  File "<stdin>", line 1, in <module>
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/__init__.py", line 834, in http_put
    post_data=post_data, **kwargs)
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/__init__.py", line 713, in http_request
    response_body=result.content)
gitlab.exceptions.GitlabHttpError: 400: b'{"error":"title, description, assignee_ids, assignee_id, milestone_id, labels, created_at, due_date, confidential, state_event, weight, discussion_locked are missing, at least one parameter must be provided"}'
>>>
```

I'm using the `iid` for issue id.

**Comment by gpocentek** [comment]
Hi @stratosgear 

In your first example you are sending an empty request to the server (no attribute update), Gitlab doesn't handle that. Could you try updating your issue object first (`issue.description += ' '` should be enough) and try the save() method again?

**Comment by stratosgear** [comment]
Hi Gauvain,

I forgot to mention that I already tried that.  It is not reflected in my minimum recreatable snippet above, but that's what I was doing in my original case.

For what it's worth, here it is again:

```
Python 3.6.3 (default, Oct 24 2017, 14:48:20)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gl = gitlab.Gitlab('http://gitlab.com', 'sbQ2gSMB6__fkHX6C9Mt', api_version=4)
>>> i = gl.projects.get(3205228).issues.get(1)
>>> i.description
'Edited description'
>>> i.description = "Some new description"
>>> i.description
'Some new description'
>>> i.save()
Traceback (most recent call last):
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/exceptions.py", line 239, in wrapped_f
    return f(*args, **kwargs)
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/mixins.py", line 222, in update
    return self.gitlab.http_put(path, post_data=data, **kwargs)
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/__init__.py", line 834, in http_put
    post_data=post_data, **kwargs)
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/__init__.py", line 713, in http_request
    response_body=result.content)
gitlab.exceptions.GitlabHttpError: 400: b'{"error":"title, description, assignee_ids, assignee_id, milestone_id, labels, created_at, due_date, confidential, state_event, weight, discussion_locked are missing, at least one parameter must be provided"}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/mixins.py", line 281, in save
    server_data = self.manager.update(obj_id, updated_data, **kwargs)
  File "/home/stratos/.virtualenvs/gliss-django/lib/python3.6/site-packages/gitlab/exceptions.py", line 241, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabUpdateError: 400: b'{"error":"title, description, assignee_ids, assignee_id, milestone_id, labels, created_at, due_date, confidential, state_event, weight, discussion_locked are missing, at least one parameter must be provided"}'
```

**Comment by fritruc** [comment]
I have the same issue only on gitlab.com, on private instance it works fine

**Comment by gpocentek** [comment]
@stratosgear @fritruc 

I've just tested to create then update (change description and assignee) an issue on gitlab.com, and everything went fine. Do you still have the same problem? It might have been a temporary regression on gitlab.com.

Thank you for your feedback.

**Comment by fritruc** [comment]
Yes, still there

**Comment by fritruc** [comment]
Oh, if i use https://gitlab.com (instead of http), it works fine

**Comment by stratosgear** [comment]
I concur.  Testing with https is working indeed (funny how I missed that).

But what a weird and confusing error response is this!  I would expect the GET to also fail...

Anyways, I have already switched to plain `requests` calls now, where I indeed use `https` there :(

**Comment by gpocentek** [comment]
Thanks for your feedback on this!

I could probably check the content of the response (is it valid json?), but it is still very surprising that gitlab.com returns 2xx responses on http requests...

**Comment by fritruc** [comment]
Calling api with http://gitlab.com returns an 301 redirection (to https)
python requests on 301 send a new requests to "Location" (https://gitlab.com/***) but it seems that the payload is lose in this requests. And then gitlab response is normal (400) since no data is provided by the second request. But it seems odd that requests don't handle this

**Comment by fritruc** [comment]
Well:
requests (with allowed redirection) erase the body of request if the return code is not 307 or 308.
In http://www.restapitutorial.com/httpstatuscodes.html:

> [...] If the 301 status code is received in response to a request other than GET or HEAD, the user agent MUST NOT automatically redirect the request unless it can be confirmed by the user, since this might change the conditions under which the request was issued. [...]

**Comment by stratosgear** [comment]
Nice investigative work!

It seems that apart from a nice, visible warning on the way the `gitlab.Gitlab(base_url)` is instantiated, it is diffucult to automatically differentiate between an "accidental" `http` or `https` reference, as both cases could be a valid option.  Or unless the `Gitlab` package prevents `requests` from automatically following redirects (which I do not think it is right to do).

Up to @gpocentek how to handle!

**Comment by gpocentek** [comment]
@fritruc thank you!

As @stratosgear mentions, it might be difficult to detect redirection problems. I'll add warnings to the documentation explaining that redirections are not supported.

Thank you all for the feedback on this issue;

**Comment by thawkins** [comment]
I'm having this same problem and yes I am using  http, not https, because i'm using a test system running in a container, every other api call seems to work fine except this one. 

Migrated Issue CDDEV-11554

Issue Create EXCEPTION: CDDEV-11553 = assignee_id, assignee_ids, confidential, created_at, description, discussion_locked, due_date, labels, milestone_id, state_event, title, weight, epic_id, epic_iid are missing, at least one parameter must be provided

**Comment by weitzman** [comment]
@thawkins I got the same error when I wasnt passing values correctly. The https is probably a red herring.
