### ISSUE TITLE
API4 notes for MR taken from wrong MR ID

### ISSUE THREAD

**Issue by ViachaslauKabak** [python-gitlab/python-gitlab#383]
using api3 was successful but using v4 - got an issue
gl = gitlab.Gitlab('URL',email='usermail',password='userpass',api_version='4')
gl.auth()
pr = gl.projects.get(1)
mr = pr.mergerequests.get(os.getenv(gitlabMergeRequestId))
nList = mr.notes.list()
for nt in nList:
    print nt.body

It returns notes from another MR

**Comment by gpocentek** [comment]
@ViachaslauKabak Are you using the merge request ID ou IID? With the v4 API you need to use the IID (unique ID in the project scope).

The code is using IID.

**Comment by ViachaslauKabak** [comment]
tried both id ad iid
no one shown right result

**Comment by ViachaslauKabak** [comment]
strange that on 10.2 everything is ok
on 8.17 there is an issue if using v4.... and only with comments reading

**Comment by ViachaslauKabak** [comment]
@gpocentek Any news?

**Comment by gpocentek** [comment]
If everything works as expected in 10.2, I guess there is a bug in 8.17. And I'm not convinced that there's a problem with python-gitlab in that case.

**Comment by ViachaslauKabak** [comment]
ok, thanks a lot
