### ISSUE TITLE
API v4 projects.create 'visibility' not supported

### ISSUE THREAD

**Issue by csoriano1618** [python-gitlab/python-gitlab#384]
I was trying to create a project with visibility public with:

`        project = self.gl.projects.create({'name': self.product,
                                           'import_url': import_url,
                                           'visibility': 'public'})
`

But seems that doesn't work, and I have to use the API v3 one like:
`        project = self.gl.projects.create({'name': self.product,
                                           'import_url': import_url,
                                           'visibility_level': 20})
`

Would be good to have support for that.

**Comment by gpocentek** [comment]
@csoriano1618 Thank you for reporting this issue.

I have tried to create a public project on gitlab.com and it works just fine:
```
In [23]: gl.projects.create({'name': 'test2', 'visibility': 'public'})
Out[23]: <Project id:4865936>

In [24]: p = gl.projects.get(4865936)

In [25]: p.visibility
Out[25]: u'public'
```

If you have the possibility to do it, could you test with an updated version of the GitLab?

Thanks.

**Comment by csoriano1618** [comment]
It was my fault, I was usingwithouth noticing api v3 and I forgot to close this issue, sorry!
