### ISSUE TITLE
Get participants from gitlab Merge Request

### ISSUE THREAD

**Issue by ViachaslauKabak** [python-gitlab/python-gitlab#387]
Need to have a chance to get participants of MR from API

**Comment by gpocentek** [comment]
Is this something implement in the GitLab API? I can't seem to find information about this feature.

**Comment by ViachaslauKabak** [comment]
you r right - there is no possibility to get this info from API
opened https://gitlab.com/gitlab-org/gitlab-ce/issues/40986

**Comment by gpocentek** [comment]
Great!

I'll keep this issue open, let's see what happens upstream.

**Comment by ViachaslauKabak** [comment]
@gpocentek,
Seems that participants were added into gitlab
