### ISSUE TITLE
Missing feature of having service integrations

### ISSUE THREAD

**Issue by ani-patel** [python-gitlab/python-gitlab#391]
Hi Team,

The module probably does not support service integrations like slack, hipchat, Jira etc which is available through the API.

**Comment by gpocentek** [comment]
@ani-patel Is this what you are looking for: http://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-services ?

**Comment by ani-patel** [comment]
Yeah exactly! Thanks a lot for your help
