### ISSUE TITLE
Bug in project.files.create(file_body)

### ISSUE THREAD

**Issue by ani-patel** [python-gitlab/python-gitlab#394]
Hi Team,

file_body = {
    "file_path": "README.md",
    "branch": "master",
    "commit_message": "LOG-1234 Added Readme file"
  }

project.files.create(file_body)

after this line if we print file_body it returns this:

file_body = {
    "branch": "master",
    "commit_message": "LOG-1234 Added Readme file"
  }

The content of the file_body changes after going through project.files.create(file_body)

Can you look into this bug and not alter client request if possible?

Thanks

**Comment by gpocentek** [comment]
This indeed look like a bug, but it shouldn't be too hard to fix.

Thanks for the report.
