### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by ani-patel** [python-gitlab/python-gitlab#396]
Hi Team,

service = project.services.get(service_name='asana', project_id=932)

This throws me an error:
Traceback (most recent call last):
    service = project.services.get(service_name='asana', project_id=932)
TypeError: get() takes exactly 2 arguments (1 given)

I think there is some incorrect key name to be used in parameters which is resulted in the error.
Can you help how can I make this work by giving the correct parameters to be passed?

Thanks

**Comment by ani-patel** [comment]
The statement works if I use v3 client for gitlab (v3 API) Can you add documentation for v4 and test if it works?

**Comment by zeddicus76** [comment]
looks to me like you only need to specify the project name. This worked for me with v4:

`service = project.services.get('asana')`
