### ISSUE TITLE
gl.user.is_admin only works in python shell, but not in code?

### ISSUE THREAD

**Issue by max-wittig** [python-gitlab/python-gitlab#401]
I've come across this weird issue, where the user admin information is not accessible, when using python-gitlab in code but working fine, when using the python shell

The same virtualenv was used
```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux

python-gitlab==1.1.0
```

### Python Shell
```python
>>> import gitlab
>>> gl = gitlab.Gitlab("https://***********", "**************", api_version=4)
>>> gl.auth()
>>> gl.user.is_admin
True
```

### Source Code and Traceback
```python
import gitlab
gl = gitlab.Gitlab("https://***********", "**************", api_version=4)
gl.auth()
print(gl.user.is_admin)

Traceback (most recent call last):
  File "/home/projects/**************/venv/lib/python3.5/site-packages/gitlab/base.py", line 564, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'is_admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/projects/*************/venv/lib/python3.5/site-packages/gitlab/base.py", line 567, in __getattr__
    value = self.__dict__['_attrs'][name]
KeyError: 'is_admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/projects/******/venv/lib/python3.5/site-packages/gitlab/base.py", line 587, in __getattr__
    return self.__dict__['_parent_attrs'][name]
KeyError: 'is_admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/projects/***********/**********.py", line 194, in <module>
    main()
  File "/home/projects/*********/**********.py", line 144, in main
    ****************=**************)
  File "/home/projects/***********/scanner.py", line 69, in __init__
    test = self.gl.user.is_admin
  File "/home/projects/********/venv/lib/python3.5/site-packages/gitlab/base.py", line 589, in __getattr__
    raise AttributeError(name)
AttributeError: is_admin

Process finished with exit code 1
```

**Comment by deveaud-m** [comment]
As described in the [Gitlab API documentation](https://docs.gitlab.com/ce/api/users.html), only administrators can see the full content of the user attributes, including `is_admin`. However the exceptions raised by the gitlab module is misleading, what about throwing something like `PermissionError`?

**Comment by gpocentek** [comment]
Hi,

python-gitlab only provides a python interface to what the GitLab REST API returns. If GitLab doesn't return the attribute, it is not available in the python-gitlab object.

@max-wittig have you done the test with CLI and API using the same GitLab user?

**Comment by max-wittig** [comment]
I noticed that I used two different GitLab users, with different permissions, so this was actually my fault.

I agree with @deveaud-m, but maybe this should be solved by GitLab instead?

Not sure, if it makes sense to integrate a check for `is_admin` into python-gitlab, because it would also need to know the context of the request etc. and that might get messy quickly.

I'm closing my issue. Please reopen, if you have another opinion or more needs to be discussed.

**Comment by gpocentek** [comment]
@max-wittig Thanks for your feedback!

I'd like to avoid doing specific checks on attributes because it's complicated to define what should be handled and what shouldn't. I'd rather simply stick to what GitLab returns to build simple objects. Testing whether an attribute exists is quite standard in python, so I think that keeping the current behaviour is the more reasonable thing to do.
