### ISSUE TITLE
Document supported Python versions in README, and PyPi

### ISSUE THREAD

**Issue by movermeyer** [python-gitlab/python-gitlab#402]
When I am considering using a new Python library, perhaps the most important information I need is to be able to tell what versions of Python the library supports.

Typically I look for:

1. I look for PyPi badges at the top of the README.MD file. ([for an example, see pyhocon](https://github.com/chimpler/pyhocon))
2. A list of supported version in the README.MD more generally.
3. Version categories from the setup.py displayed in the PyPi page. ([for an example, see pyhocon](https://pypi.python.org/pypi/pyhocon/))

python-gitlab doesn't seem to have documentation describing this.

If you came up with a list, I would be willing to do the legwork to create a PR for this documentation fix.

(I realize that it mentions it in [the docs](https://python-gitlab.readthedocs.io/en/stable/install.html), but I might not even make it there if it's not clear.)

**Comment by gpocentek** [comment]
@movermeyer Thank you for reporting this issue!

I've updated setup.py with supported (and tested) python versions for the 1.2.0 release (https://img.shields.io/pypi/pyversions/python-gitlab.svg seems OK). If you're still up to provide a PR to improve the README that would a nice update.

Thanks again!
