### ISSUE TITLE
Issue with gl.projects.all() : ProjectManager object has no attribute 'all'

### ISSUE THREAD

**Issue by olo-dw** [python-gitlab/python-gitlab#407]
Thank you for this nice very helpfull job!

I add an issue with `projects = gl.projects.all()` , the result is `AttributeError: 'ProjectManager' object has no attribute 'all'`

To add some details, I tried with the code below (I copy/paste in order to compress the code), and I add the result too. As you can see the `gl.projects.list(all=True)` is ok, but `gl.projects.all()` is not working while it is in the [official doc examples](https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#examples).

**Code:**
```
class GitlabAPIRequester(object):
    Default_Uri = 'http://localhost:8080'
    Default_Api_Version = '4'

    def __init__(self, requester=None, uri=None, token=None, api_version=None):
        self._uri = uri or GitlabAPIRequester.Default_Uri
        self._token = token
        self._api_version = api_version or GitlabAPIRequester.Default_Api_Version
        self._requester = requester or gitlab.Gitlab(self._uri, self._token, api_version=self._api_version)

    def get_projects_all(self):
        projects_all = self._requester.projects.all()
        return projects_all

    def get_projects_list(self):
        projects_list = self._requester.projects.list(all=True, lazy=True)
        return projects_list

if __name__ == '__main__':
    glr = GitlabAPIRequester(uri='https://mygitlab', token=TOKEN, api_version='4')
    print("LIST: {0}".format(glr.get_projects_list()))
    print("ALL: {0}".format(glr.get_projects_all()))
```

**Result:**
```
LIST: [<Project id:601>, <Project id:600>, (...) <Project id:10>, <Project id:7>, <Project id:6>]
Traceback (most recent call last):
  File "~/config/plugins/python-ce/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "~/config/plugins/python-ce/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "~/config/plugins/python-ce/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/projets/metrics.py/gitlab_collect/gitlab_etl.py", line 17, in <module>
    print("ALL: {0}".format(glr.get_projects_all()))
  File "/projets/metrics.py/gitlab_collect/gitlab_api.py", line 20, in get_projects_all
    projects_all = self._requester.projects.all()
AttributeError: 'ProjectManager' object has no attribute 'all'
```

source :
* https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#examples

**Comment by gpocentek** [comment]
@olo-dw Thank you for reporting this issue.

Using `gl.projects.list(all=True)` is the way to go with GitLab API v4. The `all()` method only exists in the v3 API.

The documentation is not correct, I'll update it.

**Comment by olo-dw** [comment]
Thank you for your very quick answer.

In fact, I need to retrieve the names list of my projects. And the `gl.projects.list(all=True)` grabs all the projects characteristic features. This is heavy compared to my need. Is there any other way to collect a such list?

**Comment by gpocentek** [comment]
The listing API always returns a lot of information about the projects. I don't think it is possible to limit the data return by GitLab.

This is something that should become possible with the next version of the API which is supposed to be based on GraphQL: https://docs.gitlab.com/ce/api/#road-to-graphql
