### ISSUE TITLE
Cannot list project hooks in python3

### ISSUE THREAD

**Issue by jizi** [python-gitlab/python-gitlab#410]
Hi,

I am using python-gitlab (1.2.0) and python3.5 but I am not able to list project hooks with this call:
`project.hooks.list()`, where `project` is object of my gitlab project. 
**The same code works in python2.7.** 
Do you think there is an issue on my side (configuration etc.) or is it a bug?

Thanks in advance.

BR,
Jiri

**Comment by gpocentek** [comment]
@jizi hi

I have not been able to reproduce the problem. Can you provide a sample code and the error you're getting?

Thanks.

**Comment by jizi** [comment]
Hi @gpocentek,
thanks for quick reply. Here is the code:
```
#!/usr/bin/python3

import gitlab      #pip install --upgrade python-gitlab
import requests
requests.packages.urllib3.disable_warnings()

gl = gitlab.Gitlab.from_config('kancelar')

groups = gl.groups.list(search='my-group')
projects = groups[0].projects.list(all=True)
for p in projects:
    for hook in p.hooks.list():
        print("%s %s" % (p.name, hook.url))

```

```
# ./bug.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gitlab/base.py", line 582, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gitlab/base.py", line 585, in __getattr__
    value = self.__dict__['_attrs'][name]
KeyError: 'hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gitlab/base.py", line 605, in __getattr__
    return self.__dict__['_parent_attrs'][name]
KeyError: 'hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bug.py", line 12, in <module>
    for hook in p.hooks.list():
  File "/usr/local/lib/python3.5/dist-packages/gitlab/base.py", line 607, in __getattr__
    raise AttributeError(name)
AttributeError: hooks

```

**Comment by gpocentek** [comment]
So the problem is that you are using `GroupProject` objects as `Project` objects, this doesn't work anymore (since v1.1). You need to do something like this (untested but should work):

```python
groups = gl.groups.list(search='my-group')
projects = groups[0].projects.list(all=True)
for p in projects:
    # create a lazy Project object; it's enough to get the `hook` manager
    p = gl.projects.get(p.id, lazy=True)
    for hook in p.hooks.list():
```

**Comment by jizi** [comment]
Hi @gpocentek,
thanks for explanation. Now I saw it in release notes. 
It is little bit unintuitive. Maybe it would be better to mention this somewhere in the examples [here](https://python-gitlab.readthedocs.io/en/stable/gl_objects/groups.html). 

Thank you again for prompt answers. Have a nice day.

**Comment by gpocentek** [comment]
@jizi you're absolutely right, it should be added to the docs. I reopen this issue to make sure this happens. Thanks!
