### ISSUE TITLE
search commits by commentes using regular expression

### ISSUE THREAD

**Issue by likeer** [python-gitlab/python-gitlab#411]
we'd like to search commits by commentes using regular expression，like use git command  : git log --grep=<somestring> ,what parameters should I give to the function " project.commits.list() "?

**Comment by gpocentek** [comment]
Hi @likeer,

The feature you're looking for doesn't exist in GitLab, so is not available either in python-gitlab. If you need this feature you should open an issue on GitLab (https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by likeer** [comment]
thank you very much

**Comment by likeer** [comment]
@gpocentek thank you!
