### ISSUE TITLE
Add support for Pipeline Schedule

### ISSUE THREAD

**Issue by sscherfke** [python-gitlab/python-gitlab#414]
It would be nice to have support for [Pipeline Schedules](https://docs.gitlab.com/ee/api/pipeline_schedules.html).

**Comment by gpocentek** [comment]
This is being worked on in #398.

**Comment by gpocentek** [comment]
Implemented in #398, but needs some docs/examples.

**Comment by gpocentek** [comment]
Docs added in ac123df
