### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by codyanh** [python-gitlab/python-gitlab#415]
couldn't create the protect wildcard '*-stable'
------
In page: gl_objects/protected_branches.rst

**Comment by codyanh** [comment]
project.protectedbranches.create({'name': '*-stable'})  
GitlabListError: 404: {"error":"404 Not Found"}

and  there are no how to protect the tags? example  1.1.3-release version name.

**Comment by gpocentek** [comment]
I can't reproduce the problem, creation works as expected. Are you positive that your gitlab server is recent enough and supports the protected branches API?

The `GitlabListError` exception shouldn't happen when using a `create()` method. Is the exception the result of a `project.protectedbranches.list()` by any chance?

The protected tags API doesn't exist on GitLab.

**Comment by gpocentek** [comment]
I'm closing this issue, feel free to reopen if this is still a problem.
