### ISSUE TITLE
'order_by' and 'sort' doesn't work with list() methods

### ISSUE THREAD

**Issue by zhelanov** [python-gitlab/python-gitlab#417]
For example, [GitLab API documentation](https://docs.gitlab.com/ce/api/tags.html#list-project-repository-tags) describes the possibility of using 'order_by' and 'sort' with tags, but it doesn't work in python-gitlab:
```
project.tags.list()
```
returns the same thing as
```
project.tags.list(order_by='updated', sort='desc')
```

UPD: in log I see request '/api/v4/projects/1/repository/tags?order_by=updated&sort=desc' so maybe it's an API issue

**Comment by gpocentek** [comment]
@zhelanov thanks for the report.

I tried a curl query on gitlab.com and got some surprising results, so I believe that this is indeed a problem with the Gitlab API. Some queries work fine, some don't.

As an example, this doesn't work (project 13083 is gitlab-ce): `curl "https://gitlab.com/api/v4/projects/13083/repository/tags?sort_by=name&sort=desc&per_page=4"`

**Comment by zhelanov** [comment]
I might be wrong, but there is a problem with your request: don't you need to replace **sort_by** with **order_by**?
I'm not sure that GitLab API works correct, but unequal requests return unequal responses:
```
$ curl - o 1 "https://gitlab.com/api/v4/projects/13083/repository/tags?order_by=name&sort=desc&per_page=4"
$ curl -o 2 "https://gitlab.com/api/v4/projects/13083/repository/tags?order_by=updated&sort=desc&per_page=4"
$ diff -q 1 2
Files 1 and 2 differ
```

**Comment by gpocentek** [comment]
You're right, my query was not correct. I'll keep looking into this problem.

**Comment by zhelanov** [comment]
Workaround for now:
```
_tags = project.tags.list()
tags = sorted(_tags, key=lambda tag: tag.commit['committed_date'], reverse=True)
# 'tags' cointains sorted by 'commited_date' tags, first element of list = newest tag
```
Maybe it will be useful for somebody :)

**Comment by gpocentek** [comment]
Hi @zhelanov I've used ordering/sorting on gitlab.com recently and it worked just fine. Is it still not working for you?

Thanks.

**Comment by duncz** [comment]
I'm encountering the same problem when trying to run `myrepo.jobs.list(page=page, per_page=50, scope='success', order_by='created_at', sort='desc')`

In addition to the above, I've tried `orderBy`, `createdAfter` and `createdBefore` commands, all which appear not to work.

For me, I have three issues with this:

1. Is there a documented list of acceptable parameters?
2. Should the `python-gitlab` library fail when unacceptable parameters are passed to the function?
3. There definitely needs to be a way to sort a list of jobs

With regards to `#3`, we spawn around ~25,000 jobs per day. I need to run analytics on these jobs on a daily and weekly basis. If I can't order and sort, and if I can't refine the results within a date range, it makes the API almost entirely useless to me.

NB: I appreciate this might not be the library's fault - it might be a failing of the Gitlab API.
