### ISSUE TITLE
Add support for the merge_requests_ff_only_enabled setting

### ISSUE THREAD

**Issue by chrwen-omicron** [python-gitlab/python-gitlab#425]
It seems like that this should be part of the API, at least according to this merge request: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/14272/diffs#does-this-mr-meet-the-acceptance-criteria

I was going to provide a pull request, but couldn't find any documentation about this in the GitLab API. Can you help me with that?

**Comment by gpocentek** [comment]
Hi @chrwen-omicron 

I cannot find a reference to this setting in the GitLab API source code, so there's nothing much I can do to help. Your best option is probably to open an issue on the GitLab project (https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by chrwen-omicron** [comment]
Just as I feared, thanks for taking the time to look into it!
