### ISSUE TITLE
Special handling of `path` in `gitlab.mixins.ListMixin.list` cripples endpoints with `path` query parameters

### ISSUE THREAD

**Issue by mbra** [python-gitlab/python-gitlab#428]
Pulling the `path` key from `kwargs` makes it impossible or at least very hard/ugly to call endpoints that support a `path` query parameter, like with the commits endpoint. Even though the docs do not say anything about the parameter it was added quite a while ago https://gitlab.com/gitlab-org/gitlab-ce/blob/146d4348ca6812e26729de40a831f4ae8c27fde6/lib/api/commits.rb and is still available on the master branch https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/api/commits.rb

At least to me after a quick look around, there seems no easy & clean way to fix this without breaking compatibility.

There is another very similar case (`gitlab.Gitlab._raw_list`) where this is handled with a positional argument (`path_`).

**Comment by mbra** [comment]
After taking another look, I stumbled upon the `query_data` argument of `gitlab.Gitlab.http_list`,  which at least enables me to `project.commits.list(query_data={"path": "..."})`, but it still feels like a workaround. :-(

**Comment by gpocentek** [comment]
HI @mbra 

The `query_data` argument is actually there for that use case, so you're doing things as intended.

The `_raw_list` is linked to the v3 API and will be removed from python-gitlab in a near future.
