### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by oux** [python-gitlab/python-gitlab#430]
trigger_pipeline takes only branch and tag as ref.
------
In page: api/gitlab.v4.rst

trigger_pipeline takes only branch and tag as ref.
So "can be a commit SHA" seems false.
Ref: https://gitlab.com/help/ci/triggers/README.md#triggering-a-pipeline
"Valid refs are the branch and the tag"

**Comment by gpocentek** [comment]
Thanks for reporting this error!
