### ISSUE TITLE
API for downloading a single artifact file

### ISSUE THREAD

**Issue by nickolas-pohilets** [python-gitlab/python-gitlab#431]
Seems that library is not providing API for downloading a single artifact file, only entire archive.
See https://docs.gitlab.com/ee/api/jobs.html#download-a-single-artifact-file.

**Comment by gpocentek** [comment]
Thanks for reporting this issue @nickolas-pohilets 

Issue #432 is a duplicate but has a proposed patch to implement this feature, so I'll track the progress there.
