### ISSUE TITLE
Support downloading a single artifact file

### ISSUE THREAD

**Issue by JonathonReinhart** [python-gitlab/python-gitlab#432]
GitLab 10.0 added an API route to [download a single artifact file](https://docs.gitlab.com/ee/api/jobs.html#download-a-single-artifact-file):

> `GET /projects/:id/jobs/:job_id/artifacts/*artifact_path`

Example request:

```
curl --header "PRIVATE-TOKEN: 9koXpg98eAheJpvBs5tK" \
    "https://gitlab.example.com/api/v4/projects/1/jobs/5/artifacts/some/release/file.pdf"
```

`python-gitlab` [does not appear](http://python-gitlab.readthedocs.io/en/stable/gl_objects/builds.html#id4) to support this.

I imagine something like this:

```python
job.get_artifact('some/release/file.pdf', streamed=True, action=whatever)
```

**Comment by JonathonReinhart** [comment]
Working on a patch here: https://github.com/JonathonReinhart/python-gitlab/compare/master...432-download-single-artifact

**Comment by gpocentek** [comment]
Hi @JonathonReinhart 

I've had a look at your patch. It looks OK but I'd prefer to have a new `actifact` method instead of modifying the existing `artifacts`. Let me know if you want to keep working on this, I'll be happy to review and merge!

Thanks!

**Comment by JonathonReinhart** [comment]
@gpocentek Sorry, I got busy and didn't get a chance to come back to this. I agree with your new, separate method. Thanks for the addition!

**Comment by Vickey-Wu** [comment]
i find we can use [build_or_job.trace()](https://python-gitlab.readthedocs.io/en/stable/gl_objects/builds.html?highlight=jobs#id8) to get artifacts content we need, if you had printed them in your .gitlab-ci.yml
