### ISSUE TITLE
cli 'project-commit-comment list' returns blank lines

### ISSUE THREAD

**Issue by derekschrock** [python-gitlab/python-gitlab#433]
When running 'gitlab project-commit-comment list --commit-id ... --project-id ... ' blank lines are printed per comment from the web interface.

Confirmed this by running 'gitlab project-commit-comment create ... ' to create a new comment, verified it by the web interface, counted the lines output by 'project-commit-comment list', repeat the same process and found the blank lines were previous+1.

**Comment by gpocentek** [comment]
Hi @derekschrock 

I'm not sure to understand the problem here. Could you provide the detailed list of comments and the output you get? I have not been able to produce extra blank lines locally.

Thanks!

**Comment by gpocentek** [comment]
Hi @derekschrock 

I'm not sure to understand the problem here. Could you provide the detailed list of comments and the output you get? I have not been able to produce extra blank lines locally.

Thanks!

**Comment by derekschrock** [comment]
The output is blank:

```
$ gitlab project-commit-comment list --commit-id edfcb2a581a228823aa9ebd61523905ed76489d6 --project-id 11






$
```

Looking at commit edfcb2a581a228823aa9ebd61523905ed76489d6 for project related to project-id 11 via the web interface "http://gitlab.example.com/test/foo/commit/edfcb2a581a228823aa9ebd61523905ed76489d6"  there are valid/non-blank comments.

Adding new/more comments results in more blank lines using the same project-commit-comment as above.

Before:
```
$ gitlab project-commit-comment list --commit-id edfcb2a581a228823aa9ebd61523905ed76489d6 --project-id 11 | wc -l
       5
```

After adding a new comment:

```
$ gitlab project-commit-comment list --commit-id edfcb2a581a228823aa9ebd61523905ed76489d6 --project-id 11 | wc -l
       6
```

So it's finding the comments but not displaying them correctly.

**Comment by gpocentek** [comment]
OK I've been able to reproduce the problem. This is happening with the legacy output, yaml and json output format work fine.

**Comment by gpocentek** [comment]
Notes/Comments don't have an attribute (id or something else) that can be used to display useful non-verbose information, that's why we only get empty lines. Using the versbose mode (`-v`) everything looks fine.

@derekschrock what information would you like see in a non-verbose mode?

**Comment by derekschrock** [comment]
Maybe username, create-at, line, note, and path.  If the value is None
don't display the key/value?
