### ISSUE TITLE
New issue labels parsed as single characters

### ISSUE THREAD

**Issue by m1tca00** [python-gitlab/python-gitlab#443]
When running:

```{bash}
gitlab -o json -f labels project-issue create --project-id 273 --title 'Sample Issue' --description 'Issue description' --labels foo,bar
```

Each character of "foo,bar" gets parsed as an individual label:

    {"labels": ["a", "b", "f", "o", "o", "r"]}

**Comment by gpocentek** [comment]
Hi @m1tca00, thanks for the bug report.

The labels are not properly parsed when using the command line. I'll look into that.
