### ISSUE TITLE
GPLv3?

### ISSUE THREAD

**Issue by tardyp** [python-gitlab/python-gitlab#447]
I just realized python-gitlab is license under GPLv3.

GPLv3 license is arguably not suitable for a library. 
For example, I cannot use it in https://github.com/buildbot/buildbot which is GPLv2.
I can only use it for programs in GPLv3 which are very sparse nowadays. In 2015: 8% of projects in github are GPLv3 https://blog.github.com/2015-03-09-open-source-license-usage-on-github-com/

I believe that python-gitlab has good value and is well designed. Please consider putting it in a less restrictive license so that it can be more widely used.

**Comment by gpocentek** [comment]
Actually the license is LGPL v3 (lesser GPL), which is much more permissive than GPL. You can "link" python-gitlab from any other application, even proprietary. I don't think the license will prevent you from using python-gitlab in your own project.

I am no expert on the subject though, so let me know if you think I misunderstood.

**Comment by tardyp** [comment]
Sorry about that I could swear I triple checked it wasn't LGPL.
LGPL is perfectly fine!

thanks
