### ISSUE TITLE
Implement Issue board

### ISSUE THREAD

**Issue by cookacounty** [python-gitlab/python-gitlab#451]
It seems like quite a few of the issue board functions are not implemented. Are there any plans to implement this? What I'm looking for is the ability to duplicate a set of boards across projects.

https://docs.gitlab.com/ce/api/boards.html

http://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#board-lists

**Comment by gpocentek** [comment]
Hi @cookacounty 

I don't see any GitLab API call that would let you duplicate boards across projects. Do you have a direct link to the GitLab docs or code?

All the endpoints documented on https://docs.gitlab.com/ce/api/boards.html are implemented in python-gitlab.

Thanks.
