### ISSUE TITLE
Cannot get tag/release creation/modification date

### ISSUE THREAD

**Issue by keul** [python-gitlab/python-gitlab#453]
I found no way to get from a `ProjectTag` or `ProjectTagRelease` an operation date. Both creation or modification date would be enough, but I didn't found any date attrs implemented.

Is this possible or is an unsupported feature?

**Comment by gpocentek** [comment]
I don't think that git tags hold date information. Tags are linked to a commit, which has date information, but I don't think you can modify that easily.

**Comment by keul** [comment]
@gpocentek I agree with you that tag do not have this information, while gitlab release should have it.
In a gitlab user inferface you can sort releases, and they are commonly sorted with a last modified date, while using python binding I get a random order.

**Comment by gpocentek** [comment]
@keul If you just need to sort the tags then you can use the `order_by` and `sort` parameters:

```python
project.tags.list(order_by='updated', sort='desc')
```

https://docs.gitlab.com/ce/api/tags.html#list-project-repository-tags

**Comment by keul** [comment]
🍺  This solve _my_ issue indeed.

Still... if we can sort by modification date, the data should be somewhere. Maybe this is not a python-gitlab missing feature but a gitlab API issue?

However at this point I'm just curious. Thanks!

**Comment by gpocentek** [comment]
Glad this solved your issue.

You get the commit information in the tags attributes (`tag.attributes`). python-gitlab simply retrieves what the GitLab API sends, so if you need more or different information, GitLab needs to be patched.
