### ISSUE TITLE
Convert PipelineJob to ProjectJob without http request

### ISSUE THREAD

**Issue by Dimitri0xff** [python-gitlab/python-gitlab#454]
I can't get the artifacts from PipelineJob (404 error) but I can get them from ProjectJob, because they use a different request URL.

I convert from PipelineJob to ProjectJob like this:
```
job2 = project.jobs.get(job1.id)
job2.artifacts()
```
How can I do the same without an additional http request at the first line?
Or, how can I get the artifacts from PipelineJob... (GitLab Community Edition 9.2.10, no I can't update right now)

**Comment by gpocentek** [comment]
Hi @Dimitri0xff 

You can use the `lazy` parameter:

```
job2 = project.jobs.get(job1.id, lazy=True)
job2.artifacts()
```

http://python-gitlab.readthedocs.io/en/stable/api-usage.html?highlight=lazy#lazy-objects-v4-only
