### ISSUE TITLE
Displaying a 404 page

### ISSUE THREAD

**Issue by SSKeng** [python-gitlab/python-gitlab#457]
Hi :
    My Gitlab Edition is 10.4.* When I run my python as belows:

    import gitlab
    def remove_prj(self, prj):
           prj_id = (self.gl.projects.get(prj)).id
           self.gl.projects.delete(prj_id)   
     gitlabapi = GitlabAPI(url, token)
     gitlabapi.remove_prj('abc/project')

     
The repository named 'project' under the group named 'abc' is indeed deleted, but the repository is still exist on the webpage. When I enter this repository, the 404 error page display. What should I do to solve it? 
    I try to delete this project using command 'curl', Then I get the result "{message : 202}".  What is your suggestion on me?
   BR.

**Comment by gpocentek** [comment]
Hello @SSKeng 

Are you using the v4 API?

**Comment by SSKeng** [comment]
Yes. I use V4 API. I think whether I should upgrade my Gitlab？

**Comment by gpocentek** [comment]
Could you enable the debug output and check the URL that is used by python-gitlab (`gl.enable_debug()`)?

Make sure to remove the private token from the output if you copy/paste here.

Thanks.

**Comment by SSKeng** [comment]
It was my fault, I was using the api v3 and I upgraded the gitlab.
