### ISSUE TITLE
python-gitlab cannot create tag

### ISSUE THREAD

**Issue by scm20008** [python-gitlab/python-gitlab#458]
The version is gitlab 10, and the error is as follows:

11:08:52 Traceback (most recent call last):
11:08:52   File "/opt/scripts/create_tag.py", line 22, in <module>
11:08:52     tag = project.tags.create({'tag_name': '1.0', 'ref': 'master'})
11:08:52   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/python_gitlab-1.3.0-py2.7.egg/gitlab/exceptions.py", line 253, in wrapped_f
11:08:52     raise error(e.error_message, e.response_code, e.response_body)
11:08:52 gitlab.exceptions.GitlabCreateError: 400:

according to issue #231, for gitlab it need to use https protocal?
I use http protocal for gitlab, and I need to use python-gitlab to create tag, how can I do it?

any help?

**Comment by gpocentek** [comment]
Hi @scm20008 

You need to use https only if your GitLab server uses https also.

Could you try to get the entire exception message? Without it it's difficult to understand what is happening.

**Comment by scm20008** [comment]
Hi @gpocentek thanks!

No other errors. I use http but not https.
I run python script to apply tag for gitlab in jenkins pipeline, and all the outputs are as follows:

11:08:50 [pipeline-gitlab-test] Running shell script
11:08:50 + source /opt/rh/python27/enable
11:08:50 ++ export PATH=/opt/rh/python27/root/usr/bin:/sbin:/usr/sbin:/bin:/usr/bin
11:08:50 ++ PATH=/opt/rh/python27/root/usr/bin:/sbin:/usr/sbin:/bin:/usr/bin
11:08:50 ++ export LD_LIBRARY_PATH=/opt/rh/python27/root/usr/lib64
11:08:50 ++ LD_LIBRARY_PATH=/opt/rh/python27/root/usr/lib64
11:08:50 ++ export MANPATH=/opt/rh/python27/root/usr/share/man:
11:08:50 ++ MANPATH=/opt/rh/python27/root/usr/share/man:
11:08:50 ++ export XDG_DATA_DIRS=/opt/rh/python27/root/usr/share:/usr/local/share:/usr/share
11:08:50 ++ XDG_DATA_DIRS=/opt/rh/python27/root/usr/share:/usr/local/share:/usr/share
11:08:50 ++ export PKG_CONFIG_PATH=/opt/rh/python27/root/usr/lib64/pkgconfig
11:08:50 ++ PKG_CONFIG_PATH=/opt/rh/python27/root/usr/lib64/pkgconfig
11:08:50 + python /opt/scripts/merge_branch.py feature2-hbb-dev feature2-hbb-dev-20180312-110845
11:08:52 Traceback (most recent call last):
11:08:52   File "/opt/scripts/apploy_tag.py", line 22, in <module>
11:08:52     tag = project.tags.create({'tag_name': '1.0', 'ref': 'master'})
11:08:52   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/python_gitlab-1.3.0-py2.7.egg/gitlab/exceptions.py", line 253, in wrapped_f
11:08:52     raise error(e.error_message, e.response_code, e.response_body)
11:08:52 gitlab.exceptions.GitlabCreateError: 400: 
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE



In order to get more exception message, what do I need to do?

**Comment by gpocentek** [comment]
The exception is not really helpful there (`gitlab.exceptions.GitlabCreateError: 400:`), it doesn't provide the reason for the failure. Can you try to execute the script manually (not in jenkins) to get more info?

**Comment by scm20008** [comment]
Hi @gpocentek ,

Thanks very much! According to your idea, I try to run the script manually, and it works!
so I change the env variables that need to be load, and I resolve the problem.

I guess I load only part of the env varialbes so that in Jenkins it doesnot work.

you can close this issue. thank again!
