### ISSUE TITLE
gitlab api authentication error

### ISSUE THREAD

**Issue by jaydip189** [python-gitlab/python-gitlab#459]
gl = gitlab.Gitlab('http://gitlab.com', oauth_token='rUAuB2dWFb17_y-7cRbd')
AttributeError: module 'gitlab' has no attribute 'Gitlab'

**Comment by gpocentek** [comment]
answered on #460

**Comment by d3vnick** [comment]
Since this is the first result on Google if you search: *module 'gitlab' has no attribute 'Gitlab'*

**Be sure you have installed `python-gitlab` rather than `gitlab`**

Give a thumb up to [this folk's answer](https://github.com/python-gitlab/python-gitlab/issues/460#issuecomment-445979020)
