### ISSUE TITLE
api authentication is not working

### ISSUE THREAD

**Issue by jaydip189** [python-gitlab/python-gitlab#460]
api call is not working.

 File "auth.py", line 3, in <module>
    import gitlab
  File "D:\DevOps\gitlab\gitlab.py", line 17, in <module>
    g1()
  File "D:\DevOps\gitlab\gitlab.py", line 10, in g1
    gl = gitlab.Gitlab('http://gitlab.com', oauth_token='rUAuB2dWFxccvbbd')
AttributeError: module 'gitlab' has no attribute 'Gitlab'
------
In page: api-usage.rst

**Comment by gpocentek** [comment]
Hi @jaydip189 

It looks like an import conflict. Rename your `gitlab.py` to something else and it should work.

**Comment by jaydip189** [comment]
Hi @gpocentek 

Renamed auth.py but some how api authentication is not working.I want to create project dynamically.

#!/usr/bin/env python
import gitlab

class gitlab(object):

    def g1(self,g1):

      gl = gitlab('https://gitlab.com/', private_token='rUAuB2dWFb')
      g1.auth()

**Comment by gpocentek** [comment]
You need to use: 

```
gl = gitlab.Gitlab('https://gitlab.com/', private_token='...')
```

**Comment by jaydip189** [comment]
but it's unable to fetch gitlab attributes like (e.g create project , create repo)

**Comment by gpocentek** [comment]
@jaydip189  Could you provide a complete code example that I could use to reproduce the error? And also provide the complete error you're getting.

Without this information I won't be able to help. Thank you.

**Comment by jaydip189** [comment]
@gpocentek please help me outta of this.I need to only api authentication with github (private token) 

This is the entire code of python and getting error AttributeError: module 'gitlab' has no attribute 'Gitlab'
#!/usr/bin/env python

import gitlab

def g1():

gl = gitlab.Gitlab('http://gitlab.com', private_token='xxxxxxxxxx')
g1.auth()

projects = gl.projects.list()
for project in projects:
    print(project)

def g1():
  print ('Create Project')
  print ('Create repo')

def projects():
  projects = gl.projects.list(visibility='public')

g1()
projects()

**Comment by gpocentek** [comment]
`AttributeError: module 'gitlab' has no attribute 'Gitlab'`

You still have an import problem. You can try this to see what file is imported:
```
python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gitlab
<module 'gitlab' from '/usr/lib/python2.7/dist-packages/gitlab/__init__.pyc'>
>>>
```

Make sure that the path displayed is the `__init__.py` file of the gitlab package, not a file you have written yourself.

**Comment by jaydip189** [comment]
(venv) λ python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gitlab
<module 'gitlab' from 'D:\\DevOps\\gitlab\\venv\\lib\\site-packages\\gitlab\\__init__.py'>

**Comment by gpocentek** [comment]
What does `gitlab.Gitlab` returns in the python shell?

**Comment by jaydip189** [comment]
>>> g1.auth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'g1' is not defined

**Comment by gpocentek** [comment]
`gitlab.Gitlab` is trying to execute your own code. I don't know what's happening there, but this is not a python-gitlab problem.

The only thing I can think of is that you still have a `gitlab.pyc`, `gitlab.py` or `gitlab.pyo` file somewhere.

**Comment by jaydip189** [comment]
need to declare variable of g1 right?

**Comment by jaydip189** [comment]
@gpocentek gitlab api connection is working fine now.Thanks for your help.

**Comment by jaydip189** [comment]
#!/usr/bin/env python
import gitlab


class gitlab(object):

  def g1(self):

    gl = gitlab.Gitlab('http://gitlab.com', private_token='3xxxxx')
    g1.auth()
    gl.projects.list()

class projects(object):
  def projects(self):
    projects = gl.projects.list ( )
    for project in projects:
      print (projects)

**Comment by jaydip189** [comment]
In python shell I'm getting output of project list , groups .but however i'm not getting output when i'm running program.I think projects will not calling.

**Comment by jaydip189** [comment]
I'm calling g1.project.create() method,it gives argument passing error.what i need to pass in argument.

**Comment by gpocentek** [comment]
You can find project creation examples in the documentation: http://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html

**Comment by jaydip189** [comment]
project = gl.projects.create({'name': 'project1'}) is not working.it gives data argument error.

  File "test.py", line 32, in <module>
    gitlab_projects = glab.create_projects()
  File "test.py", line 23, in create_projects
    return self.gitlab_client.projects.create ( )
  File "C:\Users\jaydipsinh.jadeja\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\exceptions.py", line 251, in wrapped_f
    return f(*args, **kwargs)
TypeError: create() missing 1 required positional argument: 'data'

**Comment by gpocentek** [comment]
I recommend you start with learning python because you are clearly not familiar with the language.

You are facing beginner issues which have nothing to do with python-gitlab.

I don't have the time to help you learn python.

**Comment by jaydip189** [comment]
Thanks for your help.I will learn python and get back to you if facing any issue with python-gitlab.

**Comment by kitten77** [comment]
Gitlab version 1.0.2
Python 3.7.1 (default, Oct 21 2018, 08:03:53) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gitlab
<module 'gitlab' from '/home/muad/workbench/gitlab/slickgear/venv_3.7/lib/python3.7/site-packages/gitlab/__init__.py'>
>>> gitlab.Gitlab()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gitlab' has no attribute 'Gitlab'

just bumped into this one, any ideas what is happening here?

**Comment by kitten77** [comment]
Yeah i found that, maybe this is something that should be fixed by renaming the Gitlab() class to PyGitlab() and return a warning deprecated use PyGitlab() ? Just a thought

**Comment by graham-macleod** [comment]
The issue I had was the python script I was testing with was called gitlab.py. Obiously, if you try to "import gitlab" then your script is going to import itself. Never call the script you're writing the same thing as what you're trying to import.

**Comment by skbly7** [comment]
This happened with me as well, and I did the follows:

```
pip install gitlab
pip install python-gitlab
pip uninstall gitlab
```

But the code wasn't working even after removal of `gitlab` package. In this case, you need to uninstall and install the `python-gitlab` again. Not sure why though. I am assuming related to how these packages are setting up after installation might be conflicting in nature.

```
pip uninstall python-gitlab
pip install python-gitlab
```

**Comment by bufferoverflow** [comment]
I've just written the following to the maintainer of [gitlab package](https://pypi.org/project/gitlab/):

```
Hi Yoginth

We face conflicts with your Python package gitlab, see https://github.com/python-gitlab/python-gitlab/issues/460#issuecomment-537837892

Do you still maintain that?
If not do you see an option to transfer the name on pypi to the maintainers of python-gitlab to avoid such issues?

Best
Roger
```

**Comment by itmeryn** [comment]
rename filename  myGitlab    if name is  gitlab  , error is show

**Comment by archerkg** [comment]
> @kitten77 make sure you've installed `python-gitlab` rather than `gitlab`

This solved the issue for me. Thanks.
