### ISSUE TITLE
http_username and http_password is not working for api basic authentication

### ISSUE THREAD

**Issue by jaydip189** [python-gitlab/python-gitlab#462]
gl = gitlab.Gitlab('https://gitlab.com', http_username='xxxx', http_password='xxxx',api_version=4)

gitlab.exceptions.GitlabAuthenticationError: 401: 401 Unauthorized

**Comment by gpocentek** [comment]
`http_username` and `http_password` are meant to be used if you have your own gitlab server, with HTTP authentication setup in additional to standard GitLab auth. Gitlab.com doesn't provide this.

User/password authentication has been disabled on gitlab.com, you need to use a token to authenticate.

You can have a look at #380 for the discussion and workarounds.
