### ISSUE TITLE
GitlabListError: 404 when retrieving subgroups

### ISSUE THREAD

**Issue by gqoew** [python-gitlab/python-gitlab#463]
Hi

I got an `GitlabListError: 404: b'{"error":"404 Not Found"}' ` when retrieving subgroups:

```python
group = gl.groups.get(id)
subgroups = group.subgroups.list()
```

What I am doing wrong?

**Comment by gpocentek** [comment]
Hi @gqoew 

Could you provide the version of python-gitlab and the version of the gitlab server? My guess is that your GitLab version doesn't support the subgroup API.
