### ISSUE TITLE
list of out range

### ISSUE THREAD

**Issue by ww110052181** [python-gitlab/python-gitlab#464]
File "2.py", line 64, in main
    csrf2, cookies2 = sign_in(csrf1, cookies1)
  File "2.py", line 44, in sign_in
    return token, r.history[0].cookies
IndexError: list index out of range

**Comment by ww110052181** [comment]
when i run the directory  'tools/generate_token.py'.above thing happened

**Comment by gpocentek** [comment]
Hi @ww110052181 

This script is meant to be used with our CI environment, there is no guarantee that it will work outside of this context.

There are several methods to authenticate to the Gitlab UI, and we don't plan to support that. You need to update the script to match your Gitlab server requirements.

**Comment by ww110052181** [comment]
thanks a lot.if i want to use it work outside of this context.wo should i do or modify this scripts.
