### ISSUE TITLE
need to give tag in import_url specific version

### ISSUE THREAD

**Issue by jaydip189** [python-gitlab/python-gitlab#465]
is it possible at that time of import_url
git clone --branch v1.0.0-alpha.8 https://username:password@gitlab.com/username/antora.git

**Comment by gpocentek** [comment]
@jaydip189 Could you explain how this issue is related to python-gitlab? Because I really don't understand. Do you have a code snippet? Do you have an error log?

**Comment by jaydip189** [comment]
Error: Name has already been taken, Import url must be a valid URL, Import url imports are not allowed from that URL, Path has already been taken'.so we can't give like this right.?

**Comment by gpocentek** [comment]
@jaydip189 

You still didn't provide information about what you are trying to do so I can't help.
