### ISSUE TITLE
generate_token.py problems

### ISSUE THREAD

**Issue by ww110052181** [python-gitlab/python-gitlab#466]
I just modify the script 'build_test_env.sh',like this

try docker run --name gitlab --detach --publish 8080:80 \
    --volume /srv/gitlab/data:/var/opt/gitlab \
    --publish 2222:22 gpocentek/test-python-gitlab:latest >/dev/null
 
add the parameter '' --volume /srv/gitlab/data:/var/opt/gitlab"

the problems happened

+ dirname build_test_env.sh    
+ ./generate_token.py
Traceback (most recent call last):
  File "./generate_token.py", line 67, in <module>
    main()
  File "./generate_token.py", line 59, in main
    csrf1, cookies1 = obtain_csrf_token()
  File "./generate_token.py", line 31, in obtain_csrf_token
    token = find_csrf_token(r.text)
  File "./generate_token.py", line 25, in find_csrf_token
    data = {param.get("content"): token.get("content")}
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by gpocentek** [comment]
GitLab needs some time to start. Did you wait a minute or two before running the generate_token script?

Make sure that gitlab is properly started (try to access it using a browser).

**Comment by ww110052181** [comment]
hi， the gitlab is started,
I just modify the script 'build_test_env.sh',like this

try docker run --name gitlab --detach --publish 8080:80 
--volume /srv/gitlab/data:/var/opt/gitlab 
--publish 2222:22 gpocentek/test-python-gitlab:latest >/dev/null

add the parameter '' --volume /srv/gitlab/data:/var/opt/gitlab"

the problem is 
  File "./generate_token.py", line 67, in <module>
    main()
  File "./generate_token.py", line 60, in main
    csrf2, cookies2 = sign_in(csrf1, cookies1)
  File "./generate_token.py", line 43, in sign_in
    return token, r.history[0].cookies
IndexError: list index out of range

**Comment by gpocentek** [comment]
The scripts works fine for me, and in the CI environment, so I guess there is something wrong with your setup. Maybe the data you are providing with the docker volume is not what the script expects.

You could probably debug the script step by step using pdb to understand what is happening, but I don't think I can help you a lot because the problem is most likely related to your environment.

**Comment by ww110052181** [comment]
thanks a lot
