### ISSUE TITLE
need to give rights to user project/repository which is import_

### ISSUE THREAD

**Issue by jaydip189** [python-gitlab/python-gitlab#467]
## Expected Behavior
any is there any method available for same?

## Specifications

  - python-gitlab version:
  - API version you are using (v4):
  - Gitlab server version (or gitlab.com):

**Comment by gpocentek** [comment]
You need to use the ProjectMember API: http://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-members

**Comment by jaydip189** [comment]
λ python Gitlab.py
Traceback (most recent call last):
  File "Gitlab.py", line 11, in <module>
    member = project.members.create({'user_id': 'tusharajmeriya', 'access_level':
NameError: name 'project' is not defined

**Comment by gpocentek** [comment]
`project` is a `Project` object that you need to create before trying to access its `members` attributes.
