### ISSUE TITLE
Add notes API examples (already supported)

### ISSUE THREAD

**Issue by ludstuen90** [python-gitlab/python-gitlab#472]
## Description of the problem, including code/CLI snippet
Documentation does not include an example of how to use python-gitlab to view notes

## Expected Behavior
The documentation should contain an API example of how to view notes. This would document functionality that already exists in this plugin: 
notes_list = mr.notes.list()

## Actual Behavior
This documentation does not exist.

**Comment by gpocentek** [comment]
Hi @ludstuen90 

Thanks for reporting this issue. The document exists in the projects page: http://python-gitlab.readthedocs.io/en/master/gl_objects/projects.html?#notes

This is probably not the best place though, so I'll move it somewhere more visible.

**Comment by ludstuen90** [comment]
@gpocentek That's it! Thanks for pointing that out -- appreciate it!
