### ISSUE TITLE
Using a "bot" to copy a merge request to several branches with python gitlab - author of merge request

### ISSUE THREAD

**Issue by maikenp** [python-gitlab/python-gitlab#473]
Hi, 

in our projects branching model and worfklow we often require developer to submit a merge request of his dev-branch to several branches upstream, say master, and release-branch. 

In order for developer himself not to have to make several merge requests, I am developing a system where developer instead labels his merge request with the other branches he wants this dev-branch to be merged into. 

Once a merge request is submitted in the gitlab upstream repo, a webhook is sent, and a script is called duplicating this original merge request and creating one or several new ones depending on the situation. 

The problem is that the merge request author of the new copied merge requests is automatically set to be the user submitting the request through the api, which for us is called  nordugrid-arc-bot. I would like the author to be the same as the original author, or at least include this person as a participant in order for this person to be linked with the merge request, and handle merge conflicts and so on. 

I have tried to set the author to be the original merge requests author, but it seems to be overwritten:

In my python-script that is called by exec of the webhook application:
```
#extracting original author
author = this_mr.author

#creating new mr_dictionary
mr_dict =  {'author':author,
                'source_branch': source_branch,
                'source_project_id': project_id,
                'target_branch': target,
                'target_project_id': project_id,
                'title': title,
                'description':descr + 'author.id: ' + str(author.id) + 'author.name: ' + str(author.name),
                'milestone':this_mr.milestone,
                'labels': ['arcbot','copied:'+target]}
```

After the mr is submitted, I see 

```
mr id:  163 	mr_iid:  46 	author:  <class 'gitlab.v3.objects.User'> => {'_module': <module 'gitlab.v3.objects' from '/Library/Python/2.7/site-packages/python_gitlab-1.2.0-py2.7.egg/gitlab/v3/objects.pyc'>, u'username': u'arcbot', u'name': u'nordugrid-arc-bot', u'avatar_url': u'https://secure.gravatar.com/avatar/37272d389e04cb26a342dda1b7156ab5?s=80&d=identicon', 'gitlab': <gitlab.Gitlab object at 0x10924c950>, '_from_api': True, u'state': u'active', u'web_url': u'https://source.coderefinery.org/arcbot', 'project_id': 205, u'id': 112}
```

See the duplicate mr here: 
https://source.coderefinery.org/maikenp/arc-test-gitlab-ci/merge_requests/46

(sorry, deleted the example, but you can see similar example here: https://source.coderefinery.org/maikenp/arc-test-gitlab-ci/merge_requests/2)

So it seems the author is overwritten by the submitter of the merge request, which in this case is nordugrid-arc-bot

Am I supposed to be able to set the author of a merge request by hand? 

If not, is there some other workaround that could work for me? 

Thanks!
Maiken

------
In page: gl_objects/mrs.rst

**Comment by gpocentek** [comment]
Hi @maikenp 

Updating the `author` attribute will not help you in that case. The GitLab API will not use this attribute.

What you could do is use `sudo` when you create the MR: just add `sudo=author.id` in your MR creation call. You bot user will require admin rights to do this though, which might be a blocker.

http://python-gitlab.readthedocs.io/en/stable/api-usage.html?highlight=sudo#sudo

**Comment by maikenp** [comment]
Oh thank you!  Admin rights on the gitlab server you mean? Yes, that might be a  blocker. 

Otherwise, it is a good solution, will see what I can do.

**Comment by gpocentek** [comment]
@maikenp I mean admin right on the gitlab server, yes. Without admin permissions you will not be able to impersonate another user.

If you can't get admin rights I don't think that you'll be able to perform actions on behalf of somebody else (which makes sense).

Let me know how it goes.

**Comment by maikenp** [comment]
A maybe final question: 
In the copied merge request made by the bot, I add a mention of the original authors name. This is good as it adds the author as a "participant" on the auto-created merge request. 

Now I wonder, and this is the main issue:
Will the original author (the actual developer) be able to resolve merge conflicts that might arise in the merge request? Or is it only the bot which is the creator of the merge request that can do that? 

I have asked my developers to add the bot as a user to their fork, where the merge request originates from.

**Comment by maikenp** [comment]
Thanks for your answers. I will close as I have resolved this.
