### ISSUE TITLE
Store gitlab url

### ISSUE THREAD

**Issue by gsemet** [python-gitlab/python-gitlab#474]
Is it possible to store the gitlab url given as arg or read from the ~/.gitlab.cfg file in a `url` member?

**Comment by gpocentek** [comment]
Hi @gsemet

The only thing that you can use right now if the `_url` attribute of a Gitlab object, but it's not exactly what is defined in the config file (`/api/vX` is appended to the url).

It would be quite easy to expose some additional attributes though.

Out of curiosity, what would be your use case for this?

**Comment by gsemet** [comment]
We would reuse this information to instantiate another gitlab (impersonate API), but it seems legit to store it to let user access it when he wishes.

Could be done through by:

```
@property
def url(self)
    return self._url.partition("/api")[0]
```

**Comment by gsemet** [comment]
Thanks !
