### ISSUE TITLE
KeyError: 'trigger_build'

### ISSUE THREAD

**Issue by myfreeheaad** [python-gitlab/python-gitlab#479]
## Description of the problem, including code/CLI snippet
After update from 1.2.0 to 1.3.0, trigger_build method can't be invocated any more, but [documentation](http://python-gitlab.readthedocs.io/en/stable/gl_objects/builds.html) says, that this part is not changed:

`project.trigger_build('<refName>', '<triggerToken>', {'some_var': 'some_value'})`

## Expected Behavior
Build for project triggered

## Actual Behavior
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gitlab/base.py", line 582, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'trigger_build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gitlab/base.py", line 585, in __getattr__
    value = self.__dict__['_attrs'][name]
KeyError: 'trigger_build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gitlab/base.py", line 605, in __getattr__
    return self.__dict__['_parent_attrs'][name]
KeyError: 'trigger_build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/gitlab/base.py", line 607, in __getattr__
    raise AttributeError(name)
AttributeError: trigger_build

```

## Specifications

  - python-gitlab version: 1.3.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  10.5.3-ee

**Comment by gpocentek** [comment]
Hi @myfreeheaad 

My guess is that you are using the default API version, which changed from v3 to v4 with python-gitlab 1.3.0. `trigger_build` only exist in the v3 API.

Could you check which API version you are using? Tou can check with the `Gitlab.api_version` attribute.

**Comment by gpocentek** [comment]
Feel free to reopen if you still have the problem with v4 API.
