### ISSUE TITLE
gl.project_services.available throws AttributeError

### ISSUE THREAD

**Issue by max-wittig** [python-gitlab/python-gitlab#482]
## Description of the problem, including code/CLI snippet
```
services = gl.project_services.available()
```
is throwing an AttributeError
```
AttributeError: 'Gitlab' object has no attribute 'project_services'
```

From the documentation: http://python-gitlab.readthedocs.io/en/latest/gl_objects/projects.html#exammples

## Expected Behavior
All strings of available GitLab services are listed. Admin token is used.

## Actual Behavior
AttributeError is thrown. Looks like this feature is not implemented, yet?

## Specifications

  - python-gitlab version: 1.3.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): Own GitLab server running 10.6.3

**Comment by gpocentek** [comment]
Hello @max-wittig 

The doc is incorrect for v4, it should be `project.services.available()`. You need to create a `Project` object first of course.
