### ISSUE TITLE
Question: cherrypick or rebase commits from a merge request

### ISSUE THREAD

**Issue by maikenp** [python-gitlab/python-gitlab#485]
Hi,

I have a webhook for merge requests, which evokes a script that creates a new merge request now to another target branch.

Lets say I have a source branch which was created off of master. This original source branch (which lives in a fork) has a merge request into the upstream master. Now I  would like to create a new merge request with the same commits as the first merge request onto another upstream target branch, let’s say next-major branch.

This works using the API and python-gitlab.

Only problem is that it is not that nice to use one source branch for merge requests into two different target branches. Reasons:

* There can be different merge conflicts for each merge, and solving this is awkward when there is one source branch
* Commits made to master which are inherited to the source branch and that are not present in the new target branch will be added to the list of commits in the new merge request. I would not like this, because it could be that these commits in fact should not be in the new target branch.

The better way to do this would therefore be to

* Create a new dev-branch (in fork) with parent being the forks copy of the upstream target branch 
* Rebase or in some way apply the commits from the original merge request onto this new dev-branch
* Create a merge request of this new dev-branch into the new target branch.

I can not seem to manage this with the API. There is a possibility to cherry-pick a merge request onto another branch, but when I try this, it only recognizes branches belonging to the target project. Not the fork project. Which is what I need, as all our merge requests come from forks, and the new source branch needs to be created in the fork.

Is there a way to do this that I have missed?

Thanks!
Maiken

**Comment by gpocentek** [comment]
Hi @maikenp 

I can't think of any solution using the current API.

My feeling is that the git workflow you are using needs a local git repository with multiple remotes, and cannot be handled with the API only.

**Comment by maikenp** [comment]
Hi, thanks a lot for your reply. 

Ok. 

Another option would be to be able to do the similar thing as the web-interface allows: 
In the merge request, click the "Cherry-pick" button, then check the box with "Start a new merge request with these changes" 

Would be awesome to also be able to do this from the API. But as far as I can see this is not possible. So that would be a feature request to GitLab API I suppose.

**Comment by maikenp** [comment]
Closing the case. 

A solution is  to create a dev-branch in the target project. Cherry-pick commits onto that branch, and merge it into source project branch.
