### ISSUE TITLE
Allow retrieving commits for merge request

### ISSUE THREAD

**Issue by rollie42** [python-gitlab/python-gitlab#491]
## Description of the problem, including code/CLI snippet
API does not support getting commits for merge request (or documentation hasn't been updated)

see: https://docs.gitlab.com/ce/api/merge_requests.html#get-single-mr-commits

## Expected Behavior
`project.commits()` should return a list of commits

## Actual Behavior
Not defined in docs

## Specifications
v4 (and v3?)

**Comment by gpocentek** [comment]
Hi @rollie42 

This is implemented, you can use the `commits()` method on `ProjectMergeRequest` objects: https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/v4/objects.py#L1561-L1587

This is documented in the v4 API: http://python-gitlab.readthedocs.io/en/stable/api/gitlab.v4.html#gitlab.v4.objects.ProjectMergeRequest.commits but I'll add an example.
