### ISSUE TITLE
I'm not able to block a user

### ISSUE THREAD

**Issue by patricialima** [python-gitlab/python-gitlab#494]
## Description of the problem, including code/CLI snippet
I'm using you package and I'm not able to block an user. For instance, when using the method block, i get an error: 404 error. 
However if I'm able to block an user in the website, what is going on with the API?

## Expected Behavior
Block an user. 

## Actual Behavior

<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <link href="/static.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
  <h1>404</h1>
  <h3>The page you were looking for doesn't exist.</h3>
  <hr/>
  <p>You may have mistyped the address or the page may have moved.</p>
</body>
</html>

## Specifications

  - python-gitlab version: 1.3.0
  - API version you are using (v3/v4): v3
  - Gitlab server version (or gitlab.com): 7

Can anyone help me?

**Comment by gpocentek** [comment]
Hi @patricialima 

Blocking a user using the API is supposed to be working, even on older version of Gitlab. Could you provide a code sample to try to reproduce the problem?

Thanks

**Comment by gpocentek** [comment]
I believe that your Gitlab server version is too old, and doesn't implement the block/unblock APIs. I've tested your sample against a 10.x server and it works fine, but it doesn't work against a Gitlab 7.12 server.

I'm afraid I can't help, the only solution I see is to upgrade your Gitlab server.

**Comment by patricialima** [comment]
@gpocentek thank you for your help. I will upgrade my gitlab version!
