### ISSUE TITLE
Search strings with a dash breaks config file parsing

### ISSUE THREAD

**Issue by jgeorgeson** [python-gitlab/python-gitlab#502]
## Description of the problem, including code/CLI snippet

While trying to search for users with a dash in the search string, CLI is throwing [this](https://github.com/python-gitlab/python-gitlab/blob/701169441194bf0441cee13f2ab5784ffad7a207/gitlab/config.py#L57) exception. Have confirmed with latest 1.4.0 release.

## Expected Behavior

```bash
[jgeorgeson@LCNVHD2DL002: ~/Code]
$ gitlab -o json -g example user list --search '-ci' --all
[]
```

## Actual Behavior

```bash
[jgeorgeson@LCNVHD2DL002: ~/Code]
$ gitlab -o json -g example user list --search '-ci' --all
Traceback (most recent call last):
  File "/usr/bin/gitlab", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/gitlab/cli.py", line 143, in main
    options.config_file)
  File "/usr/lib/python2.7/site-packages/gitlab/config.py", line 58, in __init__
    "configuration (%s)" % self.gitlab_id)
gitlab.config.GitlabDataError: Impossible to get gitlab informations from configuration (example)
```

## Specifications

  - python-gitlab version: `1.4.0`
  - API version you are using (v3/v4): `v4`
  - Gitlab server version (or gitlab.com): `10.2.8` and `10.7.2` (both EE)

**Comment by gpocentek** [comment]
Hi @jgeorgeson 

You need to escape `-` to handle the shell interpretation of the single quotes: `gitlab -o json -g example user list --search '\-ci' --all`. This is a shell behaviour, not a problem with python-gitlab.

**Comment by jgeorgeson** [comment]
Indeed. :|
