### ISSUE TITLE
query generated in list for page > 1 adds an extra id parameter

### ISSUE THREAD

**Issue by jouve** [python-gitlab/python-gitlab#504]
## Description of the problem, including code/CLI snippet
When I query group membership with more than 1 page, the queries after the first one contain an extra id parameter which I believe is useless

```
DEBUG:urllib3.connectionpool:https://:443 "GET /api/v4/groups/300/members?per_page=100&all=True HTTP/1.1" 200 27155
DEBUG:urllib3.connectionpool:https://:443 "GET /api/v4/groups/300/members?all=True&id=300&page=2&per_page=100 HTTP/1.1" 200 26820
DEBUG:urllib3.connectionpool:https://:443 "GET /api/v4/groups/300/members?all=True&id=300&page=3&per_page=100 HTTP/1.1" 200 3218
```
=> `&id=300`

This id is the same as the group id.

## Expected Behavior
no extra id param

## Actual Behavior
extra id param

## Specifications

  - python-gitlab version: python-gitlab==1.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 9.4.5

**Comment by gpocentek** [comment]
Hi @jouve 

The URL used when paginating with `all=True` or `as_list=False` (generator) is in fact the one returned by the GitLab server in the response `links` headers. The `id` attribute probably shouldn't be there but it's a GtiLab issue.

We technically could remove it in python-gitlab, but it would be additional code to handle a corner case that doesn't prevent to requests to properly work. So not worth it IMHO.
