### ISSUE TITLE
Add support to look up merge requests associated with a commit

### ISSUE THREAD

**Issue by ludstuen90** [python-gitlab/python-gitlab#516]
## Description of the problem, including code/CLI snippet
Starting in GitLab 10.7, the API now supports retrieving merge requests associated with a commit. 

## Expected Behavior
Ideally, we'd be able to use `python-gitlab` to look up merge requests associated with each commit.

## Actual Behavior
As far as I can tell, this new feature hasn't yet been implemented in Python-Gitlab.

## Specifications

  - python-gitlab version: 1.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 10.8.2-ee

**Comment by gpocentek** [comment]
Hi @ludstuen90 

This feature has been added in python-gitlab recently, in commit c19ad90b. It will be available in the 1.5 release.

**Comment by ludstuen90** [comment]
Outstanding, thanks!

**Comment by max-wittig** [comment]
@gpocentek When is 1.5 planned to be released?

**Comment by gpocentek** [comment]
@max-wittig no date defined yet, my goal is to implement the Gitlab EE features for 1.5. I think that everything could be done by the end of June, but no promise.
