### ISSUE TITLE
Fix Project all()

### ISSUE THREAD

**Issue by rokpu** [python-gitlab/python-gitlab#526]
## Description of the problem, including code/CLI snippet
The recently added project all function, `projects = gl.projects.all()`, doesn't seem to work.

## Expected Behavior
It should traditionally return all projects.

## Actual Behavior
AttributeError: 'ProjectManager' object has no attribute 'all'

## Specifications

  - python-gitlab version: 1.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by gpocentek** [comment]
Hi @rokpu 

The `all()` method doesn't exist any more in API v4. If you want to retrieve all the projects you need to use `gl.projects.list(all=True)`.

The python-gitlab documentation is incorrect and shouldn't reference the `all()` method.

**Comment by rokpu** [comment]
Thanks, @gpocentek that worked.
