### ISSUE TITLE
support author_id filter for project-merge-request CLI

### ISSUE THREAD

**Issue by nkiesel** [python-gitlab/python-gitlab#527]
Using API v4, I want to list all merge request created by me.  Gitlab API v4 added ["author_id" query parameter](https://docs.gitlab.com/ce/api/merge_requests.html#list-project-merge-requests) (amongst others I do not care about right now) in version 9.5 which would help me.

Right now I use `gitlab  -o json project-merge-request list --project-id 902  --all  | jq 'select(.author.id==18)` but I would like to use `gitlab  -o json project-merge-request list --project-id 902  --all --author-id 18` instead

**Comment by gpocentek** [comment]
Hello @nkiesel 

This filter has already been added in the master branch, it will be available in the 1.5.0 release that I intend to release by the end of the month.
