### ISSUE TITLE
Add `identities` support for User creation

### ISSUE THREAD

**Issue by raphaelyancey** [python-gitlab/python-gitlab#528]
## Description of the problem, including code/CLI snippet
```python
user_data = {
    'email': 'donald.duck@yopmail.com',
    'username': 'donald',
    'password': 'defaultpassword',
    'name': 'Donald Duck',
    'can_create_group': 'false',
    'skip_confirmation': 'true',
    'identities': [{'provider':'oauth2_generic', 'extern_uid':'3'}] # User with email `donald.duck@yopmail.com` and UID `3` already lives on the OAuth2 server
}

user = gl.users.create(user_data) # Success

user.identities # [] <--
```

## Expected Behavior
```python
user.identities == [{'provider':'oauth2_generic', 'extern_uid':'3'}]
```

## Actual Behavior
```python
user.identities == []
```

## Specifications

  - python-gitlab version: 1.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 10.4.2

**Comment by raphaelyancey** [comment]
Found it, my bad. Was trying to set it with an array whereas the API doc [clearly shows](https://docs.gitlab.com/ce/api/users.html#user-creation) that it's first-level props.

```python
u = gl.users.get(29)
u.provider = "oauth2_generic"
u.extern_uid = "3"
u.save()
```

**Comment by gpocentek** [comment]
Hi @raphaelyancey 

If that's OK with you I'll add the code sample you provided in the python-gitlab docs. This can probably be useful for other users.

**Comment by raphaelyancey** [comment]
@gpocentek Of course, go ahead!
