### ISSUE TITLE
Add support for issue "closed_by" attribute

### ISSUE THREAD

**Issue by dawithers** [python-gitlab/python-gitlab#529]
GitLab 10.6 onward supports closed_by attribute for issues

https://docs.gitlab.com/ce/api/issues.html#list-merge-requests-that-will-close-issue-on-merge

Currently the only way to do this is iterating through merge requests and matching on the "closes" attribute.

**Comment by gpocentek** [comment]
Hi @dawithers 

This feature is already implement in the master branch. It will be available in the 1.5 release.
