### ISSUE TITLE
Support for filtering and ordering when listing pipelines

### ISSUE THREAD

**Issue by feinstruktur** [python-gitlab/python-gitlab#533]
## Description of the problem, including code/CLI snippet

The pipelines list API does not support filtering and ordering:

proj = gl.projects.get(proj_id)
proj.pipelines.list(dict(ref='master'))

TypeError: list() takes 1 positional argument but 2 were given

Since there will typically be lots of pipelines in an active project this makes `list` not very useful.

## Expected Behavior

The [pipelines api](https://docs.gitlab.com/ce/api/pipelines.html) support filter parameters (e.g. `ref`, `status`, `sha`, etc) and ordering parameters (`order_by`, `sort`, etc) and ideally `list` would support all of them:

proj.pipelines.list(dict(ref='master', order_by='id', sort='asc'))

## Actual Behavior

`list` throws an exception when trying to add request parameters.

## Specifications

  - python-gitlab version: 1.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by gpocentek** [comment]
Hi @feinstruktur 

The syntax you are using is not correct. You should use `proj.pipelines.list(ref='master', order_by='id', sort='asc')`
