### ISSUE TITLE
cannot import new 1.5 version

### ISSUE THREAD

**Issue by vbenes** [python-gitlab/python-gitlab#535]
## Description of the problem, including code/CLI snippet
since the new 1.5 version

[root@testhostname harness]# python
Python 2.7.15 (default, Jun 19 2018, 09:56:21) 
[GCC 8.1.1 20180502 (Red Hat 8.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gl_api = gitlab.Gitlab.from_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/gitlab/__init__.py", line 178, in from_config
    config_files=config_files)
  File "/usr/lib/python2.7/site-packages/gitlab/config.py", line 142, in __init__
    self.api_version)
gitlab.config.GitlabDataError: Unsupported API version: 3

is this expected?

the same is on rhel7 and centos7

**Comment by vbenes** [comment]
with older version
[root@testhostname harness]# pip install -I python-gitlab==1.4.0
Collecting python-gitlab==1.4.0
  Using cached https://files.pythonhosted.org/packages/a0/bd/a75da04d189f6efe88769d392ae05d6242df0d5e0e0429bdd4415be7c15c/python-gitlab-1.4.0.tar.gz
Collecting requests>=2.4.2 (from python-gitlab==1.4.0)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting six (from python-gitlab==1.4.0)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests>=2.4.2->python-gitlab==1.4.0)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.4.2->python-gitlab==1.4.0)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests>=2.4.2->python-gitlab==1.4.0)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.4.2->python-gitlab==1.4.0)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Installing collected packages: idna, chardet, urllib3, certifi, requests, six, python-gitlab
  Running setup.py install for python-gitlab ... done
Successfully installed certifi-2018.4.16 chardet-3.0.4 idna-2.7 python-gitlab-1.4.0 requests-2.19.1 six-1.11.0 urllib3-1.23
[root@testhostname harness]# python
Python 2.7.15 (default, Jun 19 2018, 09:56:21) 
[GCC 8.1.1 20180502 (Red Hat 8.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import github
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named github
>>> import gitlab
>>> gl_api = gitlab.Gitlab.from_config()
>>>

**Comment by gpocentek** [comment]
Hi @vbenes 

API v3 support has been removed from python-gitlab 1.5.0, as noted in the release notes: http://python-gitlab.readthedocs.io/en/stable/release_notes.html#changes-from-1-4-to-1-5

If you need v3 support you will have to explicitly install python-gitlab<1.5.

**Comment by vbenes** [comment]
aha, I see it now in config, sorry it's not my code, trying to change api version, will report back and close

Thanks!!
