### ISSUE TITLE
is  "v4/projects/:id/repository/files/:file_path"  implemented ?

### ISSUE THREAD

**Issue by jmbeuken** [python-gitlab/python-gitlab#540]
## Description of the problem, including code/CLI snippet

I need to get file from repository with a specifique project id.

Previously, I using **pyapi-gitlab==7.8.5** module but it doesn't support API v4  : 

`file=gl.getfile(Project_id,"configure.ac",Branch)`

I try to find the same functionnality with python-gitlab, but I couldn't find it... 

I try to use [ project-files](http://python-gitlab.readthedocs.io/en/master/gl_objects/projects.html#project-files)...

But it's not workable...
while the link in the reference  [GitLab API:](https://docs.gitlab.com/ce/api/repository_files.html) points to the correct API used with curl  : 

`curl -H "PRIVATE-TOKEN:$token" "https://gitlab.domain.org/api/v4/projects/$id/repository/files/$file?ref=$branch"`

Any idea ?

Thanks for your help

## Specifications

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4):  v4
  - Gitlab server version (or gitlab.com):  11.0.0

**Comment by gpocentek** [comment]
Hello @jmbeuken 

You have to use the project `files` manager to retrieve files. For example:
```python
project = gl.projects.get(Project_id)
configure_ac = project.files.get("configure.ac", Branch)
content = configure_ac.decode()
```

**Comment by jmbeuken** [comment]
👍 

sorry, I misunderstood the examples in project file :-\

Thank you
