### ISSUE TITLE
members.get(1) not working ?

### ISSUE THREAD

**Issue by jmbeuken** [python-gitlab/python-gitlab#541]
## Description of the problem, including code/CLI snippet

example found on [Project members ](http://python-gitlab.readthedocs.io/en/master/gl_objects/projects.html#project-members)

code : 

```
gl = gitlab.Gitlab.from_config('project', ['/home/guest/.python-gitlab.cfg'])
gl.auth()

project = gl.projects.get(39)
members = project.members.list()
member = members[0]
print("member : %s" % member.username)
print("-------------------------------------")
member = project.members.get(1)
```
outputs : 

> member : trunk
> -------------------------------------
> Traceback (most recent call last):
>   File "./GetAllUsers.py", line 23, in <module>
>     member = project.members.get(1)
>   File "/home/buildbot/WorkSpace/abinit/local/lib/python2.7/site-packages/gitlab/exceptions.py", line 244, in wrapped_f
>     raise error(e.error_message, e.response_code, e.response_body)
> gitlab.exceptions.GitlabGetError: 404: 404 Not found

## Specifications

  - python-gitlab version:  1.5.1
  - API version you are using (v3/v4):  v4
  - Gitlab server version (or gitlab.com):  11.0.1

**Comment by gpocentek** [comment]
Is the user with id `1` a member of the project?

This API works fine for me.

**Comment by jmbeuken** [comment]
ha ! the argument of get() is the id of the member !
the title of the example is ambigous , no ?

> Get a single project member:

with the id of members, it works !

Thank you

**Comment by jmbeuken** [comment]
Thank you for  fe43a287 ! 
it's clear now...
