### ISSUE TITLE
Can't use behind proxy

### ISSUE THREAD

**Issue by cccaballero** [python-gitlab/python-gitlab#544]
## Description of the problem, including code/CLI snippet
Can't use the library or CLI tool behind an http (https) proxy

## Expected Behavior
Just work

## Actual Behavior
HTTPSConnectionPool(host='gitlab.com', port=443): Max retries exceeded with url: /api/v4/user (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Bad Gateway',)))

## Specifications

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): 3
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by gpocentek** [comment]
Hi @cccaballero 

The library supports proxies through python-requests Session objects. It is documented here: http://python-gitlab.readthedocs.io/en/stable/api-usage.html#proxy-configuration

Proxy support still needs to be implemented in the CLI though.

**Comment by cccaballero** [comment]
Hi @gpocentek , sorry for don't be more specific about the issue, I have used the proposed configuration using Session objects, but there is the 502 error, it seems to be on some calls don't going through the proxy, because I can see some "200" requests in the proxy log.

**Comment by gpocentek** [comment]
@cccaballero could you give me the URLs for which you get 502 errors? It will help me dig into this problem. You can remove specific IDs/information for privacy of course. Thanks!

**Comment by cccaballero** [comment]
Hi @gpocentek there seems to be an issue with the python requests library and my proxy, I can use tools like curl and wget without issues, but the Python requests always returns 502, so seems that it's not a  python-gitlab issue.

**Comment by gpocentek** [comment]
@cccaballero ok, thanks for the feedback.

**Comment by gpocentek** [comment]
As a side note requests seems to automatically handle the `http_proxy` and `https_proxy` variables so it is automatically handled by the `gitlab` CLI as well.

**Comment by nramirezuy** [comment]
@gpocentek What if I just need to use a proxy for Gitlab? I know I can still do it, but the user experience goes down the drain.

**Comment by max-wittig** [comment]
You can provide `no_proxy`

no_proxy=your-gitlab.com
