### ISSUE TITLE
list projects of which user is a member

### ISSUE THREAD

**Issue by bartos** [python-gitlab/python-gitlab#549]
## Description of the problem, including code/CLI snippet
How can I get a list of projects of which a user is a member? 
I can only get projects that user have created, using:
```
user_projects = user.projects.list()
```

I've found there is a [membership](https://docs.gitlab.com/ce/api/projects.html#list-user-projects) filter but I have no idea how to use it. At least I did not found a good example about this.

What I need to do is would be something like:
```
for u in ['user1','user2']:
    user = gl.users.list(username=u)[0]
    for pro in user.projects.list(membership=True):
        print(pro.name)
````

The goal is to revoke all given access for a user(or list of users). Maybe there is a simpler method for this?

## Specifications
  - python-gitlab version: 3.6.5
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 10.4.6, 10.8.4

**Comment by gpocentek** [comment]
Hi @bartos 

The GitLab user project API is not very clear, and I don't really know what the membership attribute is supposed to do. You are using it as expected with python-gitlab.

If your goal is to forbid any action you can block the user with `user.block()`.

**Comment by bartos** [comment]
Hi @gpocentek, thanks for the answer.

Unfortunatelly `user.block()` is won't work im my case.
I've figured out to compare two lists:
```
gl.projects.list(sudo=username,owned=True) # ownedOnly
gl.projects.list(sudo=username)    # all
```
And then I can simply compere both lists. 

I'm not sure if this will work in any case (for example I'm not using group access etc).. 
Assumption is `all - owned = member` ;)

**Comment by gpocentek** [comment]
Glad you found a solution! Thanks for your feedback.

**Comment by ikurek** [comment]
Any update on this for non-sudo users? When I try to use `gl.projects.list(sudo=username)` I always get `403` response.

**Comment by bartos** [comment]
@ikurek you need to be an `admin`, and second thing is that when you create a `Personal Token` to be used with the API, there is a `sudo` checkbox.
Take a look at the docs [here](docs.gitlab.com/ce/user/profile/personal_access_tokens.html).
I have no other idea why you could have a `403`.
