### ISSUE TITLE
feature idea : Kubernetes configuration

### ISSUE THREAD

**Issue by jpic** [python-gitlab/python-gitlab#551]
Thanks a lot for maintaining this library !

The feature idea : Manage k8s environments like environments, to edit clusters in the "Operations" -> "Kubernetes" project menu inside gitlab.

 gitlab.v4.objects.ProjectKubernetesManager & friends :joy:

**Comment by gpocentek** [comment]
Hello @jpic 

Thank you :)

Nice idea but this needs to be implemented in GitLab first. python-gitlab only manages what exists in the GitLab API. You should open an issue on their bugtracker to suggest this idea: https://gitlab.com/gitlab-org/gitlab-ce.

I'll be happy to add support for this feature as soon as it lands in Gitlab.

**Comment by jpic** [comment]
Thanks! [It's on](https://gitlab.com/gitlab-org/gitlab-ce/issues/49145) :joy:

**Comment by jpic** [comment]
FTR: it was [already on](https://gitlab.com/gitlab-org/gitlab-ce/issues/40473)

**Comment by J4lf** [comment]
The Gitlab API is now able to manage project level clusters and group level clusters. Would it be possible to add the support of these apis?
Thanks!

**Comment by max-wittig** [comment]
Sure. I just don't have any way to try this out, but I would be happy to review a MR regarding this topic.

**Comment by nejch** [comment]
I think this is done, with #946 and #947 merged :)
