### ISSUE TITLE
Implement MergeRequest pipeline listing

### ISSUE THREAD

**Issue by gsemet** [python-gitlab/python-gitlab#555]
https://docs.gitlab.com/ee/api/merge_requests.html#list-mr-pipelines

Does not seem to be available in Gitlab Python. This would allow doing:

```python
mr = gitlab.project.get(...).mergerequest.get(...)
mr.pipelines.list()
```

**Comment by gsemet** [comment]
Perfect !!

By the way, do you know if there is a way to find out the mergerequest from the pipeline ? For the moment I need to list all mergerequest and use the merge request pipeline

**Comment by gpocentek** [comment]
I don't think that there is an API that exposes that kind of information. You can probably open an issue on the GitLab bugtracker to request this new feature.

**Comment by gsemet** [comment]
On latest version of the Gitlab UI, it seems to retrieve this information from the commit with an weird call to:  `https://gitlab.server/path/to/project/commit/80dda390d116c06e1382390bb0a2ccc604141757/merge_requests.json`.

Ticket opened: [gitlab-ce/49438](https://gitlab.com/gitlab-org/gitlab-ce/issues/49438)
