### ISSUE TITLE
project-export download fails in cli.py

### ISSUE THREAD

**Issue by jgeorgeson** [python-gitlab/python-gitlab#559]
## Description of the problem, including code/CLI snippet

```powershell
> python --version
Python 3.6.5
7/20/2018 4:50:32 PM HBL4218 ~
> gitlab -g rd project-export download --project-id 3
```

Same behavior in Python 3.4.8 on CentOS, also with v1.5.1.

## Expected Behavior

Project export archive is downloaded

## Actual Behavior

```python
Traceback (most recent call last):
  File "C:\Python36\Scripts\gitlab-script.py", line 11, in <module>
    load_entry_point('python-gitlab==1.5.1', 'console_scripts', 'gitlab')()
  File "c:\python36\lib\site-packages\gitlab\cli.py", line 179, in main
    cli_module.run(gl, what, action, args, verbose, output, fields)
  File "c:\python36\lib\site-packages\gitlab\v4\cli.py", line 357, in run
    data = g_cli()
  File "c:\python36\lib\site-packages\gitlab\v4\cli.py", line 61, in __call__
    return self.do_custom()
  File "c:\python36\lib\site-packages\gitlab\v4\cli.py", line 73, in do_custom
    data[self.cls._id_attr] = self.args.pop(self.cls._id_attr)
KeyError: None
```

## Specifications

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 10.7.5 EE

**Comment by gpocentek** [comment]
@ManchurianSector this looks like a different issue, and from the backtrace you provided I don't think that you are not using version 1.5.1 of python-gitlab.

**Comment by gpocentek** [comment]
@jgeorgeson thanks for the bug report, the fix will be in the next release (coming soon).
