### ISSUE TITLE
Add support to add an attachment with issue note

### ISSUE THREAD

**Issue by archey** [python-gitlab/python-gitlab#56]
Is is possible to add in support for adding an attachment with the project issue note, I see the api supports it. I just dont see how to do it with the tool.

http://doc.gitlab.com/ce/api/notes.html

**Comment by gpocentek** [comment]
I don't see this feature in the gitlab API. Attachments seem to appear in the GET/LIST requests, but I don't see how they can be created. Or maybe I'm missing something?

**Comment by archey** [comment]
I believe your correct they dont seem to allow it in the api, which is quite strange. But don't worry we have it figured out. I'll close this now, thanks

**Comment by d0c-s4vage** [comment]
iirc this does exist in the API now. I'm see if I can get it working within python-gitlab and submit a pull request.

See: https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md#upload-a-file

**Comment by d0c-s4vage** [comment]
@gpocentek do you want to reopen this issue, or should I open a new issue for file uploads?

**Comment by gpocentek** [comment]
@d0c-s4vage let's re-open this one. Thank you for checking!
