### ISSUE TITLE
GitLab threw 500 error on project.branches.list(all=True)

### ISSUE THREAD

**Issue by CordThomas** [python-gitlab/python-gitlab#563]
## Description of the problem, including code/CLI snippet

I am extracting some metadata about our companies use of on-premise gitlab.   I ran the code a year ago and all worked.  I relied heavily on the gl.branches_list(...) that i have now switched to project.branches.list(...).   The code generally runs, but i just got a 500 error.   On inspection, the project in question is an empty project; no commits/code

My code is basically:

    projects = gl.projects.list(all=True) 
    for project in projects:
      branches = project.branches.list(all=True)
      for branch in branches:
        committer_id = useridmap.get(branch.commit['committer_email'].replace("@rand.org", ""))
        branched = [branch.project_id, branch.name, branch.commit['authored_date'], branch.commit['committed_date'],
                committer_id, len(branch.commit['message'])]
        branch_list.append(branched)

## Expected Behavior

I would think the code, branches.list(all=True) would return an empty set if no branches are found.  I can't seem to find a statement such as has_branches() or anything I could use to short-circuit this error.

## Actual Behavior

branches = project.branches.list(all=True)
  File "/Users/cthomas/anaconda3/lib/python3.5/site-packages/gitlab/exceptions.py", line 244, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabListError: 500: 500 Internal Server Error

## Specifications

  - python-gitlab version:   1.5.1
  - API version you are using (v3/v4):   v4
  - Gitlab server version (or gitlab.com):   10.2.1

**Comment by gpocentek** [comment]
Hi @CordThomas 

This problem seems to be a GitLab server issue rather than a python-gitlab one.

I've tested locally with a GitLab 10.8.1 installation and the request works fine on an empty project (returns an empty list). If it's possible for you I'd recommend to upgrade the GitLab server. Otherwise I don't really see an option to workaround this error except using a catch all exception.
