### ISSUE TITLE
Project issue.author.id throwing error - 'dict' object has no attribute 'id'

### ISSUE THREAD

**Issue by CordThomas** [python-gitlab/python-gitlab#564]
## Description of the problem, including code/CLI snippet

I have code that is used to identify the author of an issue:

    issue_author_id = issue.author.id

The author should be a json object that i feel should be an Author object but is being returned as a dictionary, not sure why.  So, now i have to convert a number of these calls to issue.author['id']

## Expected Behavior

Return the ID of the author object 

## Actual Behavior

Throws an error:

    AttributeError: 'dict' object has no attribute 'id'

## Specifications

  - python-gitlab version:    1.5.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):   10.2.1

**Comment by gpocentek** [comment]
Hi @CordThomas 

The `author` attribute is a dict, so you need to use `issue.author['id']`.

**Comment by CordThomas** [comment]
Thanks @gpocentek

**Comment by chandanshiva** [comment]
I have the same error for this, please help.



import json
import boto3

table = boto3.resource('dynamodb').Table('voters')
#dynamodb = boto3.resource('dynamodb')
#table = dynamodb.Table('voters')

def lambda_handler(event, context):
    
    response = table.get_item(
        Key={
        'id' : event.id
        
             }
    )
    
    return { 200, response["Item"]}





Response:
{
  "errorMessage": "'dict' object has no attribute 'id'",
  "errorType": "AttributeError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 12, in lambda_handler\n    'id' : event.id\n"
  ]
}

**Comment by max-wittig** [comment]
This is the python-gitlab library, not boto3.
