### ISSUE TITLE
Configuring mattermost service fails with error 400, because payload is not sent as JSON

### ISSUE THREAD

**Issue by matejzero** [python-gitlab/python-gitlab#568]
## Description of the problem, including code/CLI snippet

I'm trying to configure Mattermost notification service and it keeps throwing me error 400 `Bad Request`.

```
    service = project.services.get('mattermost')
    service.webhook = webhook_url
    service.save()
```

Error:
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gitlab/mixins.py", line 371, in save
    server_data = self.manager.update(obj_id, updated_data, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gitlab/v4/objects.py", line 2881, in update
    super(ProjectServiceManager, self).update(id, new_data, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gitlab/exceptions.py", line 244, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabUpdateError: 400: 400 Bad Request
```

Testing with curl, it also doesn't work if I don't explicitly set header to `application/json`:
```
$ curl -v --header "PRIVATE-TOKEN: xxxx-uti" -X PUT https://example.tld/api/v4/projects/7812837/services/mattermost -d '{"webhook":"https://mattermost.host/"}'
{"error":"webhook is missing"}
```

But it works when I set the header:
```
curl --header "PRIVATE-TOKEN: xxxx-uti" -H "Content-Type: application/json" -X PUT https://example.tld/api/v4/projects/7812837/services/mattermost -d '{"webhook":"https://mattermost.host/"}'
{"id":41005266,"title":"Mattermost notifications","created_at":"2018-08-08T08:48:45.976Z","updated_at":"2018-08-08T08:54:05.802Z","active":true,"push_events":true,"issues_events":true,"confidential_issues_events":true,"merge_requests_events":true,"tag_push_events":true,"note_events":true,"confidential_note_events":true,"pipeline_events":true,"wiki_page_events":true,"job_events":true,"properties":{"webhook":"https://mattermost.host/","notify_only_broken_pipelines":true,"notify_only_default_branch":true}}
```

## Expected Behavior

I expected that `project.save()` would save the settings and enable the service.

## Actual Behavior

GitLab returns a 400 error and doesn't setup the service. This did work when I was using API v3.

## Specifications

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.1.4

**Comment by gpocentek** [comment]
Hi @matejzero 

I've not been able to reproduce this problem (tested on a local gitlab and on gitlab.com). The Content-Type header is properly set. My guess is that a redirection is happening somewhere on the way, which removes both data and headers. Could you make sure that you are using `https://` in your gitlab URL?

Thanks.

**Comment by gpocentek** [comment]
I've tested with python-gitlab 1.5.1 and 1.6.0, againsta a local gitlab 11.0.4 and against gitlab.com, everything works fine, the Content-Type header is correct.

Could you enable debugging output with `gl.enable_debug()` before calling the `save()` method to have a look at what is sent to the server?

Thanks.

**Comment by matejzero** [comment]
I found the culprit! It was a setting in GitLab (`Allow requests to the local network from hooks and services`) which blocked outgoing connections to localhost. More info [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/48344).

After enabling it, script started to work.

Thanks for all the help and sorry for wasting your time.
