### ISSUE TITLE
Accessing a commit message via branches.list() removes all but the first line of a multi-line message

### ISSUE THREAD

**Issue by detly** [python-gitlab/python-gitlab#571]
Say I have a repo with only one branch, `master`, and the latest commit on master contains a multi-line message, like:

```text
Test of multiline commit message.

Line after empty line.
```

If I obtain this commit message via `branches.list()[0].commit['message']` I only get the first line. If I obtain it via `branches.get('master').commit['message']` I get the full message. I would expect to get the full message both ways.

The following script demonstrates the issue (substitute values for your own test project of course):

```python
import gitlab

# Set these
prj_id = 0
pvt_token = ''

client = gitlab.Gitlab('https://gitlab.com/', private_token=pvt_token)

msg1 = client.projects.get(prj_id).branches.get('master').commit['message']
msg2 = client.projects.get(prj_id).branches.list()[0].commit['message']

print(msg1)
print('----')
print(msg2)
```

The output on my machine is:

```
Test of multiline commit message.

Line after empty line.

----
Test of multiline commit message.
```

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by gpocentek** [comment]
Hi @detly 

The `message` content is dynamically generated from the GitLab server response, without any modification. The server returns different information depending on the query (list or get). GitLab itself would have to be modified to get the result you expect, this is not something I can modify on the python-gitlab side.
