### ISSUE TITLE
Any gl_object for SSH/ git clone project details?

### ISSUE THREAD

**Issue by AkhilaDamera** [python-gitlab/python-gitlab#573]
## python-gitlab/docs/gl_objects/projects.rst 
After the project creation using the gl_object, how to clone the created project to workspace?? 
Could you please let me know if there is any gl_object available for this??

  - python-gitlab version: 3.0.4 stable version
  - API version you are using (v3/v4): v4
Appreciate your help.

Thanks,
Akhila

**Comment by gpocentek** [comment]
Hi @AkhilaDamera 

Once you've created the project you get access to a set of attributes. The `ssh_url_to_repo` attribute provides the URL of the repository. You can use a git library or CLI to clone the project:

```python
import subprocess

project = gl.projects.create(data)
print(project.attributes)  # displays all the attributes
git_url = project.ssh_url_to_repo
subprocess.call(['git', 'clone', git_url])
```
