### ISSUE TITLE
gitlab <object> get just id have NOT detail ??? 

### ISSUE THREAD

**Issue by tmc9031** [python-gitlab/python-gitlab#575]
## Description of the problem, including code/CLI snippet

at first

```
$ gitlab project-merge-request list --project-id 2
iid: 8
```

## Expected Behavior

and then
```
$ gitlab project-merge-request get --project-id 2 --iid 8
  {
    "id": 8,
    "iid": 1,
    "target_branch": "master",
    "source_branch": "test1",
    "project_id": 2,
    "title": "test1",
    "state": "opened",
    "created_at": "2017-04-29T08:46:00Z",
    "updated_at": "2017-04-29T08:46:00Z",
    "upvotes": 0,
    "downvotes": 0,
    "author": {
      "id": 1,
      "username": "admin",
      "name": "Administrator",
      "state": "active",
      "avatar_url": null,
      "web_url" : "https://gitlab.example.com/admin"
    },
    "assignee": {
      "id": 1,
      "username": "admin",
      "name": "Administrator",
      "state": "active",
      "avatar_url": null,
      "web_url" : "https://gitlab.example.com/admin"
    },
```

## Actual Behavior
only get id .....
```
$ gitlab project-merge-request get --project-id 2 --iid 8
iid: 8

```
## Specifications

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): 4
  - Gitlab server version (or gitlab.com): 11.1.4-ce.0

**Comment by gpocentek** [comment]
Multiple solutions:

* `gitlab -v project-merge-request get --project-id 2 --iid 8` will display more information (verbose output)
* `gitlab -o json project-merge-request get --project-id 2 --iid 8` will display the output as unformatted json. Use a tool like `jq` if you want a better display.
* `gitlab -o yaml project-merge-request get --project-id 2 --iid 8` will display the output as yaml (you need to install pyyaml).
