### ISSUE TITLE
Getting list of pipeline's jobs does not work

### ISSUE THREAD

**Issue by nickolas-pohilets** [python-gitlab/python-gitlab#578]
## Description of the problem, including code/CLI snippet

```python3
import gitlab
g = gitlab.Gitlab('https://gitlab.example.com', private_token='...', api_version='4')
proj = g.projects.get(1, lazy=True)
for pipeline in proj.pipelines.list(as_list=False):
    jobs = pipeline.jobs.list()
    print(jobs)
    break
```

## Expected Behavior
List of jobs should be printed

## Actual Behavior
Getting `AttributeError: jobs`

## Specifications
  - python-gitlab version: 1.2.0
  - API version: v4
  - Gitlab server version: 11.1.4-ee

**Comment by gpocentek** [comment]
Hi @nickolas-pohilets 

The job listing API has been implemented in a newer release of python-gitlab, you should consider upgrading.
