### ISSUE TITLE
docs for gl.projects.owned() wrong

### ISSUE THREAD

**Issue by yamagoya** [python-gitlab/python-gitlab#579]
The documentation at 
  https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html
give example code:

    # List owned projects
    projects = gl.projects.owned()

but using that construct produces an AttributeError.

    import gitlab
    token = os.environ['TOKEN']
    gl = gitlab.Gitlab('http://gitlab.com', private_token=token)

      # This works but is not documented...
    projects = gl.projects.list(owned=True)

      # Documentation says to use this but it fails with
      #   AttributeError: 'ProjectManager' object has no attribute 'owned' 
    projects = gl.projects.owned()

  - python-gitlab version: 1.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by gpocentek** [comment]
Thank you for the bug report, I've updated the documentation.
