### ISSUE TITLE
Implement project deploy token

### ISSUE THREAD

**Issue by rgarrigue** [python-gitlab/python-gitlab#583]
Hi

I'm using GitLab Community Edition 11.0.4 and latest python-gitlab (pip installed today). There's nothing to handle deploy tokens (I'm not speaking about deploy keys here !)

![image](https://user-images.githubusercontent.com/1872031/45293872-b87f3180-b4f9-11e8-91b3-91c0c113ec84.png)

Is this planned ? 

Best regards,

**Comment by gpocentek** [comment]
Hi @rgarrigue 

I couldn't find any reference to deploy tokens in the GitLab API documentation. If this API doesn't exist python-gitlab will not be able to handle this feature. Do you have a link to code or documentation?

Thanks.

**Comment by rgarrigue** [comment]
Hi @gpocentek 

Seems it's missing, I found the related FR here https://gitlab.com/gitlab-org/gitlab-ce/issues/45149

So I guess that make this issue on hold as a reminder for later on, or if implementing new API is part of your process it can be closed.

**Comment by max-wittig** [comment]
Let's close this for now. We don't know, if this will every be available as API.

**Comment by machine424** [comment]
a Deploy Token API is now available: https://docs.gitlab.com/ee/api/deploy_keys.html
Are you planning to support it ? I can help.

**Comment by max-wittig** [comment]
Sure. We're open for MRs!

**Comment by max-wittig** [comment]
@machine424 I've check again and it seems like we already support deploy keys: https://python-gitlab.readthedocs.io/en/latest/gl_objects/deploy_keys.html

**Comment by nejch** [comment]
@max-wittig although the link given was to the Deploy Keys API, it's true that the Deploy Token API will be available with 12.9 (and is probably testable already on nightly images and gitlab.com): https://docs.gitlab.com/ee/api/deploy_tokens.html

So it looks like this will be relevant again soon :)

**Comment by machine424** [comment]
@max-wittig, I didn't check the link after pasting it. I was talking about Deploy Tokens. (thanks @nejch)
I can open a draft PR.

**Comment by machine424** [comment]
The PR is here: https://github.com/python-gitlab/python-gitlab/pull/1052

**Comment by nejch** [comment]
Closing this as #1052 has been merged.
