### ISSUE TITLE
Problem to upload a file

### ISSUE THREAD

**Issue by miguelconde91** [python-gitlab/python-gitlab#588]
I'm trying to upload a file to my gitlab repository using this way:
x = project.upload("Jenkinsfile", filepath="./Jenkinsfile") however it not work for me, so
x1 = project.upload("Jenkinsfile", filepath="/media/conde/Trabajo/Trabajo/DevOps/BOMH/bomh/Jenkinsfile") , not work, let's go to trying the documentation example because it not need a filesystem path, so it have at least to create a new file empty:
x2 = project.upload("filename.txt", filedata="data") 

But never a file is uploaded. The output of each comand is:
x = {'url': '/uploads/c52cf003900c7afe6843909317049cc3/Jenkinsfile', 'markdown': '[Jenkinsfile](/uploads/c52cf003900c7afe6843909317049cc3/Jenkinsfile)', 'alt': 'Jenkinsfile'}
x1 = {'url': '/uploads/c52cf003900c7afe6843909317049cc3/Jenkinsfile', 'markdown': '[Jenkinsfile](/uploads/c52cf003900c7afe6843909317049cc3/Jenkinsfile)', 'alt': 'Jenkinsfile'}
x2 = {'url': '/uploads/3c2a389555609ba08c3bd54bee0e7339/filename.txt', 'markdown': '[filename.txt](/uploads/3c2a389555609ba08c3bd54bee0e7339/filename.txt)', 'alt': 'filename.txt'}

What is wrong, the documentation, the API?
I can create the repository, the branchs and create some files, but not upload a file from my computer.

**Comment by gpocentek** [comment]
Hi @miguelconde91 

`project.upload` adds a file to the GitLab project, not to the project repository. The uploaded file can be used in comments, wiki pages, and so on.

To add files to the git repository of the project you must use the `project.files` manager: https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-files

**Comment by miguelconde91** [comment]
Ok, thanks by your answer. One last doubt, in the API documentation I did not find how to protect a file in my Gitlab repository against writing, something like doing this https://docs.gitlab.com/ee/user/project/file_lock.html That functionality does not is it still implemented in the API?

**Comment by gpocentek** [comment]
Hi @miguelconde91 

I looked at the docs but I don't think that the locking feature is available in the GitLab API.
