### ISSUE TITLE
Is there a way to list only projects that are not originated by a user but only shared from somewhere else

### ISSUE THREAD

**Issue by tillea** [python-gitlab/python-gitlab#591]
Hi,
I'm using

    projects = group.projects.list(all=True, order_by='name', sort='asc', simple=True)

to list all projects of a group.  Unfortunately this returns also those projects which are originated in a different group but shared with the group that is queried.  Is there a way to exclude those projects from the return set?

**Comment by norpol** [comment]
Hi.

I'd recommend reading the official [API documentation for groups](https://docs.gitlab.com/ee/api/groups.html#list-a-group-s-projects) in this case. This behavior is probably mostly based on what the API is responding, judging by this there are some return-values that should help you to distinguish between shared and actual members of.

Since you are using `simple=True` there is not as much data available, but would this snippet work for you?

```python
gl = gitlab.Gitlab(url="https://gitlab.com", private_token="<your token>")
group = gl.groups.get("sydpol/python-gitlab/test-group-1")
projects = group.projects.list(all=True, order_by="name", sort="asc", simple=True)

no_shared_projects = [
    proj
    for proj in projects
    if proj.attributes["namespace"]["name"] == group.attributes["name"]
]
```

**Comment by tillea** [comment]
Hi,
On Thu, Sep 27, 2018 at 05:10:22AM -0700, Phi|eas |ebada wrote:
> I'd recommend reading the official [API documentation for groups](https://docs.gitlab.com/ee/api/groups.html#list-a-group-s-projects) in this case. This behavior is probably mostly based on what the API is responding, judging by this there are some return-values that should help you to distinguish between shared and actual members of.
> 
> Since you are using `simple=True` there is not as much data available, but would this snippet work for you?
I'm using something similar than your code currently.  The background of my question is to fetch as sparse data as possible - that's why the simple=True parameter.  If there is no option to shorten the list of returned projects in the first place (and I do not see any option inside the API documentation) there is probably nothing the Python wrapper of the API can do.
Kind regards, Andreas.

**Comment by norpol** [comment]
Alright, please share such a detail the next time :-).

I guess the issue is resolved now?

**Comment by tillea** [comment]
On Thu, Sep 27, 2018 at 06:47:23AM -0700, Phi|eas |ebada wrote:
> Alright, please share such a detail the next time :-).
Yes, sorry.
> I guess the issue is resolved now?
Yes.  Thanks for your patience, Andreas.

**Comment by norpol** [comment]
Sorry! Wasn't meant negatively :smile:, no one asked me to come up with an example either. Was a fun quickly coming up with something, this is one of my favorite API wrappers at the moment.
