### ISSUE TITLE
python-gitlab adds a very serious overhead compared to direct requests

### ISSUE THREAD

**Issue by benoit-leveau** [python-gitlab/python-gitlab#592]
For a project with ~500 tags, calling
`project.tags.list(all=True)`
takes around 7s-10s.

Requesting the corresponding page from the web server (.../api/v4/projects/ID/repository/tags) takes around 250ms.

If an application has to query a few projects, this easily adds up to a minute, for something that really should take a couple of seconds at most.

## Specifications
  - python-gitlab version: 1.6.0
  - API version you are using: v4
  - Gitlab server version: self-hosted - 11.2.3

**Comment by benoit-leveau** [comment]
So it looks like when calling list(all=True), it will then proceed to call:

```
_query http://mygitlab/api/v4/projects/7/repository/tags
_query http://mygitlab/api/v4/projects/7/repository/tags?all=True&id=7&order_by=updated&page=2&per_page=20&sort=desc
_query http://mygitlab/api/v4/projects/7/repository/tags?all=True&id=7&order_by=updated&page=3&per_page=20&sort=desc
_query http://mygitlab/api/v4/projects/7/repository/tags?all=True&id=7&order_by=updated&page=4&per_page=20&sort=desc
_query http://mygitlab/api/v4/projects/7/repository/tags?all=True&id=7&order_by=updated&page=5&per_page=20&sort=desc
_query http://mygitlab/api/v4/projects/7/repository/tags?all=True&id=7&order_by=updated&page=6&per_page=20&sort=desc
_query http://mygitlab/api/v4/projects/7/repository/tags?all=True&id=7&order_by=updated&page=7&per_page=20&sort=desc
...
```
So I tried to change per_page to 5000 but it looks like it's hard-coding a max of 100. Even though using a max of 5000 in a web browser works.

**Comment by gpocentek** [comment]
Hi @benoit-leveau 

The hard limit of 100 item is enforced by the GitLab server side, python-gitlab doesn't have control on this.

**Comment by benoit-leveau** [comment]
Yes I've made more tests and realised the limit is set by the server.

If I want to use 100 I can use set it in the query function or for all my queries directly in the constructor of the gitlab client:
`client = Gitlab.gitlab(.., per_page=100)`

So it's all good now.
