### ISSUE TITLE
Can`t update project variable

### ISSUE THREAD

**Issue by shellshock1953** [python-gitlab/python-gitlab#594]
## Description of the problem, including code/CLI snippet

`git = gitlab.Gitlab('https://gitlab.###.com', private_token='###')`
`project = git.projects.get(510)`
`project.variables.create({'key':'new_var', 'value':'new_var_content'})`
`project.variables.list()`
`[<ProjectVariable key:new_var>]`

## Expected Behavior

`project.variables.update({'key':'new_var', 'value':'some_new_content'})`
var **new_var** will get **some_new_content**

## Actual Behavior

`project.variables.update({'key':'new_var', 'value':'some_new_content'})`
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-241-1cb678558774> in <module>()
----> 1 project.variables.update({'key':'new_var', 'value':'some_new_content'})

/data/ENV/quinta/lib/python2.7/site-packages/gitlab/exceptions.pyc in wrapped_f(*args, **kwargs)
    244         def wrapped_f(*args, **kwargs):
    245             try:
--> 246                 return f(*args, **kwargs)
    247             except GitlabHttpError as e:
    248                 raise error(e.error_message, e.response_code, e.response_body)

/data/ENV/quinta/lib/python2.7/site-packages/gitlab/mixins.pyc in update(self, id, new_data, **kwargs)
    260             path = '%s/%s' % (self.path, id)
    261
--> 262         self._check_missing_update_attrs(new_data)
    263         files = {}
    264

/data/ENV/quinta/lib/python2.7/site-packages/gitlab/mixins.pyc in _check_missing_update_attrs(self, data)
    215                 continue
    216         if missing:
--> 217             raise AttributeError("Missing attributes: %s" % ", ".join(missing))
    218
    219     def get_update_attrs(self):

AttributeError: Missing attributes: key, value
```

## Specifications

  - python-gitlab version: python-gitlab==1.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.3.0

**Comment by norpol** [comment]
Hi.

Judging by the official API documentation to [Project-level Variables API](https://docs.gitlab.com/ee/api/project_level_variables.html#create-variable), there is no distinction of update and create, besides HTTP PUT vs. POST - so I'd also expect your example to work.

If you checkout the [`mixins.py`](https://github.com/python-gitlab/python-gitlab/blob/5e6330f82b121a4d7772f4083dd94bdf9a6d915d/gitlab/mixins.py#L241) it's clear that `update` consumes  `id` and `new_data`. Here is the [documentation](https://python-gitlab.readthedocs.io/en/stable/api/gitlab.v4.html#gitlab.v4.objects.ApplicationSettingsManager.update) on this behavior.

So it's actually working like this:

`project.variables.update(id='new_var', new_data={'key':'new_var', 'value':'some_new_content'})`

By reading this, I'd expect to be able to "rename" variables by doing something like:

`project.variables.update(id='new_var', new_data={'key': 'renamed_var'})`

but just tested it, and won't work.

1. I think for consistency `update` mixin to accept just `data` (similar to `create`) and then extracting the `id` by reading the `key` (in case for variables) would be appreciated.
   1. Would still have to support the "current" way of calling `update`
   2. Trade off: Introduces complexity
2. In any case:
   1. right now there is no test for updating vars, only [create](https://github.com/python-gitlab/python-gitlab/blob/b325bd73400e3806e6ede59cc10011fbf138b877/tools/python_test_v4.py#L599) - besides there is a test for the [update mixin](https://github.com/python-gitlab/python-gitlab/blob/5e6330f82b121a4d7772f4083dd94bdf9a6d915d/gitlab/tests/test_mixins.py#L385)
    2. we should expand the documentation of group and project variables by adding the update example

**Comment by gpocentek** [comment]
@norpol renaming variables is not supported, you have to create a new variable and remove the existing one to simulate this behaviour.

@shellshock1953 you have 2 solutions to update the value of a variable:

```
# @norpol solution, with a minor change
project.variables.update(id='new_var', new_data={'value':'some_new_content'})

# or using a lazy object
v = project.variables.get('new_var', lazy=True)
v.value = 'some_new_content'
v.save()

**Comment by DylanGraham** [comment]
I have the same error in the `gitlab` command, does this need to be updated there also?

**Comment by nathan5280** [comment]
I see the same behavior with the both get and update from the command line with API version 4.

**In gitlab.v4.cli.py:**
```python
class GitLabCLI(object):
    def do_get(self):
        id = None
        if gitlab.mixins.GetWithoutIdMixin not in inspect.getmro(self.mgr_cls):
            id = self.args.pop(self.cls._id_attr)

        try:
            return self.mgr.get(id, **self.args)
        except Exception as e:
            cli.die("Impossible to get object", e)

    def do_update(self):
        id = None
        if gitlab.mixins.GetWithoutIdMixin not in inspect.getmro(self.mgr_cls):
            id = self.args.pop(self.cls._id_attr)
        try:
            return self.mgr.update(id, self.args)
        except Exception as e:
            cli.die("Impossible to update object", e)
```
I can see that the --key argument is popped off the list of arguments when it sets the id that is added to the path in the http request.  

**In gitlab.mixins.py:**
```python
class UpdateMixin(object):
    def _check_missing_update_attrs(self, data):
        required, optional = self.get_update_attrs()
        missing = []
        for attr in required:
            if attr not in data:
                missing.append(attr)
                continue
        if missing:
            raise AttributeError("Missing attributes: %s" % ", ".join(missing))
```
When the parameters are validated at this point, --key is still expected in the required arguments, but it has been popped from the argument list.  If I put --key back in the argument list, the call to GitLab will work fine.

If I add this test to tools/cli_test_v4.sh:
```commandline
# Test project variables
testcase "create project variable" '
    OUTPUT=$(GITLAB -v project-variable create --project-id $PROJECT_ID \
        --key junk --value car)
    echo $OUTPUT

    OUTPUT=$(GITLAB -v project-variable get --project-id $PROJECT_ID \
        --key junk --value bus)
    echo $OUTPUT
'
```

I get the following output.
```commandline
Testing create project variable... key: junk protected: False value: car
Impossible to update object (Missing attributes: key)
```
