### ISSUE TITLE
CLI: is there anything between single page and `--all` ?

### ISSUE THREAD

**Issue by cleeland** [python-gitlab/python-gitlab#598]
## Description of the problem, including code/CLI snippet
Any `list` operation seems to support either retrieving a single "page" (which is how the actual API works), or all entries.  Is there anything in between that would let me ask for a number of entries and it would manage the pagination, stopping when it hits the desired number of entries?

## Specifications

  - python-gitlab version: 1.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.2.3-ee

**Comment by max-wittig** [comment]
If you use list as generator:
```python
projects = gl.projects.list(as_list=False)
```

You can then just slice the generator
```python
import itertools

limit = 10 # number of projects to fetch
projects = itertools.islice(projects, limit)
```

**Comment by gpocentek** [comment]
Hi @cleeland 

With the cli you can use the `--per-page` adn `--page` options: `gitlab project list --per-page 10 --page 5`.

Note that GitLab has an hardcoded limit of 100 items per page, a higher value will be ignored by the server.

**Comment by cleeland** [comment]
@gpocentek 
> you can use the --per-page and --page options: gitlab project list --per-page 10 --page 5

this will only yield 10 entries, though--specifically (since page numbering starts at 1), entries 40-49.  I'm looking for a way to ask for a total number of entries and not have to worry about pages or page size much in the same way that `--all` relieves me of that tedium.

@max-wittig intriguing idea. Requires writing python code rather than simply using the CLI, but that may still work for me.

**Comment by hans-d** [comment]
@cleeland can you describe your use case a bit? Why would you only want to request max 223 items ? And why should the cli handle it?

If this number is between 1 and 100 (say 90) you could use `--per-page 90` as indicated by others.

Otherwise you could use `jq` (needs json output), eg `gitlab -o json project list -all | jq '.[:125]'` to get the first 125 (but yes, it will fetch more initially if there are)

**Comment by zoidbergwill** [comment]
If the generator automatically paginates for you, then fetching the first slice of whatever total limit you want could work, but I understand how receiving the first 500/125/x projects or something could be useful.

**Comment by zoidbergwill** [comment]
I do feel like how `GitlabList ` works is a bit magical [here](https://sourcegraph.com/github.com/python-gitlab/python-gitlab/-/blob/gitlab/__init__.py#L752-762), though maybe I missed some examples in the docs, or we could add more.

And I think defaulting to `per_page=100` would increase the memory overhead, but improve the performance a lot, especially in the case of people using a generator.

**Comment by bittner** [comment]
What if you have more than, say, 100 projects? You'll only get the first 100 in any case, whether you do a list or use an generator. (I guess this is just about how we handle this with Python, correct? It doesn't affect how we operate the REST API.)

Is there a way to filter the projects to circumvent the hardcoded 100 projects limit?

**Comment by max-wittig** [comment]
I think this can be solved by using something like jq. For more advanced use-cases the python API wrapper should be used.
