### ISSUE TITLE
python-gitlab TLS connection failing intermittently

### ISSUE THREAD

**Issue by jagadish432** [python-gitlab/python-gitlab#610]
## It is listing all the projects in the above url, but not always (once in a 10  times , it is failing)  
below is the code snipplet of my code:
gl = gitlab.Gitlab('https://gitlab.<client_company_name>.com', <gitlab_token>')
print(gl)
projects = gl.projects.list()

## Specifications

  - python-gitlab version: 1.4.0
  - API version you are using (v3/v4):  V4
  - Gitlab server version (or gitlab.com):  https://gitlab.<my_client_company_name>.com

**Comment by max-wittig** [comment]
Thanks for reporting this issue, but it doesn't look like an issue with python-gitlab and more with your connection. Does your company have proxies configured? Did you try with another computer? Are you getting blocked by some firewall?
What is the output of `curl -vvvv gitlab.company.com` if you run it a few times?
These are just some ideas I got, why it may fail randomly.

**Comment by gpocentek** [comment]
Closing this issue since we didn't get feedback. Feel free to reopen.
