### ISSUE TITLE
API resource_label_events

### ISSUE THREAD

**Issue by williamborba** [python-gitlab/python-gitlab#611]
## Description of the problem, including code/CLI snippet

Hello, what is the forecast to implement the new api - https://docs.gitlab.com/ce/api/resource_label_events.html

## Specifications

  - python-gitlab version: stable
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
Thanks for your feature request.

There is not really a forecast for new features. It's implemented, when someone comes around to it. If you want to speed up the process, we would be happy to review your merge request implementing the feature.
