### ISSUE TITLE
get file from a commit

### ISSUE THREAD

**Issue by jmbeuken** [python-gitlab/python-gitlab#614]
## Description of the problem, including code/CLI snippet

Hello, I use this code to study the contents of a file

```
project = gl.projects.get(Project_id)
file = project.files.get("file.txt", Branch)
content = file.decode()
```

but, I would like to select a specific commit

`file = project.files.get("file.txt", Branch,  Commit )`

how to get this "behavior" with python-gitlab ?

thank you

## Specifications

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.3.4

**Comment by gpocentek** [comment]
Hi @jmbeuken 

The 2nd argument of the `get()` method doesn't have to be a branch name, it can be a commit ID:

```python
>>> project.files.get('site.yml', '29c459cc')
<ProjectFile file_path:site.yml>
```

**Comment by jmbeuken** [comment]
Thank You...

For me,  [examples](https://python-gitlab.readthedocs.io/en/master/gl_objects/projects.html) are my bible  : I rarely look in References! :-\

Finally, I found the info in Reference v4 API:

https://python-gitlab.readthedocs.io/en/master/api/gitlab.v4.html#gitlab.v4.objects.ProjectFileManager

`ref (str) – Name of the branch, tag or commit`
