### ISSUE TITLE
Handle missing config file

### ISSUE THREAD

**Issue by FedericoCeratto** [python-gitlab/python-gitlab#622]
## Description of the problem, including code/CLI snippet

When '~/.python-gitlab.cfg' is missing, an full traceback is printed

## Expected Behavior

Create a default '~/.python-gitlab.cfg' file and print
"The tool is not configured yet. Edit ~/.python-gitlab.cfg and run the command again"

## Actual Behavior

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912537

## Specifications

  - python-gitlab version: 1.6.0

**Comment by gpocentek** [comment]
Fixed in #623
