### ISSUE TITLE
user_activities.list() : "from" parameter ?

### ISSUE THREAD

**Issue by jmbeuken** [python-gitlab/python-gitlab#629]
## Description of the problem, including code/CLI snippet

how did you implement the "from" parameter in the function : 

`activities = gl.user_activities.list(all=True, as_list=False,  from='2018-01-01')`

found in the API : https://docs.gitlab.com/ce/api/users.html#get-user-activities-admin-only

thank you

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.4.4

**Comment by gpocentek** [comment]
@jmbeuken 

Well it is not possible to use `from` for now as it obviously conflicts with the python keyword. We'll need to implement a workaround for this.

Thanks for raising the issue!
