### ISSUE TITLE
Unable to import a project with .tar.gz file

### ISSUE THREAD

**Issue by vikramuk** [python-gitlab/python-gitlab#630]
Trying to import a .tar.gz file generated by an export.Observed that the script fails to import the project
Fails on Omnibus 11.3.4 instance

## Expected Behavior
Import script is successful 

## Actual Behavior
Output variable is not defined in scope.

## Specifications

  - python-gitlab version: 1.6
  - API version you are using (v3/v4):v4 
  - Gitlab server version (or gitlab.com): private instance with 11.3.4

**Comment by vikramuk** [comment]
https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#import-export

Output is not defined..

gl.projects.import_project(open('/tmp/export.tgz', 'rb'), 'my_new_project')
# Get a ProjectImport object to track the import status
project_import = gl.projects.get(output['id'], lazy=True).imports.get()
while project_import.import_status != 'finished':
    time.sleep(1)
    project_import.refresh()

**Comment by amitanand123infogix** [comment]
I am also facing same issue
