### ISSUE TITLE
Retry-After header may be missing: need default timeout

### ISSUE THREAD

**Issue by wvxvw** [python-gitlab/python-gitlab#632]
## Description of the problem, including code/CLI snippet
The `retry-after` header is not always present, in which case, the client crashes.

## Expected Behavior
When there isn't a `retry-after` header, the client uses a default retry timeout.

## Actual Behavior
When there isn't a `retry-after` header, the client crashes

## Specifications

  - python-gitlab version: 1.6.0
  - API version you are using (v3/v4): Whatever they use on gitlab.com
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by max-wittig** [comment]
@wvxvw You can temporary disable the `obey_rate_limit` feature in the meantime (which actually then causes a 429 crash, not sure if helpful)

I will fix the feature, but I would vote against implementing a default timeout, as no one knows what the right value should be there. Could be different for every server.

Instead the feature should just be disabled, if there is no retry-after header and cause the 429 error, which also can be caught.

**Comment by wvxvw** [comment]
@max-wittig Default may come from configuration, or as an argument to the client etc.  It doesn't have to be non-configurable.

Another approach is to do some sort of "smart" back-off, where you increase the timeout every time you get "too many requests".

There are many ways to make this more useful. Raising an error in this case will only delegate the responsibility for implementation to the library user, but will not make any progress towards solving it.

**Comment by max-wittig** [comment]
@wvxvw good idea and you're right. The library user shouldn't have to deal with this stuff. It should just be possible to disable it. Thanks for your input.
