### ISSUE TITLE
Feature idea: autocompletion for CLI mode

### ISSUE THREAD

**Issue by Skyross** [python-gitlab/python-gitlab#637]
## Description of the problem, including code/CLI snippet

Feature/improve suggestion: in many of my cases, I would like to have an autocompletion to have less time to spend at docs and source code to find out all possible combination of commands/object/args.

## Expected Behavior

Would be great to have autocompletion for bash or zsh.

## Actual Behavior

No completion right now.

## Specifications

  - python-gitlab version: 1.6.0
  - API version you are using (v3/v4): 4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by jhermann** [comment]
click has completion built in, so the strategy might be "switch from argparse to click".

**Comment by orzechow** [comment]
Autocompletion is not working for me – neither in bash nor zsh.
The documentation introduced in #941 has disappeared meanwhile.

What's the state here? Is autocompletion supported?

**Comment by max-wittig** [comment]
@orzechow Did you install python-gitlab with the autocomplete extra?

pip install python-gitlab[autocompletion]

**Comment by max-wittig** [comment]
And the documentation didn't disappear. They are right here: https://python-gitlab.readthedocs.io/en/latest/cli.html#enabling-shell-autocompletion

**Comment by orzechow** [comment]
> @orzechow Did you install python-gitlab with the autocomplete extra?

Yes, I tried a fresh installation of `python-gitlab[autocompletion]` with pip and pip3, in user space and a virtual environment, with zsh and bash. None provides autocompletion.
Any tricks?

Btw. why the brackets in `python-gitlab[autocompletion]`? Is it some magic pip syntax or so?
It breaks many things... Can't find it with `pip search`, can't show if it is installed with `pip show` or `pip list`, have to put that expression into quotes in zsh, …

> And the documentation didn't disappear. They are right here: https://python-gitlab.readthedocs.io/en/latest/cli.html#enabling-shell-autocompletion

Okay, so the documentation didn't make it to stable yet, I see. The stable version of readthedocs is what duckduckgo was pointing me to:
https://python-gitlab.readthedocs.io/en/stable/cli.html

**Comment by orzechow** [comment]
Btw.

```
gitlab --version
2.2.0
```

**Comment by orzechow** [comment]
Nevermind, I forgot to run `eval "$(register-python-argcomplete gitlab)"`.
Was too confused with these brackets probably :see_no_evil: 

Works in bash and zsh now :sweat_smile:

**Comment by jhermann** [comment]
`foo[bar]` is an *extra* (bar) in "foo" and part of setuptools for ages now.

**Comment by orzechow** [comment]
> `foo[bar]` is an _extra_ (bar) in "foo" and part of setuptools for ages now.

Thanks, haven't seen that yet. I'm not a regular Python developer though.
