### ISSUE TITLE
Add/Update group/project avatar

### ISSUE THREAD

**Issue by Flow86** [python-gitlab/python-gitlab#645]
Hi,

I tried to update the group avatar via the "avatar" property of a "group" object.

I tried different approaches:

1. local file name (no error, no avatar)
2. binary file data (no error, no avatar)
3. file descriptor like #308  (json error)

Could it be that it is not implemented in 1.6.0 like #308?

**Comment by gpocentek** [comment]
Hi @Flow86 

Avatars for groups are not properly implemented yet, we'll fix that using the same method as for projects avatars.

**Comment by gpocentek** [comment]
@Flow86 it looks like Gitlab doesn't provide group avatar support in its API, so there's nothing we can do in python-gitlab.

Feel free to reopen this bug if I missed something.
