### ISSUE TITLE
Tracing job logs doesn't support state

### ISSUE THREAD

**Issue by wvxvw** [python-gitlab/python-gitlab#648]
## Description of the problem, including code/CLI snippet

When you try to use project job to stream its output "live", there's an argument to `trace()` called `stream`.  Naively, I was hoping that it would stream the output in the same way the HTML client does, but what it actually does: it issues a single HTTP request and shows whatever the result of that request was (the HTML client keeps sending HTTP requests with appending `state=...` parameter to get deltas between the already received content and the yet to be received content.)

## Expected Behavior

Behave in the same way HTML client does.

## Actual Behavior

Output isn't actually streamed in the sense that if you wanted to display all job's output, you would have to wait for job's completion.

## Specifications

  - python-gitlab version: 1.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by wvxvw** [comment]
Actually, I realized just now that the REST API don't provide this kind of functionality, but their Rails server is somehow able to store and serve deltas of logs...

**Comment by gpocentek** [comment]
Hi @wvxvw 

If the API doesn't provide this feature python-gitlab will not implement it. You can open an issue of the gitlab project, they might be interested in implementing this feature.

The `stream` option in python-gitlab provides a way to download the full trace chunk by chunk to limit the amount of memory used.
