### ISSUE TITLE
extract Filesize(Repository size) from a project through API call

### ISSUE THREAD

**Issue by roopakasturi1109** [python-gitlab/python-gitlab#650]
## Description of the problem, including code/CLI snippet
Need a way to extract FileSize of a particular project by using API
For example: issues = gl.issues.list() will list the issues similarly how to get the Filesize of a project.
We need to extract this for our work.

we used the below but its not fetching any data
items = project.repository_tree(path='docs', ref='branch1')
file_info = project.repository_blob(items[0]['id'])
content = base64.b64decode(file_info['content'])
size = file_info['size']

## Specifications
![filesize](https://user-images.githubusercontent.com/45586323/49423541-db01ad80-f7bd-11e8-9b8e-5f5a3a6c732b.png)

  - python-gitlab version:
  - API version 4
  - Gitlab 11.3.4

**Comment by amitanand123infogix** [comment]
> ## Description of the problem, including code/CLI snippet
> Need a way to extract FileSize of a particular project by using API
> For example: issues = gl.issues.list() will list the issues similarly how to get the Filesize of a project.
> We need to extract this for our work.
> 
> we used the below but its not fetching any data
> items = project.repository_tree(path='docs', ref='branch1')
> file_info = project.repository_blob(items[0]['id'])
> content = base64.b64decode(file_info['content'])
> size = file_info['size']
> 
> ## Expected Behavior
> ## Actual Behavior
> ## Specifications
> ![filesize](https://user-images.githubusercontent.com/45586323/49423541-db01ad80-f7bd-11e8-9b8e-5f5a3a6c732b.png)
> 
> * python-gitlab version:
> * API version 4
> * Gitlab 11.3.4

**Comment by gpocentek** [comment]
Hi,

I don't think that there is an API call to fetch the size of a repository. Looping through the files will not give you the correct size.

You can report a feature request on the GitLab bugtracker to get this implement, then we will be able to add it in python-gitlab.

**Comment by max-wittig** [comment]
@roopakasturi1109 Gitlab actually returns the number of items for some queries in the header. 
The property is called `X-Total`
https://docs.gitlab.com/ce/api/#pagination-link-header

**Comment by miksonx** [comment]
Hi,
@gpocentek I know this is closed but seems there is API to get the size of repository and according the documentation for python-gitlab there is method implemented
– gitlab.v4.objects.Project.additionalstatistics

https://docs.gitlab.com/ee/api/projects.html#list-all-projects

The only thing is that I'm facing error when requesting this like attribute does not exist.
>>> project.additionalstatistics.get()
Traceback (most recent call last):
  File "python-gitlab/gitlab/base.py", line 59, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'additionalstatistics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python-gitlab/gitlab/base.py", line 62, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'additionalstatistics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python-gitlab/gitlab/base.py", line 82, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'additionalstatistics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python-gitlab/gitlab/base.py", line 84, in __getattr__
    raise AttributeError(name)
AttributeError: additionalstatistics


But when I issue API call 
curl --header "Private-Token: <your_token>" "https://<your_instance>/api/v4/projects/<project_id>?statistics=true

The relevant output will be in the following format:

    "statistics": {
      "commit_count": 5914,
      "storage_size": 1727206,
      "repository_size": 0,
      "wiki_size": 52428,
      "lfs_objects_size": 0,
      "job_artifacts_size": 1674778
    },

Any hint where is my error to get this functionality.

Thank you.
