### ISSUE TITLE
Allow to add protected tags

### ISSUE THREAD

**Issue by bertramn** [python-gitlab/python-gitlab#654]
## Description of the problem, including code/CLI snippet

The Gitlab API contains a new feature to create [protected tags](https://docs.gitlab.com/ee/api/protected_tags.html). It would be awesome if this capability was added to this library.

## Expected Behavior

Able to create protected tags for roles AND users (see #653).

## Actual Behavior

No functionality exists.

## Specifications

  - python-gitlab version: 1.6
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.3

**Comment by esabouraud** [comment]
This feature is available on master : https://python-gitlab.readthedocs.io/en/latest/gl_objects/projects.html?highlight=protectedtags#project-protected-tags.
It's been a while since there was a new release though.

**Comment by gpocentek** [comment]
@max-wittig #657 is the PR for the 1.7 release.

I'll do it manually this time and let's automate things for the 1.8.
