### ISSUE TITLE
Exported commit count is different than the project conmit count

### ISSUE THREAD

**Issue by roopakasturi1109** [python-gitlab/python-gitlab#655]
## Description of the problem, including code/CLI snippet
Gitlab API extracts a different commit count where as gitlab on UI shows a different count.
For a project, if there are 2 commits on a single day, on project home page, it displays as 1 commit . when clicked on commit link, on the page opened, 2 commits is displayed.
We are currently migrating our gitlab instance, so when exported the project, the statistics display as 2 and after importing to destination again the commit count is displayed as 2 on the home page.
hence this becomes a mismatch on destination.

## Expected Behavior
Commit count should be same across pages and in exported file

## Actual Behavior
Commit count in exported tar.gz file is different from what is shown on the project home page.

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by roopakasturi1109** [comment]
![opening commits](https://user-images.githubusercontent.com/45586323/49627850-235fdc00-fa07-11e8-876b-e1c78e2078c0.png)
![project home](https://user-images.githubusercontent.com/45586323/49627851-24910900-fa07-11e8-8906-9bc55df28725.JPG)

**Comment by gpocentek** [comment]
Hi @roopakasturi1109 

This looks like a GitLab bug, not a python-gitlab one. You should probably report this problem on the GitLab bug tracker: https://gitlab.com/gitlab-org/gitlab-ce/issues/
