### ISSUE TITLE
Let's define a small set of standards for git commits

### ISSUE THREAD

**Issue by gpocentek** [python-gitlab/python-gitlab#660]
We shouldn't make a big deal out of this but it would help to have standards for consistency and automation.

@max-wittig you seem to use a consistent format, something like `topic(action): message`, could you write a small paragraph to sum this up in the docs or in the README?

**Comment by max-wittig** [comment]
Sure. Will add it to the README later. I'm using the conventional-changelog format, which I believe was invented by the angular community. Details can be found here: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

* Commits could be even linted in CI, using this tool https://github.com/marionebl/commitlint
* `CHANGELOG.md` could be automatically generated using this tool: https://github.com/clog-tool/clog-cli

**Comment by gpocentek** [comment]
Looks good! Thanks :)
