### ISSUE TITLE
Impossible to get gitlab informations from configuration

### ISSUE THREAD

**Issue by NathanUrwin** [python-gitlab/python-gitlab#661]
## Description of the problem, including code/CLI snippet

Contents of **~/.python-gitlab.cfg**:

```
[global]
default = https://lgitlab.lon.compute.pgs.com
private_token = $MY_PRIVATE_TOKEN
```

```bash
$ pipenv run gitlab
Impossible to get gitlab informations from configuration (https://lgitlab.lon.compute.pgs.com)
```

I know it's not my private token, because it works with curl on the command line:

```bash
curl -fsSL -H "PRIVATE-TOKEN: $MY_PRIVATE_TOKEN" "https://lgitlab.lon.compute.pgs.com/api/v4/projects"
{ ... }
```

## Specifications

  - python-gitlab version: 1.7.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.5.1

**Comment by max-wittig** [comment]
I think the problem is that environment variables are not parsed, inside the config file. You'll need to put the raw token in.

**Comment by NathanUrwin** [comment]
Hey @max-wittig 👋 Thanks for the quick reply!

My raw token is in the config file, I just labeled it as '$MY_PRIVATE_TOKEN' for privacy reasons 😅

**Comment by max-wittig** [comment]
Haha okay. Found the issue. Default specifies the name of the config. Not the url directly. See: https://python-gitlab.readthedocs.io/en/latest/cli.html

```ini
[global] 
default = somewhere 
ssl_verify = true 
timeout = 5

[somewhere]
url = https://some.whe.re 
private_token =vTbFeqJYCY3sibBP7BZM api_version = 4 

[elsewhere] 
url = http://else.whe.re:8080
private_token = CkqsjqcQSFH5FQKDccu4 
timeout = 1
```

**Comment by NathanUrwin** [comment]
@max-wittig That was it, thank you! 🙂

**Comment by abhiamnyuMt** [comment]
I have the following configuration:

```
[global]
default = test
url = https://gitlab.com
ssl_verify = true
timeout = 5
private_token = <private_token>
api_version = 4 
```
where <private_token> is my actual private_token.

When I run the command `gitlab project list` it throws an error : `Impossible to get gitlab informations from configuration (test)`

**Comment by technoe** [comment]
@abhiamnyuMt 
The config needs to look like this:
`[global]
default = test

[test]
url = https://gitlab.com
ssl_verify = true
timeout = 5
private_token = <private_token>
api_version = 4 
`

Yeah, I know it doesn't make sense, but this is the only thing that worked for me.
