### ISSUE TITLE
Skipping initial root password reset 

### ISSUE THREAD

**Issue by ren21** [python-gitlab/python-gitlab#662]
## Description of the problem
I'm trying to automatize gitlab deployment, but the initial root password reset (password reset when first visiting the site) gets in the way, is there a way to skip it ? I can rewrite the server if there's no wrapper option but someone happens to know where the reset is implemented ..

I tried using the ruby production console, but it doesn't seem to work ... neither does POSTING the password and password_confirm values via the python-requests library, I get a 200 status code but nothing changes .. 

  - python-gitlab version: latest
  - API version you are using: v4
  - Gitlab server version (or gitlab.com): latest CE

**Comment by max-wittig** [comment]
I honestly wouldn't recommend to use python-gitlab for this. You'll need to look into ansible and terraform.

**Comment by ren21** [comment]
@gpocentek 

Sorry I'm so late with the response, but it doesn't seem to work. It's kinda weird, I still get redirected to the password reset session, I can't sign in, it just directs me back to the reset. 

I opened a rails console to check the password values, and upon getting the root password it just says 'nil', any ideas ? 

I did add the initial_root_password option to my gitlab.rb but it just doesn't work ...
