### ISSUE TITLE
Unable to use project-export 

### ISSUE THREAD

**Issue by vik-y** [python-gitlab/python-gitlab#667]
## Description of the problem, including code/CLI snippet
Unable to export a project using cli 
```
(.venv) ~/p/gitlab ❯❯❯ gitlab project-export create --project-id 78                                                                                                                                        
Impossible to create object (404: 404 Not Found)

# The project does exist 
(.venv) ~/p/gitlab ❯❯❯ gitlab project get --id 78                                                                                                                                                            
id: 78
path: gitlab-automation
```

## Expected Behavior
Should be able to create the export request and get the export url later on. 

## Actual Behavior
Getting the error: `Impossible to create object (404: 404 Not Found)`

## Specifications

  - python-gitlab version: 1.7.0 
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 9.4.1

**Comment by gpocentek** [comment]
Hello @vik-y 

The project import/export API has been added in GitLab 10.6. You will have to upgrade your server to get access to this feature.
