### ISSUE TITLE
should_remove_source_branch NOT work

### ISSUE THREAD

**Issue by tmc9031** [python-gitlab/python-gitlab#671]
## Description of the problem, including code/CLI snippet

mr = project.mergerequests.get(mr_id)
mr.merge(should_remove_source_branch=True)

## Expected Behavior

mr merged and source branch be removed

## Actual Behavior

mr merged and source branch NOT be removed

## Specifications

  - python-gitlab version: 1.7.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  gitlab.com 11.5

**Comment by gpocentek** [comment]
Hello @tmc9031 

This looks like a GitLab issue: https://gitlab.com/gitlab-org/gitlab-ee/issues/6776

The python-gitlab code is correct (according to the gitlab docs), so this should work again when GitLab fixes the problem.
