### ISSUE TITLE
Python gitlab "reset_time_estimate" crashes with HTTP error 404

### ISSUE THREAD

**Issue by M-Bab** [python-gitlab/python-gitlab#672]
Just a typo here:

https://github.com/python-gitlab/python-gitlab/blob/85ac10200805de480a076760368336c8135e5acf/gitlab/mixins.py#L535

Fixed by:
`path = '%s/%s/reset_time_estimate' % (self.manager.path, self.get_id())`

Can we do this without pull request?

Thanks for these decent python-gitlab bindings!

**Comment by gpocentek** [comment]
Thanks @M-Bab, the MR is done.
