### ISSUE TITLE
[feature] Implement a `count()` method for listable objects

### ISSUE THREAD

**Issue by gpocentek** [python-gitlab/python-gitlab#682]
This is a followup on #670 

GitLab returns the number of available objects in the response headers. Today if a user just wants to count the objects they still have to use the `list()` method and retrieve some data. We could provide a `count()` method that would return the number of available objects using a HEAD method.

To be discussed: should we also return the pagination information (as we do when `as_list` is false)? Does this need another method?

See https://github.com/python-gitlab/python-gitlab/tree/feat/count for the simple count implementation

**Comment by max-wittig** [comment]
It does make sense. I've also used a workaround before to see the available X-Page-Items or how it's called in GitLab.

**Comment by matthew-a-dunlap** [comment]
@gpocentek Thanks for posting this, I found it useful for my fork adding the option to get the repository file metadata without the actual file contents https://github.com/python-gitlab/python-gitlab/compare/master...matthew-a-dunlap:blame-head
