### ISSUE TITLE
project.forks({}) is creating a fork with no files

### ISSUE THREAD

**Issue by jburggraaf** [python-gitlab/python-gitlab#684]
## Description of the problem, including code/CLI snippet
Following the docs to fork a project I tried both 
```
fork = project.forks.create({})
```
 and 
```
fork = project.forks.create({'namespace': gitlab.user.username})
```
both forked the project with proper settings and general data but the actual files were not in the fork.  Only a readme.md as you would see in a new Project.

## Expected Behavior
forks a project with all files intact

## Actual Behavior
creates a fork with none of the original files 

## Specifications

  - python-gitlab version: 1.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by jburggraaf** [comment]
hi @gpocentek I've retried on 2 separate projects and it does seem to be working now.  Thanks

**Comment by gpocentek** [comment]
OK, great!
