### ISSUE TITLE
Calling the mr.merge() method to report an error  404

### ISSUE THREAD

**Issue by ThinkerT** [python-gitlab/python-gitlab#693]
Hello：
          Get an MR first, report an error when performing the MR merge request method, and try to report the error many times. Please help.

------
code：

> mr = project.mergerequests.get(905607)
> mr.merge()

error:

> send: 'GET /api/v4/projects/14509/merge_requests/905607 HTTP/1.1\r\nHost: git.xxx.com\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.18.4\r\nPRIVATE-TOKEN: xxxxxxxxxxxxx\r\nContent-type: application/json\r\n\r\n'
> reply: 'HTTP/1.1 200 OK\r\n'
> header: Server: nginx
> header: Date: Mon, 28 Jan 2019 08:36:42 GMT
> header: Content-Type: application/json
> header: Content-Length: 1089
> header: Connection: keep-alive
> header: Cache-Control: max-age=0, private, must-revalidate
> header: Etag: W/"ab55013d32a2b6b9d4111xxxxx"
> header: Vary: Origin
> header: X-Request-Id: bb4ae12c-d332-4449-a55e-xxxxxx
> header: X-Runtime: 0.046787
> DEBUG:urllib3.connectionpool:http://git.xxx.com:80 "GET /api/v4/projects/14509/merge_requests/905607 HTTP/1.1" 200 1089
> send: 'PUT /api/v4/projects/14509/merge_requests/13/merge HTTP/1.1\r\nHost: git.xxx.com\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.18.4\r\nPRIVATE-TOKEN: xxxxxxxxxxxxx\r\nContent-type: application/json\r\nContent-Length: 2\r\n\r\n{}'
> reply: 'HTTP/1.1 404 Not Found\r\n'
> header: Server: nginx
> header: Date: Mon, 28 Jan 2019 08:36:42 GMT
> header: Content-Type: application/json
> header: Content-Length: 27
> header: Connection: keep-alive
> header: Cache-Control: no-cache
> header: Vary: Origin
> header: X-Request-Id: f4710481-0f8d-415e-983f-xxxx
> header: X-Runtime: 0.029016
> DEBUG:urllib3.connectionpool:http://git.xxxx.com:80 "PUT /api/v4/projects/14509/merge_requests/13/merge HTTP/1.1" 404 27
> Traceback (most recent call last):
>   File "/Users/user/wkp/agitla.py", line 40, in <module>
>     mr.merge()
>   File "/usr/local/lib/python2.7/site-packages/gitlab/cli.py", line 43, in wrapped_f
>     return f(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/gitlab/exceptions.py", line 253, in wrapped_f
>     raise error(e.error_message, e.response_code, e.response_body)
> gitlab.exceptions.GitlabMRClosedError: 404: 404 Not found
> [Finished in 0.7s with exit code 1]

**Comment by gpocentek** [comment]
Hi @ThinkerT 

Could you check the gitlab server version? Maybe this API is not supported on the version you are running.

**Comment by ThinkerT** [comment]
@gpocentek 
Upon inspection, the current version is: GitLab Community Edition 8.17.8

**Comment by max-wittig** [comment]
We only support the available version that GitLab also supports. Version 8 is a security risk and should not be running anywhere.
