### ISSUE TITLE
Split up v4/objects module?

### ISSUE THREAD

**Issue by bittner** [python-gitlab/python-gitlab#694]
Problem
--------
The [v4/objects module](https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/v4/objects.py) is more than 4000 lines long and contains classes representing both GitLab objects and their managers.

Suggested Solutions
--------------
Would it make sense to move the manager implementations to a separate module, e.g. `v4/managers`, to reduce the module length and make the related classes easier to manage?

Would it make sense to split up the implementation in all separate modules (`v4/event`, `v4/user`, `v4/project`, etc.) representing the single GitLab objects? (Probably, as an alternative to moving out the manager classes.)

**Comment by nejch** [comment]
This was done in https://github.com/python-gitlab/python-gitlab/pull/1288.
