### ISSUE TITLE
Struggling to understand languages method

### ISSUE THREAD

**Issue by CordThomas** [python-gitlab/python-gitlab#695]
## Description of the problem, including code/CLI snippet

Trying to catalog all languages used in our repositories to replace my poor man's attempt as referenced in #289 .  The code below spits out languages quite nicely but I can't seem to get the percentage value.   I have tried a few things.  Neither the original [gitlab documentation ](https://docs.gitlab.com/ce/api/projects.html#languages) nor the python-gitlab examples give an insight into how to do this.   Forgive my likely naive question.

    ...
    projects = gl.projects.list(all=True)
    for project in projects:
      project_langs = project.languages()
      for project_lang in project_langs:
        print("Project {} has Lang {}".format(str(project.id), project_lang))

I tried 
  for project_lang, lang_pct in project_langs:

but that threw error 

the project_lang object is a String, so it doesn't have any attributes.

How to get the language percentage?

## Actual Behavior

Don't know, that's the problem ;)

## Specifications

  - python-gitlab version:   1.7.0
  - API version you are using (v3/v4):  v4
  - Gitlab server version (or gitlab.com):  11.5.4

**Comment by max-wittig** [comment]
I've used the languages feature a bunch of times here: https://github.com/max-wittig/gitlab-languages

**Comment by CordThomas** [comment]
Thank you - i needed to append .items() to my languages request.   Need to dig a little deeper into better understanding this package use.
