### ISSUE TITLE
[CLI] Newline in description for issue-creation

### ISSUE THREAD

**Issue by JulianSSS** [python-gitlab/python-gitlab#696]
## Description of the problem, including code/CLI snippet
I want to use new line and task-checkbox syntax in gitlab-cli. Like this:
```
gitlab project-issue update --iid 45 --project-id 123 --description "ABC\n\nDEF\n- [ ] gtghth"
```

## Expected Behavior
I see:
ABC
DEF
- [ ] gtghth

## Actual Behavior
Is see:
ABC\n\nDEF\n- [ ] gtghth

## Specifications

  - python-gitlab version: 1.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.7.0-ee

Perhaps there is a simple solution for that. I didn't find any.

Cheers!

**Comment by JulianSSS** [comment]
I found a solution seconds after issuing - sorry for that. The solution is double wrapping with echo evaluation:
```--description "`echo "abc\n\ndef"`"```

**Comment by gpocentek** [comment]
Hi @JulianSSS have you also tried using single quotes instead of double quotes?
