### ISSUE TITLE
Add 'auto-cancel redundant pipelines' setting to project settings

### ISSUE THREAD

**Issue by chbndrhnns** [python-gitlab/python-gitlab#704]
## Description of the problem, including code/CLI snippet
I would like to activate this setting for a project. It does not seem to be exposed in this Gitlab project.

## Expected Behavior
Exposing the setting

## Actual Behavior
It is not exposed

## Specifications

  - python-gitlab version: 1.7.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): n/a

**Comment by max-wittig** [comment]
If there is no API endpoint for this, we cannot create a wrapper to call it. Please open an issue/search for an issue in the Gitlab upstream repository instead.
