### ISSUE TITLE
unable to check for file in specified branch

### ISSUE THREAD

**Issue by BlkPingu** [python-gitlab/python-gitlab#709]
## Description of the problem, including code/CLI snippet
While trying to check for the existence of a file, I found no method that could help me do that. 

## Expected Behavior
`print(authenticate_and_select_project.files.get(file_path='LICENSE.txt', ref='master'))`
> `True` or `False`
## Actual Behavior

> gitlab.exceptions.GitlabHttpError: 404: 404 File Not Found

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Enterprise Edition 11.7.5-ee

**Comment by gpocentek** [comment]
I can't reproduce this problem with the same versions.

Are you sure that both the file path and the ref are correct?

**Comment by BlkPingu** [comment]
> Are you sure that both the file path and the ref are correct?

@gpocentek You are trying to reproduce a feature **that does not exist** to the best of my knowledge.
If I could choose a label, it would be "feature request".
There is no documented way to check **if a file exists or not** as in getting `True` or `False`. 
What I can do, is open a specific file in a specific branch with `files.get(file_path='LICENSE.txt', ref='master')`.
But when I try to go through a bunch of repos, I might first want to check if a file with that name exists. In my case `LICENSE.txt`.
I think it's fundamentally flawed that you can't do this, since if you just go with with opening a file that might not exist, you get the 404 back I mentioned.
Gitlab repos are in their essence complex data structures and most collections have some kind of `contains` function. Not so with `python-gitlab`.
Am I doing something wrong or is it actually true that it's not possible to check wether or not a file with a certain name / path exists in a certain branch?

**Comment by gpocentek** [comment]
@BlkPingu sorry, I didn't read your request properly.

The `contains` function you're looking for doesn't exist in the GitLab API. Instead, you can try to get the data, and if it doesn't exist, you get a 404 response from the server. python-gitlab turns this response into an exception. That's very common behavior for REST APIs and python APIs.

If you absolutely want to check if a file exists in a repo you can use the `project.repository_tree()` method. It returns a list of the files contained in the repository: you can loop over it to test the file existence. I don't recommend this solution, it's not efficient at all.

python-gitlab only implements what exists in the GitLab API. If you want the `contains` method to be implement you need to open an issue on the GitLab project.
