### ISSUE TITLE
How to get projects under a specific namespace/group?

### ISSUE THREAD

**Issue by Ponyboy47** [python-gitlab/python-gitlab#710]
## Description of the problem, including code/CLI snippet
The company I work for has a list of about 750 total projects, but I frequently find myself only looking for ones in a particular namespace (around 125 in each namespace). Searching through all 750 projects and filtering out the ones not in the desired namespace takes 30-60 seconds, which is a really long time to wait for a user interactive application that I'm building for my company.

I found an issue from several years (#100) ago that listed an alternative v3 API that permitted searching through projects using a namespace name, but I could not find any way to do this using API v4. Does anyone know if it is possible to get a list of projects by namespace?

## Expected Behavior
```python
projects = gl.projects.list(namespace=4, simple=True, all=True)
```
or
```python
projects = gl.namespaces.get(4).projects
```

## Actual Behavior
```python
projects = [project for project in gl.projects.list(simple=True, all=True) if project.namespace["id"] == 4]
```

## Specifications

  - python-gitlab version: 1.7.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.5.3

**Comment by gpocentek** [comment]
Hi @Ponyboy47 

If your goal is really to list the projects in a group (namespace) you can use the following:

```
group = gl.groups.get(group_id_or_name, lazy=True)
projects = group.projects.list()
```

If you're looking for a specific project using its name you can use the `search` attribute:

```
gl.projects.list(search=search_string)
# or
group.projects.list(search=search_string)
```

If you know the project and group names you can use

```
gl.projects.get(group_name + '/' + project_name)
```

**Comment by Ponyboy47** [comment]
I generally do something with each of the projects in the namespace, and if I'm not then I do get the one project directly as you've suggested.
I didn't realize that a namespace was the same thing as a group. It only takes about 5 seconds now instead of 30+! Thank you!
