### ISSUE TITLE
Lazily get project attributes

### ISSUE THREAD

**Issue by Ponyboy47** [python-gitlab/python-gitlab#711]
## Description of the problem, including code/CLI snippet
To prevent multiple API calls, it is often recommended to get a lazy object instead:
```python
project = gl.projects.get(project_id, lazy=True)
```

While this allows us to get things like issues, commits, etc... lazily, it looks like it prevents getting simple attributes like the project name:
```python
project = gl.projects.get(project_id, lazy=True)
project_name = project.name

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/gitlab/base.py", line 56, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'name'
```

I have also tried to get the name from the attributes object:
```python
project = gl.projects.get(project_id, lazy=True)
project_name = project.attributes.get("name")
# None
```
There is apparently no attribute "name".

## Expected Behavior
```python
project = gl.projects.get(project_id, lazy=True)
project_name = project.name
# MyProject
```

## Specifications

  - python-gitlab version: 1.7.0
  - API version you are using (v3/v4): v3
  - Gitlab server version (or gitlab.com): 11.5.3

**Comment by max-wittig** [comment]
That's actually expected. Lazy should do zero API calls. Use simple, if you just want the basic stuff, like name, namespace and id.

```python
project = gl.projects.get(project_id, simple=True)
print(project.name)
```

**Comment by Ponyboy47** [comment]
What if I want both though? Does simple also imply lazy? (Using `simple=True` and `lazy=True` has the same issue)

I tend to collect a group of projects, then do stuff based on the commits/issues, but I usually log/display the project name as well. If I get the project lazily, then I can't display its name. Getting the project with `simple=True` works, but is it also lazy (minus getting the simple stuff)?

**Comment by max-wittig** [comment]
There is no way to get just the project name from GitLab. We're just a wrapper for the API. 

https://docs.gitlab.com/ce/api/projects.html#list-all-projects

**Comment by max-wittig** [comment]
If you have any further questions regarding this, feel free to reopen.
