### ISSUE TITLE
Issues creation error

### ISSUE THREAD

**Issue by hujarl** [python-gitlab/python-gitlab#712]
## Description of the problem, including code/CLI snippet

Unable to create an issue:

Sample code - 

gl.issues.create({'title': 'Xray scan results', 'description': 'test'})
		
AttributeError: 'IssueManager' object has no attribute 'create'

**Comment by max-wittig** [comment]
you need to get a project object in order to create issue on it. Just like with the raw GitLab API. See the docs: https://python-gitlab.readthedocs.io/en/stable/gl_objects/issues.html

**Comment by hujarl** [comment]
My apologies, I should have included more of the sample code - 

import gitlab

gl = gitlab.Gitlab('https://urltogitlab/reponame/projectname/issues', 'APIKEY' )

gl.issues.create({'title': 'Xray scan results', 'description': 'test'})

Error while running - 

AttributeError: 'IssueManager' object has no attribute 'create'

**Comment by max-wittig** [comment]
still you're missing a project to create your issue on.

```python
import gitlab

gl = gitlab.Gitlab('https://urltogitlab/reponame/projectname/issues', 'APIKEY' )
some_project = gl.projects.get(145) # project id here
some_project .issues.create({'title': 'Xray scan results', 'description': 'test'})
```

**Comment by hujarl** [comment]
Thanks for the additional info!

It is much appreciated.

**Comment by max-wittig** [comment]
No problem 😃
