### ISSUE TITLE
CLI event list fails on None

### ISSUE THREAD

**Issue by xarx00** [python-gitlab/python-gitlab#717]
## Description of the problem, including code/CLI snippet
`gitlab event list` fails in v4/cli.py#l.38 with `AttributeError: 'NoneType' object has no attribute 'lower'`.

## Specifications
  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): na
  - Gitlab server version (or gitlab.com): na

## Cause
The error is caused by the EventManager class in objects.py, because one of `_list_filters` is called "action". This name collides with the args attribute `action`, and one of them is probably overwritten. When renaming "action" in `_list_filters` to something else, `gitlab event list` continues further (and fails with another similar error).

**Comment by xarx00** [comment]
The subsequent error mentioned above is 
```
  File "c:\program files\python27\lib\site-packages\gitlab\v4\cli.py", line 364, in display
    value = value.replace('\r', '').replace('\n', ' ')
AttributeError: 'NoneType' object has no attribute 'replace'
```
It is caused by that some events on my gilab server do not have "target_title" filled in.

### Fix
Fix of the subsequent (NOT the original error):
```
--- cli.py.orig	2019-02-24 17:37:53.000000000 +0100
+++ cli.py	2019-02-27 19:17:56.045767100 +0100
@@ -357,7 +358,7 @@
                 id = getattr(obj, obj._id_attr)
                 print('%s: %s' % (obj._id_attr.replace('_', '-'), id))
             if hasattr(obj, '_short_print_attr'):
-                value = getattr(obj, obj._short_print_attr)
+                value = getattr(obj, obj._short_print_attr) or 'None'
                 value = value.replace('\r', '').replace('\n', ' ')
                 # If the attribute is a note (ProjectCommitComment) then we do
                 # some modifications to fit everything on one line
```

**Comment by xarx00** [comment]
### Fix
In order to fix the primary error of this issue, I had to rename the "action" attribute:
[fix.diff.zip](https://github.com/python-gitlab/python-gitlab/files/2912006/fix.diff.zip)

**Comment by gpocentek** [comment]
Hi @xarx00 

Could you create a pull request with this change? Thanks.
