### ISSUE TITLE
Cannot retrieve project milestones

### ISSUE THREAD

**Issue by kendallroth** [python-gitlab/python-gitlab#719]
## Description of the problem, including code/CLI snippet

The docs state that `project.milestones.list()` should return a list of all milestones in a project. However, I am getting an `AttributeError` when attempting to access the project milestones list as seen below:

```
project = gitlabInstance.projects.get(id)
print(project.milestones)
```

```
File "/home/python/app/reporting/reports.py", line 65, in generate_epic_report
  print(project.milestones)
File "/usr/local/lib/python3.7/site-packages/gitlab/base.py", line 81, in __getattr__
  raise AttributeError(name)
AttributeError: milestones
```

**NOTE:** Further testing has revealed that possibly all of the `Project` managers do not exist.

## Expected Behavior

I expect the GitLab manager to return a list of the project's milestones

## Actual Behavior

An `AttributeError` is thrown instead when attempting to access the project milestones

## Specifications

  - python-gitlab version: `1.8`
  - API version you are using (v3/v4): `v4`? (_default_)
  - Gitlab server version (or gitlab.com): `11.8.0` (self-hosted)

**Comment by kendallroth** [comment]
This is similar to #366, except that it is for project milestones rather than group milestones. Accessing `group.milestones.list()` returns an empty list with no error, so I am assuming it still works (cannot add milestones to the group to test).

**Comment by kendallroth** [comment]
I did some more testing and traced the error all the way back to `python-gitlab` `v1.4`, which seems quite strange that no one has noticed it before. I wonder if I'm doing something incorrectly, so here's the script I'm using:

```
group_id = request.params['group_id']  # Fake code
group = gitlab.groups.get(group_id)

projects = group.projects.list()
project = projects[0]  # Project does exist

milestones = project.milestones.list()
```

**Comment by kendallroth** [comment]
After some more examination (printing the `__dict__` representation of a group and a project, it looks like the managers are not being included for projects (but are for groups)? A quick glance at the source code wasn't enough to reveal what may be causing this, but it definitely appears to be the issue.

**Comment by gpocentek** [comment]
Hi @kendallroth 

You need to create a `Project` object from your `GroupProject` object to access the `milestones` manager:

```
projects = group.projects.list()
project = projects[0]  # project is a GroupProject object
real_project = gl.projects.get(project.id, lazy=True)  # lazy avoid making a new API call
milestones = real_project.milestones.list()

**Comment by kendallroth** [comment]
@gpocentek Ah, that makes sense, as I found I was able to get the list of issues from a project that I had specifically called with `gitlab.projects.get(pk)`. Thanks!
