### ISSUE TITLE
gitlab.projects doesn't include current user

### ISSUE THREAD

**Issue by njalerikson** [python-gitlab/python-gitlab#720]
## Description of the problem, including code/CLI snippet
Current user's projects are not included in project list.

```python
gitlab = Gitlab(...)
for project gitlab.projects.list():
    print(project.attributes["path_with_namespace"])
```

## Expected Behavior
Expect to see all available projects including current users'.

## Actual Behavior
All projects except authenticated users' are listed.

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.7.5

**Comment by gpocentek** [comment]
Hi @njalerikson 

Your code sample only returns 20 projects. Make sure that you list *all* the projects: `gl.projects.list(all=True)`.

python-gitlab wraps what Gitlab returns, so if you don't see your own projects it's very likely a problem with Gitlab itself.

**Comment by njalerikson** [comment]
Ah perfect, I hadn't considered it to be a Pagination issue. Thanks!
