### ISSUE TITLE
Implement project registry API

### ISSUE THREAD

**Issue by gpocentek** [python-gitlab/python-gitlab#723]
New in gitlab 11.8: https://docs.gitlab.com/ce/api/container_registry.html

**Comment by MattCzerner** [comment]
Does it work though? I get 202 return code from all `delete_in_bulk` commands and nothing happens. I cannot find any helpful information for it.

**Comment by max-wittig** [comment]
@MattCzerner it's an open issue, so it's not implemented.

**Comment by MattCzerner** [comment]
I dont understand, the PR is merged. You can actually call these methods using python-gitlab, gitlab has it implemented on their site.

So what is the current state?
I guess its more of a Gitlab API problem because it does not even work with curl requests either.

**Comment by max-wittig** [comment]
oh you're right. Didn't see that on mobile. Sorry. Please report it on gitlab.com directly then

**Comment by max-wittig** [comment]
Ah sorry I didn't see this on mobile. Then please search for issues on GitLab itself/create a new one.
