### ISSUE TITLE
Subgroups do not return Group objects

### ISSUE THREAD

**Issue by xarx00** [python-gitlab/python-gitlab#734]
## Description of the problem, including code/CLI snippet
`gl.groups.list()` returns a list of `gitlab.v4.objects.Group` class instances. On the other hand,
`group.subgroups.list()` returns a list of `gitlab.v4.objects.GroupSubgroup` instances. They do not provide methods and properties of `Group` objects.

Similarly, `group.projects.list()` does not return instances of `gitlab.v4.objects.Project`; neither `group.mergerequests.list()` nor `project.mergerequests.list()` return instances of `gitlab.v4.objects.MergeRequest`, etc.

If this is not intentional (I don't see why it should be), I suggest fixing the classes of the returned objects.

## Specifications
  - python-gitlab version: 1.8.0

## Fix
As a fix, it would suffice to change the `_obj_cls` parameter in the appropriate Manager classes to the correct instance classes. For example, in `GroupProjectManager`, it would suffice to change
`_obj_cls = GroupProject` to `_obj_cls = Project`. Unfortunately, this solution breaks the gitlab CLI help for these commands.

Hence, it is currently better to leave `_obj_cls` untouched, and inherit the current instance class from the correct instance class. For example, change `class GroupProject(RESTObject):` to `class GroupProject(Project):`.

**Comment by max-wittig** [comment]
I think this behavior should be expected, as we just follow the GitLab API specification. Thanks for working on this, but I don't think we should change this.

To get a group object from a subgroup, you simply have to request it.
```python
subgroups = gl.groups.get(1).subgroups.list()
group = gl.groups.get(subgroups[0].id)
```
