### ISSUE TITLE
Error when configuring only_mirror_protected_branches

### ISSUE THREAD

**Issue by gepolquevedo** [python-gitlab/python-gitlab#739]
## Description of the problem, including code/CLI snippet
elif project_attributes['only_mirror_protected'] == 'false':
                project.only_mirror_protected_branches = 0

project.save()

## Expected Behavior
Just expecting a warning, like: 

.local/lib/python2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

## Actual Behavior
gitlab.exceptions.GitlabUpdateError: 400: jobs_enabled, resolve_outdated_diff_discussions, ci_config_path, container_registry_enabled, default_branch, description, issues_enabled, lfs_enabled, merge_requests_enabled, merge_method, name, only_allow_merge_if_all_discussions_are_resolved, only_allow_merge_if_pipeline_succeeds, path, printing_merge_request_link_enabled, public_builds, request_access_enabled, shared_runners_enabled, snippets_enabled, tag_list, visibility, wiki_enabled, approvals_before_merge, repository_storage, external_authorization_classification_label are missing, at least one parameter must be provided

## Specifications

  - python-gitlab version: v1.8
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.1.4-ee

additional notes:
I'm not entirely sure if this is a bug or I did not use the module correctly, but it seems like the API call is POST /projects , based on the parameters being mentioned above

**Comment by gpocentek** [comment]
Hi @gepolquevedo 

Looking at the exception it seems that the `only_mirror_protected_branches` attribute is not supported by your version of GitLab. If it's possible for you I'd suggest to update the server and try again.

**Comment by gpocentek** [comment]
Feel free to reopen if the problem still exists after update, but it is most likely a server-side issue.
