### ISSUE TITLE
Should the python-gitlab add default value when call project.hooks.create?

### ISSUE THREAD

**Issue by rhinoceros** [python-gitlab/python-gitlab#740]
gitlab 11.8.0
python-gitlab (1.8.0)

Should the python-gitlab lib can add default value when call project.hooks.create?
https://docs.gitlab.com/ce/api/projects.html#add-project-hook

**create hook return 500 by default:**
``` python

    group = gl.groups.list(search='xx_group')[0]

    projects = group.projects.list(all=True)
    for project in projects:
        p = gl.projects.get(project.id)
        proj_ci_url='http://jenkins.company.com/project/CI__'+p.name
        hook = p.hooks.create({'url': proj_ci_url,'push_events': 1,'enable_ssl_verification': 0,'token':'YOUR_SECRET_TOOKEN'})

```

**we need to add more default key value**

``` 
'issues_events':0,'
merge_requests_events':0,
'tag_push_events':0,
'note_events':0,
'job_events':0,
pipeline_events':0,
'wiki_page_events':0 
```

``` python

    group = gl.groups.list(search='xx_group')[0]

    projects = group.projects.list(all=True)
    for project in projects:
        p = gl.projects.get(project.id)
        proj_ci_url='http://jenkins.company.com/project/CI__'+p.name
        hook = p.hooks.create({'url': proj_ci_url,'push_events': 1,'enable_ssl_verification': 0,'token':'YOUR_SECRET_TOOKEN','issues_events':0,'merge_requests_events':0,'tag_push_events':0,'note_events':0,'job_events':0,'pipeline_events':0,'wiki_page_events':0})

```

------
In page: index.rst

**Comment by gpocentek** [comment]
Hello @rhinoceros 

I've not been able to reproduce this problem with GtiLab 11.8.2:
```python

In [4]: p = gl.projects.create({'name': 'test_project'})

In [5]: h = p.hooks.create({'url': "https://jenkins.local/whatever", 'push_events': 1, 'enable_ssl_verification': 0, 'token':'YOUR_SECRET_TOOKEN'})

In [6]: h
Out[6]: <ProjectHook id:302>
```
Is it possible for you to update your Gitlab server and check again?

**Comment by rhinoceros** [comment]
> Hello @rhinoceros
> 
> I've not been able to reproduce this problem with GtiLab 11.8.2:
> 
> ```python
> In [4]: p = gl.projects.create({'name': 'test_project'})
> 
> In [5]: h = p.hooks.create({'url': "https://jenkins.local/whatever", 'push_events': 1, 'enable_ssl_verification': 0, 'token':'YOUR_SECRET_TOOKEN'})
> 
> In [6]: h
> Out[6]: <ProjectHook id:302>
> ```
> 
> Is it possible for you to update your Gitlab server and check again?

thanks, I will upgrade our gitlab-ce to 11.8.2 soon.
