### ISSUE TITLE
GitlabListError: 404 when retrieving subgroups  

### ISSUE THREAD

**Issue by jferreira23** [python-gitlab/python-gitlab#741]
## Description of the problem, including code/CLI snippet

I got an GitlabListError: 404: b'{"error":"404 Not Found"}' when retrieving subgroups:

```
group = gl.groups.get(id)
subgroups = group.subgroups.list()
```

## Expected Behavior

Return a list of a subgroups

## Actual Behavior

` GitlabListError: 404: b'{"error":"404 Not Found"}' `

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Enterprise Edition 9.5.4-ee
  - Python: 3.7.2

**Comment by max-wittig** [comment]
That works for me on gitlab.com, but I'm not familar with your version of GitLab and therefore can't give any support. 9.5.4 is a security risk. Please upgrade to the latest version of Gitlab.

**Comment by max-wittig** [comment]
Feel free to re-open if it's still a problem in the versions that Gitlab also supports.
