### ISSUE TITLE
output filter ignores fields with a hyphen

### ISSUE THREAD

**Issue by aboettger-tuhh** [python-gitlab/python-gitlab#742]
## Description of the problem, including code/CLI snippet

The output filter ignores fields with a hyphen.

`gitlab -o json --fields id,two-factor-enabled user list`

## Expected Behavior
```
[{"id": 1,"two-factor-enabled": True}, {"id": 2,"two-factor-enabled": False}]
```

## Actual Behavior
```
[{"id": 1}, {"id": 2}]
```

## Specifications

  - python-gitlab version:

    ```
    $ gitlab --version
    1.8.0
    ```

  - API version you are using (v3/v4):

    v4

  - Gitlab server version (or gitlab.com):

    11.8.2

**Comment by jouve** [comment]
the fields use underscores as decribed in the API docs : https://docs.gitlab.com/ee/api/users.html

```bash
gitlab -o json --fields id,two_factor_enabled user list
```

**Comment by nejch** [comment]
As @jouve said the fields have to match the GitLab API attributes as seen in the JSON response But please re-open if you feel this is unclear in the docs :)
