### ISSUE TITLE
'updated_at' attribute on issue doesn't update when updating / removing label or adding comments consecutively

### ISSUE THREAD

**Issue by cvlvxi** [python-gitlab/python-gitlab#743]
# This behaviour seems to be existent when I update / remove label

## Expected Behavior
1. Go to issue in gitlab. 
2. Make an update to label.. e.g. add label X
3. Check updated_at via python api:

```
>>> issue.attributes['updated_at'] 
timeX
```

 This will update updated_at to time X

4. Make an update to same issue -- This will update updated_at
5. Make same call after fetching issue again

```
>>> issue.attributes['updated_at'] 
timeY
```

## Actual Behavior
1. Go to issue in gitlab. 
2. Make an update..
3. Check updated_at via python api -- This will update updated_at to time X

```
>>> issue.attributes['updated_at'] 
timeX
```

4. Make an update to same issue -- This will NOT update updated_at to time Y but stay time X

```
....
>>> issue.attributes['updated_at'] 
timeX
```
5. Wait for a period...
6. Make a DIFFERENT update -- This will update updated_at to time Z

```
>>> issue.attributes['updated_at'] 
timeZ
```

## Specifications

  - python-gitlab version: 1.3.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): internal

**Comment by cvlvxi** [comment]
This seems to happen for notes/comments as well as labels... 

Sometimes the updated_at will trigger and sometimes it won't..

**Comment by cvlvxi** [comment]
By editing Description, Title will ALWAYS updated_at .. can we make this consistent?

**Comment by gpocentek** [comment]
Hello @cvlvxi 

python-gitlab doesn't take care of the `updated_at` attribute updates, the information is always received from the GitLab server. So if something is not updated as expected it is most likely because of a problem on the server side.
