### ISSUE TITLE
Url for the next request with pagination is missing port

### ISSUE THREAD

**Issue by maximsachs** [python-gitlab/python-gitlab#745]
## Description of the problem, including code/CLI snippet
When multiple requests are made using pagination to get a lot of data, then after the first request the port specified in the url gets lost. And per_page parameter is not correctly used.

```
from gitlab import Gitlab
gitlab =  Gitlab(url='https://gitlab.company.com:12345',per_page=50)
group = gitlab.groups.get(2, lazy=True) #Gets the group with id 2
milestones = group.milestones.list()
for issue in milestone.issues():
    doing something with each issue here.
```
## Expected Behavior
To get all the issues one by one.

## Actual Behavior
The group and milestones requests in my case have less than 50 entries, so pagination wont be used.
However there are many more issues and pagination is required. Then it makes the first request to `https://gitlab.company.com:12345/api/v4/groups/2/milestones/16/issues` which automatically will return the first page with issues. Then the class GitlabList will construct a new url for the next request. This new url is however missing the port. This means that the next request occurs to `https://gitlab.company.com/api/v4/groups/2/milestones/16/issues?id=2&milestone_id=16&page=2&per_page=20`, which will fail because the server is only running on port 12345. Additionally it is noted that even though per_page was specified to be 50, it constructs a url where this parameter is 20. 

I have fixed the issue for myself by modifying the line `self._query(self._next_url)` to `self._query(self._next_url.replace("company.com", "company.com:12345"))` in line 787 of the `__init__.py`. However that is clearly a bad solution as this fix only works for the gitlab of the one single server, which is acceptable for me but likely is not for many others. And the fix will be overwritten when the python-gitlab package is updated to its next version. I tried digging around in the way the url for the next request is constructed, but was unable to find the root cause of this.

## Specifications
  - python: 3.6
  - python-gitlab version: 1.8
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab community edition 11.9.1
  - requests: 2.8
  - urllib3: 1.24.1

**Comment by gpocentek** [comment]
Hi!

python-gitlab uses the headers returned by the GitLab server to know the next URL. The port should be returned by the server. If it's not the case I'd say it's a bug in GitLab.

Could you also check the `external_url` parameter in the server configuration? Maybe it's not set correctly.

Thanks.

**Comment by maximsachs** [comment]
Hi,
I just checked and external url is set to `https://gitlab.company.com:12345`

**Comment by gpocentek** [comment]
Could you run the following command to check the `link` header in the GitLab server response:

```
curl -H "PRIVATE-TOKEN: $PRIVATE_TOKEN" https://gitlab.company.com:12345/api/v4/projects -sSL -D - -o /dev/null
```

**Comment by maximsachs** [comment]
This is what it returns. Im not sure what of that is sensitive information. So I redacted a few outputs.
```
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 01 Apr 2019 06:51:34 GMT
Content-Type: application/json
Content-Length: 2
Connection: keep-alive
Cache-Control: max-age=0, private, must-revalidate
Etag: W/"redacted"
Link: <https://gitlab.company.com/api/v4/projects?membership=false&order_by=created_at&owned=false&page=1&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false>; rel="first", <https://gitlab.company.com/api/v4/projects?membership=false&order_by=created_at&owned=false&page=1&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false>; rel="last"
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Next-Page: 
X-Page: 1
X-Per-Page: 20
X-Prev-Page: 
X-Request-Id: redacted
X-Runtime: 0.026575
X-Total: 0
X-Total-Pages: 1
Strict-Transport-Security: max-age=31536000
```

**Comment by gpocentek** [comment]
The `link` attribute doesn't provide the port in the URL. GitLab is supposed to return the correct URLs there, so there is nothing we can do in python-gitlab.

You should report the issue on the GitLab bugtracker to get this fixed.

**Comment by lyenliang** [comment]
I'm using gitlab 11.10.0. Probably this bug is reopened in 11.10.0.

**Comment by projectgus** [comment]
(For reference of anyone who finds this in the future, the GitLab issue for the root cause has been reported here: https://gitlab.com/gitlab-org/gitlab-ce/issues/60644 )

**Comment by gdeban** [comment]
I have the same issue, probably because of a configuration issue on the server I am targeting. (link comes with port 80 for an https scheme, which fails)

I edited gitlab/__init__.py to replace the link base url with the base url from the original request.

I replaced
```
        try:
            self._next_url = result.links["next"]["url"]
        except KeyError:
            self._next_url = None
```
with
```
        try:
            self._next_url = result.links["next"]["url"]
            # reconstruct url from request url
            base_url = '/'.join(url.split('/')[:3]) # extract base url from request "https://server:port"
            path_and_query = '/'.join(self._next_url.split('/')[3:]) # extract path and querry from next_url
            self._next_url = base_url + '/' + path_and_query # assemble
        except KeyError:
            self._next_url = None
```

It is very ugly and could certainly be done in a safe and more elegant way, but it will work for me until I get the server guys to fix the configuration issue.
