### ISSUE TITLE
Specify subscription when looking up a public IP

### ISSUE THREAD

**Issue by stonefury** [python-gitlab/python-gitlab#747]
## Description of the problem, including code/CLI snippet

I want to lookup the actual IP of a public IP. However, the best I can do is get the NIC's ip configuration and get only the name of the public IP address.

However, I am iterating through all my subscriptions to pull inventory and I don't believe there is a concept of "effective subscription" in the sdk, is there? 

## Expected Behavior
 I need to be able to resolve the public IP somehow.

## Actual Behavior
Can only get the public IP name

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by gpocentek** [comment]
Hello,

I really don't understand what this is about. I'm even wondering if you reported this issue on the correct project. Could you explain a bit more?

**Comment by stonefury** [comment]
Totally wrong project. Please delete this. :)
