### ISSUE TITLE
Getting [limit_reached] errors when trying to create projects

### ISSUE THREAD

**Issue by monsdar** [python-gitlab/python-gitlab#748]
## Description of the problem, including code/CLI snippet
I'm running an environment with gitlab and gitlab-runner in a docker environment locally on my Desktop. To test out different things I've written a `populate.py` script which uses python-gitlab to fill the server with sample data.

The environment is available on Github: https://github.com/monsdar/docker-testbed

Most often this works flawless, but sometimes (3/10) this fails during creation of the projects with the following message:

```
>populate.py
Private Token: mwtdsXXP4VQgz6UzRS-k
Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\gitlab\exceptions.py", line 255, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Python36-32\lib\site-packages\gitlab\mixins.py", line 204, in create
    **kwargs)
  File "C:\Python36-32\lib\site-packages\gitlab\__init__.py", line 629, in http_post
    post_data=post_data, files=files, **kwargs)
  File "C:\Python36-32\lib\site-packages\gitlab\__init__.py", line 531, in http_request
    response_body=result.content)
gitlab.exceptions.GitlabHttpError: 400: {'base': ['Failed to create repository via gitlab-shell', 'Failed to create repository'], 'limit_reached': []}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Github\Docker\ci_testbed\ci_testbed\populate.py", line 111, in <module>
    main()
  File "D:\Github\Docker\ci_testbed\ci_testbed\populate.py", line 22, in main
    createProject(gl, bsGroup, "ci-templates")
  File "D:\Github\Docker\ci_testbed\ci_testbed\populate.py", line 51, in createProject
    project = gl.projects.create({'name': name, 'namespace_id': group.id})
  File "C:\Python36-32\lib\site-packages\gitlab\exceptions.py", line 257, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 400: {'base': ['Failed to create repository via gitlab-shell', 'Failed to create repository'], 'limit_reached': []}
```

I guess this is because of some kind of load balancing that isn't caught by python-gitlab?

## Expected Behavior
All projects get created. python-gitlab handles load-balancing

## Actual Behavior
In some cases (~3/10) projects can't get created. See above error message. If this happens once it won't even help to completely restart the environment (using `docker-compose down -v`). It more often than not will fail during the next start as well.

## Specifications
* python-gitlab version: 1.8.0 from pypi
* API version you are using (v3/v4): v4
* Gitlab server version (or gitlab.com): Newest available docker image. 11.8.2 (b1268e9)
* Windows 10 Prof 64 bit
* Python 3.6.1
* Docker Desktop 2.0.0.2 (30215)

**Comment by monsdar** [comment]
I'm not sure if that's really the case but I've found that it works when I run `populate.py` before accessing the page and logging in.

**Comment by gpocentek** [comment]
Hi,

The error message you receive seems to indicate that the API call worked, but that GitLab didn't manage to do the requested action. It would be interested to dive in the GitLab server logs to see if there's additional information there.

But I don't think that this problem comes from python-gitlab.

**Comment by max-wittig** [comment]
Try to create projects in the UI. Gitlab defines a project limit per user, which can also be changed via the Settings API.

**Comment by monsdar** [comment]
I can confirm that this is reproducable by logging in with the root account before calling `populate.py`. In the cases I tried it always failed when logging in first, always worked when running `populate.py` before touching the web interface for the first time.

I'll check the logs and see that I create an issue over at the GitLab tracker then. Thanks for your input!

@max-wittig: The idea behind that testbed is to automatically set up a complex group and project hierarchy. It should be possible to have an instance for CI-testing running within minutes. Having manual steps to create the projects etc would defeat the purpose.
