### ISSUE TITLE
Updating project attribute "approvals_before_merge" doesn't work

### ISSUE THREAD

**Issue by SayantanKhanra10** [python-gitlab/python-gitlab#749]
## Description of the problem, including code/CLI snippet

I am trying to set attribute value "approvals_before_merge" for every project under a group. 
What I tried:

            data = {'approvals_before_merge': '1'}
            project.attributes.update(data)
            project.save()

## Expected Behavior

I was expecting to see the value "**Approvals required**" changed in gitlab from 0 to 1 once I save.

## Actual Behavior

I don't see any changes in gitlab. It is still set to 0

## Specifications

  - python-gitlab version: **1.8.0**
  - API version you are using (v3/v4): **v4**
  - Gitlab server version (or gitlab.com): **11.8.2-ee**

**Comment by gpocentek** [comment]
Hi @SayantanKhanra10 

I think you should use the following instead:

```
project.approvals_before_merge = 1
project.save()

**Comment by SayantanKhanra10** [comment]
@gpocentek Thanks for your suggestion. I did try it before but I get the below exception when I try to save the project:

project.approvals_before_merge=1
project.save()

**Traceback (most recent call last):
  File "/Users/skhanra/gitrepo/infrastructure/repository/.venv/lib/python3.7/site-packages/gitlab/base.py", line 56, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'save'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/skhanra/gitrepo/infrastructure/repository/.venv/lib/python3.7/site-packages/gitlab/base.py", line 59, in __getattr__
    value = self.__dict__['_attrs'][name]
KeyError: 'save'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/skhanra/gitrepo/infrastructure/repository/.venv/lib/python3.7/site-packages/gitlab/base.py", line 79, in __getattr__
    return self.__dict__['_parent_attrs'][name]
KeyError: 'save'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/Users/skhanra/gitrepo/infrastructure/repository/.venv/lib/python3.7/site-packages/gitlab/base.py", line 81, in __getattr__
    raise AttributeError(name)
AttributeError: save**

**Comment by gpocentek** [comment]
Could you detail how you create the `project` object? Can you make sure it's a `Project` instance?

**Comment by SayantanKhanra10** [comment]
I create the projects like this:

from gitlab import Gitlab
gitlab = Gitlab(GITLAB_URL, gitlab_token, api_version=str(GITLAB_API_VERSION))
gitlab.projects.create({'name': stack, 'namespace_id': policy_group_id})

**Comment by gpocentek** [comment]
Could you try calling the `Gitlab` object something else than `gitlab`? I wonder if this could cause naming conflicts.

**Comment by SayantanKhanra10** [comment]
@gpocentek the project object is of type:

**<class 'gitlab.v4.objects.GroupProject'>**

Can that be an issue? Before we had the same object and updated project without any issues.

**Comment by gpocentek** [comment]
`GroupProjects` cannot be updated. You need to create a new `Project` using the object id:

```
editable_project = gl.projects.get(project.id)
editable_project.approvals_before_merge = 1
editable_project.save()

**Comment by SayantanKhanra10** [comment]
@gpocentek thanks a lot for the suggestion. That really did work. 

But has this behavior changed for some reason? Cause i have been updating projects in this way for long now. 

Only thing which has changed in our side is we upgraded gitlab.

**Comment by max-wittig** [comment]
@SayantanKhanra10 It's been like that since I remember since first using this library. Maybe you didn't get the projects in a group before? Thanks for the feedback.
