### ISSUE TITLE
Trouble to define api_version as 3

### ISSUE THREAD

**Issue by rafaelalgsantos** [python-gitlab/python-gitlab#750]
## Description of the problem, including code/CLI snippet
Hello! 
I'm having trouble to define a instance of gitlab.gitlab() using version 3 of the API 
![image](https://user-images.githubusercontent.com/29957423/55345891-6bf44700-5487-11e9-9cfa-83bcd5cd30e1.png)

Results
![image](https://user-images.githubusercontent.com/29957423/55346105-0785b780-5488-11e9-993c-15afe9a2df70.png)

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4): v3
- Gitlab server version (or gitlab.com):  GitLab 7.2.0 580a621

**Comment by gpocentek** [comment]
Hello @rafaelalgsantos 

If you really need to use the v3 API you have to install python-gitlab 1.4. But we don't support v3 API anymore, neither does GitLab.

**Comment by maherm** [comment]
@gpocentek in this case you should change the docs, which clearly state that [v3 is supported](https://python-gitlab.readthedocs.io/en/stable/switching-to-v4.html#using-the-v4-api):

> python-gitlab uses the v4 API by default since the 1.3.0 release. To use the old v3 API, explicitly define api_version in the Gitlab constructor:
> 
> `gl = gitlab.Gitlab(..., api_version=3)`
