### ISSUE TITLE
Make Project.trigger_pipeline useable without general authentication

### ISSUE THREAD

**Issue by baurmatt** [python-gitlab/python-gitlab#752]
## Description of the problem, including code/CLI snippet

Gitlab offers [Trigger tokens](https://docs.gitlab.com/ee/ci/triggers/#trigger-token) to allow $things to authenticate against the API to only trigger a pipeline. This is currently not possible (or at least I don't see how) with python-gitlab because we first need to authenticate against the Gitlab server.

## Expected Behavior

```python
pipeline = gitlab.Project(id).trigger_pipeline('master', token, variables={"DEPLOY": "true"})
```

## Actual Behavior

```python
gl = gitlab.Gitlab('https://gitlab.example-org', private_token=private_token)
project = gl.projects.get(id)
project.trigger_pipeline('master', trigger_token, variables={"DEPLOY": 'true'})
```

The problem is, that I need to have a valid user account/API token with API privileges to get the project. After that I can use the trigger_token to trigger the pipeline which is kind of counterproductive.

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.8.6-ee

**Comment by gpocentek** [comment]
Not tested, but I think you can do that with lazy objects:

```
gl = gitlab.Gitlab(URL)  # no authentication
project = gl.projects.get(id, lazy=True)
project.trigger_pipeline('master', token, variables={"DEPLOY": "true"})
```

**Comment by baurmatt** [comment]
This works great! Thanks a lot! :) Should we document this as it is a very very special use case?

**Comment by gpocentek** [comment]
Yes that would be great to have an example.
We already have a bit of documentation there: https://python-gitlab.readthedocs.io/en/stable/gl_objects/builds.html
