### ISSUE TITLE
group's projects contains some projects that don't belong to this group

### ISSUE THREAD

**Issue by ravinwind** [python-gitlab/python-gitlab#754]
## Description of the problem, including code/CLI snippet
```python
client = gitlab.client(url, private_token="....")
group = client.groups.get("my_group_name")
projects = group.projects.list(as_list = False)
for project in projects:
  print(project.name_with_namespace)
```

## Expected Behavior
I expect the result should be something like this:
```
my_group_name / project1
my_group_name / project2
my_group_name / project3
...
```

## Actual Behavior
Here's some actual result I got from my program
```
gg / wallet-flash
gg / wallet-hbb 
...
gg / shell
zp / related-issues  # zp is a person, and this is his personal project

gg / core
wwww / dev / w123  # wwww is another group while dev is wwww's subgroup, of which w123 is the project
```

## Specifications

  - python-gitlab version: lastest
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.9.0-ee

**Comment by ravinwind** [comment]
some more detail:  
my program didn't list all the projects belong to person zp or the subgroup wwww/dev, instead, it only printed two projects of zp and one project in wwww/dev, while there were about 20 projects in subgroup wwww/dev.

**Comment by gpocentek** [comment]
Hi,

The Gitlab API returns the list of projects for which `group` is a member. This is not related to namespaces.

There is an open issue to get the feature you're looking for: https://gitlab.com/gitlab-org/gitlab-ce/issues/23185.
