### ISSUE TITLE
confusion with labels.list()

### ISSUE THREAD

**Issue by Tomik292** [python-gitlab/python-gitlab#757]
## Description of the problem, including code/CLI snippet
Documentation says that to list labels for project you use
`labels = project.labels.list()`
I would expect that I get ALL labels of project, but I only get first page of labels

## Expected Behavior
`labels = project.labels.list()` returns all project labels

## Actual Behavior
`labels = project.labels.list()` returns first page of labels

## Specifications

  - python-gitlab version: 1.6.0
  - API version you are using : v4
  - gitlab.com

**Comment by gpocentek** [comment]
Hi @Tomik292 

By default `list()` operations are paginated. To retrieve all the labels you can do something like `project.labels.list(all=True, per_page=100)`.

See https://python-gitlab.readthedocs.io/en/stable/api-usage.html?highlight=pagination#pagination for more info about pagination.
