### ISSUE TITLE
Is it possible to change the id of a group?

### ISSUE THREAD

**Issue by lyenliang** [python-gitlab/python-gitlab#763]
## Description of the problem, including code/CLI snippet

 Is it possible to determine the id of the group that I created?

The following code doesn't work:

```
import gitlab

gl = gitlab.Gitlab(
    'http://my-gitlab.com', 
    private_token='<my-private-token>'
    )
# the id of the newly created group can't be determined by the id inside `group_data`
# So I try to update the id after it has been created
group_data = {'id': 117, 'name': 'MYGROUP', 'path': 'administration', 'description': 'my description', 'visibility': 'private', 'lfs_enabled': True, 'avatar_url': None, 'web_url': 'http://myweb.com/groups/administration', 'request_access_enabled': False, 'full_name': 'MYGROUP', 'full_path': 'administration', 'parent_id': None}

# View the id of the newly created group
group = gl.groups.create(group_data)
groups = gl.groups.list()
print('Group id before updating: ' + str(groups[0].attributes['id']))

# Change the group id
group.id = 555
group.save() # This line creates `gitlab.exceptions.GitlabUpdateError: 404: 404 Group Not Found` error

# View the id the group after updating
groups = gl.groups.list()
print('Group id after updating: ' + str(groups[0].attributes['id']))
```

According to [Gitlab Docs](https://docs.gitlab.com/ee/api/groups.html#update-group), gitlab supports updating the id of a group.

Why can't I use `group.id = 555` and `group.save()` to update the id of the group that I just created?

The [new-group](https://docs.gitlab.com/ee/api/groups.html#new-group) api doesn't support `id` as an attribute. That's why I try to update the id after it has been created.

Is this a bug of `python-gitlab`?

Why does the code return `404 Group Not Found` error?

## Expected Behavior
I expect the code to create a group whose `id` is 555

## Actual Behavior
I failed to change the `id` of the group that I just created. `group.save()` returns `gitlab.exceptions.GitlabUpdateError: 404: 404 Group Not Found` error.

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): community edition 11.10.0

**Comment by gpocentek** [comment]
Hi,

Gitlab doesn't allow to change the ID of a group, or the ID of any resource for that matter. You need to provide the group ID to update other attributes, but the ID cannot be changed.
