### ISSUE TITLE
tags are no more object since 1.0.0

### ISSUE THREAD

**Issue by gokuatkai** [python-gitlab/python-gitlab#764]
## Description of the problem, including code/CLI snippet
I recently upgraded from 0.21.2 to 1.8.0 and tags are no more objects but dicts instead, nothing I could find about it in changelog, newer version than 1.8.0 have same issue.

EDIT: reverted down to 1.0.0 issue seems to be introduced in that particular version.

```
    project = gitlab_client.projects.get(project)
    tags = project.tags.list()
    for tag in tags:
        print(tag.commit.id)
```
Error:
```
    print(tag.commit.id)
AttributeError: 'dict' object has no attribute 'id'
```
## Expected Behavior
Have tag as object

## Actual Behavior
tags are dict

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4

**Comment by max-wittig** [comment]
Why are you not using the latest version?

You can use tag.attributes.get("id") as workaround

**Comment by gokuatkai** [comment]
Because it also fails. One usually don't do big jump to avoid too much risk of issue.
I don't want to change thousands of line code using workaround.
This looks like a breaking change to me.

**Comment by max-wittig** [comment]
We can only support the latest version. There may be bugs in other versions. Please upgrade to the latest one.

**Comment by gokuatkai** [comment]
Sure, as I said, it is 'since' 1.0.0, after upgrading package, same error. I edit the description.

**Comment by gpocentek** [comment]
Hi,

Version 1.0 has indeed changed the behaviour, but we will not change it again.

Tags are still objects. `tags.commit` are not anymore (the exception you get is about `commit`, not `tag`).

**Comment by gokuatkai** [comment]
You are right, my bad, commit is not anymore. hope its the only one.
