### ISSUE TITLE
Unable to search group

### ISSUE THREAD

**Issue by lyenliang** [python-gitlab/python-gitlab#766]
## Description of the problem, including code/CLI snippet

I'm following the document [here](https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html) to create a project in a group. However, I got `AttributeError: 'GroupManager' object has no attribute 'search'` error when running the following code:

```
import gitlab

gl = gitlab.Gitlab(
    'http://mygitlab.com', 
    private_token='my_token'
    )

group = gl.groups.search('my-group')[0].id
print(group)
```

Is the document outdated? 
Is it possible to search group based on its `full_path`?

## Expected Behavior

`group = gl.groups.search('my-group')[0].id` returns a group whose name contains `my-group`.

## Actual Behavior

`group = gl.groups.search('my-group')[0].id` returns `AttributeError: 'GroupManager' object has no attribute 'search'` error.

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.10.0

**Comment by max-wittig** [comment]
See the documentation for the search API:
https://python-gitlab.readthedocs.io/en/stable/gl_objects/search.html
`Searches are based on a scope (issues, merge requests, and so on) and a search string.`

What you want is to search for a group:
To search for groups, use `gl.groups.list(search="string")`

Feel free to reopen, if this didn't solve your issue

**Comment by lyenliang** [comment]
Is it possible to search group by its `full_name`? 

Because I have multiple groups that have the same `name` but different `full_name`.

`gl.groups.list(search="string")` uses the group's `name` to search.
