### ISSUE TITLE
cli usage: use stdout

### ISSUE THREAD

**Issue by glensc** [python-gitlab/python-gitlab#782]
Please use stdout instead of stderr of usage, so I could grep (or pager) it:

Expected:
![image](https://user-images.githubusercontent.com/199095/58469459-38acfc00-8148-11e9-834f-85673f1a7f94.png)

Actual:
![image](https://user-images.githubusercontent.com/199095/58469448-33e84800-8148-11e9-89a6-92acf954f52c.png)

it would be useful if the output is a bit more vertical too ;)

**Comment by gpocentek** [comment]
Hi,

It's a very common practice to use stderr for error/help message, and it comes bundled with the argparse lib we are using. Redirecting the stderr to stdout as you did in the first example is the way to handle this.

**Comment by glensc** [comment]
it's inconvenient, therefore this RFE
