### ISSUE TITLE
Transfer_project

### ISSUE THREAD

**Issue by Crumbs808** [python-gitlab/python-gitlab#796]
## Description of the problem, including code/CLI snippet
I am attempting to transfer a project from my user space to a group: 

~/git/gitlab ] $ gitlab group transfer-project --id 281 --to-project-id 2705

## Expected Behavior
project 2705 should be transferred to group 281. 

## Actual Behavior
Error recieved: 
Traceback (most recent call last):
  File "/usr/local/bin/gitlab", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/gitlab/cli.py", line 188, in main
    cli_module.run(gl, what, action, args, verbose, output, fields)
  File "/Library/Python/2.7/site-packages/gitlab/v4/cli.py", line 389, in run
    data = g_cli()
  File "/Library/Python/2.7/site-packages/gitlab/v4/cli.py", line 69, in __call__
    return self.do_custom()
  File "/Library/Python/2.7/site-packages/gitlab/v4/cli.py", line 84, in do_custom
    return getattr(o, method_name)(**self.args)
  File "/Library/Python/2.7/site-packages/gitlab/cli.py", line 43, in wrapped_f
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/gitlab/exceptions.py", line 255, in wrapped_f
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/gitlab/v4/objects.py", line 911, in transfer_project
    path = '/groups/%d/projects/%d' % (self.id, to_project_id)
TypeError: %d format: a number is required, not strtr

## Specifications

  - python-gitlab version: 1.8.0 
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
Thanks for your report. We will look into it. Just a sidenote: Have you tried using python3 already? Maybe it's a python2 issue. Python2 support will be removed on the 01.01.2020.

**Comment by Crumbs808** [comment]
Good stuff i'll give that a shot. thx

**Comment by Crumbs808** [comment]
Hi Max, No dice on the python3, same error.

**Comment by reinierpost** [comment]
I just experienced the same bug with the 'gitlab' command packaged with Ubuntu 18.04.2 LTS.
It uses python3; the packages in question are:
```
gitlab-cli 1:1.3.0-2
python3-git 1:1.3.0-2
```
The bug is in file /usr/lib/python3/dist-packages/gitlab/v4/objects.py on line 700, which reads:

`        path = '/groups/%d/projects/%d' % (self.id, to_project_id)
`

My `gitlab group transfer-project` command actually works after change it to

`        path = '/groups/%d/projects/%d' % (int(self.id), int(to_project_id))
`
In the current master version of objects.py, that line is 1067 and it hasn't been changed, so I think the bug is still in there.

**Comment by max-wittig** [comment]
We don't support or create the package that comes with Ubuntu. Please use only the pip package.

**Comment by reinierpost** [comment]
I just used `pip3 install python-gitlab` to install the latest pip version (1.9.0); it does _not_ have this bug, `gitlab group transfer-project` just works.

**Comment by max-wittig** [comment]
Thanks for the report :)
