### ISSUE TITLE
Scope "bug"

### ISSUE THREAD

**Issue by romansvozil** [python-gitlab/python-gitlab#806]
## Description of the problem, including code/CLI snippet
```py
    for job in project.jobs.list(scope=['success', 'failed']):
        print(job.attributes['status'])
```
It returns jobs of only last scope.
Does python-gitlab api supports multiple scope statement for finding jobs? Because gitlap api [yes](https://docs.gitlab.com/ee/api/jobs.html#list-project-jobs)

## Expected Behavior
something like:
success
success
success
failed
success

## Actual Behavior
failed
failed
failed

## Specifications

  - python-gitlab version:1.8.0
  - API version you are using (v3/v4): v4

**Comment by EricTendian** [comment]
I was able to reproduce this. Turning on my logger to the debug level, it looks like this is the request that is sent:

```
https://gitlab.com:443 "GET /api/v4/projects/PROJECT_ID/pipelines/PIPELINE_ID/jobs?scope=success&scope=failed&page=1 HTTP/1.1" 200 1800
```

The proper request would be `GET /api/v4/projects/PROJECT_ID/pipelines/PIPELINE_ID/jobs?scope[]=success&scope[]=failed&page=1 HTTP/1.1` (note the `[]`)

I'm not confident this is the right way to fix it, but it seems like the `ListMixin` may need to be updated to properly handle the scope parameter.

**Comment by duncz** [comment]
Was this issue ever resolved? I'm encountering the same thing. Or is there any workaround?

**Comment by EricTendian** [comment]
@duncz don't know if it was resolved, I ended up working around this via not passing a scope but instead filtering the jobs I got in the response (a more expensive operation, but it works).

**Comment by romansvozil** [comment]
@duncz there is the solution I used in my project:

```py
jobs = git_project.jobs.list(query_parameters={'scope[]': ['pending', 'running', 'failed', 'success']})
```

Should work.

**Comment by JohnVillalovos** [comment]
Related issue: https://github.com/python-gitlab/python-gitlab/issues/1735
