### ISSUE TITLE
SSL CertVerification Error

### ISSUE THREAD

**Issue by TebanSierra** [python-gitlab/python-gitlab#807]
Failed to auth session with Self Signed Certificate

```python
gl = gitlab.Gitlab('https://url_to_gitlab.com', private_token='secret_token')
gl.auth()
```
While I was expecting a succesful connection I got the following error
```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
```
According to #204 I must have the CA file which might not be provided by my company. And using `ssl_verify=False` might not be a good solution. 

Any other way to establish a connection to a Self Signed GitLab?

**Comment by max-wittig** [comment]
You should be able to download the certfile from the page itself and add it to python-gitlab.

Please feel free to re-open if you have encounter related problems

**Comment by TebanSierra** [comment]
After downloading de crt file and adding the `ssl_verify` argument I still got an error:
```python
gl = gitlab.Gitlab('https://comapny.gitlab.com.co', private_token='secret_token', ssl_verify='/home/user/path/to/cert/certificate_file.crt')
gl.auth()
```
Error keeps as follow:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/gitlab/__init__.py", line 201, in auth
    self._token_auth()
  File "/usr/lib/python3.7/site-packages/gitlab/__init__.py", line 214, in _token_auth
    self.user = self._objects.CurrentUserManager(self).get()
  File "/usr/lib/python3.7/site-packages/gitlab/exceptions.py", line 255, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gitlab/mixins.py", line 68, in get
    server_data = self.gitlab.http_get(self.path, **kwargs)
  File "/usr/lib/python3.7/site-packages/gitlab/__init__.py", line 555, in http_get
    streamed=streamed, **kwargs)
  File "/usr/lib/python3.7/site-packages/gitlab/__init__.py", line 498, in http_request
    result = self.session.send(prepped, timeout=timeout, **settings)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='comapny.gitlab.com.co', port=443): Max retries exceeded with url: /api/v4/user (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))
```

**Comment by dgpicke** [comment]
While I am far from being a guru yet on this, there is one glaring item you used above.  ssl-verify is a Boolean (True or False).  think you may have misused this variable above for a cert value.

**Comment by dgpicke** [comment]
And - I am apparently a bit late to this game by a number of months

**Comment by wagmarom1** [comment]
Hello did you find any solution? I'm having the same problem here

**Comment by dgpicke** [comment]
@wagmarom1 - YES.  Figured it out.  WOW..  What a mess..  Heres the deal.  There were 5 layers of issues surrounding this problem. 
[1] Physical server connection and security; [2] GitLab server permissions & Login Types; [3] GitLab v4 API HTTP Transaction breakage and POOR documentation, 
[4] OpenSSH and Ruby/Python in Linux; and [5] GitLab-python api call errors that rode on the back of [3].  One at a time.

[1] Physical connection.  Most GitLab servers run HTTPS (eg. secure) transactions over the socket layers of your local/remote network, 
and using port 443, and performing SSL/TLS connection handshake wiith appropriate OpenSSH certs/keys.  YOU CAN connect a client that 
logs into the Gitlab HTTPS Server, by running HTTP (non-secure) transactions, and SKIP all the handshakes by setting your port to 80xx
 (eg. 8000, 8001, etc), setting firewall rules appropriately (shouldn't be much if any), and using GitLab v4 api 'GitLab Login Token', 
and with the SSL-Verification flag set to FALSE.  This will work ONLY IF both machines are (a) on the same internal subnet w NO firwall in btw,
 or (b) if firewall rules PROVIDE access if not on the same subnet. For our solution, in the end,  I had to create on my Linux server 
(eg. my gitlab v4 api webhook client) all the security needed to perform OpenSSH handshakes with the remote server (eg. certs, certstack, keys),
and using port 443 with appropriate firwall rules.  As such, using HTTP login with the SSL-Verification flag as FALSE will not work long term.

**Comment by dgpicke** [comment]
[2] Gitlab Server permissions & Login Types. The next level of issues to overcome are gitlab permission levels that yield (403 Forbiden) errors
without ANY more desciption than that. In the end, this is all about the Gitlab ADMINS setting/allowing the right permission levels for external 
v4 API transactions - 'regardless' of having a Gitlab Login token. Having a login token wont get you anything other than a generic 403/404 error 
(forbidden/not-found, respectively) in many v4 api calls. This really sucked and costed me nearly 3 weeks of sleuthing, only to find that permission 
levels in our Gitlab test env were MAINTAINER, while the prod Gitlab server were one level lower as DEVELOPER.  That one step caused tons of 403/404
 errors.  And uncovered an overwhelming problem with Gitlab Documentation that I will discuss in [3].  Finally, there is a distinction between
'LOGIN TOKENS' and 'TRIGGER TOKENS'.  Again, due to sucky documentation, using 'login tokens' with LOWER DEVELOPER rights will throw errors - even
though the TOKEN is a sanctified/trusted gitlab login token - doesnt matter. The answer is using a TRIGGER TOKEN as a 'gratus and one time login'.
I dont know if this is a vulnerability, but it was the 'only' way to bypass this 'security fighting' within Gitlabs server. And - regardless of 
have a SECURE socket connection with certs/keys.

**Comment by dgpicke** [comment]
[3] GitLab v4 API HTTP Transaction breakage and POOR documentation.  [3a] First, let me say 'painfully' that all Gitlab v4 API calls are NOT created/treated
equally, AND their documetation on may points just plain sucks. In short, using INSECURE connections (ex like HTTP w port 8000) as with SECURE connections
works GREAT for basic gitlab api features like (issues, projects, milestones, users, groups, etc).  BUT !!!  The moment you transition into 'higher level'
api callse (ex. pipelines, triggers, environment, vars, etc) - not so much.  TONS of 403/404 errors with NO explaination.  The answer is logging in using
a trigger token, NOT a login token. [3b] Documentation. I need to vent on this one. Being a seasoned design engineer/architect and a technical writer (past tense)
 for both windows and unix/linux systems, I have seen it all. And know that 'most' of the worlds users use 'How-To' guides and NOT 'reference manuals'.
There are also biggots on both sides - those for GUI interfaces and drag/drop (Windows & MAC users), and those who spend their entire lives
living-and-breathing everything from the command line (Unix/BSD/Linux). Given that the large majority of market share of users is the former, not the later,
I personally believe that the command-line croud need to 'give up their cell phones imediately' - given they cant stand GUI's. So, whats the problem
and how does that impact Gitlab usage.  Answer - a philosophy for (a) communicating how to design/use their products, and (b) how they write about
 their products. Git and Gitlab were birthed by Unix/Linux weenies who (a) seldom socialize and dont understand customer engagement, 
(b) have spent a lifetime on command line memorization and reference libs, and as such do not understand the simplicity of GUIS's and 'how-to' guides. In fact,
documetation to these folks is boring and is nearly ignored.  Socialization and instruction is left as digitized skype Q&A sessions. 
IN ALL - their documetation stinks.  They have TONS of reference guides, but, they expect everythone to LOVE memorization as they do.  I remind them
that when Einstein was criticized for NOT memorizing physics tables, he stated 'why do that when I can simply look it up'?  Back to the point,
(a) Reference only, MINIMAL "how-to's". (b) Critical info like 403/404 error origins; gitlab permission minimum bar 'per' a v4 api call type;
usage of TRIGGER tokens to circumvent login errors, etc.  AND - where the H is the 'real' video training for Gitlab?  Oh - that doesnt exist.

**Comment by dgpicke** [comment]
[4] OpenSSH and Ruby/Python in Linux.  If you are using clients w Ruby or Python as with Red Hat or other Linux OS's, you may find that the OpenSSH
standards for the language are 'too old' for current business 'security regs'.  In my case Red Hat RHEL7 Linux, they use a service called Satellite
that provides all the software and versions you are allowed to load on your RHEL7 VM.  In my case, my 'security regs' required a minimum of TLS v1.2
security handshake to create a HTTPS connection btw my client and the gitlab server. Unfortunately, RH Satellite for both Ruby and Python languages
did not provide the latest version of OpenSSH that supported the needed 'security regs'  PT. Understanding dependancies up front matters.

**Comment by dgpicke** [comment]
[5] GitLab-python api call errors that ride on the back of gitlab v4 API errors. PT. Curl vs. Gitlab v4 API w/ login token vs. Gitlab v4 API trigger token
 login, vs. Gitlab-python login options do 'not' react the same in Gitlab. Cutting to the chase - I had to punt the entire usage of gitlab-python
and write RAW HTTP strings (like single line curl strings) that uses (a) python requests, and (b) TRIGGER token based login.

**Comment by melinath** [comment]
setting `ssl_verify=False` on Gitlab instantiation "fixed" the issue well enough for me. It looks like passing a path _should_ work, since this uses requests under the hood: https://requests.readthedocs.io/en/master/user/advanced/#ssl-cert-verification but that's beyond what I need.

**Comment by DieSwartKat** [comment]
Setting the ssl_verify=False worked for me.

```
gl = gitlab.Gitlab('https://url_to_gitlab.com', private_token='secret_token', ssl_verify=False)
gl.auth()
```

**Comment by Rwarcards762** [comment]
It seems this issue, if not resolved by passing an `ssl_verify` Cert (same error) may be caused by OpenSSL in Python versions 3.6.x -- https://github.com/urllib3/urllib3/issues/1682

The literal only option is to `ssl_verify=False` in this case as a cert will ALWAYS fail.
