### ISSUE TITLE
Cannot get subgroup's subgroups

### ISSUE THREAD

**Issue by bdpqll** [python-gitlab/python-gitlab#812]
## Description of the problem, including code/CLI snippet
![image](https://user-images.githubusercontent.com/43171515/60218920-71d8a900-9879-11e9-99ae-fe142bdd0ef9.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/43171515/60218969-9e8cc080-9879-11e9-8094-67e3db6998e3.png)

## Specifications

  - python-gitlab version: 1.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by max-wittig** [comment]
You cannot get a subgroup from another subgroup. You'll need to get the group again before that. 

so you need to call the find_subgroup function with a real group, not with a subgroup. 

```python
group = gl.groups.get(othergroup.id)
find_subgroup(group, query)
```

**Comment by bdpqll** [comment]
@max-wittig thanks a lot!
