### ISSUE TITLE
python-gitlab tutorials' issue

### ISSUE THREAD

**Issue by Auggie321** [python-gitlab/python-gitlab#813]
## Description of the problem, including code/CLI snippet
#1##  
https://python-gitlab.readthedocs.io/en/stable/gl_objects/commits.html  
"commits = project.commits.list(since='2016-01-01T00:00:00Z')"  

#2##  
https://github.com/python-gitlab/python-gitlab/blob/57fa4e37aaf6ccee0d75085520f96fd15752a3df/docs/gl_objects/commits.rst  
python-gitlab/docs/gl_objects/commits.rst   
"commits = project.commits.list(since='2016-01-01T00:00:00Z')"    

Dear Sir/Miss,  
I found there have something ambiguity in tutorials/github which where maybe need to change. Please check as following:   

From #1##,#2## address's message, i thought when you searched commits info from '2016-01-01xx', maybe you need to add 'all=True' in commits.  

If you use commits = project.commits.list(since='2016-01-01T00:00:00Z'), it will loses a lot of commits info,  but commits = project.commits.list(all= True, since='2016-01-01T00:00:00Z') won't.  

Could you please change this in tutorials/github, or add something comments on it. I hope this will more clear and useful for others. Maybe this will help you.  

## Expected Behavior
change the example；
old one : commits = project.commits.list(since='2016-01-01T00:00:00Z')  
more clear way : commits = project.commits.list(all= True, since='2016-01-01T00:00:00Z')  
## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
This should be clarified now.
