### ISSUE TITLE
How to update protectedbranch?

### ISSUE THREAD

**Issue by bdpqll** [python-gitlab/python-gitlab#814]
## Description of the problem, including code/CLI snippet
![image](https://user-images.githubusercontent.com/43171515/60267624-4db9ae00-98f3-11e9-884e-96cca216c70b.png)

## Actual Behavior
Cannot update protectedbranch properties

## Specifications

  - python-gitlab version: 1.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by gpocentek** [comment]
Hello,

GitLab doesn't support updating protected branches. You need to delete the protected branch then re-create it with the correct information.

**Comment by bdpqll** [comment]
Thanks!
