### ISSUE TITLE
Listing pipelines: GitlabHttpError: 403 

### ISSUE THREAD

**Issue by vpanneer** [python-gitlab/python-gitlab#815]
## Description of the problem, including code/CLI snippet
projects = gl.projects.list(search = "sparrow_theia")
for my_project in projects:
    print(my_project)
    pipelines = my_project.pipelines.list()

## Expected Behavior
Should list all the pipelines related to the project.

## Actual Behavior
Lists the information about the  project "sparrow-theia" but fails to list the pipelines related to it .

ERROR received : 

GitlabHttpError: 403: <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
Your authorization token expired or you might have no access to this resource.

This is directly reported by the GitLab API.

**Comment by vpanneer** [comment]
Thanks for your answer.  FIY, I have a valid token(freshly generated) and possess "owner" credentials for this project. And also I'm able to retreive the list of jobs with their respective "status". Its strange that am not able to obtain the pipelines list.
Is there any particular parameter or credentials missing specifically for the pipeline?
Thanks again.

project = gl.projects.list(search = "sparrow_theia")
jobs = my_project.jobs.list()
for job in jobs:
    print(job.status)

--result---
success
success
success
failed
success
skipped
failed
success
failed

**Comment by Lucas-C** [comment]
I can report that I had the exact same issue, with a valid token
