### ISSUE TITLE
Cannot connect to local gitlab

### ISSUE THREAD

**Issue by ghost** [python-gitlab/python-gitlab#816]
## Description of the problem, including code/CLI snippet
![image](https://user-images.githubusercontent.com/43171515/60444701-60e7b900-9c26-11e9-8072-aec6a7fd8551.png)

## Expected Behavior
Using sam local invoke and establish connection to local gitlab in docker

## Actual Behavior
It concantenates URL two times
![image](https://user-images.githubusercontent.com/43171515/60444671-53323380-9c26-11e9-8012-d3eb47866d00.png)

## Specifications

  - python-gitlab version: 1.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
Is your local gitlab running on port 80?  
Try: `http://127.0.0.1` instead of just 127.0.0.1

**Comment by max-wittig** [comment]
Please feel free to reopen, if it's still not solved
