### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by ghost** [python-gitlab/python-gitlab#817]
## Description of the problem, including code/CLI snippet
![image](https://user-images.githubusercontent.com/43171515/60446480-19632c00-9c2a-11e9-9172-4a915a3fa63e.png)

## Expected Behavior
Establishing connection to local gitlab
![image](https://user-images.githubusercontent.com/43171515/60446578-592a1380-9c2a-11e9-8ebc-af5c3447e2e9.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/43171515/60446431-05b7c580-9c2a-11e9-8621-34a7b6216e0a.png)

## Specifications

  - python-gitlab version: 1.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
Seems to be a local problem, because the stacktrace shows an ConnectionError.

Is your instance behind a proxy?
