### ISSUE TITLE
Additional branch.protect() fields

### ISSUE THREAD

**Issue by plantusd** [python-gitlab/python-gitlab#821]
## Description of the problem, including code/CLI snippet
![image](https://user-images.githubusercontent.com/44056339/60962052-134e0900-a316-11e9-8fc5-2089c8e8abc7.png)

## Expected Behavior
Can you also add 
maintainers_can_push=, maintainers_can_merge=

**Comment by max-wittig** [comment]
Have you tried it. Should work as it's send to the GitLab API.

**Comment by plantusd** [comment]
Yes, here
![image](https://user-images.githubusercontent.com/44056339/60965163-d2f28900-a31d-11e9-9567-dc8f9fbd5001.png)

![image](https://user-images.githubusercontent.com/44056339/60965181-ddad1e00-a31d-11e9-8dc2-364a9cf745a5.png)

Thanks in advance!

**Comment by max-wittig** [comment]
`lazy` doesn't help you here. 

The syntax is different. See examples here: https://python-gitlab.readthedocs.io/en/stable/gl_objects/protected_branches.html#examples

**Comment by max-wittig** [comment]
You need to create a protected branch, after creating a normal branch

**Comment by plantusd** [comment]
yes, i get it, but whats the point to make branch.protect() with 
developers_can_push=, 
developers_can_merge=

w/o 

maintainers_can_push=, 
maintainers_can_merge=
