### ISSUE TITLE
Rebase an MR

### ISSUE THREAD

**Issue by jeroen92** [python-gitlab/python-gitlab#822]
## Description of the problem, including code/CLI snippet
The Gitlab REST API offers a call to attempt to rebase the `source_branch` onto the `target_branch`. This hasn't been implemented in the Python Gitlab client library. I'd like to go ahead and submit an MR for this. However, I was wondering whether there's a reason this hasn't been implemented yet. If there are no objections from your side, I'd be fine creating an MR for this feature.

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
Sure. Please go ahead.

Just make sure to follow our contribution guidelines and use conventional changelog: 
https://github.com/python-gitlab/python-gitlab#contributing

Thank you very much!

> Note: The tests currently still fail in the CI and we're not quite sure why. They work locally just fine

**Comment by jeroen92** [comment]
Nice, then I'll get going :)
