### ISSUE TITLE
Documentation bug in snippets

### ISSUE THREAD

**Issue by LightSage** [python-gitlab/python-gitlab#828]
One of the code blocks is not properly formatted. 

![Screen Shot 2019-07-17 at 3 00 25 PM](https://user-images.githubusercontent.com/46062298/61407647-d947ae80-a8a3-11e9-86e1-80f0823627ef.png)

------
In page: gl_objects/snippets.rst

**Comment by max-wittig** [comment]
Thanks for the report! Should be fixed soon!
