### ISSUE TITLE
project.approvals.set_approvers doesn't seem to  work.

### ISSUE THREAD

**Issue by sndrsmnk** [python-gitlab/python-gitlab#843]
## Description of the problem, including code/CLI snippet
This code sets all toggle flags correctly, but doesn't set the approver uid/gids:

```python
    project.approvals.set_approvers(approver_ids=[1], approver_group_ids=[11])
    project.reset_approvals_on_push = 1
    project.disable_overriding_approvers_per_merge_request = 0
    project.merge_requests_author_approval = 1
    project.only_allow_merge_if_all_discussions_are_resolved = 1
    project.approvals_before_merge = 1
    project.save()
```

## Expected Behavior
Expect to see existing uids/gids removed and the uid/gid in code snippet (`1`, `11`) added in the Gitlab WebUI at `https://mysvr/group/project/edit` section `Merge request approvals`.

## Actual Behavior
Does not set the user & group that can approve. WebUI states: `You have not added any approvers. Start by adding users or groups.`. All other settings seem to be applied. It doesn't seem to matter if there's already approvers selected or not.

## Specifications
  - python-gitlab version: 1.10.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.0.3-ee (1b1872f9d93)

**Comment by max-wittig** [comment]
Hi @sndrsmnk thanks for the report. Sadly I don't have access to the enterprise edition of GitLab to test this, but I would be happy to review any merge request from your side.

**Comment by sndrsmnk** [comment]
Doesn't gitlab-ce have this feature, or does it work for you in the gitlab-ce version?
Does my syntax look OK at all?

Could you perhaps elaborate on the difference between doing `p_mras = project.approvals.get()` and setting these flags on the `p_mras` object vs the `project` object itself? There's a lot of overlap in those objects it seems, i've come to this point now:

```python
    p_mras = project.approvals.get()
    p_mras.approvals_before_merge = 1
    p_mras.reset_approvals_on_push = 1
    p_mras.disable_overriding_approvers_per_merge_request = 0
    p_mras.merge_requests_author_approval = 1
    p_mras.only_allow_merge_if_all_discussions_are_resolved = 1
    p_mras.save()

    project.reset_approvals_on_push = 1
    project.disable_overriding_approvers_per_merge_request = 0
    project.merge_requests_author_approval = 1
    project.only_allow_merge_if_all_discussions_are_resolved = 1
    project.approvals_before_merge = 1
    project.approvals.set_approvers(approver_ids=[1], approver_group_ids=[11])
    project.save()
```

**Comment by sndrsmnk** [comment]
Hm. Python-Gitlab code looks simpler than i though. Will investigate further.

**Comment by sndrsmnk** [comment]
I'm closing this issue. It's not python-gitlab messing this up. Sorry for the noise.
Not entirely sure what is or was messing up though, it might have to do with the order of doing this.

Changed code to:

```
    p_mras = project.approvals.get()
    p_mras.approvals_before_merge = 1
    p_mras.reset_approvals_on_push = 1
    p_mras.disable_overriding_approvers_per_merge_request = 0
    p_mras.merge_requests_author_approval = 1
    p_mras.only_allow_merge_if_all_discussions_are_resolved = 1
    p_mras.save()

    project.approvals.set_approvers(approver_ids=[1], approver_group_ids=[11])

    project.approvals_before_merge = 1
    project.reset_approvals_on_push = 1
    project.disable_overriding_approvers_per_merge_request = 0
    project.merge_requests_author_approval = 1
    project.only_allow_merge_if_all_discussions_are_resolved = 1
    project.save()
```

That seems to work just fine.

**Comment by ARRIVALRobotics** [comment]
Not work!
