### ISSUE TITLE
How to download or clone specific folder or subdirectory in gitlab.

### ISSUE THREAD

**Issue by mdrijwan123** [python-gitlab/python-gitlab#844]
I want to clone or download the specific folder using Python-Gitlab.

After downloading I want to upload all the content to server but not able to know how to do that. Any help will be appreciated. Thanks.
  - python-gitlab version: 1.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Community Edition 11.3.4

**Comment by max-wittig** [comment]
This is actually not possible with the current API.

**Comment by timfeirg** [comment]
just for reference, the needed feature is being tracked in this gitlab issue: https://gitlab.com/gitlab-org/gitlab/-/issues/28827
