### ISSUE TITLE
Runner List does not support pagination options

### ISSUE THREAD

**Issue by gavk34** [python-gitlab/python-gitlab#850]
## Description of the problem, including code/CLI snippet

gitlab.runners.list(all=True)
or
gitlab.runners.list(page=1,per_page=20)

has no effect. Always only returns 6 runners. Our instance has 22 runners.

## Expected Behavior
According to https://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination
`page` and `per_page` should be available.

`all=True` should return all the items

## Actual Behavior
Neither `all=True` or pagination is working for Runners

## Specifications

  - python-gitlab version: python-gitlab-1.10.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.1.3

**Comment by max-wittig** [comment]
Are you sure that you're an admin on your instance/are allowed to view all runners?

Have you tried the same request using curl?

**Comment by gavk34** [comment]
Sorry @max-wittig for not responding to your previous comment. 

I solved it by switching to `gitlab.runners.all(all=True)` - this seems to return what I want

**Comment by NikolausDemmel** [comment]
I have the same discrepancy. More runners show up in `gitlab.runners.all(all=True)` than `gitlab.runners.list(all=True)`. 

I'm admin.

Testing the API directly, looks like the missing runners also don't show up in `api/v4/runners/all?per_page=1000`.

**Comment by goneng** [comment]
@NikolausDemmel, looks like the highest supported value for `per_page` is `100`, so maybe the `1000` is ignored.
