### ISSUE TITLE
Add `get()` method to `ProjectEnvironment`

### ISSUE THREAD

**Issue by sc250024** [python-gitlab/python-gitlab#851]
## Description of the problem, including code/CLI snippet

It would be nice to add a `get()` method to the `ProjectEnvironment*` classes. This is useful because currently simply calling `project.environments.list()` does not return all the information about a given environment, such as when it was last deployed.

## Expected Behavior

There should be a `project.environments.get(environment_id)` method, using the `environment_id` as an argument, which then calls the endpoint here (https://docs.gitlab.com/ce/api/environments.html#get-a-specific-environment), or `/projects/:id/environments/:environment_id`.

## Actual Behavior

Currently, no such method exists.

## Specifications

  - python-gitlab version: **python-gitlab==1.10.0**
  - API version you are using (v3/v4): **v4**
  - Gitlab server version (or gitlab.com): **gitlab.com**

**Comment by max-wittig** [comment]
This should be fixed with the merge: https://github.com/python-gitlab/python-gitlab/pull/865

**Comment by sc250024** [comment]
Thank you very much @max-wittig, and to @orf as well for the PR!
