### ISSUE TITLE
Failed to parse server message

### ISSUE THREAD

**Issue by rajarameshmamidi** [python-gitlab/python-gitlab#852]
## Description of the problem, including code/CLI snippet
Hi, with the help of google and docs i build below code to list all projects which were there in my repository. but i am getting "gitlab.exceptions.GitlabParsingError: Failed to parse the server message". can someone help me how to get the details?

import gitlab
gl = gitlab.Gitlab('**********', '**************')
gl.auth()
projects = gl.projects.list()
for project in projects:
    print(project)

## Specifications

  - python-gitlab version: 1.10.0
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com): GitLab Enterprise Edition 12.1.0-pre 1802ffd1444

**Comment by rajarameshmamidi** [comment]
Hi All, can someone share details on this issue.

**Comment by pbtura** [comment]
I'm having the same issue. What version of python are you using?

**Comment by max-wittig** [comment]
This should work. Can you connect to your instance via curl?

**Comment by pbtura** [comment]
When I try to connect via curl it looks like it is trying to redirect me to the login page. The response I'm getting is 
<html><body>You are being <a href="https://gitlab.com/users/sign_in">redirected</a>.</body></html>

**Comment by pbtura** [comment]
OK, I think I found the issue. I had to use a private token with full api access. Not sure why, I'm not actually writing anything so it seems like read-only access should be enough.

**Comment by rajarameshmamidi** [comment]
Hi Pbtura / max,

i am getting all details of an users with curl command to list projects of an user. 
is it possible to get project list alone?

**Comment by max-wittig** [comment]
@rajarameshmamidi I'm not sure what you mean. Could you please elaborate?

**Comment by hdpingshao** [comment]
@pbtura hello,I'm having the same issue.How did you solve it?rthanks

**Comment by pchandu587** [comment]
gl = gitlab.Gitlab('https://gitlab.com/*********',
                       private_token='******************')
gl.auth()
projects = gl.projects.list()
return HttpResponse(projects[0].name)

I am also found same issue
How to solve this

**Comment by rajarameshmamidi** [comment]
Hi chandu  & hdpingshao ,

for my requirement i used below ways. i will be happy if this help for your requirements. 

i used below way to clone a repository from git using python code.
from git import Repo
path = r'C:\Users\Desktop\for_git'
Repo.clone_from('https://username@gitlab.com/username/resopitory_name.git',path)

To know about project details of an account using Curl command :-
$ curl --header 'PRIVATE-TOKEN:tokendetails' 'https://gitlab.com/api/v4/users/user_name/projects'  

Above command will give brief description of all projects for an account specific.
