### ISSUE TITLE
SysCallError when uploading pdf to repo

### ISSUE THREAD

**Issue by james0807** [python-gitlab/python-gitlab#853]
## Description of the problem, including code/CLI snippet

When attempting to upload a pdf file to a repo using the project files mechanism, an error is received. The same code works for png files but pdf's seem to be causing a problem. Issue seems to stem from the SSL side, but I wondered if anyone had seen similar behaviour with the python-gitlab module. The same thing happens with the commit method.

If I use the api to "get" a pdf file that's been manually uploaded, I get a base64 string thats identical to the one created for the "content" parameter in the code snippet below. There seems to be something strange happening when this string is uploaded, any thoughts will be greatly appreciated.

Code:

`pdf_file = base64.b64encode(open('test.pdf','rb').read()).decode()`
`f = project.files.create({'file_path': 'test.pdf',`
                         ` 'branch': 'Systems',`
                        `  'content': pdf_file,`
                          `'encoding': 'base64',`
                          `'commit_message': 'Create testfile'})`

## Expected Behavior

File uploaded.

## Actual Behavior

`SysCallError: (10054, 'WSAECONNRESET')`

## Specifications

  - python-gitlab version: 1.10.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  gitlab.com

**Comment by james0807** [comment]
Issue seems to be getting weirder, plain text pdfs work without issue, any pdf that contains images seems to cause the issue. .npy files also aren't working but I haven't had a chance to extensively test all files types. 

Given the files are being turned into byte strings in base64, why does the format of the file make a difference to the success of the file upload?

Anyone got any ideas?

**Comment by petermarko** [comment]
Can you upload the file from gui?
Maybe it just exceeds size limit on the server...

**Comment by bufferoverflow** [comment]
seems to be not related with python-gitlab
