### ISSUE TITLE
[CLI] Question about that character named '\r\n' don't escape the newline in --description

### ISSUE THREAD

**Issue by a1vin-tian** [python-gitlab/python-gitlab#854]
## Description of the problem, including code/CLI snippet
 gitlab project-release create --description "## CHANGELOG\r\n\r\n- A\r\n-B" 

## Expected Behavior
```
CHANGELOG
* A 
* B 
```

## Actual Behavior
CHANGELOG\r\n\r\n- A\r\n-B

## Specifications

  - python-gitlab version: 1.10.0
  - API version you are using (v3/v4): v4 
  - Gitlab server version (or gitlab.com): 1.10.0

**Comment by nejch** [comment]
For future readers, simply use newlines the same way you would when adding a commit body to `git commit -m "...`.

```
gitlab project-release create \
    --project-id group/your-project \
    --ref main \
    --tag-name v1.0.0 \
    --description "## CHANGELOG
   
- A
- B
"
```
