### ISSUE TITLE
Git Blame API Support

### ISSUE THREAD

**Issue by vcajes** [python-gitlab/python-gitlab#856]
## Description of the problem, including code/CLI snippet

Gitlab is adding the Blame API to the Gitlab v.12.2 being released in around ~2 weeks.

See here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/30675

## Expected Behavior

Integration to this new API so we can consume it! 

## Actual Behavior

We are not yet integrated to the Blame API.

## Specifications

  - python-gitlab version: 1.10.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): v12.2

**Comment by max-wittig** [comment]
Thanks for the suggestion. This is just a project which is maintained by 2 people in their freetime. If you want to have this feature, when it comes out, feel free to create a merge request. I would be happy to review it and merge it once it's offical.

**Comment by max-wittig** [comment]
This is fixed.
