### ISSUE TITLE
Search issues on specific filter with `in` parameter ?

### ISSUE THREAD

**Issue by jeromelefeuvre** [python-gitlab/python-gitlab#859]
Hi !
## Description of the problem, including code/CLI snippet
I'm trying to search issues on specific filter name like title using search method like:
project.search('issues', 'foo', in='title')

## Expected Behavior
'in' keyword adding in kwargs paramater

## Actual Behavior
'in' is a specific method in Python and return error:
````
(master) =>> python2 migrate.py
  File "migrate.py", line 130
    exists = project.search('issues', jira_issue['key'], in='title')
                                                          ^
SyntaxError: invalid syntax
````

## Specifications

  - python-gitlab version: 1.10.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by petermarko** [comment]
Since gitlab API does not support such filer, python-gitlab doesn't/can't either...
See https://docs.gitlab.com/ce/api/search.html#project-search-api
