### ISSUE TITLE
Bug in project.files.create(create a new file)

### ISSUE THREAD

**Issue by wuzhaoyuan** [python-gitlab/python-gitlab#862]
## Description of the problem, including code/CLI snippet

In [4]: f = project.files.create({'file_path': 'testfile.txt',
   ...:                           'branch': 'master',
   ...:                           'content': 'fsdfdsfsf',
   ...:                           'author_email': 'test@example.com',
   ...:                           'author_name': 'yourname',
   ...:                           'encoding': 'text',
   ...:                           'commit_message': 'Create testfile'})
---------------------------------------------------------------------------
GitlabCreateError                         Traceback (most recent call last)
<ipython-input-4-ec24ae7a83f2> in <module>()
      5                           'author_name': 'yourname',
      6                           'encoding': 'text',
----> 7                           'commit_message': 'Create testfile'})

/usr/lib/python2.7/site-packages/gitlab/cli.py in wrapped_f(*args, **kwargs)
     41         @functools.wraps(f)
     42         def wrapped_f(*args, **kwargs):
---> 43             return f(*args, **kwargs)
     44 
     45         # in_obj defines whether the method belongs to the obj or the manager

/usr/lib/python2.7/site-packages/gitlab/exceptions.pyc in wrapped_f(*args, **kwargs)
    259                 return f(*args, **kwargs)
    260             except GitlabHttpError as e:
--> 261                 raise error(e.error_message, e.response_code, e.response_body)
    262 
    263         return wrapped_f

GitlabCreateError: 400: encoding does not have a valid value

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
The encoding value you've provided has an invalid value. Please try the same request with curl and you'll see that this is not a python-gitlab issue. 

Maybe your Gitlab server is too old and doesn't support this parameter yet. Not sure. 

> Additionally I would stronly recommend to use python3. Python2 support will be dropped on the 01.01.2020.

**Comment by beyondmars3** [comment]
I also encountered the same problem.
Curl is fine.

**Comment by DieSwartKat** [comment]
> I also encountered the same problem.
> Curl is fine.
> 
> Now solved, i found
> 
> The reason is that the parameter is wrong, the document gives'encoding':'text'.
> Reference: https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html
> 
> Should be removed

Just to clarify, if you remove the encoding file from the dictionary completely it will upload without encoding. Thus not like this:

```
f = project.files.create({'file_path': 'testfile.txt',
                          'branch': 'master',
                          'content': file_content,
                          'author_email': 'test@example.com',
                          'author_name': 'yourname',
                          'encoding': 'text',
                          'commit_message': 'Create testfile'})

```

but like this:

```
f = project.files.create({'file_path': 'testfile.txt',
                          'branch': 'master',
                          'content': file_content,
                          'author_email': 'test@example.com',
                          'author_name': 'yourname',
                          'commit_message': 'Create testfile'})

```

**Comment by ajcollett** [comment]
@max-wittig your docs need some updating still. If I get some time I'll try do an MR.

See "Creating a new file": https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html
