### ISSUE TITLE
Attempting to pull all merge requests from a gitlab instance returns empty dict

### ISSUE THREAD

**Issue by pdoconnell** [python-gitlab/python-gitlab#868]
## Description of the problem, including code/CLI snippet
based on the documentation [here](https://python-gitlab.readthedocs.io/en/stable/gl_objects/mrs.html), I should be able to pull all merge requests across all projects in a gitlab instance by running my_gitlab.mergerequests.list() or my_gitlab.mergerequests.list(all=True). Both of those return empty dicts. 

## Expected Behavior
Running mrs = my_gitlab.mergerequests.list() would set mrs to be a dict of all merge requests.

## Actual Behavior
mrs is empty

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.1.6 ee

**Comment by max-wittig** [comment]
You'll only get all merge requests that you've created. To get all merge requests, you'll need to supply `scope=all`. See in the offical docs: https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests
