### ISSUE TITLE
ProjectPipeline: add missing attributes

### ISSUE THREAD

**Issue by chbndrhnns** [python-gitlab/python-gitlab#869]
## Description of the problem, including code/CLI snippet
I am missing attributes for the `ProjectPipeline` object

## Expected Behavior
I see all attributes listed at https://docs.gitlab.com/ee/api/pipelines.html#get-a-single-pipeline

## Actual Behavior
I see only `id`, `sha`, `ref`, `status`, and `web_url`

## Specifications

  - python-gitlab version: 1.10
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): private

**Comment by max-wittig** [comment]
You'll get the rest of the attributes as a dict by using the `attributes` key.

pipelines.attributes["created_at"]
