### ISSUE TITLE
Search: search or list MRs by tag/author

### ISSUE THREAD

**Issue by hydrargyrum** [python-gitlab/python-gitlab#870]
Gitlab's MR API allows to search [by author or by tag](https://docs.gitlab.com/ce/api/merge_requests.html), whereas neither the [search bindings](https://python-gitlab.readthedocs.io/en/stable/api/gitlab.v4.html#gitlab.v4.objects.Project.search) nor the `.list()` bindings allow it.

**Comment by max-wittig** [comment]
Should work just fine, as it's a query parameter.

gl.mergerequests.list(author_id=5)

**Comment by max-wittig** [comment]
Feel free to re-open, if this answer is not sufficient or if I missed something
