### ISSUE TITLE
通过python-gitlab中的 gl.projects.list(all=True)不能获取到所有项目

### ISSUE THREAD

**Issue by dengyouqing** [python-gitlab/python-gitlab#872]
## Description of the problem, including code/CLI snippet
在python-gitlab中获取项目的所有project只能获取到50条记录
project_list = gl.projects.list(all=True)
print(len(project_list))  # only can get 50 projects

但是通过gitlab api 分页的方式可以获取到更多的project
headers = {'Private-Token': '************'}
data = {'per_page': 100, 'page': 11}  # adjust page can get all of projects
response = requests.get(url='http://gitlab.***.com/api/v4/projects', headers=headers, params=data)
print(len(response.json()))
## Specifications
![002](https://user-images.githubusercontent.com/21093446/64242468-29540080-cf38-11e9-90b1-38a44f56827c.jpg)

  - python-gitlab version: python-gitlab        1.9.0
  - API version you are using (v3/v4):v4
  - Gitlab server version (or gitlab.com): GitLab Community Edition 10.6.4

**Comment by max-wittig** [comment]
Hi @dengyouqing. By default, only 30 items per page are returned:

Use this to loop through all projects using a python generator

```
gl = gitlab.Gitlab("http://your-url", private_token="your-token", per_page=100)
for project in gl.projects.list(as_list=False):
      print(project)
```

Feel free to re-open, if you encounter any issues.

**Comment by dengyouqing** [comment]
yeah，the problem has been solved. 3 g u
