### ISSUE TITLE
Merge Request Approvals API

### ISSUE THREAD

**Issue by thuhc** [python-gitlab/python-gitlab#877]
## Description of the problem, including code/CLI snippet
Since GitLab 12.3, gitlab changed API for MR approvals
https://docs.gitlab.com/ee/api/merge_request_approvals.html
project.approvals.get() --> cannot get list approvals
`<class 'gitlab.v4.objects.ProjectApproval'> => {'approvers': [], 'approver_groups': [], 'approvals_before_merge': 2, 'reset_approvals_on_push': True, 'disable_overriding_approvers_per_merge_request': True, 'merge_requests_author_approval': False, 'merge_requests_disable_committers_approval': False}
`
## Expected Behavior
- Integration to this new API for MR approvals: get list approvals, add/remove approvals

## Actual Behavior
- Update API for MR approvals

## Specifications

  - python-gitlab version: 1.11
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.3

**Comment by samvasko** [comment]
The workaround right now is to call the attributes method. EG
`mr.approvals.get().attributes`

**Comment by max-wittig** [comment]
Hi @thuhc. This library is currently only maintained by me and I don't really focus on EE features. But if you want to fix this here, I would be happy to review your PR

**Comment by tymonx** [comment]
I have added two missing attributes: https://github.com/python-gitlab/python-gitlab/pull/934. It will not solve the missing `approvals` list but it fixes approvals configuration during the `.save()`

**Comment by JohnVillalovos** [comment]
Closing this since as far as I know we have support for the Merge Request Approvals API:
https://python-gitlab.readthedocs.io/en/main/gl_objects/merge_request_approvals.html

**Comment by JaxonWright** [comment]
@JohnVillalovos that is not the same API. What is being asked for is the approvals API which shows stats on the current state of approvals for the MR. What you linked are the _settings_ that determine what kind of approvals are required.

**Comment by JohnVillalovos** [comment]
> @JohnVillalovos that is not the same API. What is being asked for is the approvals API which shows stats on the current state of approvals for the MR. What you linked are the _settings_ that determine what kind of approvals are required.

The issue description above said they wanted support for doing: `project.approvals.get()` and as far as I can tell PG supports that.

If there is something else that is missing then an issue should be opened for that.

**Comment by nejch** [comment]
There's also an example for approval state in the docs linked, you can scroll down to `mr.approval_state.get()`. I admit I also personally don't have access to enterprise features though and so it's usually not a priority, not sure about @JohnVillalovos.

So I'm unsure how well this works against a real server (not mocked unit tests), here we really rely on the community when implementing features :)

**Comment by JaxonWright** [comment]
> There's also an example for approval state in the docs linked, you can scroll down to `mr.approval_state.get()`. I admit I also personally don't have access to enterprise features though and so it's usually not a priority, not sure about @JohnVillalovos.
> 
> So I'm unsure how well this works against a real server (not mocked unit tests), here we really rely on the community when implementing features :)

Wow. I looked at this page like 5 times and didn't see that. That is what I'd been looking for!

**Comment by nejch** [comment]
@JaxonWright ah, feel free to split up that page a bit if you think it's not that clear, and open a PR here, we'll be more than happy to take a look! :)
