### ISSUE TITLE
cannot list user project

### ISSUE THREAD

**Issue by LuckySB** [python-gitlab/python-gitlab#881]
## Description of the problem, including code/CLI snippet
cli command return error
```./gitlab -v user-project  list --user-id 777```

## Expected Behavior
list of user project

## Actual Behavior
```Impossible to list objects ('NoneType' object has no attribute 'id')```

## Specifications

  - python-gitlab version: 1.11.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.2.5

**Comment by LuckySB** [comment]
user with id 777 exists

``` gitlab user get --id 777
id: 777
username: s000005
```

**Comment by max-wittig** [comment]
What exactly do you want to list in the repository? What should the CLI list, if you specify a project id? I don't know much about the CLI, but it sounds like you need another parameter.

**Comment by LuckySB** [comment]
I realized that you do not understand.

the command `gitlab user-project list --user-id 777` does not work. returns an error.

If you looked at the help output `gitlab user-project list -h`, you would see that you can only set the user ID

**Comment by LuckySB** [comment]
can you fix this bug ?

**Comment by max-wittig** [comment]
I'm just a single maintainer and I never use the CLI, but if you need this feature, I would be happy to review your merge request.

**Comment by LuckySB** [comment]
@max-wittig 
Please review my request
