### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by iMerica** [python-gitlab/python-gitlab#882]
It would be very helpful to have REAL world example for using Gitlab's own free CI server instead of "somewhere".

I'm 25 minutes into using this tool and I still can't get this CLI to connect to Gitlab's servers.

Error:

> Impossible to get gitlab informations from configuration (https://gitlab.com)
------
In page: cli.rst

**Comment by max-wittig** [comment]
What would you suggest to change?

**Comment by max-wittig** [comment]
@iMerica I don't really understand, what's missing here. Please re-open, if you got any suggestions!
