### ISSUE TITLE
Unhelpful error when running project list --al

### ISSUE THREAD

**Issue by iMerica** [python-gitlab/python-gitlab#883]
## Description of the problem, including code/CLI snippet
`gitlab project list --all`

```
Impossible to list objects (HTTPSConnectionPool(host='gitlab.com', port=443): Read timed out. (read timeout=5))
```

## Expected Behavior
I expect to see all my repos or a helpful highlevel error that might suggest how to fix, not a low level networking exception

## Actual Behavior
A low level networking exception displays

## Specifications

  - python-gitlab version: Latest as of todays date
  - API version you are using (v3/v4): Latest as of todays date
  - Gitlab server version (or gitlab.com): Latest as of todays date

**Comment by max-wittig** [comment]
Are you behind a proxy?

**Comment by LoveIsGrief** [comment]
Running into the same problem

~/.python-gitlab.cfg
```cfg
[global]
default = gitlab
timeout = 10

[gitlab]
url = https://gitlab.com
private_token=myprivatetokenfromgitlab
```

Is there another host I shouuld be using?

curl works so there's no proxy

```
$ curl https://gitlab.com
<html><body>You are being <a href="https://about.gitlab.com/">redirected</a>.</body></html>
```

**Comment by LoveIsGrief** [comment]
@iMerica I just "solved" my problem. Do you have a `timeout` in your config? Try removing it. It take a non-negligible time to make the `gitlab project list`

```
real    0m27.344s
user    0m0.359s
sys     0m0.032s
```
