### ISSUE TITLE
Move a project to another group

### ISSUE THREAD

**Issue by galexandre** [python-gitlab/python-gitlab#884]
Hello everyone, 

I am trying to change the current project's group to another one. 
Example: `group1 -> project a` to `group2 -> project a` 

---
## What I have done so far 
```python
...
gitlab_project.namespace.update(id=id_new_group)
gitlab_project.namespace.update(full_path=new_group) gitlab_project.namespace.update(path=new_group)
gitlab_project.namespace.update(name=new_group)
...
gitlab_project.save()
```

I can change the name of the project without any issue, and in gitlab I will have the new name but not the group. 

## Expected Behavior
My expectation is to have `project a` into `group2`.

## Actual Behavior

However, `project a` is still in `group 1`. 

## Specifications

  - python-gitlab version: 1.90
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.8.3

Is it related to the API version or there is something wrong in the code?

**Comment by max-wittig** [comment]
I think you need to use the `transfer API`: https://python-gitlab.readthedocs.io/en/stable/api/gitlab.v4.html#gitlab.v4.objects.Project.transfer_project

**Comment by galexandre** [comment]
Yes I saw this last week (and it solved my issue), I should have read more carefully the documentation. Sorry.

**Comment by max-wittig** [comment]
@galexandre No problem. Glad it works for you!
