### ISSUE TITLE
setting approvals_before_merge for Gitlab 12.3 requires approval_rules api endpoint.

### ISSUE THREAD

**Issue by cmichael81** [python-gitlab/python-gitlab#887]
## Description of the problem, including code/CLI snippet
I am trying to set 'approvals_before_merge' it working in v11.09 but I upgraded my Gitlab server to 12.3 and now the setting is not taking effect.  The Gitlab documentation says that this is depreciated now in 12.0+ and to use "Approval Rules API."  I am unsure how to get to that endpoint.

How do I get the approval_rules info to set it for Gitlab 12.3?  I didnt see anything in the documentation for this.

Working in 11.0+
`for project in all_projects:
    approval_settings = project.approvals.get()
    pp.pprint(approval_settings.attributes)
    pp.pprint(project.attributes)`

Trying this in 12.3, but not sure how to get the approval_rules.
`for project in all_projects:
    approval_settings = project.approval_rules.get()
    pp.pprint(approval_settings.attributes)
    pp.pprint(project.attributes)`

## Expected Behavior

getting the approval rules info so I can set them

## Actual Behavior

Traceback (most recent call last):
  File "api.py", line 99, in <module>
    approval_settings = project.approval_rules.get()
  File "/Library/Python/2.7/site-packages/gitlab/base.py", line 84, in __getattr__
    raise AttributeError(name)
AttributeError: approval_rules`

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.3

**Comment by max-wittig** [comment]
I don't know much about the EE version of GitLab.

> Note: Please switch to python3. Python2 will be unsupported and will no longer receive security fixes starting 2020-01-01.

**Comment by cmichael81** [comment]
Correct, They moved some of the merge request changes to the /projects/:id/approval_rules endpoint rather than the /projects/:id/approvals.  This change will probably be merged into the CE edition sometime in the future I believe as well.  


https://docs.gitlab.com/ee/api/merge_request_approvals.html

**Comment by max-wittig** [comment]
I don't think that merge request approvals are ever gonna be in CE. That's not what an individual contributor needs and that's their model for deciding which feature to put where.

**Comment by nejch** [comment]
Both project and MR-level approval rules are now implemented with the new API so I'm closing this unless there are still any issues, please reopen if so.

See https://python-gitlab.readthedocs.io/en/stable/gl_objects/mr_approvals.html.
