### ISSUE TITLE
when auth ,why  response GitlabHttpError: 404: 404 Not Found

### ISSUE THREAD

**Issue by xiaomabetter** [python-gitlab/python-gitlab#888]
## Description of the problem, including code/CLI snippet
first use python-gitlab, 
![image](https://user-images.githubusercontent.com/13087771/65829897-cf4b1e80-e2dc-11e9-82b7-c759ba8c5b7f.png)
gl.auth()
![image](https://user-images.githubusercontent.com/13087771/65829905-e2f68500-e2dc-11e9-8b49-f851f4212b47.png)

## Specifications

  - python-gitlab version: latest
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Community Edition 11.4.5

**Comment by max-wittig** [comment]
I think password auth is no longer supported within GitLab via API:

https://docs.gitlab.com/ce/api/#authentication

**Comment by max-wittig** [comment]
@xiaomabetter Feel free to re-open, if you still encounter issues.
