### ISSUE TITLE
CLI usage without configuration file

### ISSUE THREAD

**Issue by ghost** [python-gitlab/python-gitlab#893]
Requiring a configuration file is not ideal for using the CLI on a CI server. It would be great if the required settings could also be passed as arguments or predefined environment variables.

**Comment by bufferoverflow** [comment]
That's a good idea and I'm sure contributions on this are welcome.

**Comment by atmishra** [comment]
Can I work on this?

**Comment by max-wittig** [comment]
@atmishra Sure. Contributions are always welcome!
