### ISSUE TITLE
List all Issues results in JSONDecodeException (Pagination Error)

### ISSUE THREAD

**Issue by AndyXan** [python-gitlab/python-gitlab#909]
## Description of the problem, including code/CLI snippet

With `Gitlab-CE 12.3.5` the following request `self.project.issues.list(all=True)` for Projects with more than 20 issues gets the following exception 

```python
JSONDecodeError                           Traceback (most recent call last)
~/.virtualenvs/cpython3/lib/python3.7/site-packages/gitlab/__init__.py in _query(self, url, query_data, **kwargs)
    797         try:
--> 798             self._data = result.json()
    799         except Exception:

~/.virtualenvs/cpython3/lib/python3.7/site-packages/requests/models.py in json(self, **kwargs)
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 

/usr/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:

/usr/lib/python3.7/json/decoder.py in decode(self, s, _w)
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()

/usr/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The same behaviour can be reproduced by iteration over the issues: 

```python
for iss in self.project.issues.list(state='closed', as_list='False'): 
   print("Number: {}".format(i)) 
   print(iss) 
   i += 1 
   print("---------") 
```
Which works perfectly fine until the 20th issue is reached. 

On a side note: 
```python
closed_issues = self.project.issues.list(state='closed', per_page=40, all=True) # Works
closed_issues = self.project.issues.list(state='closed', per_page=20, all=True) # JSonDecodeException
```
Works just fine. 

## Expected Behavior

Expceted Issue is the iteration over all Issues without pagination interrupting. This has been working for Gitlab 12.3.x < 12.3.5 at least at some point in the last 4-5 weeks. 

## Actual Behavior

Well, Actual Behaviour is the exception :)

## Specifications

  - python-gitlab version:  v1.12.1 
  - api_version="4",
  - Gitlab server version: `Gitlab-CE 12.3.5`

**Comment by max-wittig** [comment]
Not really sure what could be causing this. Do you have the same issues on GitLab.com?

**Comment by AndyXan** [comment]
Well.. what can I say. I rechecked it with gitlab.com and it worked. I rechecked it on my repositories, same Code and it works. 

I'm sorry for the Issue and I have no idea why it didn't work 2 weeks ago. /closed for now!
