### ISSUE TITLE
Get token from OS environment variables

### ISSUE THREAD

**Issue by arthurlogilab** [python-gitlab/python-gitlab#910]
## Description of the problem, including code/CLI snippet

It would be nice, in a docker type environment where secrets are passed though environment variables to be able to pickup private tokens (or other secrets) through this mechanism : 

```
gl = gitlab.Gitlab('https://gitlab.example.org', private-token='XXX')
```

would be replaced by : 

```
gl = gitlab.Gitlab('https://gitlab.example.org')
```

and would pick up `GITLAB_PRIVATE_TOKEN` from `os.env`

**Comment by max-wittig** [comment]
I'm not sure that's reasonable as everybody uses different environment variable names for this.

You could just do

```python
import gitlab
import os

gl = gitlab.Gitlab("https://gitlab.example.org", os.getenv("GITLAB_PRIVATE_TOKEN"))
```
