### ISSUE TITLE
Gitlab API - Failed to parse the server message

### ISSUE THREAD

**Issue by C-Zuge** [python-gitlab/python-gitlab#912]
## Description of the problem, including code/CLI snippet
Hey there! I'm trying to list some issues/projects from gitlab lib in python using Visual Code. 
my code is too simple but isn't working. The Url is private, mt token was created in the site in 'api' ('Grants complete read/write access to the API, including all groups and projects, the container registry, and the package registry') mode. 

import gitlab
#import requests

url = 'https://code.siemens.com/afgfds/asdfghjkl_ewiruty/issues'
Token = 'zxcvbnmoiu_4sd_asdfgh'

gl = gitlab.Gitlab(url, private_token=Token)
gl.auth()

issues = gl.issues.list()
for issue in issues:
    print(issue)

## Actual Behavior

Traceback (most recent call last):
  File "\lib\site-packages\gitlab\__init__.py", line 798, in _query
    self._data = result.json()
  File "\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Git_code.py", line 10, in <module>
    issues = gl.issues.list()
  File "\lib\site-packages\gitlab\exceptions.py", line 259, in wrapped_f
    return f(*args, **kwargs)
  File "\lib\site-packages\gitlab\mixins.py", line 134, in list
    obj = self.gitlab.http_list(path, **data)
  File "\lib\site-packages\gitlab\__init__.py", line 657, in http_list
    return list(GitlabList(self, url, query_data, get_next=False, **kwargs))
  File "\lib\site-packages\gitlab\__init__.py", line 780, in __init__
    self._query(url, query_data, **kwargs)
  File "\lib\site-packages\gitlab\__init__.py", line 800, in _query
    raise GitlabParsingError(error_message="Failed to parse the server message")
gitlab.exceptions.GitlabParsingError: Failed to parse the server message

## Specifications

  - python-gitlab version:
  - API version you are using (v4):
  - Gitlab server version (or gitlab.com):

**Comment by bufferoverflow** [comment]
@C-Zuge This seems to be a connectivity problem at your end. Does a curl work? Are you connected to the correct network segment?

**Comment by C-Zuge** [comment]
Unfortunately I'm connected. I've tried to use requests and curl, but nothing work. Always redirect me to the sign in page (using private_token and Oauth_token)

**Comment by max-wittig** [comment]
Your GitLab instance is blocking API requests from the Internet. This is nothing python-gitlab can fix.
