### ISSUE TITLE
Convert an object to JSON

### ISSUE THREAD

**Issue by shr1k4nt** [python-gitlab/python-gitlab#915]
Is it possible to convert the data received from Gitlab into a json object? Eg. convert the UserEvent/Project response to a json object

**Comment by max-wittig** [comment]
Yes. Could work like this (untested)

```python
import gitlab
import json

gl = gitlab.Gitlab("https://gitlab.com", "<token>")
gl.auth()
project = gl.projects.get(42)
print(json.dumps(project.attributes))
```

**Comment by max-wittig** [comment]
Feel free to re-open, if anything is not clear yet.
