### ISSUE TITLE
repositories.list() fails with hub.docker.com image

### ISSUE THREAD

**Issue by tripleawwy** [python-gitlab/python-gitlab#918]
## Description of the problem, including code/CLI snippet
the current version of the docker image can not handle the function "repositories.list()".
If I update python-gitlab inside the container it works, so please update your hub.docker.com image :).

```bash
Traceback (most recent call last):
  File "/scripts/registry-cleaner-script.py", line 91, in <module>
    main()
  File "/scripts/registry-cleaner-script.py", line 87, in main
    delete_tags(git_nr, args.projectid, args.regexp, args.keep, args.time)
  File "/scripts/registry-cleaner-script.py", line 39, in delete_tags
    repositories = project.repositories.list()
  File "/usr/local/lib/python3.7/site-packages/gitlab/base.py", line 81, in __getattr__
    raise AttributeError(name)
AttributeError: repositories
```

## Expected Behavior
to list all repositories of a project

## Actual Behavior
throws an exception see code snippet

## Specifications

  - python-gitlab version: public hosted docker image : https://hub.docker.com/r/pythongitlab/python-gitlab/builds
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.3.5

**Comment by bufferoverflow** [comment]
@gpocentek could you provide access to the docker account for @max-wittig ?

**Comment by max-wittig** [comment]
@bufferoverflow I got access. I will delete the image there.

**Comment by max-wittig** [comment]
@tripleawwy Please use `registry.gitlab.com/python-gitlab/python-gitlab:v1.12.1`

The latest image will be provided in the future with #922

**Comment by max-wittig** [comment]
@tripleawwy Thanks!
