### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by falconer** [python-gitlab/python-gitlab#927]
Running the code below will result in a 403 error.
You wonder how you want to create a project from A GitLab to B GitLab server.

Error Details
<class 'gitlab.exceptions.GitlabHttpError'>
('403 Forbidden',)
403: 403 Forbidden

------
In page: gl_objects/projects.rst

## Executable code
output = gl.projects.import_project(open('/tmp/export.tgz', 'rb'), 'my_new_project')
# Get a ProjectImport object to track the import status
project_import = gl.projects.get(output['id'], lazy=True).imports.get()
while project_import.import_status != 'finished':
    time.sleep(1)
    project_import.refresh()

**Comment by max-wittig** [comment]
Hi @falconer. Thanks for the report. Could you maybe please elaborate a bit what exactly is wrong in the documentation?

**Comment by max-wittig** [comment]
Please reopen, if you got something more concrete.
