### ISSUE TITLE
Increase weight of Issue with every Bug Event

### ISSUE THREAD

**Issue by Ly0n** [python-gitlab/python-gitlab#933]
## Description of the problem, including code/CLI snippet
I wont to increase the weight of an issue with every bug that appears. For this I wrote a tool to help users create issues. 
Unfortunately I can not find anything about weight in the documentation, but Gitlab has this API:
https://docs.gitlab.com/ee/api/issues.html#list-group-issues

```
old_issue_id = project.issues.list(search=input_titel)[0]
working_issue = project.issues.get(old_issue_id.iid)
weight_old = issue_changes.weight
issue_changes.weight = weight_old + 1
```

## Expected Behavior
weight can be increased by python-gitlab 

## Actual Behavior
python-gitlab does not know about weight

## Specifications
Metadata-Version: 2.0
Name: python-gitlab
Version: 1.6.0
Summary: Interact with GitLab API
Home-page: https://github.com/python-gitlab/python-gitlab
Author: Gauvain Pocentek
Author-email: gauvain@pocentek.net
Installer: pip
License: LGPLv3
Location: /home/obelix/.local/lib/python2.7/site-packages
Requires: requests, six
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Console
  Intended Audience :: System Administrators
  License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)
  Natural Language :: English
  Operating System :: POSIX
  Operating System :: Microsoft :: Windows
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
Entry-points:
  [console_scripts]
  gitlab = gitlab.cli:main

Gitlab:
 GitLab Enterprise Edition 11.9.9-ee
GitLab is open source software to collaborate on code.

**Comment by max-wittig** [comment]
Hi @Ly0n I don't have/nor use any edition of GitLab EE, but if you would create an MR to add this feature, I would be happy to review it.

**Comment by nejch** [comment]
This is very after-the-fact, but for future readers: you were pretty close @Ly0n. `weight` is just a normal attribute so you just need to call `save()`. Something like this (could be even shorter)

```python
old_issue = project.issues.list(search=input_title)[0]
issue = project.issues.get(old_issue.iid)

weight_old = issue.weight
working.weight = weight_old + 1

issue.save()
```

Of course you'll need Premium for this and maybe the original is returned as a string so you'll want to check it works as expected.
