### ISSUE TITLE
Add support for audit events

### ISSUE THREAD

**Issue by idanbensha** [python-gitlab/python-gitlab#948]
There's no support for the Audit Events API via the python gitlab client.

See here:
https://docs.gitlab.com/ee/api/audit_events.html

## Specifications

  - python-gitlab version: 1.9
  - API version you are using (v3/v4): v4

**Comment by max-wittig** [comment]
Hi I don't have access to the enterprise version of GitLab. But if you like to have this feature, I would be happy to review any merge requests regarding this.

**Comment by idanbensha** [comment]
Hello, that would be great.
I will apply a PR adding this feature ASAP!
