### ISSUE TITLE
Add support for pipeline detailed information

### ISSUE THREAD

**Issue by rostskadat** [python-gitlab/python-gitlab#950]
## Description of the problem, including code/CLI snippet

The [Gitlab Pipeline API](https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines) returns detailed information about the pipeline (such as the `created_at` attributes).

## Expected Behavior

I would expect the `project.pipelines.list()` and the `project.pipelines.get(pipeline_id)` to return these detailed information.

## Actual Behavior

The detailed information about the pipeline are not present neither in `pipelines.list()` nor in `pipelines.get(piepline_id)`

## Specifications

  - python-gitlab version: 1.12.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.2.5-ee

**Comment by max-wittig** [comment]
I think you just need to retrieve the attributes of the object.

```python
pipelines.get(piepline_id).attributes
```

**Comment by rostskadat** [comment]
Sorry, I just figured this out. I was a bit confused while reading the documentation.
I'm closing the incident.

Thanks
