### ISSUE TITLE
Missing imports api 

### ISSUE THREAD

**Issue by weaming** [python-gitlab/python-gitlab#952]
## Description of the problem, including code/CLI snippet

missing https://docs.gitlab.com/ee/api/import.html

## Expected Behavior

gl.imports.github ...

## Actual Behavior

not found in this lib.

## Specifications

  - python-gitlab version: 1.13.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): whatever

**Comment by max-wittig** [comment]
This was added by @andrew-littlebits in the last release. Thanks again!
