### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by marioviranov** [python-gitlab/python-gitlab#957]
------
In page: gl_objects/commits.rst

I have tried the commits = project.commits.list(ref_name='my_branch') with and without the ref_name as an input, I entered master specifically , it gives the same ProjectCommit ids whether its commits = project.commits.list(ref_name='my_branch') or commits = project.commits.list()

**Comment by max-wittig** [comment]
so are commits missing on your branch or whats going on specifically?

**Comment by ViranovM** [comment]
They are not missing , they just aren't filtered by the branch I'm giving as a value, basically it gives all the commits regardless of specifying a branch or not.
