### ISSUE TITLE
Surprising interaction between "as_list" and "all"

### ISSUE THREAD

**Issue by mitar** [python-gitlab/python-gitlab#962]
From [reading here](https://python-gitlab.readthedocs.io/en/stable/api-usage.html) I understood that I have to use `all=True` if I want to get all results, and then do `as_list=False` to get a generator to iterate over. But in fact this does not work well together. By specifying `all=True` it first starts fetching all results and generator does not call anything with results as pages are coming in.

I think `all=True` should just work with `as_list=False`. If I understand correctly, `all=True` is a noop in that case because `as_list=False` already implies it?

**Comment by max-wittig** [comment]
Yes. Basically, if you supply as_list you won't need all=True.

**Comment by mitar** [comment]
Yes, but I think that if you supply `as_list` `all` should just be ignored.

**Comment by max-wittig** [comment]
Good point
