### ISSUE TITLE
Unable to set labels on issues

### ISSUE THREAD

**Issue by tamasgal** [python-gitlab/python-gitlab#975]
## Description of the problem, including code/CLI snippet

Setting issue labels like explained in the docs does not have any effect. Creating issues and other stuff seem to work fine!

```
[ins] In [28]: issue = project.issues.get(7)                                                 

[ins] In [29]: issue.labels                                                                  
Out[29]: []

[ins] In [30]: issue.labels = ['todo']                                                       

[ins] In [31]: issue.labels                                                                  
Out[31]: ['todo']

[ins] In [32]: issue.save()                                                                  

[ins] In [33]: issue.labels                                                                  
Out[33]: []
```

## Expected Behavior

Issue labels should be updated both in the UI and in the issue manager istance.

## Actual Behavior

Issue labels are not updated.

## Specifications

  - python-gitlab version: 1.14.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.4.3

**Comment by max-wittig** [comment]
Just tried it. Not sure what's going on with your client, but works for me:

![image](https://user-images.githubusercontent.com/6639323/71071815-96a13f80-217d-11ea-805a-1486a6222e49.png)
![image](https://user-images.githubusercontent.com/6639323/71071832-9e60e400-217d-11ea-81f6-8a4efe48330e.png)

https://gitlab.com/max-wittig/gitlab-status/issues/1

**Comment by pavelpp29** [comment]
I can’t add a label either.

Specifications:
python-gitlab version: 2.2.0
API version you are using (v3/v4): v4
Gitlab server version (or gitlab.com): 12.8.1
Python: 3.7

![send_support](https://user-images.githubusercontent.com/45298943/82184177-dcf6f800-98ef-11ea-958a-2e34bd49501b.png)
![test (#129)](https://user-images.githubusercontent.com/45298943/82184169-d799ad80-98ef-11ea-8582-4fdaf689efe4.png)

**Comment by joeypencil** [comment]
Also having the same problem. I already tried the following:

- Setting the labels in the `project.issues.create()` call
- Setting the labels by explicit assignment through the newly-created issues IID (using `project.issues.get()`)
- Using a new project object, having a new issue object using the new issue's IID, then assigning the labels

None of them work.

**Comment by joeypencil** [comment]
@tamasgal @pavelpp29 I just found out what caused the issue.

If you're using gitlab token-based authentication, make sure **the user** associated with that token **is a member of the project** you're using the python-gitlab module on.

**Comment by pavelpp29** [comment]
> @tamasgal @pavelpp29 I just found out what caused the issue.
> 
> If you're using gitlab token-based authentication, make sure **the user** associated with that token **is a member of the project** you're using the python-gitlab module on.

Resolved thanks

**Comment by nejch** [comment]
Seems like this was just a permission issue, closing. :)
