### ISSUE TITLE
How to create subgroups

### ISSUE THREAD

**Issue by AlmuHS** [python-gitlab/python-gitlab#976]
## Description of the problem, including code/CLI snippet
I'm trying to create subgroups from python-gitlab, but I don't find how to do this in the docs

I created a group with:
```
group = gl.groups.create({'name': 'group1', 'path': 'group1'})
group.description = 'My awesome group'
group.save()
```
and I'm trying to create a subgroup with:

`subgroup = gl.groups.create({'name': 's2', 'path': 's2'}, parent=group.attributes['id'])`

## Expected Behavior

Create a subgroup s2 in group1

## Actual Behavior

Created a new group with name s2

## Specifications

  - python-gitlab version: 1.14.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
You'll need to use the subgroup API for this:

```python
gl.groups.get(1).subgroups.create(...)
```

See: https://python-gitlab.readthedocs.io/en/stable/gl_objects/groups.html#subgroups

**Comment by AlmuHS** [comment]
> You'll need to use the subgroup API for this:
> 
> ```python
> gl.groups.get(1).subgroups.create(...)
> ```
> 
> See: https://python-gitlab.readthedocs.io/en/stable/gl_objects/groups.html#subgroups

This is not valid

```
Traceback (most recent call last):
  File "gitlab_api.py", line 36, in <module>
    gl.groups.get('group1').subgroups.create({'name': 's3', 'path': 's3'})
AttributeError: 'GroupSubgroupManager' object has no attribute 'create'
```

**Comment by max-wittig** [comment]
Ah okay. I guess the subgroup API is only for listing. Then you'll have to set the correct path in your request. Path should be 'group1/s2' in your example

**Comment by AlmuHS** [comment]
> Ah okay. I guess the subgroup API is only for listing. Then you'll have to set the correct path in your request. Path should be 'group1/s2' in your example

This don't works :(

```
gl.groups.create({'name': 's3', 'path': 'group1/s3'})
```

Returns this error:

```
Traceback (most recent call last):
  File "gitlab_api.py", line 55, in <module>
    gl.groups.create({'name': 's3', 'path': 'group1/s3'})
  File "/home/almu/.local/lib/python3.7/site-packages/gitlab/exceptions.py", line 269, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 400: Failed to save group {:path=>["can contain only letters, digits, '_', '-' and '.'. Cannot start with '-' or end in '.', '.git' or '.atom'."]}
```

**Comment by max-wittig** [comment]
python-gitlab follows the gitlab api one by one. So you'll need to supply the `parent_id` https://docs.gitlab.com/ee/api/groups.html#new-group

**Comment by AlmuHS** [comment]
> python-gitlab follows the gitlab api one by one. So you'll need to supply the `parent_id` https://docs.gitlab.com/ee/api/groups.html#new-group

The group was created previously

**Comment by max-wittig** [comment]
Then you need to look for the id in the gui or search for the group

**Comment by daqingshu** [comment]
sub_group = gl.groups.create({"name": sub_group_name, "path": sub_group_name, "parent_id": group.id})
