### ISSUE TITLE
Docker registry api

### ISSUE THREAD

**Issue by deadstar2011** [python-gitlab/python-gitlab#983]
## Description of the problem, including code/CLI snippet
Hi. Cannot get the project registry list with command:

`repositories = project.repositories.list()`

Full code:

`projects = gl.projects.list(all = True)`
`for project in projects:`
       ` repositories = project.repositories.list()`
Its rise the error:

`Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.7/site-packages/gitlab/base.py", line 56, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'repositories'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.7/site-packages/gitlab/base.py", line 59, in __getattr__
    value = self.__dict__['_attrs'][name]
KeyError: 'repositories'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.7/site-packages/gitlab/base.py", line 79, in __getattr__
    return self.__dict__['_parent_attrs'][name]
KeyError: 'repositories'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/mounted/ansible/scripts/test_piplines.py", line 40, in <module>
    repositories = project.repositories.list()
  File "/home/dev/.local/lib/python3.7/site-packages/gitlab/base.py", line 81, in __getattr__
    raise AttributeError(name)
AttributeError: repositories

Process finished with exit code 1`

## Specifications

  - python-gitlab version: 1.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.4.1

**Comment by max-wittig** [comment]
Not sure what's going on. It works for me just fine using gitlab.com: 
![image](https://user-images.githubusercontent.com/6639323/71166693-8f4c6580-2253-11ea-9dcc-6b755d4ee065.png)

Are you sure that your instance has this configured.

**Comment by deadstar2011** [comment]
> Not sure what's going on. It works for me just fine using gitlab.com:
> ![image](https://user-images.githubusercontent.com/6639323/71166693-8f4c6580-2253-11ea-9dcc-6b755d4ee065.png)
> 
> Are you sure that your instance has this configured.

Yeah, we using self-hosted gitlab 12.4.1 version with docker registry.

Very strange, because CURL to gitlab api return right things:
1) `curl --header "PRIVATE-TOKEN: MY_ADMIN_TOKEN" "https://gitlab.userstory.ru/api/v4/projects/1103/registry/repositories"
[{"id":228,"name":"nginx","path":"userstory-rusatom/rusatom-laravel/nginx","project_id":1103,"location":"cr.userstory.ru/userstory-rusatom/rusatom-laravel/nginx","created_at":"2019-12-18T11:41:09.835+07:00"},{"id":231,"name":"fpm","path":"userstory-rusatom/rusatom-laravel/fpm","project_id":1103,"location":"cr.userstory.ru/userstory-rusatom/rusatom-laravel/fpm","created_at":"2019-12-18T11:52:56.682+07:00"}]`

2) `curl --header "PRIVATE-TOKEN: MY_ADMIN_TOKEN" "https://gitlab.userstory.ru/api/v4/projects/1103/registry/repositories?tags=1"
[{"id":228,"name":"nginx","path":"userstory-rusatom/rusatom-laravel/nginx","project_id":1103,"location":"cr.userstory.ru/userstory-rusatom/rusatom-laravel/nginx","created_at":"2019-12-18T11:41:09.835+07:00","tags":[{"name":"dev","path":"userstory-rusatom/rusatom-laravel/nginx:dev","location":"cr.userstory.ru/userstory-rusatom/rusatom-laravel/nginx:dev"},{"name":"latest","path":"userstory-rusatom/rusatom-laravel/nginx:latest","location":"cr.userstory.ru/userstory-rusatom/rusatom-laravel/nginx:latest"}]},{"id":231,"name":"fpm","path":"userstory-rusatom/rusatom-laravel/fpm","project_id":1103,"location":"cr.userstory.ru/userstory-rusatom/rusatom-laravel/fpm","created_at":"2019-12-18T11:52:56.682+07:00","tags":[{"name":"dev","path":"userstory-rusatom/rusatom-laravel/fpm:dev","location":"cr.userstory.ru/userstory-rusatom/rusatom-laravel/fpm:dev"},{"name":"latest","path":"userstory-rusatom/rusatom-laravel/fpm:latest","location":"cr.userstory.ru/userstory-rusatom/rusatom-laravel/fpm:latest"}]}]`
