### ISSUE TITLE
Get the size of a repository

### ISSUE THREAD

**Issue by AlmuHS** [python-gitlab/python-gitlab#989]
## Description of the problem, including code/CLI snippet
I want to see the storage size of a repository

## Expected Behavior
Similar to this: (https://forum.gitlab.com/t/how-to-retrieve-repository-size-through-rest-api/28088/2
)
## Actual Behavior
Project attributes don't shows the statistics

## Specifications

  - python-gitlab version: 1.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
You have the call the projects api with the statistics=true parameter

**Comment by miksonx** [comment]
@max-wittig can you give as example how to use statistics=true parameter?
Thank you
