### ISSUE TITLE
unicode_literals

### ISSUE THREAD

**Issue by Asher256** [python-gitlab/python-gitlab#99]
To be backware compatible with Python 2 regarding unicodes (related to the quick fix https://github.com/gpocentek/python-gitlab/pull/98), have you ever thought about unicode_literals?
1. Adding "from **future** import unicode_literals" at the top of python-gitlab's Python modules,
2. Removing the u prefix before unicode strings (already done),
3. Adding a b prefix before bytestrings.

**Comment by guyzmo** [comment]
Well this is not an issue anymore, as python 3.2 is deprecated, and with python 3.4 and over, `u''` support is now back in. You should either upgrade your distribution, or install an up to date python (using nix or linuxbrew).

**Comment by Asher256** [comment]
Upgrading a distribution it is not easy when you use Debian Wheezy in prod in more than 2000+ nodes ;-) . It takes time.

**Comment by gpocentek** [comment]
Using unicode_literals might change the behavior and break tools depending on python-gitlab. I'm not sure of the benefits of this change.

**Comment by guyzmo** [comment]
@gpocentek no it won't change the behaviour, and there's no reason it would break tools (besides code that only runs on python 2.6, which has now been officially deprecated anyway, so breaking it is good!).

The benefit is that it's a first step towards making the code base better suited for python 3, even though thanks to the reintroduction of `u''` in python 3.3 and newer, supporting both 2.7 and 3.x (with x>3) is smoother.

And it's also avoiding a whole range of issues related to str -> unicode conversions and the other way around.

**Comment by Asher256** [comment]
I agree with Guyzmo.

**Comment by gpocentek** [comment]
I've not received bug reports about such issues in ages, so I don't think this is really needed.
