### ISSUE TITLE
How to revert a commit of a project

### ISSUE THREAD

**Issue by AlmuHS** [python-gitlab/python-gitlab#991]
## Description of the problem, including code/CLI snippet
I need to remove an specific commit in a project

## Expected Behavior
https://docs.gitlab.com/ce/api/commits.html#revert-a-commit

## Specifications

  - python-gitlab version: 
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.4

**Comment by AlmuHS** [comment]
Not implemented yet?

**Comment by max-wittig** [comment]
yep. Seems like it. I would be happy to review any MRs, if you want to contribute :+1:

**Comment by AlmuHS** [comment]
> yep. Seems like it. I would be happy to review any MRs, if you want to contribute +1

Where are the functions to create commit? To check this as base
