### ISSUE TITLE
Change attribute of existing project variables

### ISSUE THREAD

**Issue by markuman** [python-gitlab/python-gitlab#992]
## Description of the problem, including code/CLI snippet

I need to change the attribute of an existing project variable. E.g. `protected`  or `masked`.  
But it looks like that it is only possible to set them due creation while update of the project variable itself is possible.

## Actual Behavior

```
>>> pl[5].variables.create({"key": "m", "value": "test", "protected": True})
>>> pv = pl[5].variables.list()
>>> pv[1]
<ProjectVariable key:m>
>>> pv[1].attributes
{'variable_type': 'env_var', 'key': 'm', 'value': 'test', 'protected': True, 'masked': False, 'environment_scope': '*', 'project_id': 188}
>>> pv[1].attributes.update({'masked': True})
###
### everything has no affect
>>> pv[1].attributes.update()
>>> pv[1].save()
>>> pv[1].attributes['masked'] = True
>>> pv[1].attributes['masked']
False
```

## Specifications

  - python-gitlab version: v1.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by lmmx** [comment]
This is a non-issue: the value used here `"test"` is only 4 characters long. The value must be at least 8 characters long to be masked. Try setting that in the web UI and you'll be unable to do so there as well. 

```py
>>> p.variables.create({"key": "foo", "value": "barbazbax", "protected": True, "masked": True})
<ProjectVariable key:foo>
```
