### ISSUE TITLE
member.access_level

### ISSUE THREAD

**Issue by CS2015YWB** [python-gitlab/python-gitlab#993]
## Description of the problem, including code/CLI snippet
GroupMember and ProjectMember have the same function to change member's access in group or project:
For example:
` member.access_level = gitlab.MAINTAINER_ACCESS` 

But, I can't use `member.access_level` in project after I use `member.access_level` in group, it will be error.

I am very confused that there are two same attribute for group and project.

  - python-gitlab version: 1.10.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
Not sure what you mean. Could you elaborate?

**Comment by CS2015YWB** [comment]
> Not sure what you mean. Could you elaborate?

Sorry, my English is not very good. Can you understand Chinese?

I want to say that ** item ** and ** group ** in GitLab API have the same properties
`project.members.access_level` and` group.members.access_level`, in general, ** project ** and ** group ** are ** objects **, but for a ** object **, the program It cannot be distinguished whether it is ** project ** or ** group **. If the same member in a piece of code includes both group member permission adjustment and project member permission adjustment (because project member permissions generally inherit groups Member permissions, so usually adjust the group member permissions first, and then adjust the project member permissions), and an error will occur.
But now, I have solved the problem and found something interesting that I never knew before. If the member permissions in ** project ** are inherited from ** group **, then this member cannot be queried from ** project ** through the API, only manually created in ** project ** or manually Only users with modified permissions can be queried.

I don't know if you understand, thank you very much!
