### ISSUE TITLE
Add Support for Epic Links

### ISSUE THREAD

**Issue by ToTryHardRay** [python-gitlab/python-gitlab#999]
## Description of the problem, including code/CLI snippet
Would be really cool if this had support for Epic Links in order to get access to all the child epics of a parent epic.
https://docs.gitlab.com/ee/api/epic_links.html
This is where gitlab mentions that ability
## Expected Behavior
To work similar to issue links

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
Hi @ToTryHardRay I don't have access to an EE instance, but I would be happy to review any merge request regarding this.
